export const MAX_INSTRUCTION_SOURCE_BYTES = 128 * 1024;
// UTF-8 BOM plus the worst-case CRLF-to-LF normalization overhead.
export const MAX_INSTRUCTION_SOURCE_FILE_BYTES =
  MAX_INSTRUCTION_SOURCE_BYTES * 2 + 3;
export const MAX_INSTRUCTION_ENVELOPE_BYTES = 128 * 1024;
export const INSTRUCTION_ADVISORY_BYTES = 32 * 1024;
export const INSTRUCTION_ADVISORY_LINES = 200;
export const INSTRUCTION_PROVIDER_RESERVE_TOKENS = 16 * 1024;
export const MAX_DISCOVERED_LOCAL_FILES = 256;

export const MAX_INSTRUCTION_PROFILE_NAME_LENGTH = 200;
export const MAX_INSTRUCTION_PROFILE_DESCRIPTION_LENGTH = 2_000;
export const MAX_INSTRUCTION_WORKSPACE_DISPLAY_NAME_LENGTH = 300;
export const MAX_INSTRUCTION_TAGS = 64;
export const MAX_INSTRUCTION_TAG_LENGTH = 80;
export const MAX_INSTRUCTION_TAG_RULE_DEPTH = 8;
export const MAX_INSTRUCTION_TAG_RULE_NODES = 128;
