import { parseArgs, type ParseArgsConfig } from "node:util";

export const cliTokenOptions = {
  json: { type: "boolean" },
  verbose: { type: "boolean", short: "v" },
  help: { type: "boolean", short: "h" },
  quick: { type: "boolean" },
  "set-api": { type: "boolean" },
  "set-global-memory": { type: "string" },
  mode: { type: "string" },
  provider: { type: "string" },
  "runtime-provider": { type: "string" },
  key: { type: "string" },
  task: { type: "string" },
  model: { type: "string" },
  reasoning: { type: "string" },
  "default-model": { type: "string" },
  "session-memory": { type: "string" },
  "global-memory": { type: "string" },
  "executor-turns": { type: "string" },
  "autopilot-iterations": { type: "string" },
  infinite: { type: "boolean" },
  "conversation-context-file": { type: "string" },
  "deterministic-action-json": { type: "string" },
  "skip-file-change-detection": { type: "boolean" },
  context: { type: "string", multiple: true },
  image: { type: "string", multiple: true },
  cwd: { type: "string" },
  name: { type: "string" },
  cron: { type: "string" },
  trigger: { type: "string", multiple: true },
  "trigger-filter": { type: "string", multiple: true },
  "trigger-recovery-filter": { type: "string", multiple: true },
  "trigger-firing-mode": { type: "string" },
  "trigger-cooldown-ms": { type: "string" },
  "trigger-repeat-ms": { type: "string" },
  "trigger-debounce-ms": { type: "string" },
  "trigger-dedupe-key-template": { type: "string" },
  "trigger-max-events": { type: "string" },
  "trigger-window-ms": { type: "string" },
  "interval-ms": { type: "string" },
  "delay-ms": { type: "string" },
  "run-at": { type: "string" },
  timezone: { type: "string" },
  "scheduler-target": { type: "string" },
  prompt: { type: "string" },
  "prompt-file": { type: "string" },
  "scheduled-ralph-flow": { type: "string" },
  "scheduled-ralph-flow-scope": { type: "string" },
  "scheduled-ralph-param": { type: "string", multiple: true },
  "scheduled-ralph-run-log-scope": { type: "string" },
  "scheduled-ralph-max-transitions": { type: "string" },
  "scheduled-ralph-profile": { type: "string" },
  "scheduled-ralph-resume-policy": { type: "string" },
  "scheduled-ralph-allowed-root": { type: "string", multiple: true },
  "scheduled-ralph-allow-commands": { type: "string" },
  "scheduled-ralph-allow-writes": { type: "string" },
  "scheduled-ralph-allow-network": { type: "string" },
  "scheduled-ralph-allow-mcp-tools": { type: "string" },
  "flow-json": { type: "string" },
  "flow-json-file": { type: "string" },
  "expected-fingerprint": { type: "string" },
  "watch-json": { type: "string" },
  "watch-json-file": { type: "string" },
  "existing-flow-json": { type: "string" },
  "existing-flow-json-file": { type: "string" },
  revision: { type: "string" },
  "flow-target": { type: "string" },
  "generation-mode": { type: "string" },
  param: { type: "string", multiple: true },
  "params-file": { type: "string" },
  "input-json": { type: "string" },
  "input-json-file": { type: "string" },
  "retry-current": { type: "boolean" },
  isolated: { type: "boolean" },
  "max-rounds": { type: "string" },
  "max-transitions": { type: "string" },
  "instruction-boundary-policy": { type: "string" },
  trace: { type: "boolean" },
  "context-pack": { type: "string", multiple: true },
  macro: { type: "string", multiple: true },
  "missed-run-policy": { type: "string" },
  "missed-run-grace-ms": { type: "string" },
  "retry-attempts": { type: "string" },
  "retry-min-ms": { type: "string" },
  "retry-max-ms": { type: "string" },
  "retry-factor": { type: "string" },
  "retry-randomize": { type: "string" },
  "dedupe-key": { type: "string" },
  "request-id": { type: "string" },
  "ttl-ms": { type: "string" },
  "max-duration-ms": { type: "string" },
  "concurrency-key": { type: "string" },
  "concurrency-limit": { type: "string" },
  "history-limit": { type: "string" },
  "max-catch-up-runs": { type: "string" },
  "event-type": { type: "string" },
  "event-kind": { type: "string" },
  "event-source": { type: "string" },
  "event-payload-json": { type: "string" },
  "event-dedupe-key": { type: "string" },
  "event-occurred-at": { type: "string" },
  "service-poll-ms": { type: "string" },
  "service-idle-shutdown-ms": { type: "string" },
  "service-abandoned-run-stale-ms": { type: "string" },
  "service-max-iterations": { type: "string" },
  "service-max-runs-per-tick": { type: "string" },
  "service-start-event-type": { type: "string" },
  "service-start-event-kind": { type: "string" },
  "service-start-event-dedupe-key": { type: "string" },
  "arguments-json": { type: "string" },
  "include-disabled": { type: "boolean" },
  agent: { type: "string" },
  phase: { type: "string" },
  "unused-days": { type: "string" },
  "never-used-days": { type: "string" },
  apply: { type: "boolean" },
  scope: { type: "string" },
  path: { type: "string" },
  "ralph-flow": { type: "string" },
  "flow-scope": { type: "string" },
  description: { type: "string" },
  profile: { type: "string", multiple: true },
  "expected-revision": { type: "string" },
  "expected-digest": { type: "string" },
  surface: { type: "string" },
  "include-content": { type: "boolean" },
  "include-workspaces": { type: "boolean" },
  "decisions-file": { type: "string" },
  "confirm-assignment-removal": { type: "boolean" },
  "metadata-json": { type: "string" },
  "manager-url": { type: "string" },
  "enrollment-key": { type: "string" },
  "display-name": { type: "string" },
} as const satisfies NonNullable<ParseArgsConfig["options"]>;

export const tokenizeCliArgs = (argv: string[]) =>
  parseArgs({
    args: argv,
    options: cliTokenOptions,
    allowPositionals: true,
    strict: true,
  });

export type CliTokenValues = ReturnType<typeof tokenizeCliArgs>["values"];
