import type { RalphFlow } from "../ralph.js";
import type { RalphStarterFlow } from "../ralph-starter-flows.js";

const RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS = 30 * 60;

const RALPH_VALIDATOR_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["decision", "confidence", "summary", "evidence", "remainingWork"],
  properties: {
    decision: { type: "string", enum: ["DONE", "CONTINUE", "RETRY", "ERROR"] },
    confidence: { type: "number", minimum: 0, maximum: 1 },
    summary: { type: "string" },
    evidence: { type: "array", items: { type: "string" }, maxItems: 30 },
    remainingWork: { type: "array", items: { type: "string" }, maxItems: 30 },
  },
} as const;

const autonomousCodeImprovementLoopFlow: RalphFlow = {
  schemaVersion: 1,
  id: "starter-autonomous-code-improvement-loop",
  alias: "autonomous-code-improvement-loop",
  name: "Autonomous Code Improvement Loop",
  description:
    "Bounded autonomous improvement cycle that discovers and scores evidence-backed work packages, verifies and reviews them, defers exhausted packages, and can be scheduled repeatedly without human intervention.",
  settings: {
    maxTransitions: 500,
    autonomy: {
      recoverFailedEnd: true,
      maxRecoveryAttempts: 3,
      transitionExhaustion: "checkpoint",
      recoveryExhaustion: "defer",
      deferToBlockId: "defer-scope",
    },
  },
  variables: [
    { name: "scopeRoot", type: "path", default: ".", required: false },
    { name: "scopeSelectionStrategy", type: "text", default: "priority", required: false },
    { name: "scopeRegistryFile", type: "path", default: ".machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json", required: false },
    { name: "scopeRegistryMarkdown", type: "path", default: ".machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md", required: false },
    { name: "scopeScanMaxDepth", type: "number", default: "4", required: false },
    { name: "scopeScanMaxResults", type: "number", default: "240", required: false },
    { name: "improvementPolicy", type: "text", default: "Prefer high-confidence improvements to correctness, reliability, UX, accessibility, performance, error handling, tests, or maintainability. Behavior changes are allowed when they are intentional, bounded, documented, and verified.", required: false },
    { name: "meaningfulThreshold", type: "text", default: "Only continue when there is concrete code, test, runtime, UX, accessibility, performance, or security evidence that the improvement is worth making now. Stop instead of inventing speculative cleanup, premature abstraction, cosmetic churn, or tiny nits.", required: false },
    { name: "riskTolerance", type: "text", default: "ambitious", required: false },
    { name: "implementationScope", type: "text", default: "auto-detect", required: false },
    { name: "excludePaths", type: "text", default: "node_modules, dist, build, coverage, target, .next, .nuxt, .turbo, .cache, vendor, generated, .machdoch", required: false },
    { name: "enableOnlineResearch", type: "boolean", default: "true", required: false },
    { name: "allowDependencyChanges", type: "boolean", default: "true", required: false },
    { name: "allowSchemaChanges", type: "boolean", default: "true", required: false },
    { name: "allowPublicApiChanges", type: "boolean", default: "true", required: false },
    { name: "verificationCommand", type: "text", default: "", required: false },
    { name: "enableVisualReview", type: "boolean", default: "false", required: false },
    { name: "targetUrl", type: "url", default: "", required: false },
    { name: "healthUrl", type: "url", default: "", required: false },
    { name: "screenshotPath", type: "path", default: "", required: false },
    { name: "maxImprovementPasses", type: "number", default: "8", required: false },
    { name: "maxVerificationRepairPasses", type: "number", default: "3", required: false },
    { name: "activeImprovementFile", type: "path", default: ".machdoch/ralph/code-improvements/active-improvement.json", required: false },
    { name: "completedImprovementsFile", type: "path", default: ".machdoch/ralph/code-improvements/completed-improvements.jsonl", required: false },
    { name: "improvementOutcomesFile", type: "path", default: ".machdoch/ralph/code-improvements/outcomes.jsonl", required: false },
    { name: "archivedImprovementsDirectory", type: "path", default: ".machdoch/ralph/code-improvements/archive", required: false },
    { name: "projectCommandsFile", type: "path", default: "{{run:artifactRoot}}/code-improvements/project-commands.json", required: false },
    { name: "candidateFile", type: "path", default: "{{run:artifactRoot}}/code-improvements/candidate.json", required: false },
    { name: "reviewFile", type: "path", default: "{{run:artifactRoot}}/code-improvements/review.json", required: false },
    { name: "gitSnapshotFile", type: "path", default: "{{run:artifactRoot}}/code-improvements/git-snapshot.json", required: false },
    { name: "gitDiffFile", type: "path", default: "{{run:artifactRoot}}/code-improvements/git-diff.json", required: false },
    { name: "improvementReportFile", type: "path", default: "{{run:artifactRoot}}/code-improvements/final-report.json", required: false },
    { name: "improvementReportMarkdown", type: "path", default: "{{run:artifactRoot}}/code-improvements/final-report.md", required: false },
    { name: "notesFile", type: "path", default: ".machdoch/ralph/code-improvements/RALPH_CODE_IMPROVEMENT_NOTES.md", required: false },
  ],
  blocks: [
    {
      id: "start",
      title: "Start",
      position: { x: 0, y: 0 },
      size: { width: 256, height: 140 },
      type: "START",
    },
    {
      id: "scan-scopes",
      title: "Scan Scope Evidence",
      position: { x: 700, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SCAN_SCOPE_EVIDENCE",
        rootPath: "{{scopeRoot:path=.}}",
        excludePaths: "{{excludePaths:text=node_modules, dist, build, coverage, target, .next, .nuxt, .turbo, .cache, vendor, generated, .machdoch}}",
        maxDepth: "{{scopeScanMaxDepth:number=4}}",
        maxResults: "{{scopeScanMaxResults:number=240}}",
      },
    },
    {
      id: "update-scope-registry",
      title: "Update Scope Registry",
      position: { x: 1040, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "UPDATE_SCOPE_REGISTRY",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md}}",
        strategy: "{{scopeSelectionStrategy:text=priority}}",
        includeMarkdown: true,
      },
    },
    {
      id: "select-scope",
      title: "Select Improvement Scope",
      position: { x: 1380, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SELECT_SCOPE",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        strategy: "{{scopeSelectionStrategy:text=priority}}",
      },
    },
    {
      id: "detect-project-commands",
      title: "Detect Project Commands",
      position: { x: 1720, y: -160 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "DETECT_PROJECT_COMMANDS",
        rootPath: "{{data:select-scope:scope.paths.0}}",
        outputPath:
          "{{projectCommandsFile:path=.machdoch/ralph/code-improvements/project-commands.json}}",
      },
    },
    {
      id: "read-completed-improvements",
      title: "Read Completed Improvements",
      position: { x: 1720, y: 40 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "QUERY_JSONL",
        path: "{{completedImprovementsFile:path=.machdoch/ralph/code-improvements/completed-improvements.jsonl}}",
        maxResults: 50,
        order: "newest",
      },
    },
    {
      id: "propose-improvements",
      title: "Propose Improvement Portfolio",
      position: { x: 2060, y: 40 },
      size: { width: 320, height: 250 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        maxAttempts: 2,
        schema: {
          type: "object",
          additionalProperties: false,
          required: ["projectConstitution", "candidates", "researchDecision"],
          properties: {
            projectConstitution: {
              type: "object",
              additionalProperties: false,
              required: ["purpose", "users", "outcomes", "technicalDirection", "constraints"],
              properties: {
                purpose: { type: "string" },
                users: { type: "array", items: { type: "string" } },
                outcomes: { type: "array", items: { type: "string" } },
                technicalDirection: { type: "array", items: { type: "string" } },
                constraints: { type: "array", items: { type: "string" } },
              },
            },
            candidates: {
              type: "array",
              minItems: 1,
              maxItems: 5,
              items: {
                type: "object",
                additionalProperties: false,
                required: ["id", "title", "evidence", "valueScore", "confidenceScore", "effortScore", "riskScore", "verificationPlan"],
                properties: {
                  id: { type: "string" },
                  title: { type: "string" },
                  evidence: { type: "array", items: { type: "string" } },
                  valueScore: { type: "number", minimum: 0, maximum: 100 },
                  confidenceScore: { type: "number", minimum: 0, maximum: 100 },
                  effortScore: { type: "number", minimum: 0, maximum: 100 },
                  riskScore: { type: "number", minimum: 0, maximum: 100 },
                  verificationPlan: { type: "array", items: { type: "string" } },
                },
              },
            },
            researchDecision: {
              type: "object",
              additionalProperties: false,
              required: ["needsResearch", "reason", "queries"],
              properties: {
                needsResearch: { type: "boolean" },
                reason: { type: "string" },
                queries: { type: "array", items: { type: "string" } },
              },
            },
          },
        },
        prompt:
          "Inspect selected scope {{result:select-scope}}, detected commands {{result:detect-project-commands}}, and the bounded relevant history {{result:read-completed-improvements}} without editing files. Infer a concise project constitution, then generate 3-5 materially different cohesive improvement packages. Score each from 0-100 for user/maintainer value, evidence confidence, expected effort, and risk. Prefer dependency-aware packages supported by runtime, test, complexity, churn, accessibility, performance, reliability, or correctness evidence. Identify only focused research needed to discriminate among the best candidates. Make bounded reversible assumptions autonomously; when credentials or external state are unavailable, leave that candidate for later and score the remaining candidates. Return only schema-valid JSON.",
      },
    },
    {
      id: "research-decision",
      title: "Use Online Research?",
      position: { x: 2400, y: -150 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'variables.enableOnlineResearch === "true" && lastData?.output?.researchDecision?.needsResearch === true',
        },
      },
    },
    {
      id: "improvement-research",
      title: "Improvement Research",
      position: { x: 2720, y: -180 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        webAccess: true,
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Use content enrichment only for the structured research decision in provisional portfolio {{data:propose-improvements:output}}. If search_web is available, run focused searches for current primary-source framework/library behavior, changelogs, release notes, accessibility guidance, performance recommendations, testing approaches, security advisories, and standards that discriminate among the leading packages. Use fetch_url on the best official or maintainer pages before relying on them, and inspect local package/config metadata for version assumptions. Keep findings concise with source links, freshness/version notes, practical implications, explicit non-findings, and which candidates should be promoted, revised, or rejected. If web search is unavailable, say so and rely on local evidence plus provided URLs. Do not research broadly just to find extra work.",
    },
    {
      id: "choose-improvement",
      title: "Plan Improvement Package",
      position: { x: 3060, y: 0 },
      size: { width: 320, height: 250 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{candidateFile:path=.machdoch/ralph/code-improvements/candidate.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: [
            "decision",
            "rationale",
            "scopeAnalysis",
            "researchDecision",
            "selectedCandidate",
            "rejectedCandidates",
            "stopReason",
          ],
          properties: {
            decision: { type: "string", enum: ["IMPLEMENT", "STOP", "DEFER"] },
            rationale: { type: "string" },
            scopeAnalysis: {
              type: "object",
              required: ["scope", "scopeCluster", "signals", "constraints", "stopSignals"],
              properties: {
                scope: {
                  type: "object",
                  required: ["id", "title", "kind", "paths", "risk"],
                  properties: {
                    id: { type: "string" },
                    title: { type: "string" },
                    kind: { type: "string" },
                    paths: { type: "array", items: { type: "string" } },
                    globs: { type: "array", items: { type: "string" } },
                    tags: { type: "array", items: { type: "string" } },
                    priority: { type: "number" },
                    risk: { type: "string", enum: ["low", "medium", "high"] },
                  },
                },
                scopeCluster: {
                  type: "object",
                  required: ["rootScopeId", "scopeIds", "paths", "risk", "rationale"],
                  properties: {
                    rootScopeId: { type: "string" },
                    scopeIds: { type: "array", items: { type: "string" } },
                    paths: { type: "array", items: { type: "string" } },
                    globs: { type: "array", items: { type: "string" } },
                    tags: { type: "array", items: { type: "string" } },
                    risk: { type: "string", enum: ["low", "medium", "high"] },
                    rationale: { type: "array", items: { type: "string" } },
                  },
                },
                signals: { type: "array", items: { type: "string" } },
                constraints: { type: "array", items: { type: "string" } },
                stopSignals: { type: "array", items: { type: "string" } },
              },
            },
            researchDecision: {
              type: "object",
              required: ["needsResearch", "reason", "queries"],
              properties: {
                needsResearch: { type: "boolean" },
                reason: { type: "string" },
                queries: { type: "array", items: { type: "string" } },
              },
            },
            selectedCandidate: {
              anyOf: [
                {
                  type: "object",
                  additionalProperties: false,
                  required: [
                    "id",
                    "title",
                    "evidence",
                    "value",
                    "currentBehavior",
                    "proposedBehavior",
                    "relatedChanges",
                    "affectedFiles",
                    "acceptanceCriteria",
                    "expectedOutcome",
                    "riskAssessment",
                    "verificationPlan",
                    "verificationTier",
                    "reviewTier",
                    "rollbackNotes",
                    "remainingRelatedWork",
                  ],
                  properties: {
                id: { type: "string" },
                title: { type: "string" },
                evidence: { type: "array", items: { type: "string" } },
                value: { type: "string" },
                currentBehavior: { type: "string" },
                proposedBehavior: { type: "string" },
                relatedChanges: {
                  type: "array",
                  items: {
                    type: "object",
                    required: ["title", "description", "affectedFiles"],
                    properties: {
                      title: { type: "string" },
                      description: { type: "string" },
                      affectedFiles: { type: "array", items: { type: "string" } },
                    },
                  },
                },
                affectedFiles: { type: "array", items: { type: "string" } },
                acceptanceCriteria: { type: "array", items: { type: "string" } },
                expectedOutcome: { type: "string" },
                riskAssessment: { type: "string" },
                verificationPlan: { type: "array", items: { type: "string" } },
                verificationTier: { type: "string", enum: ["focused", "standard", "broad"] },
                reviewTier: { type: "string", enum: ["validator-only", "strict"] },
                rollbackNotes: { type: "array", items: { type: "string" } },
                remainingRelatedWork: { type: "array", items: { type: "string" } },
                  },
                },
                {
                  type: "object",
                  properties: {},
                  additionalProperties: false,
                },
              ],
            },
            rejectedCandidates: {
              type: "array",
              items: {
                type: "object",
                required: ["id", "reason"],
                properties: {
                  id: { type: "string" },
                  title: { type: "string" },
                  reason: { type: "string" },
                  evidence: { type: "array", items: { type: "string" } },
                },
              },
            },
            stopReason: { type: "string" },
          },
        },
        prompt:
          "Refine, rescore, and select from provisional portfolio {{data:propose-improvements:output}} after focused research {{summary:improvement-research}}. Inspect selected JSON scope and dependency-aware scope cluster {{result:select-scope}} without editing files. Use detected commands {{result:detect-project-commands}}, bounded completed improvement history {{result:read-completed-improvements}}, latest completed append {{result:append-completed-improvement}}, implementationScope={{implementationScope:text=auto-detect}}, riskTolerance={{riskTolerance:text=ambitious}}, excludePaths={{excludePaths:text=}}, and policy {{improvementPolicy:text=}}. Reject candidates contradicted by research and revise acceptance criteria when current primary sources change the plan. Return decision IMPLEMENT only for the highest-value cohesive work package, not one micro-change: select 2-5 tightly related changes when they share evidence, files, tests, or acceptance criteria and are safer/productive to complete together. The package must use the schema fields id (stable kebab-case), title, evidence, value (local or primary-source user/maintainer value), currentBehavior, proposedBehavior, relatedChanges with affectedFiles, affectedFiles, acceptanceCriteria, expectedOutcome, riskAssessment, verificationTier (focused, standard, or broad), reviewTier (validator-only or strict), verificationPlan, rollbackNotes, and remainingRelatedWork. Prefer focused verification for low-risk localized packages; require broad verification and strict review for shared contracts, persistence, IPC/API, schemas, dependencies, config, or broad UI behavior. Behavior changes, dependencies, schemas, migrations, and public APIs are allowed when necessary for the selected outcome and covered by rollback and verification plans. Make the best bounded reversible product/domain assumption from repository evidence. Return DEFER only when unavailable external credentials or state make every candidate impossible now; otherwise pick autonomously. Return STOP when the remaining ideas are speculative, tiny nits, cosmetic churn, premature abstractions, duplicate completed work, or fail threshold {{meaningfulThreshold:text=}}. If decision is STOP or DEFER, selectedCandidate must be {} and stopReason must explain the evidence-backed reason. Return only schema-valid JSON.",
      },
    },
    {
      id: "has-actionable-improvement",
      title: "Actionable Improvement?",
      position: { x: 3400, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'context.resultsByBlock?.["choose-improvement"]?.data?.output?.decision === "IMPLEMENT" && context.resultsByBlock?.["choose-improvement"]?.data?.output?.selectedCandidate && Object.keys(context.resultsByBlock["choose-improvement"].data.output.selectedCandidate).length > 0',
        },
      },
    },
    {
      id: "selection-is-deferred",
      title: "Selection Deferred?",
      position: { x: 3560, y: 260 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "String(context.resultsByBlock?.['choose-improvement']?.data?.output?.decision ?? '').toUpperCase() === 'DEFER'",
        },
      },
    },
    {
      id: "find-active-improvement",
      title: "Find Existing Active Improvement",
      position: { x: 3720, y: -220 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FILE_EXISTS",
        path: "{{activeImprovementFile:path=.machdoch/ralph/code-improvements/active-improvement.json}}",
      },
    },
    {
      id: "archive-superseded-improvement",
      title: "Archive Superseded Improvement",
      position: { x: 3880, y: -260 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "ARCHIVE_FILE",
        path: "{{activeImprovementFile:path=.machdoch/ralph/code-improvements/active-improvement.json}}",
        rootPath:
          "{{archivedImprovementsDirectory:path=.machdoch/ralph/code-improvements/archive}}",
      },
    },
    {
      id: "write-active-improvement",
      title: "Track Active Improvement",
      position: { x: 3720, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "WRITE_JSON",
        path: "{{activeImprovementFile:path=.machdoch/ralph/code-improvements/active-improvement.json}}",
        input: "{{data:choose-improvement:output.selectedCandidate}}",
      },
    },
    {
      id: "git-snapshot-before",
      title: "Git Snapshot",
      position: { x: 4060, y: -180 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_SNAPSHOT",
        cwd: ".",
        outputPath:
          "{{gitSnapshotFile:path=.machdoch/ralph/code-improvements/git-snapshot.json}}",
      },
    },
    {
      id: "count-improvement-pass",
      title: "Count Improvement Pass",
      position: { x: 4060, y: 230 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        counterName:
          "autonomous-code-improvement-loop.implementation-pass.{{data:select-scope:scope.id}}.{{data:choose-improvement:output.selectedCandidate.id}}",
        maxAttempts: "{{maxImprovementPasses:number=8}}",
      },
    },
    {
      id: "baseline-verification",
      title: "Record Verification Baseline",
      position: { x: 4060, y: -360 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{verificationCommand:text=}}",
        fallbackCommand: "{{data:detect-project-commands:focusedVerificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "implement-improvement",
      title: "Implement Improvement",
      position: { x: 4060, y: 40 },
      size: { width: 320, height: 250 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 4,
      },
      type: "PROMPT",
      prompt:
        "Implement the active code improvement package at {{activeImprovementFile:path=.machdoch/ralph/code-improvements/active-improvement.json}} using package {{data:choose-improvement:output.selectedCandidate}}, selected scope cluster {{result:select-scope}}, focused research {{summary:improvement-research}}, deterministic baseline {{result:git-snapshot-before}}, verification baseline {{result:baseline-verification}}, detected commands, pass count, latest validator/reviewer feedback, scope guard {{result:scope-change-guard}}, work-yield evidence {{data:work-yield-analysis:output}}, and verification routing. Complete the cohesive package within selected paths plus required adjacent tests/docs/imports. Favor correctness, reliability, UX, accessibility, performance, and maintainability; security-only hardening is low priority in this nonsecurity flow unless fixing an observed regression. Add meaningful tests, avoid speculative cleanup, and repair only new/worsened failures. Dependency changes use allowDependencyChanges={{allowDependencyChanges:boolean=true}}, schemas/migrations use allowSchemaChanges={{allowSchemaChanges:boolean=true}}, and public APIs use allowPublicApiChanges={{allowPublicApiChanges:boolean=true}} when necessary and verified. Make bounded reversible decisions autonomously, do not start/restart servers, and append a concise evidence note to {{notesFile:path=.machdoch/ralph/code-improvements/RALPH_CODE_IMPROVEMENT_NOTES.md}}.",
    },
    {
      id: "select-verification-command",
      title: "Select Verification Tier",
      position: { x: 4400, y: -140 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "TRANSFORM_JSON",
        input: "{}",
        expression:
          "(() => { const candidate = context.resultsByBlock?.get?.('choose-improvement')?.data?.output?.selectedCandidate ?? {}; const commands = context.resultsByBlock?.get?.('detect-project-commands')?.data ?? {}; const requestedTier = String(candidate.verificationTier ?? candidate.riskAssessment?.verificationTier ?? '').toLowerCase(); const requestedReviewTier = String(candidate.reviewTier ?? candidate.riskAssessment?.reviewTier ?? '').toLowerCase(); const riskText = JSON.stringify([candidate.risk, candidate.riskAssessment, candidate.affectedFiles, candidate.relatedChanges, candidate.acceptanceCriteria]).toLowerCase(); const highRisk = /(database|migration|schema|ipc|api|dependency|package|lockfile|persistence|public api|contract)/u.test(riskText); const tier = highRisk || requestedTier === 'broad' || requestedTier === 'strict' ? 'broad' : requestedTier === 'standard' ? 'standard' : 'focused'; const detectedCommand = tier === 'broad' ? commands.broadVerificationCommand : tier === 'standard' ? commands.standardVerificationCommand : commands.focusedVerificationCommand; const command = (variables.verificationCommand ?? '').trim() || detectedCommand || commands.verificationCommand || ''; const reviewTier = highRisk || requestedReviewTier === 'strict' || tier === 'broad' ? 'strict' : 'validator-only'; return { tier, command, reviewTier, highRisk, source: (variables.verificationCommand ?? '').trim() ? 'variable' : 'detected', focusedCommand: commands.focusedVerificationCommand || '', standardCommand: commands.standardVerificationCommand || '', broadCommand: commands.broadVerificationCommand || '' }; })()",
      },
    },
    {
      id: "verification-decision",
      title: "Run Verification?",
      position: { x: 4400, y: 40 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "Boolean(context.resultsByBlock?.['select-verification-command']?.data?.output?.command?.trim())",
        },
      },
    },
    {
      id: "run-verification",
      title: "Run Verification",
      position: { x: 4720, y: -110 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{data:select-verification-command:output.command}}",
        fallbackCommand: "{{data:detect-project-commands:focusedVerificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "count-verification-repair",
      title: "Count Verification Repair",
      position: { x: 4720, y: 330 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        counterName:
          "autonomous-code-improvement-loop.verification-repair.{{data:select-scope:scope.id}}.{{data:choose-improvement:output.selectedCandidate.id}}",
        maxAttempts: "{{maxVerificationRepairPasses:number=3}}",
      },
    },
    {
      id: "fix-validation-failures",
      title: "Fix Validation Failures",
      position: { x: 4720, y: 120 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "PROMPT",
      prompt:
        "Fix verification failures from {{result:run-verification}} that were caused by the current code improvement package, comparing signatures with pre-change baseline {{result:baseline-verification}}. Repair only new or worsened failures. Keep fixes scoped to active package {{data:choose-improvement:output.selectedCandidate}} and selected scope cluster {{result:select-scope}}. Do not broaden the package or start unrelated work.",
    },
    {
      id: "visual-decision",
      title: "Run Visual Review?",
      position: { x: 5060, y: 40 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'variables.enableVisualReview === "true" && (Boolean(variables.targetUrl?.trim()) || Boolean(variables.screenshotPath?.trim()))',
        },
      },
    },
    {
      id: "visual-review",
      title: "Visual Review",
      position: { x: 5380, y: 40 },
      size: { width: 280, height: 190 },
      type: "UTILITY",
      utility: {
        type: "UI_ANALYZE",
        adapter: "auto",
        targetUrl: "{{targetUrl:url=}}",
        screenshotPath: "{{screenshotPath:path=}}",
        server: {
          mode: "existing",
          healthUrl: "{{healthUrl:url=}}",
        },
        checks: {
          screenshots: true,
          accessibility: true,
          console: true,
          network: true,
          responsive: true,
        },
        viewports: [
          { name: "desktop", width: 1280, height: 900 },
          { name: "tablet", width: 768, height: 1024 },
          { name: "mobile", width: 390, height: 844 },
          { name: "small-mobile", width: 320, height: 568 },
        ],
        timeoutSeconds: 30,
        fullPage: true,
        waitUntil: "domcontentloaded",
      },
    },
    {
      id: "git-diff-summary",
      title: "Git Diff Summary",
      position: { x: 5720, y: -100 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_DIFF_SUMMARY",
        cwd: ".",
        outputPath:
          "{{gitDiffFile:path=.machdoch/ralph/code-improvements/git-diff.json}}",
      },
    },
    {
      id: "scope-change-guard",
      title: "Guard Improvement Scope",
      position: { x: 5880, y: -260 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CHANGE_SCOPE_GUARD",
        input:
          "{\"scope\":{{data:select-scope:scope}},\"gitSummary\":{{data:git-diff-summary}}}",
      },
    },
    {
      id: "work-yield-analysis",
      title: "Assess Improvement Work Yield",
      position: { x: 6040, y: -180 },
      size: { width: 300, height: 190 },
      type: "UTILITY",
      utility: {
        type: "TRANSFORM_JSON",
        input: "{}",
        expression:
          "(() => { const diff = context.resultsByBlock?.get?.('git-diff-summary'); const baseline = context.resultsByBlock?.get?.('git-snapshot-before'); const current = Array.isArray(diff?.data?.files) ? diff.data.files : []; const before = new Map((Array.isArray(baseline?.data?.files) ? baseline.data.files : []).map((file) => [String(file?.path ?? '').replace(/\\\\/gu, '/'), file?.signature])); const changedFiles = current.filter((file) => before.get(String(file?.path ?? '').replace(/\\\\/gu, '/')) !== file?.signature).map((file) => String(file?.path ?? '').replace(/\\\\/gu, '/')).filter(Boolean); return { changedFiles, changedFileCount: changedFiles.length, producedWork: changedFiles.length > 0, diffOutput: diff?.output ?? '', scopeGuard: context.resultsByBlock?.get?.('scope-change-guard')?.output ?? '' }; })()",
      },
    },
    {
      id: "useful-work-produced",
      title: "Useful Work Produced?",
      position: { x: 6220, y: -120 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "lastData?.producedWork === true && lastData?.scopeGuard === 'IN_SCOPE'",
        },
      },
    },
    {
      id: "review-tier-decision",
      title: "Strict Review?",
      position: { x: 6060, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'context.resultsByBlock?.["select-verification-command"]?.data?.output?.reviewTier === "strict"',
        },
      },
    },
    {
      id: "independent-review",
      title: "Independent Review",
      position: { x: 6400, y: 0 },
      size: { width: 320, height: 250 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{reviewFile:path=.machdoch/ralph/code-improvements/review.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          additionalProperties: false,
          required: ["decision", "summary", "findings", "behaviorChangeAssessment", "securityRegressionAssessment", "verificationAssessment"],
          properties: {
            decision: { type: "string", enum: ["PASS", "FIX", "DEFER"] },
            summary: { type: "string" },
            findings: {
              type: "array",
              items: {
                type: "object",
                required: ["severity", "title", "evidence", "requiredFix"],
                properties: {
                  severity: { type: "string", enum: ["critical", "high", "medium", "low", "info"] },
                  title: { type: "string" },
                  evidence: { type: "string" },
                  requiredFix: { type: "string" },
                  affectedFiles: { type: "array", items: { type: "string" } },
                },
              },
            },
            behaviorChangeAssessment: { type: "string" },
            securityRegressionAssessment: { type: "string" },
            verificationAssessment: { type: "string" },
          },
        },
        prompt:
          "Review the current code improvement package as a separate reviewer because verification routing requested strict review. Active package: {{data:choose-improvement:output.selectedCandidate}}. Scope cluster: {{result:select-scope}}. Diff: {{result:git-diff-summary}}. Baseline verification: {{result:baseline-verification}}. Post-change verification: {{result:run-verification}}. Visual review: {{result:visual-review}}. Evaluate only the active package, selected scope cluster, and required adjacent tests/docs/imports. Ignore unrelated workspace changes outside that scope unless they directly break verification of this package. Check functionality, intentional behavior changes, tests, docs, maintainability, complexity, accessibility, and performance claims. Return decision PASS when the package is cohesive, bounded, justified, and introduced no new regression relative to baseline. Return FIX when specific autonomous repairs remain. Return DEFER only when unavailable external credentials or state prevent completion after bounded reversible assumptions have been exhausted. Return only schema-valid JSON.",
      },
    },
    {
      id: "review-is-deferred",
      title: "Review Deferred?",
      position: { x: 6580, y: 280 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "String(context.resultsByBlock?.['independent-review']?.data?.output?.decision ?? '').toUpperCase() === 'DEFER'",
        },
      },
    },
    {
      id: "review-needs-fix",
      title: "Review Needs Fix?",
      position: { x: 6740, y: 280 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "String(context.resultsByBlock?.['independent-review']?.data?.output?.decision ?? '').toUpperCase() === 'FIX'",
        },
      },
    },
    {
      id: "validate-improvement",
      title: "Validate Improvement",
      position: { x: 6740, y: 0 },
      size: { width: 320, height: 250 },
      type: "UTILITY",
      utility: {
        type: "VALIDATOR_JSON",
        maxAttempts: 2,
        schema: RALPH_VALIDATOR_SCHEMA,
        prompt:
          "Validate the autonomous code improvement package against selected scope {{result:select-scope}}, strict review {{data:independent-review:output}}, baseline/post-change verification, visual review, scope guard {{result:scope-change-guard}}, work-yield evidence {{data:work-yield-analysis:output}}, and git diff {{result:git-diff-summary}}. Ignore unrelated workspace changes. Return DONE only when acceptance criteria pass, scope guard is IN_SCOPE, deterministic work yield proves relevant changed files, and no new/worsened failure exists. Return CONTINUE for bounded remaining work, RETRY for own regressions or reviewer FIX, and ERROR only for unavailable external state or repeated non-progress. Security-only enhancements are not a completion requirement in this nonsecurity flow. Never wait for a human; include confidence, summary, evidence, and remainingWork.",
      },
    },
    {
      id: "final-report",
      title: "Final Improvement Report",
      position: { x: 7080, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{improvementReportFile:path=.machdoch/ralph/code-improvements/final-report.json}}",
        outputPath:
          "{{improvementReportMarkdown:path=.machdoch/ralph/code-improvements/final-report.md}}",
      },
    },
    {
      id: "read-active-improvement",
      title: "Read Active Improvement",
      position: { x: 7420, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "READ_JSON",
        path: "{{activeImprovementFile:path=.machdoch/ralph/code-improvements/active-improvement.json}}",
      },
    },
    {
      id: "append-completed-improvement",
      title: "Append Completed Improvement",
      position: { x: 7760, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{completedImprovementsFile:path=.machdoch/ralph/code-improvements/completed-improvements.jsonl}}",
        input: "{{data:read-active-improvement:json}}",
      },
    },
    {
      id: "archive-active-improvement",
      title: "Archive Active Improvement",
      position: { x: 8100, y: -120 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "ARCHIVE_FILE",
        path: "{{activeImprovementFile:path=.machdoch/ralph/code-improvements/active-improvement.json}}",
        rootPath:
          "{{archivedImprovementsDirectory:path=.machdoch/ralph/code-improvements/archive}}",
      },
    },
    {
      id: "mark-scope-result",
      title: "Mark Scope Result",
      position: { x: 3720, y: 300 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md}}",
        result: "DONE",
        includeMarkdown: true,
      },
    },
    {
      id: "retained-active-report",
      title: "Retained Active Improvement Report",
      position: { x: 7080, y: 120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{improvementReportFile:path=.machdoch/ralph/code-improvements/final-report.json}}",
        outputPath:
          "{{improvementReportMarkdown:path=.machdoch/ralph/code-improvements/final-report.md}}",
      },
    },
    {
      id: "defer-scope",
      title: "Defer Exhausted Package",
      position: { x: 3720, y: 500 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md}}",
        result: "DEFERRED_AFTER_BOUNDED_REPAIR",
        includeMarkdown: true,
      },
    },
    {
      id: "mark-stop-scope",
      title: "Mark No-Action Scope",
      position: { x: 3720, y: 680 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md}}",
        result: "STOP_NO_MEANINGFUL_WORK",
        includeMarkdown: true,
      },
    },
    {
      id: "mark-invalid-scope",
      title: "Mark Invalid Scope Outcome",
      position: { x: 3720, y: 860 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md}}",
        result: "INVALID_OUTPUT",
        includeMarkdown: true,
      },
    },
    {
      id: "record-done-outcome",
      title: "Record Completed Improvement Outcome",
      position: { x: 8260, y: -320 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{improvementOutcomesFile:path=.machdoch/ralph/code-improvements/outcomes.jsonl}}",
        input: "{\"outcome\":\"DONE\",\"scopeId\":\"{{data:select-scope:scope.id}}\",\"candidateId\":\"{{data:choose-improvement:output.selectedCandidate.id}}\"}",
      },
    },
    {
      id: "record-deferred-outcome",
      title: "Record Deferred Improvement Outcome",
      position: { x: 8260, y: 60 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{improvementOutcomesFile:path=.machdoch/ralph/code-improvements/outcomes.jsonl}}",
        input: "{\"outcome\":\"DEFER\",\"scopeRoot\":\"{{scopeRoot:path=.}}\"}",
      },
    },
    {
      id: "record-stop-outcome",
      title: "Record No-Action Improvement Outcome",
      position: { x: 8260, y: 260 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{improvementOutcomesFile:path=.machdoch/ralph/code-improvements/outcomes.jsonl}}",
        input: "{\"outcome\":\"STOP\",\"scopeRoot\":\"{{scopeRoot:path=.}}\",\"reason\":\"No evidence-backed package cleared the threshold.\"}",
      },
    },
    {
      id: "record-invalid-outcome",
      title: "Record Invalid Improvement Outcome",
      position: { x: 8260, y: 460 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{improvementOutcomesFile:path=.machdoch/ralph/code-improvements/outcomes.jsonl}}",
        input: "{\"outcome\":\"INVALID\",\"scopeRoot\":\"{{scopeRoot:path=.}}\",\"reason\":\"Discovery, state, or validation output was invalid.\"}",
      },
    },
    {
      id: "scope-cycle-complete",
      title: "Scope Cycle Complete?",
      position: { x: 4060, y: 300 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "['EMPTY', 'ERROR'].includes(String(context.resultsByBlock?.['scan-scopes']?.output ?? '')) || context.resultsByBlock?.['select-scope']?.output === 'EMPTY' || ['mark-scope-result', 'defer-scope', 'mark-stop-scope', 'mark-invalid-scope'].some((id) => context.resultsByBlock?.[id]?.data?.cycleCompleted === true)",
        },
      },
    },
    {
      id: "success",
      title: "No Meaningful Improvements",
      position: { x: 4400, y: 300 },
      size: { width: 280, height: 114 },
      type: "END",
      status: "success",
    },
    {
      id: "deferred",
      title: "Active Improvement Retained for Retry",
      position: { x: 4400, y: 520 },
      size: { width: 280, height: 114 },
      type: "END",
      status: "success",
    },
  ],
  edges: [
    { id: "start-to-scan-scopes", from: "start", fromOutput: "SUCCESS", to: "scan-scopes" },
    { id: "scan-scopes-to-update", from: "scan-scopes", fromOutput: "SUCCESS", to: "update-scope-registry" },
    { id: "scan-scopes-empty", from: "scan-scopes", fromOutput: "EMPTY", to: "record-stop-outcome" },
    { id: "scan-scopes-error", from: "scan-scopes", fromOutput: "ERROR", to: "record-invalid-outcome" },
    { id: "update-registry-to-select", from: "update-scope-registry", fromOutput: "SUCCESS", to: "select-scope" },
    { id: "update-registry-empty", from: "update-scope-registry", fromOutput: "EMPTY", to: "record-stop-outcome" },
    { id: "update-registry-error", from: "update-scope-registry", fromOutput: "ERROR", to: "record-invalid-outcome" },
    { id: "select-scope-to-detect", from: "select-scope", fromOutput: "SELECTED", to: "detect-project-commands" },
    { id: "select-scope-empty", from: "select-scope", fromOutput: "EMPTY", to: "record-stop-outcome" },
    { id: "select-scope-error", from: "select-scope", fromOutput: "ERROR", to: "record-invalid-outcome" },
    { id: "detect-success-to-history", from: "detect-project-commands", fromOutput: "SUCCESS", to: "read-completed-improvements" },
    { id: "detect-empty-to-history", from: "detect-project-commands", fromOutput: "EMPTY", to: "read-completed-improvements" },
    { id: "detect-error-to-history", from: "detect-project-commands", fromOutput: "ERROR", to: "read-completed-improvements" },
    { id: "history-success-to-propose", from: "read-completed-improvements", fromOutput: "SUCCESS", to: "propose-improvements" },
    { id: "history-empty-to-propose", from: "read-completed-improvements", fromOutput: "EMPTY", to: "propose-improvements" },
    { id: "history-not-found-to-propose", from: "read-completed-improvements", fromOutput: "NOT_FOUND", to: "propose-improvements" },
    { id: "history-invalid-to-propose", from: "read-completed-improvements", fromOutput: "INVALID", to: "propose-improvements" },
    { id: "history-error-to-propose", from: "read-completed-improvements", fromOutput: "ERROR", to: "propose-improvements" },
    { id: "propose-to-research-decision", from: "propose-improvements", fromOutput: "SUCCESS", to: "research-decision" },
    { id: "propose-invalid", from: "propose-improvements", fromOutput: "INVALID", to: "mark-invalid-scope" },
    { id: "propose-error", from: "propose-improvements", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "research-decision-run", from: "research-decision", fromOutput: "MATCH", to: "improvement-research" },
    { id: "research-decision-skip", from: "research-decision", fromOutput: "NO_MATCH", to: "choose-improvement" },
    { id: "research-decision-error", from: "research-decision", fromOutput: "ERROR", to: "choose-improvement" },
    { id: "research-to-refine", from: "improvement-research", fromOutput: "SUCCESS", to: "choose-improvement" },
    { id: "research-error-to-refine", from: "improvement-research", fromOutput: "ERROR", to: "choose-improvement" },
    { id: "choose-to-actionable", from: "choose-improvement", fromOutput: "SUCCESS", to: "has-actionable-improvement" },
    { id: "choose-invalid", from: "choose-improvement", fromOutput: "INVALID", to: "mark-invalid-scope" },
    { id: "choose-error", from: "choose-improvement", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "actionable-to-find-active", from: "has-actionable-improvement", fromOutput: "MATCH", to: "find-active-improvement" },
    { id: "not-actionable-to-classify", from: "has-actionable-improvement", fromOutput: "NO_MATCH", to: "selection-is-deferred" },
    { id: "actionable-error", from: "has-actionable-improvement", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "selection-deferred", from: "selection-is-deferred", fromOutput: "MATCH", to: "defer-scope" },
    { id: "selection-stopped", from: "selection-is-deferred", fromOutput: "NO_MATCH", to: "mark-stop-scope" },
    { id: "selection-classification-error", from: "selection-is-deferred", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "active-improvement-exists", from: "find-active-improvement", fromOutput: "EXISTS", to: "archive-superseded-improvement" },
    { id: "active-improvement-missing", from: "find-active-improvement", fromOutput: "MISSING", to: "write-active-improvement" },
    { id: "active-improvement-check-error", from: "find-active-improvement", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "superseded-archive-to-write", from: "archive-superseded-improvement", fromOutput: "SUCCESS", to: "write-active-improvement" },
    { id: "superseded-archive-missing-to-write", from: "archive-superseded-improvement", fromOutput: "NOT_FOUND", to: "write-active-improvement" },
    { id: "superseded-archive-error", from: "archive-superseded-improvement", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "write-to-snapshot", from: "write-active-improvement", fromOutput: "SUCCESS", to: "git-snapshot-before" },
    { id: "write-invalid", from: "write-active-improvement", fromOutput: "INVALID", to: "mark-invalid-scope" },
    { id: "write-error", from: "write-active-improvement", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "snapshot-to-baseline", from: "git-snapshot-before", fromOutput: "SUCCESS", to: "baseline-verification" },
    { id: "snapshot-error-to-baseline", from: "git-snapshot-before", fromOutput: "ERROR", to: "baseline-verification" },
    { id: "baseline-success-to-count", from: "baseline-verification", fromOutput: "SUCCESS", to: "count-improvement-pass" },
    { id: "baseline-failed-to-count", from: "baseline-verification", fromOutput: "FAILED", to: "count-improvement-pass" },
    { id: "baseline-error-to-count", from: "baseline-verification", fromOutput: "ERROR", to: "count-improvement-pass" },
    { id: "count-improvement-pass-continue", from: "count-improvement-pass", fromOutput: "CONTINUE", to: "implement-improvement" },
    { id: "count-improvement-pass-limit", from: "count-improvement-pass", fromOutput: "LIMIT_REACHED", to: "defer-scope" },
    { id: "count-improvement-pass-error", from: "count-improvement-pass", fromOutput: "ERROR", to: "defer-scope" },
    { id: "implement-to-verification-tier", from: "implement-improvement", fromOutput: "SUCCESS", to: "select-verification-command" },
    { id: "implement-error", from: "implement-improvement", fromOutput: "ERROR", to: "defer-scope" },
    { id: "verification-tier-to-decision", from: "select-verification-command", fromOutput: "SUCCESS", to: "verification-decision" },
    { id: "verification-tier-error", from: "select-verification-command", fromOutput: "ERROR", to: "verification-decision" },
    { id: "verification-decision-run", from: "verification-decision", fromOutput: "MATCH", to: "run-verification" },
    { id: "verification-decision-skip", from: "verification-decision", fromOutput: "NO_MATCH", to: "visual-decision" },
    { id: "verification-decision-error", from: "verification-decision", fromOutput: "ERROR", to: "visual-decision" },
    { id: "verification-success-to-visual", from: "run-verification", fromOutput: "SUCCESS", to: "visual-decision" },
    { id: "verification-failed-to-repair-counter", from: "run-verification", fromOutput: "FAILED", to: "count-verification-repair" },
    { id: "verification-error-to-repair-counter", from: "run-verification", fromOutput: "ERROR", to: "count-verification-repair" },
    { id: "repair-counter-to-fix", from: "count-verification-repair", fromOutput: "CONTINUE", to: "fix-validation-failures" },
    { id: "repair-counter-limit", from: "count-verification-repair", fromOutput: "LIMIT_REACHED", to: "defer-scope" },
    { id: "repair-counter-error", from: "count-verification-repair", fromOutput: "ERROR", to: "defer-scope" },
    { id: "fix-validation-to-decision", from: "fix-validation-failures", fromOutput: "SUCCESS", to: "verification-decision" },
    { id: "fix-validation-error", from: "fix-validation-failures", fromOutput: "ERROR", to: "defer-scope" },
    { id: "visual-decision-run", from: "visual-decision", fromOutput: "MATCH", to: "visual-review" },
    { id: "visual-decision-skip", from: "visual-decision", fromOutput: "NO_MATCH", to: "git-diff-summary" },
    { id: "visual-decision-error", from: "visual-decision", fromOutput: "ERROR", to: "git-diff-summary" },
    { id: "visual-success-to-diff", from: "visual-review", fromOutput: "SUCCESS", to: "git-diff-summary" },
    { id: "visual-unavailable-to-diff", from: "visual-review", fromOutput: "UNAVAILABLE", to: "git-diff-summary" },
    { id: "visual-error-to-diff", from: "visual-review", fromOutput: "ERROR", to: "git-diff-summary" },
    { id: "diff-success-to-scope-guard", from: "git-diff-summary", fromOutput: "SUCCESS", to: "scope-change-guard" },
    { id: "diff-empty-to-scope-guard", from: "git-diff-summary", fromOutput: "EMPTY", to: "scope-change-guard" },
    { id: "diff-error-to-scope-guard", from: "git-diff-summary", fromOutput: "ERROR", to: "scope-change-guard" },
    { id: "scope-guard-in-scope", from: "scope-change-guard", fromOutput: "IN_SCOPE", to: "work-yield-analysis" },
    { id: "scope-guard-out-of-scope", from: "scope-change-guard", fromOutput: "OUT_OF_SCOPE", to: "count-improvement-pass" },
    { id: "scope-guard-empty", from: "scope-change-guard", fromOutput: "EMPTY", to: "count-improvement-pass" },
    { id: "scope-guard-error", from: "scope-change-guard", fromOutput: "ERROR", to: "count-improvement-pass" },
    { id: "work-yield-to-decision", from: "work-yield-analysis", fromOutput: "SUCCESS", to: "useful-work-produced" },
    { id: "work-yield-error-to-count", from: "work-yield-analysis", fromOutput: "ERROR", to: "count-improvement-pass" },
    { id: "useful-work-to-review", from: "useful-work-produced", fromOutput: "MATCH", to: "review-tier-decision" },
    { id: "no-useful-work-to-count", from: "useful-work-produced", fromOutput: "NO_MATCH", to: "count-improvement-pass" },
    { id: "useful-work-error-to-count", from: "useful-work-produced", fromOutput: "ERROR", to: "count-improvement-pass" },
    { id: "review-tier-strict", from: "review-tier-decision", fromOutput: "MATCH", to: "independent-review" },
    { id: "review-tier-validator-only", from: "review-tier-decision", fromOutput: "NO_MATCH", to: "validate-improvement" },
    { id: "review-tier-error-to-validate", from: "review-tier-decision", fromOutput: "ERROR", to: "validate-improvement" },
    { id: "review-to-defer-check", from: "independent-review", fromOutput: "SUCCESS", to: "review-is-deferred" },
    { id: "review-invalid", from: "independent-review", fromOutput: "INVALID", to: "mark-invalid-scope" },
    { id: "review-error", from: "independent-review", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "review-deferred", from: "review-is-deferred", fromOutput: "MATCH", to: "defer-scope" },
    { id: "review-not-deferred", from: "review-is-deferred", fromOutput: "NO_MATCH", to: "review-needs-fix" },
    { id: "review-defer-check-error", from: "review-is-deferred", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "review-fix", from: "review-needs-fix", fromOutput: "MATCH", to: "fix-validation-failures" },
    { id: "review-pass", from: "review-needs-fix", fromOutput: "NO_MATCH", to: "validate-improvement" },
    { id: "review-fix-check-error", from: "review-needs-fix", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "validate-done", from: "validate-improvement", fromOutput: "DONE", to: "read-active-improvement" },
    { id: "validate-continue", from: "validate-improvement", fromOutput: "CONTINUE", to: "count-improvement-pass" },
    { id: "validate-retry", from: "validate-improvement", fromOutput: "RETRY", to: "count-verification-repair" },
    { id: "validate-error", from: "validate-improvement", fromOutput: "ERROR", to: "defer-scope" },
    { id: "validate-invalid", from: "validate-improvement", fromOutput: "INVALID", to: "defer-scope" },
    { id: "read-active-success-to-append", from: "read-active-improvement", fromOutput: "SUCCESS", to: "append-completed-improvement" },
    { id: "read-active-invalid", from: "read-active-improvement", fromOutput: "INVALID", to: "mark-invalid-scope" },
    { id: "read-active-not-found", from: "read-active-improvement", fromOutput: "NOT_FOUND", to: "mark-invalid-scope" },
    { id: "read-active-error", from: "read-active-improvement", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "append-completed-to-mark", from: "append-completed-improvement", fromOutput: "SUCCESS", to: "mark-scope-result" },
    { id: "append-completed-invalid", from: "append-completed-improvement", fromOutput: "INVALID", to: "mark-invalid-scope" },
    { id: "append-completed-error", from: "append-completed-improvement", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "mark-done-to-ledger", from: "mark-scope-result", fromOutput: "SUCCESS", to: "record-done-outcome" },
    { id: "mark-done-missing-to-ledger", from: "mark-scope-result", fromOutput: "NOT_FOUND", to: "record-done-outcome" },
    { id: "mark-done-error-to-ledger", from: "mark-scope-result", fromOutput: "ERROR", to: "record-done-outcome" },
    { id: "mark-defer-to-ledger", from: "defer-scope", fromOutput: "SUCCESS", to: "record-deferred-outcome" },
    { id: "mark-defer-missing-to-ledger", from: "defer-scope", fromOutput: "NOT_FOUND", to: "record-deferred-outcome" },
    { id: "mark-defer-error-to-ledger", from: "defer-scope", fromOutput: "ERROR", to: "record-deferred-outcome" },
    { id: "mark-stop-to-ledger", from: "mark-stop-scope", fromOutput: "SUCCESS", to: "record-stop-outcome" },
    { id: "mark-stop-missing-to-ledger", from: "mark-stop-scope", fromOutput: "NOT_FOUND", to: "record-stop-outcome" },
    { id: "mark-stop-error-to-ledger", from: "mark-stop-scope", fromOutput: "ERROR", to: "record-stop-outcome" },
    { id: "mark-invalid-to-ledger", from: "mark-invalid-scope", fromOutput: "SUCCESS", to: "record-invalid-outcome" },
    { id: "mark-invalid-missing-to-ledger", from: "mark-invalid-scope", fromOutput: "NOT_FOUND", to: "record-invalid-outcome" },
    { id: "mark-invalid-error-to-ledger", from: "mark-invalid-scope", fromOutput: "ERROR", to: "record-invalid-outcome" },
    { id: "done-ledger-to-archive", from: "record-done-outcome", fromOutput: "SUCCESS", to: "archive-active-improvement" },
    { id: "done-ledger-invalid-to-retained-report", from: "record-done-outcome", fromOutput: "INVALID", to: "retained-active-report" },
    { id: "done-ledger-error-to-retained-report", from: "record-done-outcome", fromOutput: "ERROR", to: "retained-active-report" },
    { id: "defer-ledger-to-retained-report", from: "record-deferred-outcome", fromOutput: "SUCCESS", to: "retained-active-report" },
    { id: "defer-ledger-invalid-to-retained-report", from: "record-deferred-outcome", fromOutput: "INVALID", to: "retained-active-report" },
    { id: "defer-ledger-error-to-retained-report", from: "record-deferred-outcome", fromOutput: "ERROR", to: "retained-active-report" },
    { id: "stop-ledger-to-archive", from: "record-stop-outcome", fromOutput: "SUCCESS", to: "archive-active-improvement" },
    { id: "stop-ledger-invalid-to-retained-report", from: "record-stop-outcome", fromOutput: "INVALID", to: "retained-active-report" },
    { id: "stop-ledger-error-to-retained-report", from: "record-stop-outcome", fromOutput: "ERROR", to: "retained-active-report" },
    { id: "invalid-ledger-to-archive", from: "record-invalid-outcome", fromOutput: "SUCCESS", to: "archive-active-improvement" },
    { id: "invalid-ledger-invalid-to-retained-report", from: "record-invalid-outcome", fromOutput: "INVALID", to: "retained-active-report" },
    { id: "invalid-ledger-error-to-retained-report", from: "record-invalid-outcome", fromOutput: "ERROR", to: "retained-active-report" },
    { id: "archive-to-report", from: "archive-active-improvement", fromOutput: "SUCCESS", to: "final-report" },
    { id: "archive-missing-to-report", from: "archive-active-improvement", fromOutput: "NOT_FOUND", to: "final-report" },
    { id: "archive-error-to-retained-report", from: "archive-active-improvement", fromOutput: "ERROR", to: "retained-active-report" },
    { id: "report-success-to-cycle", from: "final-report", fromOutput: "SUCCESS", to: "scope-cycle-complete" },
    { id: "report-error-to-cycle", from: "final-report", fromOutput: "ERROR", to: "scope-cycle-complete" },
    { id: "retained-report-success-to-deferred", from: "retained-active-report", fromOutput: "SUCCESS", to: "deferred" },
    { id: "retained-report-error-to-deferred", from: "retained-active-report", fromOutput: "ERROR", to: "deferred" },
    { id: "scope-cycle-complete-success", from: "scope-cycle-complete", fromOutput: "MATCH", to: "success" },
    { id: "scope-cycle-next", from: "scope-cycle-complete", fromOutput: "NO_MATCH", to: "select-scope" },
    { id: "scope-cycle-error", from: "scope-cycle-complete", fromOutput: "ERROR", to: "select-scope" },
  ],
};

export const autonomousCodeImprovementLoopStarterFlow = {
  id: "autonomous-code-improvement-loop",
  version: 11,
  defaultAlias: "autonomous-code-improvement-loop",
  category: "Code Quality",
  tags: ["autonomous", "improvement", "behavior-change", "validation"],
  flow: autonomousCodeImprovementLoopFlow,
} as const satisfies RalphStarterFlow;
