import type { RalphFlow } from "../ralph.js";
import type { RalphStarterFlow } from "../ralph-starter-flows.js";

const RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS = 30 * 60;

const ENRICHED_UI_DESIGN_POLICY = [
  "Preserve the repository's existing design-system conventions, component APIs, tokens, routing, data fetching, and accessibility patterns before inventing new UI primitives.",
  "Aim for a clean, minimalist, modern interface with strong hierarchy, restrained color, clear spacing, stable dimensions, and no decorative clutter.",
  "Make layouts responsive and mobile friendly across desktop, tablet, mobile, and small-mobile states; avoid horizontal overflow, clipped content, overlapping text, and controls that resize or shift unexpectedly.",
  "Use badges sparingly for status or category information only; do not turn ordinary labels, metadata, or explanatory text into badge-heavy UI.",
  "Keep copy concise and task-focused; remove overexplained helper text while preserving necessary labels, errors, empty states, and accessible names.",
  "Use icons only when they improve recognition or scanability, prefer the existing icon library, pair unfamiliar icons with labels/tooltips, and keep icon-only controls keyboard and screen-reader accessible.",
  "Respect WCAG 2.2-oriented accessibility: semantic HTML, labels, visible focus, keyboard operation, sufficient contrast, target size/spacing, source order, alt text where needed, and no focus traps.",
  "Check responsive and hydration-sensitive UI for console errors, layout bugs, network failures, loading/empty/error/success states, and regressions introduced by client/server boundaries.",
].join(" ");

const autonomousUiImprovementLoopFlow: RalphFlow = {
  schemaVersion: 1,
  id: "starter-autonomous-ui-improvement-loop",
  alias: "autonomous-ui-improvement-loop",
  name: "Autonomous UI Improvement Loop",
  description:
    "Endless autonomous loop that discovers UI-focused improvement opportunities, applies a configurable design policy, verifies code and visual states, and stops when no meaningful UI candidate remains.",
  settings: {
    maxTransitions: 500,
  },
  variables: [
    { name: "scopeRoot", type: "path", default: ".", required: false },
    { name: "uiScope", type: "text", default: "auto-detect", required: false },
    { name: "scopeSelectionStrategy", type: "text", default: "round-robin", required: false },
    { name: "scopeRegistryFile", type: "path", default: ".machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.json", required: false },
    { name: "scopeRegistryMarkdown", type: "path", default: ".machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.md", required: false },
    { name: "designPolicy", type: "text", default: ENRICHED_UI_DESIGN_POLICY, required: false },
    { name: "uiImprovementPolicy", type: "text", default: "Prefer visible, user-facing UI improvements that make the product clearer, calmer, more responsive, more accessible, and easier to operate without broad redesign churn.", required: false },
    { name: "meaningfulThreshold", type: "text", default: "Continue only when there is concrete UI evidence: layout overflow, overlapping text, responsive breakage, accessibility issue, confusing hierarchy, overexplained copy, badge/icon misuse, inconsistent design-system usage, hydration/console errors, or a clearly bounded visual polish opportunity with user value. Stop instead of inventing speculative redesigns or tiny cosmetic nits.", required: false },
    { name: "riskTolerance", type: "text", default: "ambitious", required: false },
    { name: "allowAmbitiousUiChanges", type: "boolean", default: "true", required: false },
    { name: "excludePaths", type: "text", default: "node_modules, dist, build, coverage, target, .next, .nuxt, .turbo, .cache, vendor, generated, .machdoch", required: false },
    { name: "enableOnlineResearch", type: "boolean", default: "true", required: false },
    { name: "verificationCommand", type: "text", default: "", required: false },
    { name: "enableVisualReview", type: "boolean", default: "true", required: false },
    { name: "targetUrl", type: "url", default: "", required: false },
    { name: "targetUrlEnvKey", type: "text", default: "RALPH_UI_TARGET_URL", required: false },
    { name: "healthUrl", type: "url", default: "", required: false },
    { name: "healthUrlEnvKey", type: "text", default: "RALPH_UI_HEALTH_URL", required: false },
    { name: "screenshotPath", type: "path", default: "", required: false },
    { name: "maxUiImprovementPasses", type: "number", default: "8", required: false },
    { name: "activeUiImprovementFile", type: "path", default: ".machdoch/ralph/ui-improvements/active-ui-improvement.json", required: false },
    { name: "completedUiImprovementsFile", type: "path", default: ".machdoch/ralph/ui-improvements/completed-ui-improvements.jsonl", required: false },
    { name: "archivedUiImprovementsDirectory", type: "path", default: ".machdoch/ralph/ui-improvements/archive", required: false },
    { name: "projectCommandsFile", type: "path", default: ".machdoch/ralph/ui-improvements/project-commands.json", required: false },
    { name: "scopeAnalysisFile", type: "path", default: ".machdoch/ralph/ui-improvements/scope-analysis.json", required: false },
    { name: "candidateFile", type: "path", default: ".machdoch/ralph/ui-improvements/candidate.json", required: false },
    { name: "reviewFile", type: "path", default: ".machdoch/ralph/ui-improvements/review.json", required: false },
    { name: "gitSnapshotFile", type: "path", default: ".machdoch/ralph/ui-improvements/git-snapshot.json", required: false },
    { name: "gitDiffFile", type: "path", default: ".machdoch/ralph/ui-improvements/git-diff.json", required: false },
    { name: "uiReportFile", type: "path", default: ".machdoch/ralph/ui-improvements/final-report.json", required: false },
    { name: "uiReportMarkdown", type: "path", default: ".machdoch/ralph/ui-improvements/final-report.md", required: false },
    { name: "notesFile", type: "path", default: ".machdoch/ralph/ui-improvements/RALPH_UI_IMPROVEMENT_NOTES.md", required: false },
  ],
  blocks: [
    {
      id: "start",
      title: "Start",
      position: { x: 0, y: 0 },
      size: { width: 256, height: 140 },
      type: "START",
    },
    {
      id: "scan-ui-scopes",
      title: "Scan UI Scope Evidence",
      position: { x: 700, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SCAN_SCOPE_EVIDENCE",
        rootPath: "{{scopeRoot:path=.}}",
        excludePaths: "{{excludePaths:text=node_modules, dist, build, coverage, target, .next, .nuxt, .turbo, .cache, vendor, generated, .machdoch}}",
        maxDepth: 5,
        maxResults: 280,
      },
    },
    {
      id: "update-scope-registry",
      title: "Update UI Scope Registry",
      position: { x: 1040, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "UPDATE_SCOPE_REGISTRY",
        flowAlias: "autonomous-ui-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.md}}",
        strategy: "{{scopeSelectionStrategy:text=round-robin}}",
        includeMarkdown: true,
      },
    },
    {
      id: "select-scope",
      title: "Select UI Scope",
      position: { x: 1380, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SELECT_SCOPE",
        flowAlias: "autonomous-ui-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.json}}",
        strategy: "{{scopeSelectionStrategy:text=round-robin}}",
      },
    },
    {
      id: "detect-project-commands",
      title: "Detect Project Commands",
      position: { x: 1720, y: -160 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "DETECT_PROJECT_COMMANDS",
        rootPath: "{{scopeRoot:path=.}}",
        outputPath:
          "{{projectCommandsFile:path=.machdoch/ralph/ui-improvements/project-commands.json}}",
      },
    },
    {
      id: "read-completed-ui-improvements",
      title: "Read Completed UI Improvements",
      position: { x: 1720, y: 40 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "READ_JSONL",
        path: "{{completedUiImprovementsFile:path=.machdoch/ralph/ui-improvements/completed-ui-improvements.jsonl}}",
      },
    },
    {
      id: "analyze-selected-ui-scope",
      title: "Analyze Selected UI Scope",
      position: { x: 2060, y: 0 },
      size: { width: 320, height: 230 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{scopeAnalysisFile:path=.machdoch/ralph/ui-improvements/scope-analysis.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: ["scope", "uiSignals", "designSystem", "constraints", "verification", "stopSignals"],
          properties: {
            scope: { type: "object" },
            uiSignals: { type: "array", items: { type: "string" } },
            designSystem: { type: "array", items: { type: "string" } },
            constraints: { type: "array", items: { type: "string" } },
            verification: { type: "array", items: { type: "string" } },
            stopSignals: { type: "array", items: { type: "string" } },
          },
        },
        prompt:
          "Inspect selected JSON scope {{result:select-scope}} without editing files. Apply uiScope={{uiScope:text=auto-detect}}, riskTolerance={{riskTolerance:text=ambitious}}, allowAmbitiousUiChanges={{allowAmbitiousUiChanges:boolean=true}}, designPolicy={{designPolicy:text=}}, detected commands {{result:detect-project-commands}}, completed history {{result:read-completed-ui-improvements}}, and excludePaths={{excludePaths:text=}}. Auto-detect UI-related files, routes, components, styles, design-system usage, accessibility surfaces, responsive layouts, tests, stories, screenshots, and user-facing copy. Identify concrete evidence for valuable UI improvements: clean minimalist design gaps, responsive/mobile issues, layout overflow, overlapping text, badge overuse, overexplained copy, weak icon usage, inaccessible controls, hydration or console issues, loading/empty/error/success state bugs, or inconsistency with existing UI conventions. Also identify stop signals: no UI-relevant scope, no evidence-backed candidate, only speculative redesign, only tiny cosmetic nits, or work already completed. Return only schema-valid JSON.",
      },
    },
    {
      id: "research-decision",
      title: "Use Online Research?",
      position: { x: 2400, y: -150 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression: 'variables.enableOnlineResearch === "true"',
        },
      },
    },
    {
      id: "ui-research",
      title: "UI Best-Practice Research",
      position: { x: 2720, y: -180 },
      size: { width: 300, height: 230 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        webAccess: true,
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Use content enrichment to sharpen the UI improvement scope. If search_web is available, run focused searches for current primary-source framework/library behavior, official design-system docs in this repo's stack, W3C/WAI WCAG guidance, MDN accessibility/responsive guidance, web.dev responsive guidance, browser/runtime notes, and testing approaches relevant to scope analysis {{data:analyze-selected-ui-scope:output}}. Use fetch_url on the best official or maintainer pages before relying on them. Keep findings concise with source links, freshness/version notes, practical UI implications, and explicit non-findings. If web search is unavailable, say so and rely on local evidence plus provided URLs. Do not research broadly just to find extra redesign work.",
    },
    {
      id: "choose-ui-improvement",
      title: "Choose UI Improvement",
      position: { x: 3060, y: 0 },
      size: { width: 320, height: 250 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{candidateFile:path=.machdoch/ralph/ui-improvements/candidate.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: ["decision", "rationale", "selectedCandidate", "rejectedCandidates", "stopReason"],
          properties: {
            decision: { type: "string" },
            rationale: { type: "string" },
            selectedCandidate: {
              type: "object",
              properties: {
                id: { type: "string" },
                title: { type: "string" },
              },
            },
            rejectedCandidates: { type: "array", items: { type: "object" } },
            stopReason: { type: "string" },
          },
        },
        prompt:
          "Select exactly one autonomous UI improvement for selected scope {{result:select-scope}}, or decide STOP. Use scope analysis {{data:analyze-selected-ui-scope:output}}, research {{summary:ui-research}}, completed history {{result:read-completed-ui-improvements}}, latest completed append {{result:append-completed-ui-improvement}}, uiImprovementPolicy={{uiImprovementPolicy:text=}}, designPolicy={{designPolicy:text=}}, riskTolerance={{riskTolerance:text=ambitious}}, and allowAmbitiousUiChanges={{allowAmbitiousUiChanges:boolean=true}}. Return decision IMPLEMENT only when the candidate has a stable kebab-case id, title, concrete UI evidence, user value, bounded scope, currentBehavior, proposedBehavior, acceptanceCriteria, affectedFiles, visualReviewPlan, verificationPlan, accessibility/responsive considerations, and rollbackNotes. Ambitious polish is allowed when configured and still preserves existing design-system conventions. Return STOP when remaining ideas are speculative, badge/copy/icon churn without evidence, broad redesigns requiring product approval, duplicate of completed history, unsafe dependency/schema changes, dev-server startup needs, or fail threshold {{meaningfulThreshold:text=}}. If decision is STOP, selectedCandidate must be {} and stopReason must explain the evidence-backed reason. Return only schema-valid JSON.",
      },
    },
    {
      id: "has-actionable-ui-improvement",
      title: "Actionable UI Improvement?",
      position: { x: 3400, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'lastData?.output?.decision === "IMPLEMENT" && lastData.output.selectedCandidate && Object.keys(lastData.output.selectedCandidate).length > 0',
        },
      },
    },
    {
      id: "write-active-ui-improvement",
      title: "Track Active UI Improvement",
      position: { x: 3720, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "WRITE_JSON",
        path: "{{activeUiImprovementFile:path=.machdoch/ralph/ui-improvements/active-ui-improvement.json}}",
        input: "{{data:choose-ui-improvement:output.selectedCandidate}}",
      },
    },
    {
      id: "git-snapshot-before",
      title: "Git Snapshot Before",
      position: { x: 4060, y: -170 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_SNAPSHOT",
        outputPath:
          "{{gitSnapshotFile:path=.machdoch/ralph/ui-improvements/git-snapshot.json}}",
      },
    },
    {
      id: "count-ui-improvement-pass",
      title: "Count UI Improvement Pass",
      position: { x: 4060, y: 230 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        counterName:
          "autonomous-ui-improvement-loop.implementation-pass.{{data:select-scope:scope.id}}.{{data:choose-ui-improvement:output.selectedCandidate.id}}",
        maxAttempts: "{{maxUiImprovementPasses:number=8}}",
      },
    },
    {
      id: "implement-ui-improvement",
      title: "Implement UI Improvement",
      position: { x: 4060, y: 40 },
      size: { width: 340, height: 260 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 4,
      },
      type: "PROMPT",
      prompt:
        "Implement the active UI improvement at {{activeUiImprovementFile:path=.machdoch/ralph/ui-improvements/active-ui-improvement.json}} using candidate {{data:choose-ui-improvement:output.selectedCandidate}}, selected scope {{result:select-scope}}, scope analysis {{data:analyze-selected-ui-scope:output}}, research {{summary:ui-research}}, git baseline {{result:git-snapshot-before}}, detected commands {{result:detect-project-commands}}, pass count {{result:count-ui-improvement-pass}}, latest validator feedback {{result:validate-ui-improvement}}, latest review feedback {{data:independent-ui-review:output}}, and designPolicy={{designPolicy:text=}}. Keep changes bounded to the selected UI scope and required adjacent tests/docs/imports. Preserve existing design-system conventions, components, icons, tokens, responsive patterns, and copy tone unless the candidate explicitly improves them. Prefer clean minimalist modern UI, responsive/mobile friendly layout, restrained badges, concise copy, useful icons, accessible controls, stable dimensions, no overlapping text, no overflow, no hydration or responsive UI bugs, and verified desktop/mobile states. Add or update meaningful tests when feasible. Do not start or restart servers. Do not hardcode target URLs; use targetUrl={{targetUrl:url=}} or env key {{targetUrlEnvKey:text=RALPH_UI_TARGET_URL}} supplied at runtime for visual review. Append a concise note to {{notesFile:path=.machdoch/ralph/ui-improvements/RALPH_UI_IMPROVEMENT_NOTES.md}} with UI behavior changes, verification, visual-review status, and remaining risks.",
    },
    {
      id: "verification-decision",
      title: "Run Verification?",
      position: { x: 4400, y: 40 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "Boolean(variables.verificationCommand?.trim() || context.resultsByBlock?.['detect-project-commands']?.data?.verificationCommand?.trim())",
        },
      },
    },
    {
      id: "run-verification",
      title: "Run Verification",
      position: { x: 4720, y: -110 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{verificationCommand:text=}}",
        fallbackCommand: "{{data:detect-project-commands:verificationCommand}}",
        timeoutSeconds: RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "fix-validation-failures",
      title: "Fix Validation Failures",
      position: { x: 4720, y: 120 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "PROMPT",
      prompt:
        "Fix verification failures from {{result:run-verification}} that were caused by the current UI improvement. Distinguish pre-existing failures from own regressions. Keep fixes scoped to active UI improvement {{data:choose-ui-improvement:output.selectedCandidate}} and selected scope {{result:select-scope}}. Do not broaden the improvement or start another candidate. Do not start or restart servers.",
    },
    {
      id: "resolve-runtime-urls",
      title: "Resolve Runtime URLs",
      position: { x: 5060, y: -130 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "TRANSFORM_JSON",
        input: "{}",
        expression:
          "(() => { const readEnv = (key) => { if (!key || typeof process === 'undefined') return ''; const value = process.env?.[String(key).trim()]; return typeof value === 'string' ? value.trim() : ''; }; const configuredTargetUrl = (variables.targetUrl ?? '').trim(); const configuredHealthUrl = (variables.healthUrl ?? '').trim(); const targetUrl = configuredTargetUrl || readEnv(variables.targetUrlEnvKey); const healthUrl = configuredHealthUrl || readEnv(variables.healthUrlEnvKey); return { targetUrl, healthUrl, targetUrlEnvKey: variables.targetUrlEnvKey, healthUrlEnvKey: variables.healthUrlEnvKey, targetSource: targetUrl ? (configuredTargetUrl ? 'variable' : variables.targetUrlEnvKey) : '', healthSource: healthUrl ? (configuredHealthUrl ? 'variable' : variables.healthUrlEnvKey) : '' }; })()",
      },
    },
    {
      id: "visual-decision",
      title: "Run Visual Review?",
      position: { x: 5380, y: 40 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'variables.enableVisualReview === "true" && (Boolean(context.resultsByBlock?.["resolve-runtime-urls"]?.data?.output?.targetUrl?.trim()) || Boolean(variables.screenshotPath?.trim()))',
        },
      },
    },
    {
      id: "visual-review",
      title: "Visual Review",
      position: { x: 5700, y: 40 },
      size: { width: 280, height: 190 },
      type: "UTILITY",
      utility: {
        type: "UI_ANALYZE",
        adapter: "auto",
        targetUrl: "{{data:resolve-runtime-urls:output.targetUrl}}",
        screenshotPath: "{{screenshotPath:path=}}",
        server: {
          mode: "existing",
          healthUrl: "{{data:resolve-runtime-urls:output.healthUrl}}",
        },
        checks: {
          screenshots: true,
          accessibility: true,
          console: true,
          network: true,
          responsive: true,
        },
        viewports: [
          { name: "desktop", width: 1280, height: 900 },
          { name: "tablet", width: 768, height: 1024 },
          { name: "mobile", width: 390, height: 844 },
          { name: "small-mobile", width: 320, height: 568 },
        ],
        timeoutSeconds: 30,
        fullPage: true,
        waitUntil: "domcontentloaded",
      },
    },
    {
      id: "git-diff-summary",
      title: "Git Diff Summary",
      position: { x: 6040, y: 40 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_DIFF_SUMMARY",
        outputPath:
          "{{gitDiffFile:path=.machdoch/ralph/ui-improvements/git-diff.json}}",
      },
    },
    {
      id: "independent-ui-review",
      title: "Independent UI Review",
      position: { x: 6380, y: 40 },
      size: { width: 320, height: 250 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{reviewFile:path=.machdoch/ralph/ui-improvements/review.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: ["decision", "summary", "issues", "verificationNotes", "visualNotes"],
          properties: {
            decision: { type: "string" },
            summary: { type: "string" },
            issues: { type: "array", items: { type: "object" } },
            verificationNotes: { type: "array", items: { type: "string" } },
            visualNotes: { type: "array", items: { type: "string" } },
          },
        },
        prompt:
          "Review the current UI improvement as a separate reviewer. Active improvement: {{data:choose-ui-improvement:output.selectedCandidate}}. Diff: {{result:git-diff-summary}}. Verification: {{result:run-verification}}. Runtime URL resolution: {{data:resolve-runtime-urls:output}}. Visual review: {{result:visual-review}}. Evaluate only the active candidate, selected UI scope, and required adjacent tests/docs/imports. Ignore unrelated workspace changes outside that scope unless they directly break verification of this improvement. Check designPolicy={{designPolicy:text=}}, responsive/mobile behavior, accessibility, clean minimalist hierarchy, badge restraint, concise copy, useful icon usage, layout overflow, overlapping text, focus/keyboard states, console/network/hydration issues, design-system consistency, and security regressions at UI/API/IPC boundaries. Return decision PASS when the improvement is bounded, justified, verified or explicitly justified as unverified, and does not introduce regressions. Return FIX when specific issues remain. Return BLOCKED when unsafe, ambiguous, requires dev-server startup, or requires human/product approval. Return only schema-valid JSON.",
      },
    },
    {
      id: "validate-ui-improvement",
      title: "Validate UI Improvement",
      position: { x: 6740, y: 40 },
      size: { width: 320, height: 250 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "VALIDATOR_JSON",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: ["decision", "confidence", "summary", "evidence", "remainingWork"],
          properties: {
            decision: { type: "string" },
            confidence: { type: "number" },
            summary: { type: "string" },
            evidence: { type: "array", items: { type: "string" } },
            remainingWork: { type: "array", items: { type: "string" } },
          },
        },
        prompt:
          "Validate the latest autonomous UI improvement. Candidate: {{data:choose-ui-improvement:output.selectedCandidate}}. Review: {{data:independent-ui-review:output}}. Verification: {{result:run-verification}}. Runtime URL resolution: {{data:resolve-runtime-urls:output}}. Visual review: {{result:visual-review}}. Git diff: {{result:git-diff-summary}}. Notes file: {{notesFile:path=.machdoch/ralph/ui-improvements/RALPH_UI_IMPROVEMENT_NOTES.md}}. Judge only the active candidate, selected UI scope, and required adjacent tests/docs/imports. Ignore unrelated workspace changes outside that scope unless they directly break verification of this improvement. Return DONE only when the improvement implements the selected candidate, preserves or improves the existing design system, satisfies designPolicy={{designPolicy:text=}}, has no obvious desktop/mobile overflow, overlapping text, badge overuse, copy bloat, icon misuse, accessibility regression, console/network/hydration regression, or unreviewed visual state, and verification is passing or skipped with a sound reason. Return CONTINUE only when the same candidate still needs bounded implementation work; the flow counter enforces maxUiImprovementPasses={{maxUiImprovementPasses:number=8}}. Return RETRY when validation/review found own regressions that should be corrected. Return ERROR when blocked by unsafe changes, ambiguous behavior, required human/product decision, unavailable credentials/tooling/URL, required dev-server startup, repeated failure, or work that no longer meets meaningfulThreshold={{meaningfulThreshold:text=}}.",
      },
    },
    {
      id: "final-report",
      title: "Final UI Improvement Report",
      position: { x: 7080, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{uiReportFile:path=.machdoch/ralph/ui-improvements/final-report.json}}",
        outputPath:
          "{{uiReportMarkdown:path=.machdoch/ralph/ui-improvements/final-report.md}}",
      },
    },
    {
      id: "read-active-ui-improvement",
      title: "Read Active UI Improvement",
      position: { x: 7420, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "READ_JSON",
        path: "{{activeUiImprovementFile:path=.machdoch/ralph/ui-improvements/active-ui-improvement.json}}",
      },
    },
    {
      id: "append-completed-ui-improvement",
      title: "Append Completed UI Improvement",
      position: { x: 7760, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{completedUiImprovementsFile:path=.machdoch/ralph/ui-improvements/completed-ui-improvements.jsonl}}",
        input: "{{data:read-active-ui-improvement:json}}",
      },
    },
    {
      id: "archive-active-ui-improvement",
      title: "Archive Active UI Improvement",
      position: { x: 8100, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "ARCHIVE_FILE",
        path: "{{activeUiImprovementFile:path=.machdoch/ralph/ui-improvements/active-ui-improvement.json}}",
        rootPath:
          "{{archivedUiImprovementsDirectory:path=.machdoch/ralph/ui-improvements/archive}}",
      },
    },
    {
      id: "mark-scope-result",
      title: "Mark Scope Result",
      position: { x: 3720, y: 300 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "autonomous-ui-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.md}}",
        result: "DONE",
        includeMarkdown: true,
      },
    },
    {
      id: "scope-cycle-complete",
      title: "Scope Cycle Complete?",
      position: { x: 4060, y: 300 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression: "lastData?.cycleCompleted === true",
        },
      },
    },
    {
      id: "success",
      title: "No Meaningful UI Improvements",
      position: { x: 4400, y: 300 },
      size: { width: 280, height: 114 },
      type: "END",
      status: "success",
    },
    {
      id: "blocked",
      title: "Blocked",
      position: { x: 3060, y: 340 },
      size: { width: 256, height: 114 },
      type: "END",
      status: "failed",
    },
  ],
  edges: [
    { id: "start-to-scan-ui-scopes", from: "start", fromOutput: "SUCCESS", to: "scan-ui-scopes" },
    { id: "scan-ui-scopes-to-update", from: "scan-ui-scopes", fromOutput: "SUCCESS", to: "update-scope-registry" },
    { id: "scan-ui-scopes-empty", from: "scan-ui-scopes", fromOutput: "EMPTY", to: "blocked" },
    { id: "scan-ui-scopes-error", from: "scan-ui-scopes", fromOutput: "ERROR", to: "blocked" },
    { id: "update-registry-to-select", from: "update-scope-registry", fromOutput: "SUCCESS", to: "select-scope" },
    { id: "update-registry-empty", from: "update-scope-registry", fromOutput: "EMPTY", to: "success" },
    { id: "update-registry-error", from: "update-scope-registry", fromOutput: "ERROR", to: "blocked" },
    { id: "select-scope-to-detect", from: "select-scope", fromOutput: "SELECTED", to: "detect-project-commands" },
    { id: "select-scope-empty", from: "select-scope", fromOutput: "EMPTY", to: "success" },
    { id: "select-scope-error", from: "select-scope", fromOutput: "ERROR", to: "blocked" },
    { id: "detect-success-to-history", from: "detect-project-commands", fromOutput: "SUCCESS", to: "read-completed-ui-improvements" },
    { id: "detect-empty-to-history", from: "detect-project-commands", fromOutput: "EMPTY", to: "read-completed-ui-improvements" },
    { id: "detect-error-to-history", from: "detect-project-commands", fromOutput: "ERROR", to: "read-completed-ui-improvements" },
    { id: "history-success-to-analysis", from: "read-completed-ui-improvements", fromOutput: "SUCCESS", to: "analyze-selected-ui-scope" },
    { id: "history-empty-to-analysis", from: "read-completed-ui-improvements", fromOutput: "EMPTY", to: "analyze-selected-ui-scope" },
    { id: "history-not-found-to-analysis", from: "read-completed-ui-improvements", fromOutput: "NOT_FOUND", to: "analyze-selected-ui-scope" },
    { id: "history-invalid-to-analysis", from: "read-completed-ui-improvements", fromOutput: "INVALID", to: "analyze-selected-ui-scope" },
    { id: "history-error-to-analysis", from: "read-completed-ui-improvements", fromOutput: "ERROR", to: "analyze-selected-ui-scope" },
    { id: "analysis-success-to-research-decision", from: "analyze-selected-ui-scope", fromOutput: "SUCCESS", to: "research-decision" },
    { id: "analysis-invalid", from: "analyze-selected-ui-scope", fromOutput: "INVALID", to: "blocked" },
    { id: "analysis-error", from: "analyze-selected-ui-scope", fromOutput: "ERROR", to: "blocked" },
    { id: "research-decision-run", from: "research-decision", fromOutput: "MATCH", to: "ui-research" },
    { id: "research-decision-skip", from: "research-decision", fromOutput: "NO_MATCH", to: "choose-ui-improvement" },
    { id: "research-decision-error", from: "research-decision", fromOutput: "ERROR", to: "choose-ui-improvement" },
    { id: "research-to-choose", from: "ui-research", fromOutput: "SUCCESS", to: "choose-ui-improvement" },
    { id: "research-error-to-choose", from: "ui-research", fromOutput: "ERROR", to: "choose-ui-improvement" },
    { id: "choose-to-actionable", from: "choose-ui-improvement", fromOutput: "SUCCESS", to: "has-actionable-ui-improvement" },
    { id: "choose-invalid", from: "choose-ui-improvement", fromOutput: "INVALID", to: "blocked" },
    { id: "choose-error", from: "choose-ui-improvement", fromOutput: "ERROR", to: "blocked" },
    { id: "actionable-to-write", from: "has-actionable-ui-improvement", fromOutput: "MATCH", to: "write-active-ui-improvement" },
    { id: "not-actionable-to-mark", from: "has-actionable-ui-improvement", fromOutput: "NO_MATCH", to: "mark-scope-result" },
    { id: "actionable-error", from: "has-actionable-ui-improvement", fromOutput: "ERROR", to: "mark-scope-result" },
    { id: "write-to-snapshot", from: "write-active-ui-improvement", fromOutput: "SUCCESS", to: "git-snapshot-before" },
    { id: "write-invalid", from: "write-active-ui-improvement", fromOutput: "INVALID", to: "blocked" },
    { id: "write-error", from: "write-active-ui-improvement", fromOutput: "ERROR", to: "blocked" },
    { id: "snapshot-to-count-ui-improvement-pass", from: "git-snapshot-before", fromOutput: "SUCCESS", to: "count-ui-improvement-pass" },
    { id: "snapshot-error-to-count-ui-improvement-pass", from: "git-snapshot-before", fromOutput: "ERROR", to: "count-ui-improvement-pass" },
    { id: "count-ui-improvement-pass-continue", from: "count-ui-improvement-pass", fromOutput: "CONTINUE", to: "implement-ui-improvement" },
    { id: "count-ui-improvement-pass-limit", from: "count-ui-improvement-pass", fromOutput: "LIMIT_REACHED", to: "blocked" },
    { id: "count-ui-improvement-pass-error", from: "count-ui-improvement-pass", fromOutput: "ERROR", to: "blocked" },
    { id: "implement-to-verification-decision", from: "implement-ui-improvement", fromOutput: "SUCCESS", to: "verification-decision" },
    { id: "implement-error", from: "implement-ui-improvement", fromOutput: "ERROR", to: "blocked" },
    { id: "verification-decision-run", from: "verification-decision", fromOutput: "MATCH", to: "run-verification" },
    { id: "verification-decision-skip", from: "verification-decision", fromOutput: "NO_MATCH", to: "resolve-runtime-urls" },
    { id: "verification-decision-error", from: "verification-decision", fromOutput: "ERROR", to: "resolve-runtime-urls" },
    { id: "verification-success-to-runtime-urls", from: "run-verification", fromOutput: "SUCCESS", to: "resolve-runtime-urls" },
    { id: "verification-failed-to-fix", from: "run-verification", fromOutput: "FAILED", to: "fix-validation-failures" },
    { id: "verification-error-to-fix", from: "run-verification", fromOutput: "ERROR", to: "fix-validation-failures" },
    { id: "fix-validation-to-decision", from: "fix-validation-failures", fromOutput: "SUCCESS", to: "verification-decision" },
    { id: "fix-validation-error", from: "fix-validation-failures", fromOutput: "ERROR", to: "blocked" },
    { id: "runtime-urls-success-to-visual-decision", from: "resolve-runtime-urls", fromOutput: "SUCCESS", to: "visual-decision" },
    { id: "runtime-urls-error-to-visual-decision", from: "resolve-runtime-urls", fromOutput: "ERROR", to: "visual-decision" },
    { id: "visual-decision-run", from: "visual-decision", fromOutput: "MATCH", to: "visual-review" },
    { id: "visual-decision-skip", from: "visual-decision", fromOutput: "NO_MATCH", to: "git-diff-summary" },
    { id: "visual-decision-error", from: "visual-decision", fromOutput: "ERROR", to: "git-diff-summary" },
    { id: "visual-success-to-diff", from: "visual-review", fromOutput: "SUCCESS", to: "git-diff-summary" },
    { id: "visual-unavailable-to-diff", from: "visual-review", fromOutput: "UNAVAILABLE", to: "git-diff-summary" },
    { id: "visual-error-to-diff", from: "visual-review", fromOutput: "ERROR", to: "git-diff-summary" },
    { id: "diff-success-to-review", from: "git-diff-summary", fromOutput: "SUCCESS", to: "independent-ui-review" },
    { id: "diff-empty-to-review", from: "git-diff-summary", fromOutput: "EMPTY", to: "independent-ui-review" },
    { id: "diff-error-to-review", from: "git-diff-summary", fromOutput: "ERROR", to: "independent-ui-review" },
    { id: "review-to-validate", from: "independent-ui-review", fromOutput: "SUCCESS", to: "validate-ui-improvement" },
    { id: "review-invalid", from: "independent-ui-review", fromOutput: "INVALID", to: "blocked" },
    { id: "review-error", from: "independent-ui-review", fromOutput: "ERROR", to: "blocked" },
    { id: "validate-done", from: "validate-ui-improvement", fromOutput: "DONE", to: "final-report" },
    { id: "validate-continue", from: "validate-ui-improvement", fromOutput: "CONTINUE", to: "count-ui-improvement-pass" },
    { id: "validate-retry", from: "validate-ui-improvement", fromOutput: "RETRY", to: "count-ui-improvement-pass" },
    { id: "validate-error", from: "validate-ui-improvement", fromOutput: "ERROR", to: "blocked" },
    { id: "validate-invalid", from: "validate-ui-improvement", fromOutput: "INVALID", to: "blocked" },
    { id: "report-success-to-read-active", from: "final-report", fromOutput: "SUCCESS", to: "read-active-ui-improvement" },
    { id: "report-error-to-read-active", from: "final-report", fromOutput: "ERROR", to: "read-active-ui-improvement" },
    { id: "read-active-success-to-append", from: "read-active-ui-improvement", fromOutput: "SUCCESS", to: "append-completed-ui-improvement" },
    { id: "read-active-invalid", from: "read-active-ui-improvement", fromOutput: "INVALID", to: "blocked" },
    { id: "read-active-not-found", from: "read-active-ui-improvement", fromOutput: "NOT_FOUND", to: "blocked" },
    { id: "read-active-error", from: "read-active-ui-improvement", fromOutput: "ERROR", to: "blocked" },
    { id: "append-completed-to-archive", from: "append-completed-ui-improvement", fromOutput: "SUCCESS", to: "archive-active-ui-improvement" },
    { id: "append-completed-invalid", from: "append-completed-ui-improvement", fromOutput: "INVALID", to: "blocked" },
    { id: "append-completed-error", from: "append-completed-ui-improvement", fromOutput: "ERROR", to: "blocked" },
    { id: "archive-success-to-history", from: "archive-active-ui-improvement", fromOutput: "SUCCESS", to: "read-completed-ui-improvements" },
    { id: "archive-not-found-to-history", from: "archive-active-ui-improvement", fromOutput: "NOT_FOUND", to: "read-completed-ui-improvements" },
    { id: "archive-error", from: "archive-active-ui-improvement", fromOutput: "ERROR", to: "blocked" },
    { id: "mark-scope-success", from: "mark-scope-result", fromOutput: "SUCCESS", to: "scope-cycle-complete" },
    { id: "mark-scope-not-found", from: "mark-scope-result", fromOutput: "NOT_FOUND", to: "blocked" },
    { id: "mark-scope-error", from: "mark-scope-result", fromOutput: "ERROR", to: "blocked" },
    { id: "scope-cycle-complete-success", from: "scope-cycle-complete", fromOutput: "MATCH", to: "success" },
    { id: "scope-cycle-next", from: "scope-cycle-complete", fromOutput: "NO_MATCH", to: "select-scope" },
    { id: "scope-cycle-error", from: "scope-cycle-complete", fromOutput: "ERROR", to: "select-scope" },
  ],
};

export const autonomousUiImprovementLoopStarterFlow = {
  id: "autonomous-ui-improvement-loop",
  version: 2,
  defaultAlias: "autonomous-ui-improvement-loop",
  category: "Design Quality",
  tags: ["autonomous", "ui", "design", "visual-check"],
  flow: autonomousUiImprovementLoopFlow,
} as const satisfies RalphStarterFlow;
