import type { RalphFlow } from "../ralph.js";
import type { RalphStarterFlow } from "../ralph-starter-flows.js";

const RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS = 30 * 60;

const RALPH_TASK_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["id", "title", "status", "batchKey", "dependencies", "likelyFiles", "size"],
  properties: {
    id: { type: "string", minLength: 1 },
    title: { type: "string", minLength: 1 },
    status: { type: "string", enum: ["planned", "implementing", "verifying", "repairing", "completed", "deferred"] },
    batchKey: { type: "string" },
    dependencies: { type: "array", items: { type: "string", minLength: 1 }, maxItems: 20 },
    likelyFiles: { type: "array", items: { type: "string", minLength: 1 }, maxItems: 50 },
    size: { type: "string", enum: ["small", "medium", "large"] },
    acceptanceCriteria: { type: "array", items: { type: "string" }, maxItems: 20 },
    priority: { type: "number", minimum: 0, maximum: 100 },
  },
} as const;

const RALPH_VALIDATOR_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["decision", "confidence", "summary", "evidence", "remainingWork"],
  properties: {
    decision: { type: "string", enum: ["DONE", "CONTINUE", "RETRY", "ERROR"] },
    confidence: { type: "number", minimum: 0, maximum: 1 },
    summary: { type: "string" },
    evidence: { type: "array", items: { type: "string" }, maxItems: 30 },
    remainingWork: { type: "array", items: { type: "string" }, maxItems: 30 },
  },
} as const;

const autonomousFeatureGenerationLoopFlow: RalphFlow = {
  schemaVersion: 1,
  id: "starter-autonomous-feature-generation-loop",
  alias: "autonomous-feature-generation-loop",
  name: "Autonomous Feature Generation Loop",
  description:
    "Bounded autonomous feature cycle that persists a project constitution, scores several product opportunities, implements the best shippable goal, and defers exhausted goals before continuing.",
  settings: {
    maxTransitions: 500,
    autonomy: {
      recoverFailedEnd: true,
      maxRecoveryAttempts: 3,
      transitionExhaustion: "checkpoint",
      recoveryExhaustion: "defer",
      deferToBlockId: "record-deferred-goal-outcome",
    },
  },
  variables: [
    {
      name: "goalFilePath",
      type: "path",
      default: ".machdoch/autonomous-features/active-goal.json",
      required: false,
    },
    { name: "completedGoalsFile", type: "path", default: ".machdoch/autonomous-features/completed-goals.jsonl", required: false },
    { name: "goalOutcomesFile", type: "path", default: ".machdoch/autonomous-features/outcomes.jsonl", required: false },
    { name: "archivedGoalsDirectory", type: "path", default: ".machdoch/autonomous-features/archive", required: false },
    { name: "projectProfileFile", type: "path", default: ".machdoch/autonomous-features/project-profile.json", required: false },
    { name: "projectCommandsFile", type: "path", default: "{{run:artifactRoot}}/autonomous-features/project-commands.json", required: false },
    { name: "gitSnapshotFile", type: "path", default: "{{run:artifactRoot}}/autonomous-features/git-snapshot.json", required: false },
    { name: "gitDiffFile", type: "path", default: "{{run:artifactRoot}}/autonomous-features/git-diff.json", required: false },
    { name: "autonomousReportFile", type: "path", default: "{{run:artifactRoot}}/autonomous-features/final-report.json", required: false },
    { name: "autonomousReportMarkdown", type: "path", default: "{{run:artifactRoot}}/autonomous-features/final-report.md", required: false },
    { name: "maxGoalsPerRun", type: "number", default: "100", required: false },
    {
      name: "projectVision",
      type: "text",
      default: "",
      required: false,
    },
    {
      name: "featureStrategy",
      type: "text",
      default:
        "Prefer high-impact, shippable, coherent product improvements that fit the repository and compound over time.",
      required: false,
    },
    {
      name: "inspirationSources",
      type: "text",
      default:
        "Similar products, popular open-source alternatives, current platform capabilities, state-of-the-art UX patterns, and emerging/hyped feature ideas.",
      required: false,
    },
    {
      name: "enableOnlineResearch",
      type: "boolean",
      default: "true",
      required: false,
    },
    {
      name: "implementationScope",
      type: "text",
      default: "auto-detect",
      required: false,
    },
    {
      name: "excludedAreas",
      type: "text",
      default:
        "generated files, vendor directories, unrelated dependency upgrades",
      required: false,
    },
    {
      name: "riskTolerance",
      type: "text",
      default: "ambitious",
      required: false,
    },
    {
      name: "verificationCommand",
      type: "text",
      default: "",
      required: false,
    },
    {
      name: "enableVisualReview",
      type: "boolean",
      default: "false",
      required: false,
    },
    {
      name: "targetUrl",
      type: "url",
      default: "",
      required: false,
    },
    {
      name: "healthUrl",
      type: "url",
      default: "",
      required: false,
    },
    {
      name: "screenshotPath",
      type: "path",
      default: "",
      required: false,
    },
    {
      name: "authInstructions",
      type: "text",
      default: "",
      required: false,
    },
    {
      name: "designGuidelines",
      type: "text",
      default: "",
      required: false,
    },
    {
      name: "maxImplementationPasses",
      type: "number",
      default: "10",
      required: false,
    },
    { name: "allowDependencyChanges", type: "boolean", default: "true", required: false },
    { name: "allowSchemaChanges", type: "boolean", default: "true", required: false },
    { name: "allowPublicApiChanges", type: "boolean", default: "true", required: false },
    {
      name: "maxTasksPerImplementationPass",
      type: "number",
      default: "3",
      required: false,
    },
  ],
  blocks: [
    {
      id: "start",
      title: "Start",
      position: { x: 0, y: 0 },
      size: { width: 256, height: 140 },
      type: "START",
    },
    {
      id: "find-active-goal",
      title: "Find Active Goal",
      position: { x: 720, y: 0 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "FILE_EXISTS",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
      },
    },
    {
      id: "read-active-goal",
      title: "Read Active Goal",
      position: { x: 1060, y: -120 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "READ_JSON",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
      },
    },
    {
      id: "prepare-active-goal",
      title: "Prepare Active Goal",
      position: { x: 1400, y: -120 },
      size: { width: 280, height: 190 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Resume the tracked autonomous feature goal from {{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}. JSON read result: {{result:read-active-goal}}. Extract the goal, acceptance criteria, plan, completed tasks, verification expectations, risks, and next planned/implementing work. Do not create a new goal while this file exists and never edit task lifecycle fields; runtime task utilities own them.",
    },
    {
      id: "detect-project-commands",
      title: "Detect Project Commands",
      position: { x: 860, y: 300 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "DETECT_PROJECT_COMMANDS",
        rootPath: ".",
        outputPath:
          "{{projectCommandsFile:path=.machdoch/autonomous-features/project-commands.json}}",
      },
    },
    {
      id: "read-completed-goals",
      title: "Read Completed Goals",
      position: { x: 1020, y: 360 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "QUERY_JSONL",
        path: "{{completedGoalsFile:path=.machdoch/autonomous-features/completed-goals.jsonl}}",
        maxResults: 50,
        order: "newest",
      },
    },
    {
      id: "understand-project",
      title: "Understand Project",
      position: { x: 1060, y: 140 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{projectProfileFile:path=.machdoch/autonomous-features/project-profile.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: ["product", "constitution", "architecture", "currentFeatures", "extensionPoints", "constraints"],
          properties: {
            product: { type: "string" },
            constitution: {
              type: "object",
              required: ["purpose", "users", "desiredOutcomes", "productPrinciples", "technicalDirection", "measurablePriorities"],
              properties: {
                purpose: { type: "string" },
                users: { type: "array", items: { type: "string" } },
                desiredOutcomes: { type: "array", items: { type: "string" } },
                productPrinciples: { type: "array", items: { type: "string" } },
                technicalDirection: { type: "array", items: { type: "string" } },
                measurablePriorities: { type: "array", items: { type: "string" } },
              },
            },
            architecture: { type: "array", items: { type: "string" } },
            currentFeatures: { type: "array", items: { type: "string" } },
            extensionPoints: { type: "array", items: { type: "string" } },
            constraints: { type: "array", items: { type: "string" } },
          },
        },
        prompt:
          "No active autonomous feature goal was found. Inspect the repository to infer and persist a project constitution: product purpose, users, desired outcomes, product principles, technical direction, measurable priorities, architecture, current features, extension points, tests, scripts, constraints, and recently changed areas. Compare bounded completed goal history {{result:read-completed-goals}} and detected commands {{result:detect-project-commands}}. Apply projectVision={{projectVision:text=}}, implementationScope={{implementationScope:text=auto-detect}}, excludedAreas={{excludedAreas:text=}}, and riskTolerance={{riskTolerance:text=ambitious}}. Make bounded evidence-backed assumptions autonomously. Do not change files. Return only schema-valid JSON.",
      },
    },
    {
      id: "research-decision",
      title: "Use Online Research?",
      position: { x: 1380, y: 140 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'variables.enableOnlineResearch === "true" && context.resultsByBlock?.["draft-feature-goal"]?.data?.output?.researchDecision?.needsResearch === true',
        },
      },
    },
    {
      id: "research-inspiration",
      title: "Research Inspiration",
      position: { x: 1400, y: 140 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        webAccess: true,
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "PROMPT",
      prompt:
          "Research only the focused questions in structured provisional portfolio {{data:draft-feature-goal:output.researchDecision}}. If search_web is available, use primary/official sources and fetch_url for the best pages. Compare findings against candidate ranking {{data:draft-feature-goal:output.candidates}}, persisted profile {{data:understand-project:output}}, and newest completed goals {{result:read-completed-goals}}. Produce concise source links, freshness/version assumptions, candidate implications, implementation leverage, and contradictions. If web search is unavailable, say so and rely on local evidence; do not broaden into generic inspiration.",
    },
    {
      id: "draft-feature-goal",
      title: "Draft Feature Goal",
      position: { x: 1740, y: 140 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        maxAttempts: 2,
        schema: {
          type: "object",
          additionalProperties: false,
          required: ["candidates", "researchDecision"],
          properties: {
            candidates: {
              type: "array",
              minItems: 1,
              maxItems: 5,
              items: {
                type: "object",
                additionalProperties: false,
                required: ["id", "title", "evidence", "scorecard", "acceptanceCriteria", "dependencies", "likelyFiles", "verificationPlan"],
                properties: {
                  id: { type: "string", minLength: 1 },
                  title: { type: "string", minLength: 1 },
                  evidence: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 20 },
                  scorecard: {
                    type: "object",
                    additionalProperties: false,
                    required: ["userValue", "evidenceConfidence", "novelty", "implementationLeverage", "testability", "effort", "risk"],
                    properties: {
                      userValue: { type: "number", minimum: 0, maximum: 100 },
                      evidenceConfidence: { type: "number", minimum: 0, maximum: 100 },
                      novelty: { type: "number", minimum: 0, maximum: 100 },
                      implementationLeverage: { type: "number", minimum: 0, maximum: 100 },
                      testability: { type: "number", minimum: 0, maximum: 100 },
                      effort: { type: "number", minimum: 0, maximum: 100 },
                      risk: { type: "number", minimum: 0, maximum: 100 },
                    },
                  },
                  acceptanceCriteria: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 20 },
                  dependencies: { type: "array", items: { type: "string" }, maxItems: 20 },
                  likelyFiles: { type: "array", items: { type: "string" }, maxItems: 50 },
                  verificationPlan: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 20 },
                },
              },
            },
            researchDecision: {
              type: "object",
              additionalProperties: false,
              required: ["needsResearch", "reason", "queries"],
              properties: {
                needsResearch: { type: "boolean" },
                reason: { type: "string" },
                queries: { type: "array", items: { type: "string" }, maxItems: 8 },
              },
            },
          },
        },
        prompt:
          "Before broad research, build a structured portfolio of 3-5 materially different feature opportunities from persisted constitution {{data:understand-project:output.constitution}}, full profile {{data:understand-project:output}}, projectVision={{projectVision:text=}}, featureStrategy={{featureStrategy:text=}}, inspirationSources={{inspirationSources:text=}}, completed goals {{result:read-completed-goals}}, and detected commands {{result:detect-project-commands}}. Score every dimension 0-100, cite concrete local evidence, bound lists, and identify only focused research queries that could change ranking or implementation. Dependencies, schemas, migrations, and public APIs may change when necessary and verified. Avoid duplicates, security-only work, and mere cleanup. Return only schema-valid JSON.",
      },
    },
    {
      id: "improve-feature-goal",
      title: "Improve Feature Goal",
      position: { x: 2080, y: 140 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        maxAttempts: 2,
        schema: {
          type: "object",
          additionalProperties: false,
          required: ["id", "title", "rationale", "selectionScorecard", "acceptanceCriteria", "tasks", "status"],
          properties: {
            id: { type: "string", minLength: 1 },
            title: { type: "string", minLength: 1 },
            rationale: { type: "string" },
            selectionScorecard: {
              type: "object",
              required: ["userValue", "evidenceConfidence", "novelty", "implementationLeverage", "testability", "effort", "risk"],
              properties: {
                userValue: { type: "number", minimum: 0, maximum: 100 },
                evidenceConfidence: { type: "number", minimum: 0, maximum: 100 },
                novelty: { type: "number", minimum: 0, maximum: 100 },
                implementationLeverage: { type: "number", minimum: 0, maximum: 100 },
                testability: { type: "number", minimum: 0, maximum: 100 },
                effort: { type: "number", minimum: 0, maximum: 100 },
                risk: { type: "number", minimum: 0, maximum: 100 },
              },
            },
            acceptanceCriteria: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 30 },
            tasks: {
              type: "array",
              maxItems: 50,
              items: RALPH_TASK_SCHEMA,
            },
            status: { type: "string", enum: ["planned", "implementing", "completed", "deferred", "no_action"] },
          },
        },
        prompt:
          "Critique, rescore, and select the strongest feature from structured portfolio {{data:draft-feature-goal:output}} using persisted constitution {{data:understand-project:output.constitution}} and focused research {{summary:research-inspiration}}. Strengthen product value, reduce ambiguity, remove contradicted work, and add measurable acceptance criteria. Every task must include stable id, canonical status planned/implementing/verifying/repairing/completed/deferred, batchKey, dependencies, likelyFiles, size, acceptanceCriteria, and priority so runtime utilities own lifecycle transitions and up to {{maxTasksPerImplementationPass:number=3}} compatible tasks can run per pass. Use task deferred only for unavailable external state; use top-level deferred only when the entire goal is externally impossible. Make the best bounded reversible product assumption without human approval. If every candidate lacks value/evidence, return status no_action with tasks []; otherwise select autonomously. Return only schema-valid JSON for {{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}.",
      },
    },
    {
      id: "has-actionable-goal",
      title: "Actionable Goal?",
      position: { x: 2280, y: 360 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "lastData?.output && Array.isArray(lastData.output.tasks) && lastData.output.tasks.length > 0 && !['deferred', 'no_action', 'no-action', 'stop', 'none', 'completed'].includes(String(lastData.output.status ?? '').toLowerCase())",
        },
      },
    },
    {
      id: "selection-is-deferred",
      title: "Selection Deferred?",
      position: { x: 2440, y: 420 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "String(context.resultsByBlock?.['improve-feature-goal']?.data?.output?.status ?? '').toLowerCase() === 'deferred'",
        },
      },
    },
    {
      id: "write-active-goal",
      title: "Track Active Goal",
      position: { x: 2420, y: 140 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "WRITE_JSON",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
        input: "{{data:improve-feature-goal:output}}",
      },
    },
    {
      id: "create-implementation-plan",
      title: "Create Implementation Plan",
      position: { x: 2760, y: 0 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Create or update implementation guidance around active goal JSON {{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}} without changing task lifecycle fields. Use active goal context {{summary:prepare-active-goal}}, newly tracked goal {{result:write-active-goal}}, detected commands {{result:detect-project-commands}}, and durable project profile {{data:understand-project:output}} when present. Confirm the checklist is dependency-aware, resumable, scoped to {{implementationScope:text=auto-detect}}, respects excludedAreas={{excludedAreas:text=}}, and includes verification, visual, auth, and design expectations. SELECT_JSON_TASK and MARK_JSON_TASK exclusively own status transitions.",
    },
    {
      id: "read-canonical-active-goal",
      title: "Read Canonical Active Goal",
      position: { x: 2860, y: -300 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "READ_JSON",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
      },
    },
    {
      id: "select-next-task",
      title: "Select Next Task",
      position: { x: 2860, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SELECT_JSON_TASK",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
        jsonPath: "tasks",
        strategy: "start-to-end",
        maxTasks: "{{maxTasksPerImplementationPass:number=3}}",
      },
    },
    {
      id: "goal-is-complete",
      title: "Goal Deterministically Complete?",
      position: { x: 3020, y: 420 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "Array.isArray(lastData?.tasks) && lastData.tasks.length > 0 && lastData.tasks.every((task) => String(task?.status ?? '').toLowerCase() === 'completed')",
        },
      },
    },
    {
      id: "git-snapshot-before",
      title: "Git Snapshot",
      position: { x: 2930, y: -210 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_SNAPSHOT",
        cwd: ".",
        outputPath:
          "{{gitSnapshotFile:path=.machdoch/autonomous-features/git-snapshot.json}}",
      },
    },
    {
      id: "implement-feature",
      title: "Implement Feature",
      position: { x: 3100, y: 0 },
      size: { width: 300, height: 220 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 4,
      },
      type: "PROMPT",
      prompt:
        "Implement the selected active-goal task batch {{data:select-next-task:tasks}} from {{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}; primary task for compatibility is {{data:select-next-task:task}}. Complete every compatible selected task in this pass. Use git baseline {{result:git-snapshot-before}}, baseline verification {{result:baseline-verification}}, detected commands {{result:detect-project-commands}}, pass count {{result:count-implementation-pass}}, validation feedback {{result:validate-goal}}, work-yield analysis {{data:work-yield-analysis:output}}, and durable constitution {{data:understand-project:output.constitution}}. Follow local patterns, keep changes scoped, avoid excluded areas {{excludedAreas:text=}}, apply authInstructions={{authInstructions:text=}} and designGuidelines={{designGuidelines:text=}}, and add meaningful tests. Dependency changes are allowed with allowDependencyChanges={{allowDependencyChanges:boolean=true}}, schemas/migrations with allowSchemaChanges={{allowSchemaChanges:boolean=true}}, and public APIs with allowPublicApiChanges={{allowPublicApiChanges:boolean=true}} when required and verified. Never edit task lifecycle fields: runtime SELECT_JSON_TASK and MARK_JSON_TASK own every status transition. Repair only new or worsened failures relative to baseline and make bounded reversible assumptions autonomously.",
    },
    {
      id: "mark-tasks-verifying",
      title: "Mark Goal Tasks Verifying",
      position: { x: 3280, y: 190 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_JSON_TASK",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
        jsonPath: "tasks",
        input: "{{data:select-next-task}}",
        status: "verifying",
        enforce: true,
      },
    },
    {
      id: "work-yield-analysis",
      title: "Assess Work Yield",
      position: { x: 3440, y: -190 },
      size: { width: 300, height: 190 },
      type: "UTILITY",
      utility: {
        type: "TRANSFORM_JSON",
        input: "{}",
        expression:
          "(() => { const diffResult = context.resultsByBlock?.get?.('git-diff-summary'); const baselineResult = context.resultsByBlock?.get?.('git-snapshot-before'); const currentFiles = Array.isArray(diffResult?.data?.files) ? diffResult.data.files : []; const baselineFiles = Array.isArray(baselineResult?.data?.files) ? baselineResult.data.files : []; const normalize = (value) => String(value ?? '').replace(/\\\\/gu, '/').replace(/^\\.\\/+/, ''); const baseline = new Map(baselineFiles.filter((file) => file && typeof file.path === 'string').map((file) => [normalize(file.path), file.signature])); const changedSinceBaselineFiles = currentFiles.filter((file) => file && typeof file.path === 'string' && baseline.get(normalize(file.path)) !== file.signature).map((file) => normalize(file.path)); const stateFile = normalize(variables.goalFilePath || '.machdoch/autonomous-features/active-goal.json'); const implementationFiles = changedSinceBaselineFiles.filter((path) => path !== stateFile); const selectedTasks = context.resultsByBlock?.get?.('select-next-task')?.data?.tasks; const selectedTaskCount = Array.isArray(selectedTasks) ? selectedTasks.length : 1; const diffErrored = diffResult?.output === 'ERROR'; const onlyStateFileChanged = changedSinceBaselineFiles.length > 0 && implementationFiles.length === 0; const shouldVerify = diffErrored || implementationFiles.length > 0; return { shouldVerify, diffOutput: diffResult?.output ?? '', selectedTaskCount, stateFile, changedSinceBaselineCount: changedSinceBaselineFiles.length, changedSinceBaselineFiles, implementationFileCount: implementationFiles.length, implementationFiles, onlyStateFileChanged, baselineFileCount: baselineFiles.length, currentFileCount: currentFiles.length, reason: shouldVerify ? (diffErrored ? 'Git diff summary failed; keep verification path available.' : 'Implementation changed files beyond the flow state file since the pre-pass snapshot.') : (onlyStateFileChanged ? 'Only the active goal JSON changed; skip expensive verification and let validation request real implementation work.' : 'Implementation produced no file changes beyond the pre-pass snapshot; skip expensive verification and let validation request another implementation pass.') }; })()",
      },
    },
    {
      id: "work-yield-decision",
      title: "Useful Work Produced?",
      position: { x: 3440, y: 30 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression: "lastData?.shouldVerify === true",
        },
      },
    },
    {
      id: "count-implementation-pass",
      title: "Count Implementation Pass",
      position: { x: 3100, y: 250 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        counterName:
          "autonomous-feature-generation-loop.implementation-pass.{{data:read-canonical-active-goal:json.id}}.{{data:select-next-task:task.id}}.{{data:select-next-task:index}}",
        maxAttempts: "{{maxImplementationPasses:number=10}}",
      },
    },
    {
      id: "baseline-verification",
      title: "Record Verification Baseline",
      position: { x: 3100, y: -360 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{verificationCommand:text=}}",
        fallbackCommand: "{{data:detect-project-commands:focusedVerificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "verification-decision",
      title: "Run Verification?",
      position: { x: 3440, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "Boolean(variables.verificationCommand?.trim() || context.resultsByBlock?.['detect-project-commands']?.data?.verificationCommand?.trim())",
        },
      },
    },
    {
      id: "run-verification",
      title: "Run Verification",
      position: { x: 3760, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{verificationCommand:text=}}",
        fallbackCommand: "{{data:detect-project-commands:verificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "visual-decision",
      title: "Run Visual Review?",
      position: { x: 3760, y: 120 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'variables.enableVisualReview === "true" && (Boolean(variables.targetUrl?.trim()) || Boolean(variables.screenshotPath?.trim()))',
        },
      },
    },
    {
      id: "visual-review",
      title: "Visual Review",
      position: { x: 4100, y: 20 },
      size: { width: 280, height: 190 },
      type: "UTILITY",
      utility: {
        type: "UI_ANALYZE",
        adapter: "auto",
        targetUrl: "{{targetUrl:url=}}",
        screenshotPath: "{{screenshotPath:path=}}",
        server: {
          mode: "existing",
          healthUrl: "{{healthUrl:url=}}",
        },
        checks: {
          screenshots: true,
          accessibility: true,
          console: true,
          network: true,
          responsive: true,
        },
        viewports: [
          { name: "desktop", width: 1280, height: 900 },
          { name: "tablet", width: 768, height: 1024 },
          { name: "mobile", width: 390, height: 844 },
          { name: "small-mobile", width: 320, height: 568 },
        ],
        timeoutSeconds: 30,
        fullPage: true,
        waitUntil: "domcontentloaded",
      },
    },
    {
      id: "git-diff-summary",
      title: "Git Diff Summary",
      position: { x: 4270, y: -170 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_DIFF_SUMMARY",
        cwd: ".",
        outputPath:
          "{{gitDiffFile:path=.machdoch/autonomous-features/git-diff.json}}",
      },
    },
    {
      id: "validate-goal",
      title: "Validate Goal",
      position: { x: 4440, y: 0 },
      size: { width: 320, height: 250 },
      type: "UTILITY",
      utility: {
        type: "VALIDATOR_JSON",
        maxAttempts: 2,
        schema: RALPH_VALIDATOR_SCHEMA,
        prompt:
          "Validate active goal JSON {{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}} against selected task batch {{data:select-next-task:tasks}}, work-yield analysis {{data:work-yield-analysis:output}}, baseline verification {{result:baseline-verification}}, post-change verification {{result:run-verification}}, git diff {{result:git-diff-summary}}, and visual review {{result:visual-review}}. Judge only the active goal and required adjacent tests/docs/imports; ignore unrelated workspace changes. If no implementation files changed or only goal JSON changed, avoid DONE unless the task truly required no file changes. Return DONE when the whole goal is implemented and no new/worsened verification failure exists relative to baseline, CONTINUE when bounded tasks remain, RETRY for own regressions, and ERROR only when unavailable external credentials/state or repeated non-progress makes this goal deferrable. Never wait for a human decision; make the best bounded reversible assumption. Include confidence, summary, evidence, and remainingWork.",
      },
    },
    {
      id: "mark-tasks-repairing",
      title: "Mark Goal Tasks Repairing",
      position: { x: 4620, y: 300 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_JSON_TASK",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
        jsonPath: "tasks",
        input: "{{data:select-next-task}}",
        status: "repairing",
        enforce: true,
      },
    },
    {
      id: "mark-tasks-completed",
      title: "Mark Goal Tasks Completed",
      position: { x: 4620, y: -220 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_JSON_TASK",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
        jsonPath: "tasks",
        input: "{{data:select-next-task}}",
        status: "completed",
        enforce: true,
      },
    },
    {
      id: "mark-tasks-deferred",
      title: "Mark Goal Tasks Deferred",
      position: { x: 4620, y: 500 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_JSON_TASK",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
        jsonPath: "tasks",
        input: "{{data:select-next-task}}",
        status: "deferred",
        enforce: true,
      },
    },
    {
      id: "read-completed-goal",
      title: "Read Completed Goal",
      position: { x: 4800, y: 0 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "READ_JSON",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
      },
    },
    {
      id: "append-completed-goal",
      title: "Append Completed Goal",
      position: { x: 5140, y: 0 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{completedGoalsFile:path=.machdoch/autonomous-features/completed-goals.jsonl}}",
        input: "{{data:read-completed-goal:json}}",
      },
    },
    {
      id: "final-report",
      title: "Final Autonomous Report",
      position: { x: 5480, y: -120 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{autonomousReportFile:path=.machdoch/autonomous-features/final-report.json}}",
        outputPath:
          "{{autonomousReportMarkdown:path=.machdoch/autonomous-features/final-report.md}}",
      },
    },
    {
      id: "archive-goal",
      title: "Archive Completed Goal",
      position: { x: 5820, y: 0 },
      size: { width: 280, height: 160 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "ARCHIVE_FILE",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
        rootPath:
          "{{archivedGoalsDirectory:path=.machdoch/autonomous-features/archive}}",
      },
    },
    {
      id: "retained-goal-report",
      title: "Retained Goal State Report",
      position: { x: 5660, y: 220 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{autonomousReportFile:path=.machdoch/autonomous-features/final-report.json}}",
        outputPath:
          "{{autonomousReportMarkdown:path=.machdoch/autonomous-features/final-report.md}}",
      },
    },
    {
      id: "stop-goal-report",
      title: "No-Action Goal Report",
      position: { x: 5660, y: 420 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{autonomousReportFile:path=.machdoch/autonomous-features/final-report.json}}",
        outputPath:
          "{{autonomousReportMarkdown:path=.machdoch/autonomous-features/final-report.md}}",
      },
    },
    {
      id: "record-done-goal-outcome",
      title: "Record Completed Goal Outcome",
      position: { x: 5320, y: -180 },
      size: { width: 280, height: 160 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{goalOutcomesFile:path=.machdoch/autonomous-features/outcomes.jsonl}}",
        input:
          "{\"outcome\":\"DONE\",\"goalId\":\"{{data:read-completed-goal:json.id}}\"}",
      },
    },
    {
      id: "record-deferred-goal-outcome",
      title: "Record Deferred Goal Outcome",
      position: { x: 5320, y: 220 },
      size: { width: 280, height: 160 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{goalOutcomesFile:path=.machdoch/autonomous-features/outcomes.jsonl}}",
        input:
          "{\"outcome\":\"DEFER\",\"goalPath\":\"{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}\",\"reason\":\"Bounded repair exhausted or external state unavailable.\"}",
      },
    },
    {
      id: "record-no-action-goal-outcome",
      title: "Record No-Action Goal Outcome",
      position: { x: 5320, y: 400 },
      size: { width: 280, height: 160 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{goalOutcomesFile:path=.machdoch/autonomous-features/outcomes.jsonl}}",
        input:
          "{\"outcome\":\"STOP\",\"goalPath\":\"{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}\",\"reason\":\"No evidence-backed feature cleared the meaningful-work threshold.\"}",
      },
    },
    {
      id: "record-invalid-goal-outcome",
      title: "Record Invalid Goal Outcome",
      position: { x: 5320, y: 580 },
      size: { width: 280, height: 160 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{goalOutcomesFile:path=.machdoch/autonomous-features/outcomes.jsonl}}",
        input:
          "{\"outcome\":\"INVALID\",\"reason\":\"Goal discovery, state recovery, or validation produced invalid structured data.\"}",
      },
    },
    {
      id: "goals-per-run-counter",
      title: "Goals Per Run Counter",
      position: { x: 6160, y: 0 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        path: ".machdoch/autonomous-features/run-counters.json",
        counterName: "processed-goals.{{run:id}}",
        maxAttempts: "{{maxGoalsPerRun:number=100}}",
      },
    },
    {
      id: "success",
      title: "No Actionable Feature Goal",
      position: { x: 6500, y: 0 },
      size: { width: 280, height: 114 },
      type: "END",
      status: "success",
    },
    {
      id: "deferred",
      title: "Goal State Retained for Retry",
      position: { x: 6160, y: 300 },
      size: { width: 280, height: 114 },
      type: "END",
      status: "success",
    },
  ],
  edges: [
    { id: "start-to-detect-commands", from: "start", fromOutput: "SUCCESS", to: "detect-project-commands" },
    { id: "detect-commands-to-find", from: "detect-project-commands", fromOutput: "SUCCESS", to: "find-active-goal" },
    { id: "detect-commands-empty-to-find", from: "detect-project-commands", fromOutput: "EMPTY", to: "find-active-goal" },
    { id: "detect-commands-error-to-find", from: "detect-project-commands", fromOutput: "ERROR", to: "find-active-goal" },
    { id: "active-goal-found", from: "find-active-goal", fromOutput: "EXISTS", to: "read-active-goal" },
    { id: "active-goal-empty", from: "find-active-goal", fromOutput: "MISSING", to: "read-completed-goals" },
    { id: "active-goal-search-error", from: "find-active-goal", fromOutput: "ERROR", to: "read-completed-goals" },
    { id: "read-active-goal-success", from: "read-active-goal", fromOutput: "SUCCESS", to: "prepare-active-goal" },
    { id: "read-active-goal-invalid", from: "read-active-goal", fromOutput: "INVALID", to: "record-invalid-goal-outcome" },
    { id: "read-active-goal-not-found", from: "read-active-goal", fromOutput: "NOT_FOUND", to: "read-completed-goals" },
    { id: "read-active-goal-error", from: "read-active-goal", fromOutput: "ERROR", to: "read-completed-goals" },
    { id: "prepare-active-goal-success", from: "prepare-active-goal", fromOutput: "SUCCESS", to: "create-implementation-plan" },
    { id: "prepare-active-goal-error", from: "prepare-active-goal", fromOutput: "ERROR", to: "record-deferred-goal-outcome" },
    { id: "completed-goals-to-understand", from: "read-completed-goals", fromOutput: "SUCCESS", to: "understand-project" },
    { id: "completed-goals-empty-to-understand", from: "read-completed-goals", fromOutput: "EMPTY", to: "understand-project" },
    { id: "completed-goals-missing-to-understand", from: "read-completed-goals", fromOutput: "NOT_FOUND", to: "understand-project" },
    { id: "completed-goals-invalid-to-understand", from: "read-completed-goals", fromOutput: "INVALID", to: "understand-project" },
    { id: "completed-goals-error-to-understand", from: "read-completed-goals", fromOutput: "ERROR", to: "understand-project" },
    { id: "understand-to-portfolio", from: "understand-project", fromOutput: "SUCCESS", to: "draft-feature-goal" },
    { id: "understand-invalid", from: "understand-project", fromOutput: "INVALID", to: "record-invalid-goal-outcome" },
    { id: "understand-error", from: "understand-project", fromOutput: "ERROR", to: "record-invalid-goal-outcome" },
    { id: "portfolio-to-research-decision", from: "draft-feature-goal", fromOutput: "SUCCESS", to: "research-decision" },
    { id: "portfolio-invalid", from: "draft-feature-goal", fromOutput: "INVALID", to: "record-invalid-goal-outcome" },
    { id: "portfolio-error", from: "draft-feature-goal", fromOutput: "ERROR", to: "record-invalid-goal-outcome" },
    { id: "research-decision-run", from: "research-decision", fromOutput: "MATCH", to: "research-inspiration" },
    { id: "research-decision-skip", from: "research-decision", fromOutput: "NO_MATCH", to: "improve-feature-goal" },
    { id: "research-decision-error", from: "research-decision", fromOutput: "ERROR", to: "improve-feature-goal" },
    { id: "research-to-improve", from: "research-inspiration", fromOutput: "SUCCESS", to: "improve-feature-goal" },
    { id: "research-error-to-improve", from: "research-inspiration", fromOutput: "ERROR", to: "improve-feature-goal" },
    { id: "improve-to-actionable-goal", from: "improve-feature-goal", fromOutput: "SUCCESS", to: "has-actionable-goal" },
    { id: "improve-invalid", from: "improve-feature-goal", fromOutput: "INVALID", to: "record-invalid-goal-outcome" },
    { id: "improve-error", from: "improve-feature-goal", fromOutput: "ERROR", to: "record-invalid-goal-outcome" },
    { id: "actionable-goal-to-write", from: "has-actionable-goal", fromOutput: "MATCH", to: "write-active-goal" },
    { id: "no-actionable-goal", from: "has-actionable-goal", fromOutput: "NO_MATCH", to: "selection-is-deferred" },
    { id: "actionable-goal-error", from: "has-actionable-goal", fromOutput: "ERROR", to: "record-invalid-goal-outcome" },
    { id: "selection-deferred-to-ledger", from: "selection-is-deferred", fromOutput: "MATCH", to: "record-deferred-goal-outcome" },
    { id: "selection-stop-to-ledger", from: "selection-is-deferred", fromOutput: "NO_MATCH", to: "record-no-action-goal-outcome" },
    { id: "selection-status-error-to-invalid", from: "selection-is-deferred", fromOutput: "ERROR", to: "record-invalid-goal-outcome" },
    { id: "write-to-plan", from: "write-active-goal", fromOutput: "SUCCESS", to: "create-implementation-plan" },
    { id: "write-invalid", from: "write-active-goal", fromOutput: "INVALID", to: "record-invalid-goal-outcome" },
    { id: "write-error", from: "write-active-goal", fromOutput: "ERROR", to: "record-invalid-goal-outcome" },
    { id: "plan-to-read-canonical-goal", from: "create-implementation-plan", fromOutput: "SUCCESS", to: "read-canonical-active-goal" },
    { id: "plan-error", from: "create-implementation-plan", fromOutput: "ERROR", to: "record-deferred-goal-outcome" },
    { id: "canonical-goal-to-select", from: "read-canonical-active-goal", fromOutput: "SUCCESS", to: "select-next-task" },
    { id: "canonical-goal-invalid", from: "read-canonical-active-goal", fromOutput: "INVALID", to: "record-invalid-goal-outcome" },
    { id: "canonical-goal-missing", from: "read-canonical-active-goal", fromOutput: "NOT_FOUND", to: "record-invalid-goal-outcome" },
    { id: "canonical-goal-error", from: "read-canonical-active-goal", fromOutput: "ERROR", to: "record-invalid-goal-outcome" },
    { id: "select-task-to-snapshot", from: "select-next-task", fromOutput: "SELECTED", to: "git-snapshot-before" },
    { id: "select-task-empty-to-state-check", from: "select-next-task", fromOutput: "EMPTY", to: "goal-is-complete" },
    { id: "goal-state-complete-to-read", from: "goal-is-complete", fromOutput: "MATCH", to: "read-completed-goal" },
    { id: "goal-state-deadlock-to-defer", from: "goal-is-complete", fromOutput: "NO_MATCH", to: "record-deferred-goal-outcome" },
    { id: "goal-state-error-to-invalid", from: "goal-is-complete", fromOutput: "ERROR", to: "record-invalid-goal-outcome" },
    { id: "select-task-not-found", from: "select-next-task", fromOutput: "NOT_FOUND", to: "record-invalid-goal-outcome" },
    { id: "select-task-invalid", from: "select-next-task", fromOutput: "INVALID", to: "record-invalid-goal-outcome" },
    { id: "select-task-error", from: "select-next-task", fromOutput: "ERROR", to: "record-deferred-goal-outcome" },
    { id: "snapshot-to-baseline", from: "git-snapshot-before", fromOutput: "SUCCESS", to: "baseline-verification" },
    { id: "snapshot-error-to-baseline", from: "git-snapshot-before", fromOutput: "ERROR", to: "baseline-verification" },
    { id: "baseline-success-to-count", from: "baseline-verification", fromOutput: "SUCCESS", to: "count-implementation-pass" },
    { id: "baseline-failed-to-count", from: "baseline-verification", fromOutput: "FAILED", to: "count-implementation-pass" },
    { id: "baseline-error-to-count", from: "baseline-verification", fromOutput: "ERROR", to: "count-implementation-pass" },
    { id: "count-implementation-pass-continue", from: "count-implementation-pass", fromOutput: "CONTINUE", to: "implement-feature" },
    { id: "count-implementation-pass-limit", from: "count-implementation-pass", fromOutput: "LIMIT_REACHED", to: "mark-tasks-deferred" },
    { id: "count-implementation-pass-error", from: "count-implementation-pass", fromOutput: "ERROR", to: "mark-tasks-deferred" },
    { id: "implementation-to-mark-verifying", from: "implement-feature", fromOutput: "SUCCESS", to: "mark-tasks-verifying" },
    { id: "implementation-error", from: "implement-feature", fromOutput: "ERROR", to: "mark-tasks-deferred" },
    { id: "mark-verifying-to-diff", from: "mark-tasks-verifying", fromOutput: "SUCCESS", to: "git-diff-summary" },
    { id: "mark-verifying-missing", from: "mark-tasks-verifying", fromOutput: "NOT_FOUND", to: "record-invalid-goal-outcome" },
    { id: "mark-verifying-invalid", from: "mark-tasks-verifying", fromOutput: "INVALID", to: "record-invalid-goal-outcome" },
    { id: "mark-verifying-error", from: "mark-tasks-verifying", fromOutput: "ERROR", to: "record-invalid-goal-outcome" },
    { id: "git-diff-success-to-work-yield", from: "git-diff-summary", fromOutput: "SUCCESS", to: "work-yield-analysis" },
    { id: "git-diff-empty-to-work-yield", from: "git-diff-summary", fromOutput: "EMPTY", to: "work-yield-analysis" },
    { id: "git-diff-error-to-work-yield", from: "git-diff-summary", fromOutput: "ERROR", to: "work-yield-analysis" },
    { id: "work-yield-analysis-success", from: "work-yield-analysis", fromOutput: "SUCCESS", to: "work-yield-decision" },
    { id: "work-yield-analysis-error", from: "work-yield-analysis", fromOutput: "ERROR", to: "verification-decision" },
    { id: "work-yield-useful", from: "work-yield-decision", fromOutput: "MATCH", to: "verification-decision" },
    { id: "work-yield-empty-to-validate", from: "work-yield-decision", fromOutput: "NO_MATCH", to: "validate-goal" },
    { id: "work-yield-error-to-verification-decision", from: "work-yield-decision", fromOutput: "ERROR", to: "verification-decision" },
    { id: "verification-decision-run", from: "verification-decision", fromOutput: "MATCH", to: "run-verification" },
    { id: "verification-decision-skip", from: "verification-decision", fromOutput: "NO_MATCH", to: "visual-decision" },
    { id: "verification-decision-error", from: "verification-decision", fromOutput: "ERROR", to: "visual-decision" },
    { id: "verification-success-to-visual-decision", from: "run-verification", fromOutput: "SUCCESS", to: "visual-decision" },
    { id: "verification-failed-to-visual-decision", from: "run-verification", fromOutput: "FAILED", to: "visual-decision" },
    { id: "verification-error-to-visual-decision", from: "run-verification", fromOutput: "ERROR", to: "visual-decision" },
    { id: "visual-decision-run", from: "visual-decision", fromOutput: "MATCH", to: "visual-review" },
    { id: "visual-decision-skip", from: "visual-decision", fromOutput: "NO_MATCH", to: "validate-goal" },
    { id: "visual-decision-error", from: "visual-decision", fromOutput: "ERROR", to: "validate-goal" },
    { id: "visual-success-to-validate", from: "visual-review", fromOutput: "SUCCESS", to: "validate-goal" },
    { id: "visual-unavailable-to-validate", from: "visual-review", fromOutput: "UNAVAILABLE", to: "validate-goal" },
    { id: "visual-error-to-validate", from: "visual-review", fromOutput: "ERROR", to: "validate-goal" },
    { id: "validation-done-to-mark-completed", from: "validate-goal", fromOutput: "DONE", to: "mark-tasks-completed" },
    { id: "validation-continue", from: "validate-goal", fromOutput: "CONTINUE", to: "mark-tasks-repairing" },
    { id: "validation-retry", from: "validate-goal", fromOutput: "RETRY", to: "mark-tasks-repairing" },
    { id: "validation-error", from: "validate-goal", fromOutput: "ERROR", to: "mark-tasks-deferred" },
    { id: "validation-invalid", from: "validate-goal", fromOutput: "INVALID", to: "mark-tasks-deferred" },
    { id: "mark-repairing-to-select", from: "mark-tasks-repairing", fromOutput: "SUCCESS", to: "select-next-task" },
    { id: "mark-repairing-missing", from: "mark-tasks-repairing", fromOutput: "NOT_FOUND", to: "record-invalid-goal-outcome" },
    { id: "mark-repairing-invalid", from: "mark-tasks-repairing", fromOutput: "INVALID", to: "record-invalid-goal-outcome" },
    { id: "mark-repairing-error", from: "mark-tasks-repairing", fromOutput: "ERROR", to: "record-invalid-goal-outcome" },
    { id: "mark-completed-to-select", from: "mark-tasks-completed", fromOutput: "SUCCESS", to: "select-next-task" },
    { id: "mark-completed-missing-to-select", from: "mark-tasks-completed", fromOutput: "NOT_FOUND", to: "select-next-task" },
    { id: "mark-completed-invalid", from: "mark-tasks-completed", fromOutput: "INVALID", to: "record-invalid-goal-outcome" },
    { id: "mark-completed-error", from: "mark-tasks-completed", fromOutput: "ERROR", to: "record-invalid-goal-outcome" },
    { id: "mark-deferred-to-ledger", from: "mark-tasks-deferred", fromOutput: "SUCCESS", to: "record-deferred-goal-outcome" },
    { id: "mark-deferred-missing-to-ledger", from: "mark-tasks-deferred", fromOutput: "NOT_FOUND", to: "record-deferred-goal-outcome" },
    { id: "mark-deferred-invalid", from: "mark-tasks-deferred", fromOutput: "INVALID", to: "record-invalid-goal-outcome" },
    { id: "mark-deferred-error", from: "mark-tasks-deferred", fromOutput: "ERROR", to: "record-invalid-goal-outcome" },
    { id: "read-completed-to-append", from: "read-completed-goal", fromOutput: "SUCCESS", to: "append-completed-goal" },
    { id: "read-completed-invalid", from: "read-completed-goal", fromOutput: "INVALID", to: "record-invalid-goal-outcome" },
    { id: "read-completed-not-found", from: "read-completed-goal", fromOutput: "NOT_FOUND", to: "record-invalid-goal-outcome" },
    { id: "read-completed-error", from: "read-completed-goal", fromOutput: "ERROR", to: "record-invalid-goal-outcome" },
    { id: "append-completed-to-outcome", from: "append-completed-goal", fromOutput: "SUCCESS", to: "record-done-goal-outcome" },
    { id: "append-completed-invalid", from: "append-completed-goal", fromOutput: "INVALID", to: "record-invalid-goal-outcome" },
    { id: "append-completed-error", from: "append-completed-goal", fromOutput: "ERROR", to: "record-invalid-goal-outcome" },
    { id: "done-outcome-to-archive", from: "record-done-goal-outcome", fromOutput: "SUCCESS", to: "archive-goal" },
    { id: "done-outcome-invalid-to-retained-report", from: "record-done-goal-outcome", fromOutput: "INVALID", to: "retained-goal-report" },
    { id: "done-outcome-error-to-retained-report", from: "record-done-goal-outcome", fromOutput: "ERROR", to: "retained-goal-report" },
    { id: "deferred-outcome-to-retained-report", from: "record-deferred-goal-outcome", fromOutput: "SUCCESS", to: "retained-goal-report" },
    { id: "deferred-outcome-invalid-to-retained-report", from: "record-deferred-goal-outcome", fromOutput: "INVALID", to: "retained-goal-report" },
    { id: "deferred-outcome-error-to-retained-report", from: "record-deferred-goal-outcome", fromOutput: "ERROR", to: "retained-goal-report" },
    { id: "no-action-outcome-to-stop-report", from: "record-no-action-goal-outcome", fromOutput: "SUCCESS", to: "stop-goal-report" },
    { id: "no-action-outcome-invalid-to-retained-report", from: "record-no-action-goal-outcome", fromOutput: "INVALID", to: "retained-goal-report" },
    { id: "no-action-outcome-error-to-retained-report", from: "record-no-action-goal-outcome", fromOutput: "ERROR", to: "retained-goal-report" },
    { id: "invalid-outcome-to-retained-report", from: "record-invalid-goal-outcome", fromOutput: "SUCCESS", to: "retained-goal-report" },
    { id: "invalid-outcome-invalid-to-retained-report", from: "record-invalid-goal-outcome", fromOutput: "INVALID", to: "retained-goal-report" },
    { id: "invalid-outcome-error-to-retained-report", from: "record-invalid-goal-outcome", fromOutput: "ERROR", to: "retained-goal-report" },
    { id: "archive-to-report", from: "archive-goal", fromOutput: "SUCCESS", to: "final-report" },
    { id: "archive-not-found-to-report", from: "archive-goal", fromOutput: "NOT_FOUND", to: "final-report" },
    { id: "archive-error-to-retained-report", from: "archive-goal", fromOutput: "ERROR", to: "retained-goal-report" },
    { id: "report-success-to-counter", from: "final-report", fromOutput: "SUCCESS", to: "goals-per-run-counter" },
    { id: "report-error-to-counter", from: "final-report", fromOutput: "ERROR", to: "goals-per-run-counter" },
    { id: "retained-report-success-to-deferred", from: "retained-goal-report", fromOutput: "SUCCESS", to: "deferred" },
    { id: "retained-report-error-to-deferred", from: "retained-goal-report", fromOutput: "ERROR", to: "deferred" },
    { id: "stop-report-success-to-end", from: "stop-goal-report", fromOutput: "SUCCESS", to: "success" },
    { id: "stop-report-error-to-end", from: "stop-goal-report", fromOutput: "ERROR", to: "success" },
    { id: "counter-continue-to-detect-next", from: "goals-per-run-counter", fromOutput: "CONTINUE", to: "detect-project-commands" },
    { id: "counter-limit-to-success", from: "goals-per-run-counter", fromOutput: "LIMIT_REACHED", to: "success" },
    { id: "counter-error", from: "goals-per-run-counter", fromOutput: "ERROR", to: "success" },
  ],
};

export const autonomousFeatureGenerationLoopStarterFlow = {
  id: "autonomous-feature-generation-loop",
  version: 11,
  defaultAlias: "autonomous-feature-generation-loop",
  category: "Implementation",
  tags: ["autonomous", "feature", "loop"],
  flow: autonomousFeatureGenerationLoopFlow,
} as const satisfies RalphStarterFlow;
