import type { RalphFlow } from "../ralph.js";
import type { RalphStarterFlow } from "../ralph-starter-flows.js";

const RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS = 30 * 60;

const autonomousCodeImprovementLoopFlow: RalphFlow = {
  schemaVersion: 1,
  id: "starter-autonomous-code-improvement-loop",
  alias: "autonomous-code-improvement-loop",
  name: "Autonomous Code Improvement Loop",
  description:
    "Endless autonomous loop that discovers evidence-backed code improvements, allows justified behavior changes, verifies and reviews them, and stops when no meaningful candidate remains.",
  settings: {
    maxTransitions: 500,
  },
  variables: [
    { name: "scopeRoot", type: "path", default: ".", required: false },
    { name: "scopeSelectionStrategy", type: "text", default: "priority", required: false },
    { name: "scopeRegistryFile", type: "path", default: ".machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json", required: false },
    { name: "scopeRegistryMarkdown", type: "path", default: ".machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md", required: false },
    { name: "improvementPolicy", type: "text", default: "Prefer high-confidence improvements to correctness, reliability, UX, accessibility, performance, error handling, tests, or maintainability. Behavior changes are allowed when they are intentional, bounded, documented, and verified.", required: false },
    { name: "meaningfulThreshold", type: "text", default: "Only continue when there is concrete code, test, runtime, UX, accessibility, performance, or security evidence that the improvement is worth making now. Stop instead of inventing speculative cleanup, premature abstraction, cosmetic churn, or tiny nits.", required: false },
    { name: "riskTolerance", type: "text", default: "moderate", required: false },
    { name: "implementationScope", type: "text", default: "auto-detect", required: false },
    { name: "excludePaths", type: "text", default: "node_modules, dist, build, coverage, target, .next, .nuxt, .turbo, .cache, vendor, generated, .machdoch", required: false },
    { name: "enableOnlineResearch", type: "boolean", default: "true", required: false },
    { name: "allowDependencyChanges", type: "boolean", default: "false", required: false },
    { name: "allowSchemaChanges", type: "boolean", default: "false", required: false },
    { name: "verificationCommand", type: "text", default: "", required: false },
    { name: "enableVisualReview", type: "boolean", default: "false", required: false },
    { name: "targetUrl", type: "url", default: "", required: false },
    { name: "healthUrl", type: "url", default: "", required: false },
    { name: "screenshotPath", type: "path", default: "", required: false },
    { name: "maxImprovementPasses", type: "number", default: "8", required: false },
    { name: "activeImprovementFile", type: "path", default: ".machdoch/ralph/code-improvements/active-improvement.json", required: false },
    { name: "completedImprovementsFile", type: "path", default: ".machdoch/ralph/code-improvements/completed-improvements.jsonl", required: false },
    { name: "archivedImprovementsDirectory", type: "path", default: ".machdoch/ralph/code-improvements/archive", required: false },
    { name: "projectCommandsFile", type: "path", default: ".machdoch/ralph/code-improvements/project-commands.json", required: false },
    { name: "scopeAnalysisFile", type: "path", default: ".machdoch/ralph/code-improvements/scope-analysis.json", required: false },
    { name: "candidateFile", type: "path", default: ".machdoch/ralph/code-improvements/candidate.json", required: false },
    { name: "reviewFile", type: "path", default: ".machdoch/ralph/code-improvements/review.json", required: false },
    { name: "gitSnapshotFile", type: "path", default: ".machdoch/ralph/code-improvements/git-snapshot.json", required: false },
    { name: "gitDiffFile", type: "path", default: ".machdoch/ralph/code-improvements/git-diff.json", required: false },
    { name: "improvementReportFile", type: "path", default: ".machdoch/ralph/code-improvements/final-report.json", required: false },
    { name: "improvementReportMarkdown", type: "path", default: ".machdoch/ralph/code-improvements/final-report.md", required: false },
    { name: "notesFile", type: "path", default: ".machdoch/ralph/code-improvements/RALPH_CODE_IMPROVEMENT_NOTES.md", required: false },
  ],
  blocks: [
    {
      id: "start",
      title: "Start",
      position: { x: 0, y: 0 },
      size: { width: 256, height: 140 },
      type: "START",
    },
    {
      id: "scan-scopes",
      title: "Scan Scope Evidence",
      position: { x: 700, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SCAN_SCOPE_EVIDENCE",
        rootPath: "{{scopeRoot:path=.}}",
        excludePaths: "{{excludePaths:text=node_modules, dist, build, coverage, target, .next, .nuxt, .turbo, .cache, vendor, generated, .machdoch}}",
        maxDepth: 4,
        maxResults: 240,
      },
    },
    {
      id: "update-scope-registry",
      title: "Update Scope Registry",
      position: { x: 1040, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "UPDATE_SCOPE_REGISTRY",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md}}",
        strategy: "{{scopeSelectionStrategy:text=priority}}",
        includeMarkdown: true,
      },
    },
    {
      id: "select-scope",
      title: "Select Improvement Scope",
      position: { x: 1380, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SELECT_SCOPE",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        strategy: "{{scopeSelectionStrategy:text=priority}}",
      },
    },
    {
      id: "detect-project-commands",
      title: "Detect Project Commands",
      position: { x: 1720, y: -160 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "DETECT_PROJECT_COMMANDS",
        rootPath: "{{data:select-scope:scope.paths.0}}",
        outputPath:
          "{{projectCommandsFile:path=.machdoch/ralph/code-improvements/project-commands.json}}",
      },
    },
    {
      id: "read-completed-improvements",
      title: "Read Completed Improvements",
      position: { x: 1720, y: 40 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "READ_JSONL",
        path: "{{completedImprovementsFile:path=.machdoch/ralph/code-improvements/completed-improvements.jsonl}}",
      },
    },
    {
      id: "research-decision",
      title: "Use Online Research?",
      position: { x: 2400, y: -150 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'variables.enableOnlineResearch === "true" && lastData?.output?.researchDecision?.needsResearch === true',
        },
      },
    },
    {
      id: "improvement-research",
      title: "Improvement Research",
      position: { x: 2720, y: -180 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        webAccess: true,
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Use content enrichment only for the structured research decision in work package {{data:choose-improvement:output.researchDecision}} and selected package {{data:choose-improvement:output.selectedCandidate}}. If search_web is available, run focused searches for current primary-source framework/library behavior, changelogs, release notes, accessibility guidance, performance recommendations, testing approaches, security advisories, and standards relevant to the package. Use fetch_url on the best official or maintainer pages before relying on them, and inspect local package/config metadata for version assumptions. Keep findings concise with source links, freshness/version notes, practical implications, and explicit non-findings. If web search is unavailable, say so and rely on local evidence plus provided URLs. Do not research broadly just to find extra work.",
    },
    {
      id: "choose-improvement",
      title: "Plan Improvement Package",
      position: { x: 3060, y: 0 },
      size: { width: 320, height: 250 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{candidateFile:path=.machdoch/ralph/code-improvements/candidate.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: [
            "decision",
            "rationale",
            "scopeAnalysis",
            "researchDecision",
            "selectedCandidate",
            "rejectedCandidates",
            "stopReason",
          ],
          properties: {
            decision: { type: "string" },
            rationale: { type: "string" },
            scopeAnalysis: {
              type: "object",
              properties: {
                scope: { type: "object" },
                scopeCluster: { type: "object" },
                signals: { type: "array", items: { type: "string" } },
                constraints: { type: "array", items: { type: "string" } },
                stopSignals: { type: "array", items: { type: "string" } },
              },
            },
            researchDecision: {
              type: "object",
              required: ["needsResearch", "reason", "queries"],
              properties: {
                needsResearch: { type: "boolean" },
                reason: { type: "string" },
                queries: { type: "array", items: { type: "string" } },
              },
            },
            selectedCandidate: {
              type: "object",
              properties: {
                id: { type: "string" },
                title: { type: "string" },
                relatedChanges: { type: "array", items: { type: "object" } },
                affectedFiles: { type: "array", items: { type: "string" } },
                acceptanceCriteria: { type: "array", items: { type: "string" } },
                verificationPlan: { type: "array", items: { type: "string" } },
                verificationTier: { type: "string" },
                reviewTier: { type: "string" },
              },
            },
            rejectedCandidates: { type: "array", items: { type: "object" } },
            stopReason: { type: "string" },
          },
        },
        prompt:
          "Inspect selected JSON scope and dependency-aware scope cluster {{result:select-scope}} without editing files. Use detected commands {{result:detect-project-commands}}, completed improvement history {{result:read-completed-improvements}}, latest completed append {{result:append-completed-improvement}}, implementationScope={{implementationScope:text=auto-detect}}, riskTolerance={{riskTolerance:text=moderate}}, excludePaths={{excludePaths:text=}}, and policy {{improvementPolicy:text=}}. Merge scope analysis, online-research decision, and improvement selection into one structured decision. Return decision IMPLEMENT only for one cohesive work package, not one micro-change: select 2-5 tightly related changes when they share evidence, files, tests, or acceptance criteria and are safer/productive to complete together. The package must have a stable kebab-case id, title, concrete evidence, local or primary-source user/maintainer value, currentBehavior, proposedBehavior, relatedChanges with affected files, acceptanceCriteria, expectedOutcome, riskAssessment, verificationTier (focused, standard, or broad), reviewTier (validator-only or strict), verificationPlan, rollbackNotes, and remainingRelatedWork. Prefer focused verification for low-risk localized packages; require broad verification and strict review for shared contracts, security, persistence, IPC/API, schemas, dependencies, auth, config, or broad UI behavior. Set researchDecision.needsResearch true only when the package depends on current external docs, APIs, framework/library behavior, security guidance, compatibility, or comparable product context; include focused queries. Set it false when local evidence and existing commands are enough. Behavior changes are allowed only when they improve correctness, UX, accessibility, reliability, performance, error handling, tests, or maintainability and can be verified. Return STOP when this scope cluster's remaining ideas are speculative, tiny nits, cosmetic churn, premature abstractions, broad rewrites, duplicate of completed history, require product/domain approval, require unsafe schema/dependency changes, or fail threshold {{meaningfulThreshold:text=}}. STOP means this scope is done for the current cycle only after no worthwhile related package remains in the scope cluster. Do not dig for weak work to keep the loop busy. If decision is STOP, selectedCandidate must be {} and stopReason must explain the evidence-backed reason. Return only schema-valid JSON.",
      },
    },
    {
      id: "has-actionable-improvement",
      title: "Actionable Improvement?",
      position: { x: 3400, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'context.resultsByBlock?.["choose-improvement"]?.data?.output?.decision === "IMPLEMENT" && context.resultsByBlock?.["choose-improvement"]?.data?.output?.selectedCandidate && Object.keys(context.resultsByBlock["choose-improvement"].data.output.selectedCandidate).length > 0',
        },
      },
    },
    {
      id: "write-active-improvement",
      title: "Track Active Improvement",
      position: { x: 3720, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "WRITE_JSON",
        path: "{{activeImprovementFile:path=.machdoch/ralph/code-improvements/active-improvement.json}}",
        input: "{{data:choose-improvement:output.selectedCandidate}}",
      },
    },
    {
      id: "git-snapshot-before",
      title: "Git Snapshot",
      position: { x: 4060, y: -180 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_SNAPSHOT",
        cwd: ".",
        outputPath:
          "{{gitSnapshotFile:path=.machdoch/ralph/code-improvements/git-snapshot.json}}",
      },
    },
    {
      id: "count-improvement-pass",
      title: "Count Improvement Pass",
      position: { x: 4060, y: 230 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        counterName:
          "autonomous-code-improvement-loop.implementation-pass.{{data:select-scope:scope.id}}.{{data:choose-improvement:output.selectedCandidate.id}}",
        maxAttempts: "{{maxImprovementPasses:number=8}}",
      },
    },
    {
      id: "implement-improvement",
      title: "Implement Improvement",
      position: { x: 4060, y: 40 },
      size: { width: 320, height: 250 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 4,
      },
      type: "PROMPT",
      prompt:
        "Implement the active code improvement package at {{activeImprovementFile:path=.machdoch/ralph/code-improvements/active-improvement.json}} using package {{data:choose-improvement:output.selectedCandidate}}, selected scope and scope cluster {{result:select-scope}}, scope analysis {{data:choose-improvement:output.scopeAnalysis}}, research {{summary:improvement-research}}, git baseline {{result:git-snapshot-before}}, detected commands {{result:detect-project-commands}}, pass count {{result:count-improvement-pass}}, latest validator feedback {{result:validate-improvement}}, latest review feedback {{data:independent-review:output}}, and verification routing {{data:select-verification-command:output}}. Complete the cohesive package before stopping; do not split tightly related package changes into separate future cycles unless blocked by risk or missing evidence. Behavior changes are allowed when tied to currentBehavior/proposedBehavior, acceptanceCriteria, expectedOutcome, and verificationPlan. Keep changes bounded to the selected scope cluster and required adjacent tests/docs/imports. Add or update meaningful tests when feasible. Update docs only when behavior, commands, or user interaction changes. Do not perform broad formatting sweeps, speculative abstractions, unrelated cleanup, or extra unrelated packages. Dependency changes require allowDependencyChanges={{allowDependencyChanges:boolean=false}} and a documented necessity. Schema or migration changes require allowSchemaChanges={{allowSchemaChanges:boolean=false}} and must be blocked if unsafe. Do not start or restart servers. Append a concise note to {{notesFile:path=.machdoch/ralph/code-improvements/RALPH_CODE_IMPROVEMENT_NOTES.md}} with package changes, behavior changes, verification tier, verification command/status, and remaining risks.",
    },
    {
      id: "select-verification-command",
      title: "Select Verification Tier",
      position: { x: 4400, y: -140 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "TRANSFORM_JSON",
        input: "{}",
        expression:
          "(() => { const candidate = context.resultsByBlock?.get?.('choose-improvement')?.data?.output?.selectedCandidate ?? {}; const commands = context.resultsByBlock?.get?.('detect-project-commands')?.data ?? {}; const requestedTier = String(candidate.verificationTier ?? candidate.riskAssessment?.verificationTier ?? '').toLowerCase(); const requestedReviewTier = String(candidate.reviewTier ?? candidate.riskAssessment?.reviewTier ?? '').toLowerCase(); const riskText = JSON.stringify([candidate.risk, candidate.riskAssessment, candidate.affectedFiles, candidate.relatedChanges, candidate.acceptanceCriteria]).toLowerCase(); const highRisk = /(security|auth|token|secret|permission|database|migration|schema|ipc|api|dependency|package|lockfile|persistence|public api|contract|credential)/u.test(riskText); const tier = highRisk || requestedTier === 'broad' || requestedTier === 'strict' ? 'broad' : requestedTier === 'standard' ? 'standard' : 'focused'; const detectedCommand = tier === 'broad' ? commands.broadVerificationCommand : tier === 'standard' ? commands.standardVerificationCommand : commands.focusedVerificationCommand; const command = (variables.verificationCommand ?? '').trim() || detectedCommand || commands.verificationCommand || ''; const reviewTier = highRisk || requestedReviewTier === 'strict' || tier === 'broad' ? 'strict' : 'validator-only'; return { tier, command, reviewTier, highRisk, source: (variables.verificationCommand ?? '').trim() ? 'variable' : 'detected', focusedCommand: commands.focusedVerificationCommand || '', standardCommand: commands.standardVerificationCommand || '', broadCommand: commands.broadVerificationCommand || '' }; })()",
      },
    },
    {
      id: "verification-decision",
      title: "Run Verification?",
      position: { x: 4400, y: 40 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "Boolean(context.resultsByBlock?.['select-verification-command']?.data?.output?.command?.trim())",
        },
      },
    },
    {
      id: "run-verification",
      title: "Run Verification",
      position: { x: 4720, y: -110 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{data:select-verification-command:output.command}}",
        fallbackCommand: "{{data:detect-project-commands:focusedVerificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "fix-validation-failures",
      title: "Fix Validation Failures",
      position: { x: 4720, y: 120 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "PROMPT",
      prompt:
        "Fix verification failures from {{result:run-verification}} that were caused by the current code improvement package. Distinguish pre-existing failures from own regressions. Keep fixes scoped to active package {{data:choose-improvement:output.selectedCandidate}} and selected scope cluster {{result:select-scope}}. Do not broaden the package or start an unrelated package.",
    },
    {
      id: "visual-decision",
      title: "Run Visual Review?",
      position: { x: 5060, y: 40 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'variables.enableVisualReview === "true" && (Boolean(variables.targetUrl?.trim()) || Boolean(variables.screenshotPath?.trim()))',
        },
      },
    },
    {
      id: "visual-review",
      title: "Visual Review",
      position: { x: 5380, y: 40 },
      size: { width: 280, height: 190 },
      type: "UTILITY",
      utility: {
        type: "UI_ANALYZE",
        adapter: "auto",
        targetUrl: "{{targetUrl:url=}}",
        screenshotPath: "{{screenshotPath:path=}}",
        server: {
          mode: "existing",
          healthUrl: "{{healthUrl:url=}}",
        },
        checks: {
          screenshots: true,
          accessibility: true,
          console: true,
          network: true,
          responsive: true,
        },
        viewports: [
          { name: "desktop", width: 1280, height: 900 },
          { name: "tablet", width: 768, height: 1024 },
          { name: "mobile", width: 390, height: 844 },
          { name: "small-mobile", width: 320, height: 568 },
        ],
        timeoutSeconds: 30,
        fullPage: true,
        waitUntil: "domcontentloaded",
      },
    },
    {
      id: "git-diff-summary",
      title: "Git Diff Summary",
      position: { x: 5720, y: -100 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_DIFF_SUMMARY",
        cwd: ".",
        outputPath:
          "{{gitDiffFile:path=.machdoch/ralph/code-improvements/git-diff.json}}",
      },
    },
    {
      id: "review-tier-decision",
      title: "Strict Review?",
      position: { x: 6060, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'context.resultsByBlock?.["select-verification-command"]?.data?.output?.reviewTier === "strict"',
        },
      },
    },
    {
      id: "independent-review",
      title: "Independent Review",
      position: { x: 6400, y: 0 },
      size: { width: 320, height: 250 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{reviewFile:path=.machdoch/ralph/code-improvements/review.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: ["decision", "summary", "findings", "behaviorChangeAssessment", "securityRegressionAssessment", "verificationAssessment"],
          properties: {
            decision: { type: "string" },
            summary: { type: "string" },
            findings: { type: "array", items: { type: "object" } },
            behaviorChangeAssessment: { type: "string" },
            securityRegressionAssessment: { type: "string" },
            verificationAssessment: { type: "string" },
          },
        },
        prompt:
          "Review the current code improvement package as a separate reviewer because verification routing requested strict review. Active package: {{data:choose-improvement:output.selectedCandidate}}. Scope cluster: {{result:select-scope}}. Diff: {{result:git-diff-summary}}. Verification routing: {{data:select-verification-command:output}}. Verification: {{result:run-verification}}. Visual review: {{result:visual-review}}. Evaluate only the active package, selected scope cluster, and required adjacent tests/docs/imports. Ignore unrelated workspace changes outside that scope unless they directly break verification of this package. Check functionality, behavior changes, tests, docs, maintainability, complexity, over-engineering, accessibility, performance claims, and security regressions. Treat user input, files, network responses, environment variables, IPC/API boundaries, logs, credentials, auth, access control, shell/file operations, and data protection as security-sensitive. Return decision PASS when the package is cohesive, bounded, justified, verified or explicitly justified as unverified, and does not introduce regressions. Return FIX when specific issues remain. Return BLOCKED when unsafe, ambiguous, or requires human/product approval. Return only schema-valid JSON.",
      },
    },
    {
      id: "validate-improvement",
      title: "Validate Improvement",
      position: { x: 6740, y: 0 },
      size: { width: 320, height: 250 },
      type: "UTILITY",
      utility: {
        type: "VALIDATOR_JSON",
        maxAttempts: 2,
        prompt:
          "Validate the latest autonomous code improvement package. Package: {{data:choose-improvement:output.selectedCandidate}}. Scope cluster: {{result:select-scope}}. Verification routing: {{data:select-verification-command:output}}. Strict review, when run: {{data:independent-review:output}}. Verification: {{result:run-verification}}. Visual review: {{result:visual-review}}. Git diff: {{result:git-diff-summary}}. Notes file: {{notesFile:path=.machdoch/ralph/code-improvements/RALPH_CODE_IMPROVEMENT_NOTES.md}}. Judge only the active package, selected scope cluster, and required adjacent tests/docs/imports. Ignore unrelated workspace changes outside that scope unless they directly break verification of this package. For validator-only low-risk packages, avoid demanding a duplicate strict review when focused verification passed and the diff is localized. Return DONE only when the whole cohesive package is implemented, any behavior change is intentional and captured by acceptance criteria/tests/docs as feasible, verification is passing or skipped with a sound reason, no security regression is introduced, and no further worthwhile related work remains for this package. Return CONTINUE only when the same package still needs bounded implementation work; the flow counter enforces maxImprovementPasses={{maxImprovementPasses:number=8}}. Return RETRY when validation/review found own regressions that should be corrected. Return ERROR when blocked by unsafe changes, ambiguous behavior, required human/product decision, unavailable credentials/tooling, repeated failure, or work that no longer meets meaningfulThreshold={{meaningfulThreshold:text=}}.",
      },
    },
    {
      id: "final-report",
      title: "Final Improvement Report",
      position: { x: 7080, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{improvementReportFile:path=.machdoch/ralph/code-improvements/final-report.json}}",
        outputPath:
          "{{improvementReportMarkdown:path=.machdoch/ralph/code-improvements/final-report.md}}",
      },
    },
    {
      id: "read-active-improvement",
      title: "Read Active Improvement",
      position: { x: 7420, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "READ_JSON",
        path: "{{activeImprovementFile:path=.machdoch/ralph/code-improvements/active-improvement.json}}",
      },
    },
    {
      id: "append-completed-improvement",
      title: "Append Completed Improvement",
      position: { x: 7760, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{completedImprovementsFile:path=.machdoch/ralph/code-improvements/completed-improvements.jsonl}}",
        input: "{{data:read-active-improvement:json}}",
      },
    },
    {
      id: "archive-active-improvement",
      title: "Archive Active Improvement",
      position: { x: 8100, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "ARCHIVE_FILE",
        path: "{{activeImprovementFile:path=.machdoch/ralph/code-improvements/active-improvement.json}}",
        rootPath:
          "{{archivedImprovementsDirectory:path=.machdoch/ralph/code-improvements/archive}}",
      },
    },
    {
      id: "mark-scope-result",
      title: "Mark Scope Result",
      position: { x: 3720, y: 300 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md}}",
        result: "DONE",
        includeMarkdown: true,
      },
    },
    {
      id: "scope-cycle-complete",
      title: "Scope Cycle Complete?",
      position: { x: 4060, y: 300 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression: "lastData?.cycleCompleted === true",
        },
      },
    },
    {
      id: "success",
      title: "No Meaningful Improvements",
      position: { x: 4400, y: 300 },
      size: { width: 280, height: 114 },
      type: "END",
      status: "success",
    },
    {
      id: "blocked",
      title: "Blocked",
      position: { x: 3060, y: 340 },
      size: { width: 256, height: 114 },
      type: "END",
      status: "failed",
    },
  ],
  edges: [
    { id: "start-to-scan-scopes", from: "start", fromOutput: "SUCCESS", to: "scan-scopes" },
    { id: "scan-scopes-to-update", from: "scan-scopes", fromOutput: "SUCCESS", to: "update-scope-registry" },
    { id: "scan-scopes-empty", from: "scan-scopes", fromOutput: "EMPTY", to: "blocked" },
    { id: "scan-scopes-error", from: "scan-scopes", fromOutput: "ERROR", to: "blocked" },
    { id: "update-registry-to-select", from: "update-scope-registry", fromOutput: "SUCCESS", to: "select-scope" },
    { id: "update-registry-empty", from: "update-scope-registry", fromOutput: "EMPTY", to: "success" },
    { id: "update-registry-error", from: "update-scope-registry", fromOutput: "ERROR", to: "blocked" },
    { id: "select-scope-to-detect", from: "select-scope", fromOutput: "SELECTED", to: "detect-project-commands" },
    { id: "select-scope-empty", from: "select-scope", fromOutput: "EMPTY", to: "success" },
    { id: "select-scope-error", from: "select-scope", fromOutput: "ERROR", to: "blocked" },
    { id: "detect-success-to-history", from: "detect-project-commands", fromOutput: "SUCCESS", to: "read-completed-improvements" },
    { id: "detect-empty-to-history", from: "detect-project-commands", fromOutput: "EMPTY", to: "read-completed-improvements" },
    { id: "detect-error-to-history", from: "detect-project-commands", fromOutput: "ERROR", to: "read-completed-improvements" },
    { id: "history-success-to-choose", from: "read-completed-improvements", fromOutput: "SUCCESS", to: "choose-improvement" },
    { id: "history-empty-to-choose", from: "read-completed-improvements", fromOutput: "EMPTY", to: "choose-improvement" },
    { id: "history-not-found-to-choose", from: "read-completed-improvements", fromOutput: "NOT_FOUND", to: "choose-improvement" },
    { id: "history-invalid-to-choose", from: "read-completed-improvements", fromOutput: "INVALID", to: "choose-improvement" },
    { id: "history-error-to-choose", from: "read-completed-improvements", fromOutput: "ERROR", to: "choose-improvement" },
    { id: "choose-to-research-decision", from: "choose-improvement", fromOutput: "SUCCESS", to: "research-decision" },
    { id: "choose-invalid", from: "choose-improvement", fromOutput: "INVALID", to: "blocked" },
    { id: "choose-error", from: "choose-improvement", fromOutput: "ERROR", to: "blocked" },
    { id: "research-decision-run", from: "research-decision", fromOutput: "MATCH", to: "improvement-research" },
    { id: "research-decision-skip", from: "research-decision", fromOutput: "NO_MATCH", to: "has-actionable-improvement" },
    { id: "research-decision-error", from: "research-decision", fromOutput: "ERROR", to: "has-actionable-improvement" },
    { id: "research-to-actionable", from: "improvement-research", fromOutput: "SUCCESS", to: "has-actionable-improvement" },
    { id: "research-error-to-actionable", from: "improvement-research", fromOutput: "ERROR", to: "has-actionable-improvement" },
    { id: "actionable-to-write", from: "has-actionable-improvement", fromOutput: "MATCH", to: "write-active-improvement" },
    { id: "not-actionable-to-mark", from: "has-actionable-improvement", fromOutput: "NO_MATCH", to: "mark-scope-result" },
    { id: "actionable-error", from: "has-actionable-improvement", fromOutput: "ERROR", to: "mark-scope-result" },
    { id: "write-to-snapshot", from: "write-active-improvement", fromOutput: "SUCCESS", to: "git-snapshot-before" },
    { id: "write-invalid", from: "write-active-improvement", fromOutput: "INVALID", to: "blocked" },
    { id: "write-error", from: "write-active-improvement", fromOutput: "ERROR", to: "blocked" },
    { id: "snapshot-to-count-improvement-pass", from: "git-snapshot-before", fromOutput: "SUCCESS", to: "count-improvement-pass" },
    { id: "snapshot-error-to-count-improvement-pass", from: "git-snapshot-before", fromOutput: "ERROR", to: "count-improvement-pass" },
    { id: "count-improvement-pass-continue", from: "count-improvement-pass", fromOutput: "CONTINUE", to: "implement-improvement" },
    { id: "count-improvement-pass-limit", from: "count-improvement-pass", fromOutput: "LIMIT_REACHED", to: "blocked" },
    { id: "count-improvement-pass-error", from: "count-improvement-pass", fromOutput: "ERROR", to: "blocked" },
    { id: "implement-to-verification-tier", from: "implement-improvement", fromOutput: "SUCCESS", to: "select-verification-command" },
    { id: "implement-error", from: "implement-improvement", fromOutput: "ERROR", to: "blocked" },
    { id: "verification-tier-to-decision", from: "select-verification-command", fromOutput: "SUCCESS", to: "verification-decision" },
    { id: "verification-tier-error", from: "select-verification-command", fromOutput: "ERROR", to: "verification-decision" },
    { id: "verification-decision-run", from: "verification-decision", fromOutput: "MATCH", to: "run-verification" },
    { id: "verification-decision-skip", from: "verification-decision", fromOutput: "NO_MATCH", to: "visual-decision" },
    { id: "verification-decision-error", from: "verification-decision", fromOutput: "ERROR", to: "visual-decision" },
    { id: "verification-success-to-visual", from: "run-verification", fromOutput: "SUCCESS", to: "visual-decision" },
    { id: "verification-failed-to-fix", from: "run-verification", fromOutput: "FAILED", to: "fix-validation-failures" },
    { id: "verification-error-to-fix", from: "run-verification", fromOutput: "ERROR", to: "fix-validation-failures" },
    { id: "fix-validation-to-decision", from: "fix-validation-failures", fromOutput: "SUCCESS", to: "verification-decision" },
    { id: "fix-validation-error", from: "fix-validation-failures", fromOutput: "ERROR", to: "blocked" },
    { id: "visual-decision-run", from: "visual-decision", fromOutput: "MATCH", to: "visual-review" },
    { id: "visual-decision-skip", from: "visual-decision", fromOutput: "NO_MATCH", to: "git-diff-summary" },
    { id: "visual-decision-error", from: "visual-decision", fromOutput: "ERROR", to: "git-diff-summary" },
    { id: "visual-success-to-diff", from: "visual-review", fromOutput: "SUCCESS", to: "git-diff-summary" },
    { id: "visual-unavailable-to-diff", from: "visual-review", fromOutput: "UNAVAILABLE", to: "git-diff-summary" },
    { id: "visual-error-to-diff", from: "visual-review", fromOutput: "ERROR", to: "git-diff-summary" },
    { id: "diff-success-to-review-tier", from: "git-diff-summary", fromOutput: "SUCCESS", to: "review-tier-decision" },
    { id: "diff-empty-to-review-tier", from: "git-diff-summary", fromOutput: "EMPTY", to: "review-tier-decision" },
    { id: "diff-error-to-review-tier", from: "git-diff-summary", fromOutput: "ERROR", to: "review-tier-decision" },
    { id: "review-tier-strict", from: "review-tier-decision", fromOutput: "MATCH", to: "independent-review" },
    { id: "review-tier-validator-only", from: "review-tier-decision", fromOutput: "NO_MATCH", to: "validate-improvement" },
    { id: "review-tier-error-to-validate", from: "review-tier-decision", fromOutput: "ERROR", to: "validate-improvement" },
    { id: "review-to-validate", from: "independent-review", fromOutput: "SUCCESS", to: "validate-improvement" },
    { id: "review-invalid", from: "independent-review", fromOutput: "INVALID", to: "blocked" },
    { id: "review-error", from: "independent-review", fromOutput: "ERROR", to: "blocked" },
    { id: "validate-done", from: "validate-improvement", fromOutput: "DONE", to: "final-report" },
    { id: "validate-continue", from: "validate-improvement", fromOutput: "CONTINUE", to: "count-improvement-pass" },
    { id: "validate-retry", from: "validate-improvement", fromOutput: "RETRY", to: "count-improvement-pass" },
    { id: "validate-error", from: "validate-improvement", fromOutput: "ERROR", to: "blocked" },
    { id: "validate-invalid", from: "validate-improvement", fromOutput: "INVALID", to: "blocked" },
    { id: "report-success-to-read-active", from: "final-report", fromOutput: "SUCCESS", to: "read-active-improvement" },
    { id: "report-error-to-read-active", from: "final-report", fromOutput: "ERROR", to: "read-active-improvement" },
    { id: "read-active-success-to-append", from: "read-active-improvement", fromOutput: "SUCCESS", to: "append-completed-improvement" },
    { id: "read-active-invalid", from: "read-active-improvement", fromOutput: "INVALID", to: "blocked" },
    { id: "read-active-not-found", from: "read-active-improvement", fromOutput: "NOT_FOUND", to: "blocked" },
    { id: "read-active-error", from: "read-active-improvement", fromOutput: "ERROR", to: "blocked" },
    { id: "append-completed-to-archive", from: "append-completed-improvement", fromOutput: "SUCCESS", to: "archive-active-improvement" },
    { id: "append-completed-invalid", from: "append-completed-improvement", fromOutput: "INVALID", to: "blocked" },
    { id: "append-completed-error", from: "append-completed-improvement", fromOutput: "ERROR", to: "blocked" },
    { id: "archive-success-to-mark-scope", from: "archive-active-improvement", fromOutput: "SUCCESS", to: "mark-scope-result" },
    { id: "archive-not-found-to-mark-scope", from: "archive-active-improvement", fromOutput: "NOT_FOUND", to: "mark-scope-result" },
    { id: "archive-error", from: "archive-active-improvement", fromOutput: "ERROR", to: "blocked" },
    { id: "mark-scope-success", from: "mark-scope-result", fromOutput: "SUCCESS", to: "scope-cycle-complete" },
    { id: "mark-scope-not-found", from: "mark-scope-result", fromOutput: "NOT_FOUND", to: "blocked" },
    { id: "mark-scope-error", from: "mark-scope-result", fromOutput: "ERROR", to: "blocked" },
    { id: "scope-cycle-complete-success", from: "scope-cycle-complete", fromOutput: "MATCH", to: "success" },
    { id: "scope-cycle-next", from: "scope-cycle-complete", fromOutput: "NO_MATCH", to: "select-scope" },
    { id: "scope-cycle-error", from: "scope-cycle-complete", fromOutput: "ERROR", to: "select-scope" },
  ],
};

export const autonomousCodeImprovementLoopStarterFlow = {
  id: "autonomous-code-improvement-loop",
  version: 9,
  defaultAlias: "autonomous-code-improvement-loop",
  category: "Code Quality",
  tags: ["autonomous", "improvement", "behavior-change", "validation"],
  flow: autonomousCodeImprovementLoopFlow,
} as const satisfies RalphStarterFlow;
