import type { RalphFlow } from "../ralph.js";
import type { RalphStarterFlow } from "../ralph-starter-flows.js";

const autonomousFeatureGenerationLoopFlow: RalphFlow = {
  schemaVersion: 1,
  id: "starter-autonomous-feature-generation-loop",
  alias: "autonomous-feature-generation-loop",
  name: "Autonomous Feature Generation Loop",
  description:
    "Endless autonomous loop that discovers useful new feature goals, tracks one active goal JSON file, implements until done, archives the goal, and starts again.",
  settings: {
    maxTransitions: 500,
  },
  variables: [
    {
      name: "goalDirectory",
      type: "path",
      default: ".machdoch/autonomous-features",
      required: false,
    },
    {
      name: "goalFileName",
      type: "text",
      default: "active-goal.json",
      required: false,
    },
    {
      name: "goalFilePath",
      type: "path",
      default: ".machdoch/autonomous-features/active-goal.json",
      required: false,
    },
    { name: "completedGoalsFile", type: "path", default: ".machdoch/autonomous-features/completed-goals.jsonl", required: false },
    { name: "archivedGoalsDirectory", type: "path", default: ".machdoch/autonomous-features/archive", required: false },
    { name: "projectProfileFile", type: "path", default: ".machdoch/autonomous-features/project-profile.json", required: false },
    { name: "projectCommandsFile", type: "path", default: ".machdoch/autonomous-features/project-commands.json", required: false },
    { name: "gitSnapshotFile", type: "path", default: ".machdoch/autonomous-features/git-snapshot.json", required: false },
    { name: "gitDiffFile", type: "path", default: ".machdoch/autonomous-features/git-diff.json", required: false },
    { name: "autonomousReportFile", type: "path", default: ".machdoch/autonomous-features/final-report.json", required: false },
    { name: "autonomousReportMarkdown", type: "path", default: ".machdoch/autonomous-features/final-report.md", required: false },
    { name: "maxGoalsPerRun", type: "number", default: "100", required: false },
    {
      name: "projectVision",
      type: "text",
      default: "",
      required: false,
    },
    {
      name: "featureStrategy",
      type: "text",
      default:
        "Prefer high-impact, shippable, coherent product improvements that fit the repository and compound over time.",
      required: false,
    },
    {
      name: "inspirationSources",
      type: "text",
      default:
        "Similar products, popular open-source alternatives, current platform capabilities, state-of-the-art UX patterns, and emerging/hyped feature ideas.",
      required: false,
    },
    {
      name: "enableOnlineResearch",
      type: "boolean",
      default: "true",
      required: false,
    },
    {
      name: "implementationScope",
      type: "text",
      default: "auto-detect",
      required: false,
    },
    {
      name: "excludedAreas",
      type: "text",
      default:
        "secrets, credentials, destructive migrations, unrelated dependency upgrades, generated files, vendor directories",
      required: false,
    },
    {
      name: "riskTolerance",
      type: "text",
      default: "moderate",
      required: false,
    },
    {
      name: "verificationCommand",
      type: "text",
      default: "",
      required: false,
    },
    {
      name: "enableVisualReview",
      type: "boolean",
      default: "false",
      required: false,
    },
    {
      name: "targetUrl",
      type: "url",
      default: "",
      required: false,
    },
    {
      name: "healthUrl",
      type: "url",
      default: "",
      required: false,
    },
    {
      name: "screenshotPath",
      type: "path",
      default: "",
      required: false,
    },
    {
      name: "authInstructions",
      type: "text",
      default: "",
      required: false,
    },
    {
      name: "designGuidelines",
      type: "text",
      default: "",
      required: false,
    },
    {
      name: "maxImplementationPasses",
      type: "number",
      default: "10",
      required: false,
    },
  ],
  blocks: [
    {
      id: "start",
      title: "Start",
      position: { x: 0, y: 0 },
      size: { width: 256, height: 140 },
      type: "START",
    },
    {
      id: "find-active-goal",
      title: "Find Active Goal",
      position: { x: 720, y: 0 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "FILE_EXISTS",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
      },
    },
    {
      id: "read-active-goal",
      title: "Read Active Goal",
      position: { x: 1060, y: -120 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "READ_JSON",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
      },
    },
    {
      id: "prepare-active-goal",
      title: "Prepare Active Goal",
      position: { x: 1400, y: -120 },
      size: { width: 280, height: 190 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Resume the tracked autonomous feature goal from {{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}. JSON read result: {{result:read-active-goal}}. Extract the goal, acceptance criteria, plan, completed tasks, verification expectations, risks, and next todo/in_progress work. Do not create a new goal while this file exists.",
    },
    {
      id: "detect-project-commands",
      title: "Detect Project Commands",
      position: { x: 860, y: 300 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "DETECT_PROJECT_COMMANDS",
        rootPath: ".",
        outputPath:
          "{{projectCommandsFile:path=.machdoch/autonomous-features/project-commands.json}}",
      },
    },
    {
      id: "understand-project",
      title: "Understand Project",
      position: { x: 1060, y: 140 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{projectProfileFile:path=.machdoch/autonomous-features/project-profile.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: ["product", "architecture", "currentFeatures", "extensionPoints", "constraints"],
          properties: {
            product: { type: "string" },
            architecture: { type: "array", items: { type: "string" } },
            currentFeatures: { type: "array", items: { type: "string" } },
            extensionPoints: { type: "array", items: { type: "string" } },
            constraints: { type: "array", items: { type: "string" } },
          },
        },
        prompt:
          "No active autonomous feature goal was found. Inspect the repository to understand the product, architecture, users, current feature set, extension points, tests, scripts, constraints, and recently changed areas. Use detected project commands {{result:detect-project-commands}}. Apply projectVision={{projectVision:text=}}, implementationScope={{implementationScope:text=auto-detect}}, excludedAreas={{excludedAreas:text=}}, and riskTolerance={{riskTolerance:text=moderate}}. Do not change files. Return only schema-valid JSON.",
      },
    },
    {
      id: "research-decision",
      title: "Use Online Research?",
      position: { x: 1380, y: 140 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression: 'variables.enableOnlineResearch === "true"',
        },
      },
    },
    {
      id: "research-inspiration",
      title: "Research Inspiration",
      position: { x: 1400, y: 140 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        webAccess: true,
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "PROMPT",
      prompt:
        "Research current and comparable products, open-source alternatives, new platform capabilities, state-of-the-art UX, and emerging/hyped ideas relevant to this project. Inspiration sources: {{inspirationSources:text=}}. Produce a concise opportunity map with links. Project profile: {{data:understand-project:output}}.",
    },
    {
      id: "draft-feature-goal",
      title: "Draft Feature Goal",
      position: { x: 1740, y: 140 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Define one concrete new feature goal for autonomous implementation. Use project profile {{data:understand-project:output}}, research {{summary:research-inspiration}}, projectVision={{projectVision:text=}}, featureStrategy={{featureStrategy:text=}}, riskTolerance={{riskTolerance:text=moderate}}, excludedAreas={{excludedAreas:text=}}, completed goals history at {{completedGoalsFile:path=.machdoch/autonomous-features/completed-goals.jsonl}}, and detected commands {{result:detect-project-commands}}. Choose a feature that is valuable, coherent with the codebase, shippable in a bounded loop, testable, and not merely cleanup. Avoid duplicating already completed work. Include acceptance criteria, non-goals, dependencies, likely files, verification plan, visual review needs, and a task checklist.",
    },
    {
      id: "improve-feature-goal",
      title: "Improve Feature Goal",
      position: { x: 2080, y: 140 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: ["id", "title", "rationale", "acceptanceCriteria", "tasks", "status"],
          properties: {
            id: { type: "string" },
            title: { type: "string" },
            rationale: { type: "string" },
            acceptanceCriteria: { type: "array", items: { type: "string" } },
            tasks: {
              type: "array",
              items: {
                type: "object",
                required: ["id", "title", "status"],
                properties: {
                  id: { type: "string" },
                  title: { type: "string" },
                  status: { type: "string" },
                },
              },
            },
            status: { type: "string" },
          },
        },
        prompt:
          "Critique and improve the drafted feature goal from {{summary:draft-feature-goal}}. Strengthen product value, reduce ambiguity, make the scope implementable, remove risky or irrelevant work, add measurable acceptance criteria, include a resumable checklist, and ensure it fits featureStrategy={{featureStrategy:text=}}. Return JSON suitable for {{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}} with stable task ids and status values todo/in_progress/done/blocked.",
      },
    },
    {
      id: "write-active-goal",
      title: "Track Active Goal",
      position: { x: 2420, y: 140 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "WRITE_JSON",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
        input: "{{data:improve-feature-goal:output}}",
      },
    },
    {
      id: "create-implementation-plan",
      title: "Create Implementation Plan",
      position: { x: 2760, y: 0 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Create or update the implementation plan in active goal JSON {{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}. Use active goal context {{summary:prepare-active-goal}}, newly tracked goal {{result:write-active-goal}}, detected commands {{result:detect-project-commands}}, and project profile {{data:understand-project:output}} when present. Confirm the checklist is ordered, resumable, scoped to {{implementationScope:text=auto-detect}}, respects excludedAreas={{excludedAreas:text=}}, includes verificationCommand={{verificationCommand:text=}} when configured, visual review expectations, authInstructions={{authInstructions:text=}}, and designGuidelines={{designGuidelines:text=}}.",
    },
    {
      id: "select-next-task",
      title: "Select Next Task",
      position: { x: 2860, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SELECT_JSON_TASK",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
        jsonPath: "tasks",
        strategy: "start-to-end",
      },
    },
    {
      id: "git-snapshot-before",
      title: "Git Snapshot",
      position: { x: 2930, y: -210 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_SNAPSHOT",
        cwd: ".",
        outputPath:
          "{{gitSnapshotFile:path=.machdoch/autonomous-features/git-snapshot.json}}",
      },
    },
    {
      id: "implement-feature",
      title: "Implement Feature",
      position: { x: 3100, y: 0 },
      size: { width: 300, height: 220 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 4,
      },
      type: "PROMPT",
      prompt:
        "Implement the selected active-goal task {{data:select-next-task:task}} from {{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}. Use git baseline {{result:git-snapshot-before}}, detected commands {{result:detect-project-commands}}, and latest validation feedback {{lastResult}}. Preserve existing behavior, follow local patterns, keep changes scoped, avoid excluded areas {{excludedAreas:text=}}, use authInstructions={{authInstructions:text=}} and designGuidelines={{designGuidelines:text=}}, add or update tests where appropriate, and update the selected task plus goal JSON checklist with completed items and resume notes.",
    },
    {
      id: "verification-decision",
      title: "Run Verification?",
      position: { x: 3440, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "Boolean(variables.verificationCommand?.trim() || context.resultsByBlock?.['detect-project-commands']?.data?.verificationCommand?.trim())",
        },
      },
    },
    {
      id: "run-verification",
      title: "Run Verification",
      position: { x: 3760, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{verificationCommand:text=}}",
        fallbackCommand: "{{data:detect-project-commands:verificationCommand}}",
      },
    },
    {
      id: "visual-decision",
      title: "Run Visual Review?",
      position: { x: 3760, y: 120 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'variables.enableVisualReview === "true" && (Boolean(variables.targetUrl?.trim()) || Boolean(variables.screenshotPath?.trim()))',
        },
      },
    },
    {
      id: "visual-review",
      title: "Visual Review",
      position: { x: 4100, y: 20 },
      size: { width: 280, height: 190 },
      type: "UTILITY",
      utility: {
        type: "UI_ANALYZE",
        adapter: "auto",
        targetUrl: "{{targetUrl:url=}}",
        screenshotPath: "{{screenshotPath:path=}}",
        server: {
          mode: "existing",
          healthUrl: "{{healthUrl:url=}}",
        },
        checks: {
          screenshots: true,
          accessibility: true,
          console: true,
          network: true,
          responsive: true,
        },
        viewports: [
          { name: "desktop", width: 1280, height: 900 },
          { name: "tablet", width: 768, height: 1024 },
          { name: "mobile", width: 390, height: 844 },
          { name: "small-mobile", width: 320, height: 568 },
        ],
        timeoutSeconds: 30,
        fullPage: true,
        waitUntil: "domcontentloaded",
      },
    },
    {
      id: "git-diff-summary",
      title: "Git Diff Summary",
      position: { x: 4270, y: -170 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_DIFF_SUMMARY",
        cwd: ".",
        outputPath:
          "{{gitDiffFile:path=.machdoch/autonomous-features/git-diff.json}}",
      },
    },
    {
      id: "validate-goal",
      title: "Validate Goal",
      position: { x: 4440, y: 0 },
      size: { width: 320, height: 250 },
      type: "UTILITY",
      utility: {
        type: "VALIDATOR_JSON",
        maxAttempts: 2,
        prompt:
          "Validate active goal JSON {{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}} against implementation changes, selected task {{data:select-next-task:task}}, verification result {{result:run-verification}}, git diff {{result:git-diff-summary}}, visual review {{result:visual-review}}, and latest implementation summary. Judge only the active goal, selected task, goal file, and required adjacent tests/docs/imports. Ignore unrelated workspace changes outside that goal/task unless they directly break verification of the active goal. Return JSON with decision DONE when the whole goal is completely implemented, verified or verification is explicitly skipped because no command is configured, and the goal file accurately records completion. Return CONTINUE when more tasks remain. Return RETRY when the last implementation pass needs correction. Return ERROR when blocked by missing context, unsafe changes in the active goal/task, failing verification that cannot be fixed, or repeated ambiguity. Include confidence, summary, evidence, and remainingWork.",
      },
    },
    {
      id: "read-completed-goal",
      title: "Read Completed Goal",
      position: { x: 4800, y: 0 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "READ_JSON",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
      },
    },
    {
      id: "append-completed-goal",
      title: "Append Completed Goal",
      position: { x: 5140, y: 0 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{completedGoalsFile:path=.machdoch/autonomous-features/completed-goals.jsonl}}",
        input: "{{data:read-completed-goal:json}}",
      },
    },
    {
      id: "final-report",
      title: "Final Autonomous Report",
      position: { x: 5480, y: -120 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{autonomousReportFile:path=.machdoch/autonomous-features/final-report.json}}",
        outputPath:
          "{{autonomousReportMarkdown:path=.machdoch/autonomous-features/final-report.md}}",
      },
    },
    {
      id: "archive-goal",
      title: "Archive Completed Goal",
      position: { x: 5820, y: 0 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "ARCHIVE_FILE",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
        rootPath:
          "{{archivedGoalsDirectory:path=.machdoch/autonomous-features/archive}}",
      },
    },
    {
      id: "goals-per-run-counter",
      title: "Goals Per Run Counter",
      position: { x: 6160, y: 0 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        path: ".machdoch/autonomous-features/run-counters.json",
        counterName: "completed-goals",
        maxAttempts: "{{maxGoalsPerRun:number=100}}",
      },
    },
    {
      id: "blocked",
      title: "Blocked",
      position: { x: 2760, y: 280 },
      size: { width: 256, height: 114 },
      type: "END",
      status: "failed",
    },
  ],
  edges: [
    { id: "start-to-find", from: "start", fromOutput: "SUCCESS", to: "find-active-goal" },
    { id: "active-goal-found", from: "find-active-goal", fromOutput: "EXISTS", to: "read-active-goal" },
    { id: "active-goal-empty", from: "find-active-goal", fromOutput: "MISSING", to: "detect-project-commands" },
    { id: "active-goal-search-error", from: "find-active-goal", fromOutput: "ERROR", to: "detect-project-commands" },
    { id: "read-active-goal-success", from: "read-active-goal", fromOutput: "SUCCESS", to: "prepare-active-goal" },
    { id: "read-active-goal-invalid", from: "read-active-goal", fromOutput: "INVALID", to: "detect-project-commands" },
    { id: "read-active-goal-not-found", from: "read-active-goal", fromOutput: "NOT_FOUND", to: "detect-project-commands" },
    { id: "read-active-goal-error", from: "read-active-goal", fromOutput: "ERROR", to: "detect-project-commands" },
    { id: "prepare-active-goal-success", from: "prepare-active-goal", fromOutput: "SUCCESS", to: "create-implementation-plan" },
    { id: "prepare-active-goal-error", from: "prepare-active-goal", fromOutput: "ERROR", to: "blocked" },
    { id: "detect-commands-to-understand", from: "detect-project-commands", fromOutput: "SUCCESS", to: "understand-project" },
    { id: "detect-commands-empty-to-understand", from: "detect-project-commands", fromOutput: "EMPTY", to: "understand-project" },
    { id: "detect-commands-error-to-understand", from: "detect-project-commands", fromOutput: "ERROR", to: "understand-project" },
    { id: "understand-to-research-decision", from: "understand-project", fromOutput: "SUCCESS", to: "research-decision" },
    { id: "understand-invalid", from: "understand-project", fromOutput: "INVALID", to: "blocked" },
    { id: "understand-error", from: "understand-project", fromOutput: "ERROR", to: "blocked" },
    { id: "research-decision-run", from: "research-decision", fromOutput: "MATCH", to: "research-inspiration" },
    { id: "research-decision-skip", from: "research-decision", fromOutput: "NO_MATCH", to: "draft-feature-goal" },
    { id: "research-decision-error", from: "research-decision", fromOutput: "ERROR", to: "draft-feature-goal" },
    { id: "research-to-draft", from: "research-inspiration", fromOutput: "SUCCESS", to: "draft-feature-goal" },
    { id: "research-error-to-draft", from: "research-inspiration", fromOutput: "ERROR", to: "draft-feature-goal" },
    { id: "draft-to-improve", from: "draft-feature-goal", fromOutput: "SUCCESS", to: "improve-feature-goal" },
    { id: "draft-error", from: "draft-feature-goal", fromOutput: "ERROR", to: "blocked" },
    { id: "improve-to-write", from: "improve-feature-goal", fromOutput: "SUCCESS", to: "write-active-goal" },
    { id: "improve-invalid", from: "improve-feature-goal", fromOutput: "INVALID", to: "blocked" },
    { id: "improve-error", from: "improve-feature-goal", fromOutput: "ERROR", to: "blocked" },
    { id: "write-to-plan", from: "write-active-goal", fromOutput: "SUCCESS", to: "create-implementation-plan" },
    { id: "write-invalid", from: "write-active-goal", fromOutput: "INVALID", to: "blocked" },
    { id: "write-error", from: "write-active-goal", fromOutput: "ERROR", to: "blocked" },
    { id: "plan-to-select-task", from: "create-implementation-plan", fromOutput: "SUCCESS", to: "select-next-task" },
    { id: "plan-error", from: "create-implementation-plan", fromOutput: "ERROR", to: "blocked" },
    { id: "select-task-to-snapshot", from: "select-next-task", fromOutput: "SELECTED", to: "git-snapshot-before" },
    { id: "select-task-empty-to-validate", from: "select-next-task", fromOutput: "EMPTY", to: "validate-goal" },
    { id: "select-task-not-found", from: "select-next-task", fromOutput: "NOT_FOUND", to: "blocked" },
    { id: "select-task-invalid", from: "select-next-task", fromOutput: "INVALID", to: "blocked" },
    { id: "select-task-error", from: "select-next-task", fromOutput: "ERROR", to: "blocked" },
    { id: "snapshot-to-implement", from: "git-snapshot-before", fromOutput: "SUCCESS", to: "implement-feature" },
    { id: "snapshot-error-to-implement", from: "git-snapshot-before", fromOutput: "ERROR", to: "implement-feature" },
    { id: "implementation-to-verification-decision", from: "implement-feature", fromOutput: "SUCCESS", to: "verification-decision" },
    { id: "implementation-error", from: "implement-feature", fromOutput: "ERROR", to: "blocked" },
    { id: "verification-decision-run", from: "verification-decision", fromOutput: "MATCH", to: "run-verification" },
    { id: "verification-decision-skip", from: "verification-decision", fromOutput: "NO_MATCH", to: "visual-decision" },
    { id: "verification-decision-error", from: "verification-decision", fromOutput: "ERROR", to: "visual-decision" },
    { id: "verification-success-to-visual-decision", from: "run-verification", fromOutput: "SUCCESS", to: "visual-decision" },
    { id: "verification-failed-to-visual-decision", from: "run-verification", fromOutput: "FAILED", to: "visual-decision" },
    { id: "verification-error-to-visual-decision", from: "run-verification", fromOutput: "ERROR", to: "visual-decision" },
    { id: "visual-decision-run", from: "visual-decision", fromOutput: "MATCH", to: "visual-review" },
    { id: "visual-decision-skip", from: "visual-decision", fromOutput: "NO_MATCH", to: "git-diff-summary" },
    { id: "visual-decision-error", from: "visual-decision", fromOutput: "ERROR", to: "git-diff-summary" },
    { id: "visual-success-to-diff", from: "visual-review", fromOutput: "SUCCESS", to: "git-diff-summary" },
    { id: "visual-unavailable-to-diff", from: "visual-review", fromOutput: "UNAVAILABLE", to: "git-diff-summary" },
    { id: "visual-error-to-diff", from: "visual-review", fromOutput: "ERROR", to: "git-diff-summary" },
    { id: "git-diff-success-to-validate", from: "git-diff-summary", fromOutput: "SUCCESS", to: "validate-goal" },
    { id: "git-diff-empty-to-validate", from: "git-diff-summary", fromOutput: "EMPTY", to: "validate-goal" },
    { id: "git-diff-error-to-validate", from: "git-diff-summary", fromOutput: "ERROR", to: "validate-goal" },
    { id: "validation-done-to-read-completed", from: "validate-goal", fromOutput: "DONE", to: "read-completed-goal" },
    { id: "validation-continue", from: "validate-goal", fromOutput: "CONTINUE", to: "select-next-task" },
    { id: "validation-retry", from: "validate-goal", fromOutput: "RETRY", to: "select-next-task" },
    { id: "validation-error", from: "validate-goal", fromOutput: "ERROR", to: "blocked" },
    { id: "validation-invalid", from: "validate-goal", fromOutput: "INVALID", to: "blocked" },
    { id: "read-completed-to-append", from: "read-completed-goal", fromOutput: "SUCCESS", to: "append-completed-goal" },
    { id: "read-completed-invalid", from: "read-completed-goal", fromOutput: "INVALID", to: "blocked" },
    { id: "read-completed-not-found", from: "read-completed-goal", fromOutput: "NOT_FOUND", to: "blocked" },
    { id: "read-completed-error", from: "read-completed-goal", fromOutput: "ERROR", to: "blocked" },
    { id: "append-completed-to-report", from: "append-completed-goal", fromOutput: "SUCCESS", to: "final-report" },
    { id: "append-completed-invalid", from: "append-completed-goal", fromOutput: "INVALID", to: "blocked" },
    { id: "append-completed-error", from: "append-completed-goal", fromOutput: "ERROR", to: "blocked" },
    { id: "report-success-to-archive", from: "final-report", fromOutput: "SUCCESS", to: "archive-goal" },
    { id: "report-error-to-archive", from: "final-report", fromOutput: "ERROR", to: "archive-goal" },
    { id: "archive-to-counter", from: "archive-goal", fromOutput: "SUCCESS", to: "goals-per-run-counter" },
    { id: "archive-not-found-to-counter", from: "archive-goal", fromOutput: "NOT_FOUND", to: "goals-per-run-counter" },
    { id: "archive-error", from: "archive-goal", fromOutput: "ERROR", to: "blocked" },
    { id: "counter-continue-to-find-next", from: "goals-per-run-counter", fromOutput: "CONTINUE", to: "find-active-goal" },
    { id: "counter-limit-to-blocked", from: "goals-per-run-counter", fromOutput: "LIMIT_REACHED", to: "blocked" },
    { id: "counter-error", from: "goals-per-run-counter", fromOutput: "ERROR", to: "blocked" },
  ],
};

export const autonomousFeatureGenerationLoopStarterFlow = {
  id: "autonomous-feature-generation-loop",
  version: 4,
  defaultAlias: "autonomous-feature-generation-loop",
  category: "Implementation",
  tags: ["autonomous", "feature", "loop"],
  flow: autonomousFeatureGenerationLoopFlow,
} as const satisfies RalphStarterFlow;
