import type { RalphFlow } from "../ralph.js";
import type { RalphStarterFlow } from "../ralph-starter-flows.js";

const RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS = 30 * 60;

const autonomousFeatureGenerationLoopFlow: RalphFlow = {
  schemaVersion: 1,
  id: "starter-autonomous-feature-generation-loop",
  alias: "autonomous-feature-generation-loop",
  name: "Autonomous Feature Generation Loop",
  description:
    "Endless autonomous loop that discovers useful new feature goals, tracks one active goal JSON file, implements until done, archives the goal, and starts again.",
  settings: {
    maxTransitions: 500,
  },
  variables: [
    {
      name: "goalDirectory",
      type: "path",
      default: ".machdoch/autonomous-features",
      required: false,
    },
    {
      name: "goalFileName",
      type: "text",
      default: "active-goal.json",
      required: false,
    },
    {
      name: "goalFilePath",
      type: "path",
      default: ".machdoch/autonomous-features/active-goal.json",
      required: false,
    },
    { name: "completedGoalsFile", type: "path", default: ".machdoch/autonomous-features/completed-goals.jsonl", required: false },
    { name: "archivedGoalsDirectory", type: "path", default: ".machdoch/autonomous-features/archive", required: false },
    { name: "projectProfileFile", type: "path", default: ".machdoch/autonomous-features/project-profile.json", required: false },
    { name: "projectCommandsFile", type: "path", default: ".machdoch/autonomous-features/project-commands.json", required: false },
    { name: "gitSnapshotFile", type: "path", default: ".machdoch/autonomous-features/git-snapshot.json", required: false },
    { name: "gitDiffFile", type: "path", default: ".machdoch/autonomous-features/git-diff.json", required: false },
    { name: "autonomousReportFile", type: "path", default: ".machdoch/autonomous-features/final-report.json", required: false },
    { name: "autonomousReportMarkdown", type: "path", default: ".machdoch/autonomous-features/final-report.md", required: false },
    { name: "maxGoalsPerRun", type: "number", default: "100", required: false },
    {
      name: "projectVision",
      type: "text",
      default: "",
      required: false,
    },
    {
      name: "featureStrategy",
      type: "text",
      default:
        "Prefer high-impact, shippable, coherent product improvements that fit the repository and compound over time.",
      required: false,
    },
    {
      name: "inspirationSources",
      type: "text",
      default:
        "Similar products, popular open-source alternatives, current platform capabilities, state-of-the-art UX patterns, and emerging/hyped feature ideas.",
      required: false,
    },
    {
      name: "enableOnlineResearch",
      type: "boolean",
      default: "true",
      required: false,
    },
    {
      name: "implementationScope",
      type: "text",
      default: "auto-detect",
      required: false,
    },
    {
      name: "excludedAreas",
      type: "text",
      default:
        "secrets, credentials, destructive migrations, unrelated dependency upgrades, generated files, vendor directories",
      required: false,
    },
    {
      name: "riskTolerance",
      type: "text",
      default: "moderate",
      required: false,
    },
    {
      name: "verificationCommand",
      type: "text",
      default: "",
      required: false,
    },
    {
      name: "enableVisualReview",
      type: "boolean",
      default: "false",
      required: false,
    },
    {
      name: "targetUrl",
      type: "url",
      default: "",
      required: false,
    },
    {
      name: "healthUrl",
      type: "url",
      default: "",
      required: false,
    },
    {
      name: "screenshotPath",
      type: "path",
      default: "",
      required: false,
    },
    {
      name: "authInstructions",
      type: "text",
      default: "",
      required: false,
    },
    {
      name: "designGuidelines",
      type: "text",
      default: "",
      required: false,
    },
    {
      name: "maxImplementationPasses",
      type: "number",
      default: "10",
      required: false,
    },
    {
      name: "maxTasksPerImplementationPass",
      type: "number",
      default: "3",
      required: false,
    },
  ],
  blocks: [
    {
      id: "start",
      title: "Start",
      position: { x: 0, y: 0 },
      size: { width: 256, height: 140 },
      type: "START",
    },
    {
      id: "find-active-goal",
      title: "Find Active Goal",
      position: { x: 720, y: 0 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "FILE_EXISTS",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
      },
    },
    {
      id: "read-active-goal",
      title: "Read Active Goal",
      position: { x: 1060, y: -120 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "READ_JSON",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
      },
    },
    {
      id: "prepare-active-goal",
      title: "Prepare Active Goal",
      position: { x: 1400, y: -120 },
      size: { width: 280, height: 190 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Resume the tracked autonomous feature goal from {{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}. JSON read result: {{result:read-active-goal}}. Extract the goal, acceptance criteria, plan, completed tasks, verification expectations, risks, and next todo/in_progress work. Do not create a new goal while this file exists.",
    },
    {
      id: "detect-project-commands",
      title: "Detect Project Commands",
      position: { x: 860, y: 300 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "DETECT_PROJECT_COMMANDS",
        rootPath: ".",
        outputPath:
          "{{projectCommandsFile:path=.machdoch/autonomous-features/project-commands.json}}",
      },
    },
    {
      id: "read-completed-goals",
      title: "Read Completed Goals",
      position: { x: 1020, y: 360 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "READ_JSONL",
        path: "{{completedGoalsFile:path=.machdoch/autonomous-features/completed-goals.jsonl}}",
      },
    },
    {
      id: "understand-project",
      title: "Understand Project",
      position: { x: 1060, y: 140 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{projectProfileFile:path=.machdoch/autonomous-features/project-profile.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: ["product", "architecture", "currentFeatures", "extensionPoints", "constraints"],
          properties: {
            product: { type: "string" },
            architecture: { type: "array", items: { type: "string" } },
            currentFeatures: { type: "array", items: { type: "string" } },
            extensionPoints: { type: "array", items: { type: "string" } },
            constraints: { type: "array", items: { type: "string" } },
          },
        },
        prompt:
          "No active autonomous feature goal was found. Inspect the repository to understand the product, architecture, users, current feature set, extension points, tests, scripts, constraints, recently changed areas, and completed goal history {{result:read-completed-goals}}. Use detected project commands {{result:detect-project-commands}}. Apply projectVision={{projectVision:text=}}, implementationScope={{implementationScope:text=auto-detect}}, excludedAreas={{excludedAreas:text=}}, and riskTolerance={{riskTolerance:text=moderate}}. Do not change files. Return only schema-valid JSON.",
      },
    },
    {
      id: "research-decision",
      title: "Use Online Research?",
      position: { x: 1380, y: 140 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression: 'variables.enableOnlineResearch === "true"',
        },
      },
    },
    {
      id: "research-inspiration",
      title: "Research Inspiration",
      position: { x: 1400, y: 140 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        webAccess: true,
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "PROMPT",
      prompt:
        "Use content enrichment to find better feature opportunities before drafting a goal. If search_web is available, run focused searches for current comparable products, open-source alternatives, platform capabilities, state-of-the-art UX patterns, release notes, and emerging/hyped ideas relevant to this project. Use fetch_url on the best official, product, standards, or maintainer pages before relying on them. Inspiration sources: {{inspirationSources:text=}}. Produce a concise opportunity map with source links, freshness/version assumptions, likely fit, implementation leverage, risks, and duplicates to avoid from completed goals {{result:read-completed-goals}}. If web search is unavailable, say so and ground the opportunity map in local repository evidence plus any provided URLs. Project profile: {{data:understand-project:output}}.",
    },
    {
      id: "draft-feature-goal",
      title: "Draft Feature Goal",
      position: { x: 1740, y: 140 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Define one concrete new feature goal for autonomous implementation, or clearly recommend no new goal when there is no credible shippable opportunity. Use project profile {{data:understand-project:output}}, research {{summary:research-inspiration}}, projectVision={{projectVision:text=}}, featureStrategy={{featureStrategy:text=}}, riskTolerance={{riskTolerance:text=moderate}}, excludedAreas={{excludedAreas:text=}}, completed goals history {{result:read-completed-goals}}, and detected commands {{result:detect-project-commands}}. Choose a feature only when it is valuable, coherent with the codebase, source-backed or clearly supported by local product evidence, shippable in a bounded loop, testable, and not merely cleanup. Avoid duplicating already completed work. Include acceptance criteria, non-goals, source/content-enrichment notes, dependencies, likely files, verification plan, visual review needs, and a task checklist.",
    },
    {
      id: "improve-feature-goal",
      title: "Improve Feature Goal",
      position: { x: 2080, y: 140 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: ["id", "title", "rationale", "acceptanceCriteria", "tasks", "status"],
          properties: {
            id: { type: "string" },
            title: { type: "string" },
            rationale: { type: "string" },
            acceptanceCriteria: { type: "array", items: { type: "string" } },
            tasks: {
              type: "array",
              items: {
                type: "object",
                required: ["id", "title", "status"],
                properties: {
                  id: { type: "string" },
                  title: { type: "string" },
                  status: { type: "string" },
                },
              },
            },
            status: { type: "string" },
          },
        },
        prompt:
          "Critique and improve the drafted feature goal from {{summary:draft-feature-goal}}. Strengthen product value, reduce ambiguity, make the scope implementable, remove risky or irrelevant work, add measurable acceptance criteria, include a resumable checklist, and ensure it fits featureStrategy={{featureStrategy:text=}}. Shape tasks for meaningful autonomous batches: use stable task ids, status values todo/in_progress/done/blocked/no_action, optional batchKey for tasks that should travel together, optional dependsOn/dependencies for strict prerequisites, likelyFiles when known, and task sizes that let up to {{maxTasksPerImplementationPass:number=3}} compatible tasks be completed in one implementation pass. If the draft does not contain a valuable, safe, non-duplicate feature, return status no_action with tasks [] and explain the reason in rationale instead of inventing work. Return JSON suitable for {{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}.",
      },
    },
    {
      id: "has-actionable-goal",
      title: "Actionable Goal?",
      position: { x: 2280, y: 360 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "lastData?.output && Array.isArray(lastData.output.tasks) && lastData.output.tasks.length > 0 && !['blocked', 'no_action', 'no-action', 'stop', 'none'].includes(String(lastData.output.status ?? '').toLowerCase())",
        },
      },
    },
    {
      id: "write-active-goal",
      title: "Track Active Goal",
      position: { x: 2420, y: 140 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "WRITE_JSON",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
        input: "{{data:improve-feature-goal:output}}",
      },
    },
    {
      id: "create-implementation-plan",
      title: "Create Implementation Plan",
      position: { x: 2760, y: 0 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Create or update the implementation plan in active goal JSON {{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}. Use active goal context {{summary:prepare-active-goal}}, newly tracked goal {{result:write-active-goal}}, detected commands {{result:detect-project-commands}}, and project profile {{data:understand-project:output}} when present. Confirm the checklist is ordered, resumable, scoped to {{implementationScope:text=auto-detect}}, respects excludedAreas={{excludedAreas:text=}}, includes verificationCommand={{verificationCommand:text=}} when configured, visual review expectations, authInstructions={{authInstructions:text=}}, and designGuidelines={{designGuidelines:text=}}.",
    },
    {
      id: "select-next-task",
      title: "Select Next Task",
      position: { x: 2860, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SELECT_JSON_TASK",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
        jsonPath: "tasks",
        strategy: "start-to-end",
        maxTasks: "{{maxTasksPerImplementationPass:number=3}}",
      },
    },
    {
      id: "git-snapshot-before",
      title: "Git Snapshot",
      position: { x: 2930, y: -210 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_SNAPSHOT",
        cwd: ".",
        outputPath:
          "{{gitSnapshotFile:path=.machdoch/autonomous-features/git-snapshot.json}}",
      },
    },
    {
      id: "implement-feature",
      title: "Implement Feature",
      position: { x: 3100, y: 0 },
      size: { width: 300, height: 220 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 4,
      },
      type: "PROMPT",
      prompt:
        "Implement the selected active-goal task batch {{data:select-next-task:tasks}} from {{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}; primary task for compatibility is {{data:select-next-task:task}}. Complete every compatible selected task in this pass unless blocked by a real dependency, risk, or failing evidence. Use git baseline {{result:git-snapshot-before}}, detected commands {{result:detect-project-commands}}, pass count {{result:count-implementation-pass}}, latest validation feedback {{result:validate-goal}}, and latest work-yield analysis {{data:work-yield-analysis:output}}. Preserve existing behavior, follow local patterns, keep changes scoped, avoid excluded areas {{excludedAreas:text=}}, use authInstructions={{authInstructions:text=}} and designGuidelines={{designGuidelines:text=}}, add or update tests where appropriate, and update each selected task plus goal JSON checklist with completed items and resume notes. If no implementation files can be changed safely, leave the selected tasks unfinished and explain the blocker instead of only changing the goal JSON.",
    },
    {
      id: "work-yield-analysis",
      title: "Assess Work Yield",
      position: { x: 3440, y: -190 },
      size: { width: 300, height: 190 },
      type: "UTILITY",
      utility: {
        type: "TRANSFORM_JSON",
        input: "{}",
        expression:
          "(() => { const diffResult = context.resultsByBlock?.get?.('git-diff-summary'); const baselineResult = context.resultsByBlock?.get?.('git-snapshot-before'); const currentFiles = Array.isArray(diffResult?.data?.files) ? diffResult.data.files : []; const baselineFiles = Array.isArray(baselineResult?.data?.files) ? baselineResult.data.files : []; const normalize = (value) => String(value ?? '').replace(/\\\\/gu, '/').replace(/^\\.\\/+/, ''); const baseline = new Map(baselineFiles.filter((file) => file && typeof file.path === 'string').map((file) => [normalize(file.path), file.signature])); const changedSinceBaselineFiles = currentFiles.filter((file) => file && typeof file.path === 'string' && baseline.get(normalize(file.path)) !== file.signature).map((file) => normalize(file.path)); const stateFile = normalize(variables.goalFilePath || '.machdoch/autonomous-features/active-goal.json'); const implementationFiles = changedSinceBaselineFiles.filter((path) => path !== stateFile); const selectedTasks = context.resultsByBlock?.get?.('select-next-task')?.data?.tasks; const selectedTaskCount = Array.isArray(selectedTasks) ? selectedTasks.length : 1; const diffErrored = diffResult?.output === 'ERROR'; const onlyStateFileChanged = changedSinceBaselineFiles.length > 0 && implementationFiles.length === 0; const shouldVerify = diffErrored || implementationFiles.length > 0; return { shouldVerify, diffOutput: diffResult?.output ?? '', selectedTaskCount, stateFile, changedSinceBaselineCount: changedSinceBaselineFiles.length, changedSinceBaselineFiles, implementationFileCount: implementationFiles.length, implementationFiles, onlyStateFileChanged, baselineFileCount: baselineFiles.length, currentFileCount: currentFiles.length, reason: shouldVerify ? (diffErrored ? 'Git diff summary failed; keep verification path available.' : 'Implementation changed files beyond the flow state file since the pre-pass snapshot.') : (onlyStateFileChanged ? 'Only the active goal JSON changed; skip expensive verification and let validation request real implementation work.' : 'Implementation produced no file changes beyond the pre-pass snapshot; skip expensive verification and let validation request another implementation pass.') }; })()",
      },
    },
    {
      id: "work-yield-decision",
      title: "Useful Work Produced?",
      position: { x: 3440, y: 30 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression: "lastData?.shouldVerify === true",
        },
      },
    },
    {
      id: "count-implementation-pass",
      title: "Count Implementation Pass",
      position: { x: 3100, y: 250 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        counterName:
          "autonomous-feature-generation-loop.implementation-pass.{{data:select-next-task:task.id}}.{{data:select-next-task:index}}",
        maxAttempts: "{{maxImplementationPasses:number=10}}",
      },
    },
    {
      id: "verification-decision",
      title: "Run Verification?",
      position: { x: 3440, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "Boolean(variables.verificationCommand?.trim() || context.resultsByBlock?.['detect-project-commands']?.data?.verificationCommand?.trim())",
        },
      },
    },
    {
      id: "run-verification",
      title: "Run Verification",
      position: { x: 3760, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{verificationCommand:text=}}",
        fallbackCommand: "{{data:detect-project-commands:verificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "visual-decision",
      title: "Run Visual Review?",
      position: { x: 3760, y: 120 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'variables.enableVisualReview === "true" && (Boolean(variables.targetUrl?.trim()) || Boolean(variables.screenshotPath?.trim()))',
        },
      },
    },
    {
      id: "visual-review",
      title: "Visual Review",
      position: { x: 4100, y: 20 },
      size: { width: 280, height: 190 },
      type: "UTILITY",
      utility: {
        type: "UI_ANALYZE",
        adapter: "auto",
        targetUrl: "{{targetUrl:url=}}",
        screenshotPath: "{{screenshotPath:path=}}",
        server: {
          mode: "existing",
          healthUrl: "{{healthUrl:url=}}",
        },
        checks: {
          screenshots: true,
          accessibility: true,
          console: true,
          network: true,
          responsive: true,
        },
        viewports: [
          { name: "desktop", width: 1280, height: 900 },
          { name: "tablet", width: 768, height: 1024 },
          { name: "mobile", width: 390, height: 844 },
          { name: "small-mobile", width: 320, height: 568 },
        ],
        timeoutSeconds: 30,
        fullPage: true,
        waitUntil: "domcontentloaded",
      },
    },
    {
      id: "git-diff-summary",
      title: "Git Diff Summary",
      position: { x: 4270, y: -170 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_DIFF_SUMMARY",
        cwd: ".",
        outputPath:
          "{{gitDiffFile:path=.machdoch/autonomous-features/git-diff.json}}",
      },
    },
    {
      id: "validate-goal",
      title: "Validate Goal",
      position: { x: 4440, y: 0 },
      size: { width: 320, height: 250 },
      type: "UTILITY",
      utility: {
        type: "VALIDATOR_JSON",
        maxAttempts: 2,
        prompt:
          "Validate active goal JSON {{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}} against implementation changes, selected task batch {{data:select-next-task:tasks}}, work-yield analysis {{data:work-yield-analysis:output}}, verification result {{result:run-verification}}, git diff {{result:git-diff-summary}}, visual review {{result:visual-review}}, and latest implementation summary. Judge only the active goal, selected task batch, goal file, and required adjacent tests/docs/imports. Ignore unrelated workspace changes outside that goal/task batch unless they directly break verification of the active goal. If work-yield analysis reports no implementation files changed or only the active goal JSON changed, avoid DONE and request another implementation pass unless the selected task batch truly required no file changes. Return JSON with decision DONE when the whole goal is completely implemented, verified or verification is explicitly skipped because no command is configured or no implementation files changed, and the goal file accurately records completion. Return CONTINUE when more tasks remain. Return RETRY when the last implementation pass needs correction. Return ERROR when blocked by missing context, unsafe changes in the active goal/task batch, failing verification that cannot be fixed, or repeated ambiguity. Include confidence, summary, evidence, and remainingWork.",
      },
    },
    {
      id: "read-completed-goal",
      title: "Read Completed Goal",
      position: { x: 4800, y: 0 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "READ_JSON",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
      },
    },
    {
      id: "append-completed-goal",
      title: "Append Completed Goal",
      position: { x: 5140, y: 0 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{completedGoalsFile:path=.machdoch/autonomous-features/completed-goals.jsonl}}",
        input: "{{data:read-completed-goal:json}}",
      },
    },
    {
      id: "final-report",
      title: "Final Autonomous Report",
      position: { x: 5480, y: -120 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{autonomousReportFile:path=.machdoch/autonomous-features/final-report.json}}",
        outputPath:
          "{{autonomousReportMarkdown:path=.machdoch/autonomous-features/final-report.md}}",
      },
    },
    {
      id: "archive-goal",
      title: "Archive Completed Goal",
      position: { x: 5820, y: 0 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "ARCHIVE_FILE",
        path: "{{goalFilePath:path=.machdoch/autonomous-features/active-goal.json}}",
        rootPath:
          "{{archivedGoalsDirectory:path=.machdoch/autonomous-features/archive}}",
      },
    },
    {
      id: "goals-per-run-counter",
      title: "Goals Per Run Counter",
      position: { x: 6160, y: 0 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        path: ".machdoch/autonomous-features/run-counters.json",
        counterName: "completed-goals",
        maxAttempts: "{{maxGoalsPerRun:number=100}}",
      },
    },
    {
      id: "blocked",
      title: "Blocked",
      position: { x: 2760, y: 280 },
      size: { width: 256, height: 114 },
      type: "END",
      status: "failed",
    },
    {
      id: "success",
      title: "No Actionable Feature Goal",
      position: { x: 6500, y: 0 },
      size: { width: 280, height: 114 },
      type: "END",
      status: "success",
    },
  ],
  edges: [
    { id: "start-to-detect-commands", from: "start", fromOutput: "SUCCESS", to: "detect-project-commands" },
    { id: "detect-commands-to-find", from: "detect-project-commands", fromOutput: "SUCCESS", to: "find-active-goal" },
    { id: "detect-commands-empty-to-find", from: "detect-project-commands", fromOutput: "EMPTY", to: "find-active-goal" },
    { id: "detect-commands-error-to-find", from: "detect-project-commands", fromOutput: "ERROR", to: "find-active-goal" },
    { id: "active-goal-found", from: "find-active-goal", fromOutput: "EXISTS", to: "read-active-goal" },
    { id: "active-goal-empty", from: "find-active-goal", fromOutput: "MISSING", to: "read-completed-goals" },
    { id: "active-goal-search-error", from: "find-active-goal", fromOutput: "ERROR", to: "read-completed-goals" },
    { id: "read-active-goal-success", from: "read-active-goal", fromOutput: "SUCCESS", to: "prepare-active-goal" },
    { id: "read-active-goal-invalid", from: "read-active-goal", fromOutput: "INVALID", to: "read-completed-goals" },
    { id: "read-active-goal-not-found", from: "read-active-goal", fromOutput: "NOT_FOUND", to: "read-completed-goals" },
    { id: "read-active-goal-error", from: "read-active-goal", fromOutput: "ERROR", to: "read-completed-goals" },
    { id: "prepare-active-goal-success", from: "prepare-active-goal", fromOutput: "SUCCESS", to: "create-implementation-plan" },
    { id: "prepare-active-goal-error", from: "prepare-active-goal", fromOutput: "ERROR", to: "blocked" },
    { id: "completed-goals-to-understand", from: "read-completed-goals", fromOutput: "SUCCESS", to: "understand-project" },
    { id: "completed-goals-empty-to-understand", from: "read-completed-goals", fromOutput: "EMPTY", to: "understand-project" },
    { id: "completed-goals-missing-to-understand", from: "read-completed-goals", fromOutput: "NOT_FOUND", to: "understand-project" },
    { id: "completed-goals-invalid-to-understand", from: "read-completed-goals", fromOutput: "INVALID", to: "understand-project" },
    { id: "completed-goals-error-to-understand", from: "read-completed-goals", fromOutput: "ERROR", to: "understand-project" },
    { id: "understand-to-research-decision", from: "understand-project", fromOutput: "SUCCESS", to: "research-decision" },
    { id: "understand-invalid", from: "understand-project", fromOutput: "INVALID", to: "blocked" },
    { id: "understand-error", from: "understand-project", fromOutput: "ERROR", to: "blocked" },
    { id: "research-decision-run", from: "research-decision", fromOutput: "MATCH", to: "research-inspiration" },
    { id: "research-decision-skip", from: "research-decision", fromOutput: "NO_MATCH", to: "draft-feature-goal" },
    { id: "research-decision-error", from: "research-decision", fromOutput: "ERROR", to: "draft-feature-goal" },
    { id: "research-to-draft", from: "research-inspiration", fromOutput: "SUCCESS", to: "draft-feature-goal" },
    { id: "research-error-to-draft", from: "research-inspiration", fromOutput: "ERROR", to: "draft-feature-goal" },
    { id: "draft-to-improve", from: "draft-feature-goal", fromOutput: "SUCCESS", to: "improve-feature-goal" },
    { id: "draft-error", from: "draft-feature-goal", fromOutput: "ERROR", to: "blocked" },
    { id: "improve-to-actionable-goal", from: "improve-feature-goal", fromOutput: "SUCCESS", to: "has-actionable-goal" },
    { id: "improve-invalid", from: "improve-feature-goal", fromOutput: "INVALID", to: "blocked" },
    { id: "improve-error", from: "improve-feature-goal", fromOutput: "ERROR", to: "blocked" },
    { id: "actionable-goal-to-write", from: "has-actionable-goal", fromOutput: "MATCH", to: "write-active-goal" },
    { id: "no-actionable-goal", from: "has-actionable-goal", fromOutput: "NO_MATCH", to: "success" },
    { id: "actionable-goal-error", from: "has-actionable-goal", fromOutput: "ERROR", to: "blocked" },
    { id: "write-to-plan", from: "write-active-goal", fromOutput: "SUCCESS", to: "create-implementation-plan" },
    { id: "write-invalid", from: "write-active-goal", fromOutput: "INVALID", to: "blocked" },
    { id: "write-error", from: "write-active-goal", fromOutput: "ERROR", to: "blocked" },
    { id: "plan-to-select-task", from: "create-implementation-plan", fromOutput: "SUCCESS", to: "select-next-task" },
    { id: "plan-error", from: "create-implementation-plan", fromOutput: "ERROR", to: "blocked" },
    { id: "select-task-to-snapshot", from: "select-next-task", fromOutput: "SELECTED", to: "git-snapshot-before" },
    { id: "select-task-empty-to-validate", from: "select-next-task", fromOutput: "EMPTY", to: "validate-goal" },
    { id: "select-task-not-found", from: "select-next-task", fromOutput: "NOT_FOUND", to: "blocked" },
    { id: "select-task-invalid", from: "select-next-task", fromOutput: "INVALID", to: "blocked" },
    { id: "select-task-error", from: "select-next-task", fromOutput: "ERROR", to: "blocked" },
    { id: "snapshot-to-count-implementation-pass", from: "git-snapshot-before", fromOutput: "SUCCESS", to: "count-implementation-pass" },
    { id: "snapshot-error-to-count-implementation-pass", from: "git-snapshot-before", fromOutput: "ERROR", to: "count-implementation-pass" },
    { id: "count-implementation-pass-continue", from: "count-implementation-pass", fromOutput: "CONTINUE", to: "implement-feature" },
    { id: "count-implementation-pass-limit", from: "count-implementation-pass", fromOutput: "LIMIT_REACHED", to: "blocked" },
    { id: "count-implementation-pass-error", from: "count-implementation-pass", fromOutput: "ERROR", to: "blocked" },
    { id: "implementation-to-diff", from: "implement-feature", fromOutput: "SUCCESS", to: "git-diff-summary" },
    { id: "implementation-error", from: "implement-feature", fromOutput: "ERROR", to: "blocked" },
    { id: "git-diff-success-to-work-yield", from: "git-diff-summary", fromOutput: "SUCCESS", to: "work-yield-analysis" },
    { id: "git-diff-empty-to-work-yield", from: "git-diff-summary", fromOutput: "EMPTY", to: "work-yield-analysis" },
    { id: "git-diff-error-to-work-yield", from: "git-diff-summary", fromOutput: "ERROR", to: "work-yield-analysis" },
    { id: "work-yield-analysis-success", from: "work-yield-analysis", fromOutput: "SUCCESS", to: "work-yield-decision" },
    { id: "work-yield-analysis-error", from: "work-yield-analysis", fromOutput: "ERROR", to: "verification-decision" },
    { id: "work-yield-useful", from: "work-yield-decision", fromOutput: "MATCH", to: "verification-decision" },
    { id: "work-yield-empty-to-validate", from: "work-yield-decision", fromOutput: "NO_MATCH", to: "validate-goal" },
    { id: "work-yield-error-to-verification-decision", from: "work-yield-decision", fromOutput: "ERROR", to: "verification-decision" },
    { id: "verification-decision-run", from: "verification-decision", fromOutput: "MATCH", to: "run-verification" },
    { id: "verification-decision-skip", from: "verification-decision", fromOutput: "NO_MATCH", to: "visual-decision" },
    { id: "verification-decision-error", from: "verification-decision", fromOutput: "ERROR", to: "visual-decision" },
    { id: "verification-success-to-visual-decision", from: "run-verification", fromOutput: "SUCCESS", to: "visual-decision" },
    { id: "verification-failed-to-visual-decision", from: "run-verification", fromOutput: "FAILED", to: "visual-decision" },
    { id: "verification-error-to-visual-decision", from: "run-verification", fromOutput: "ERROR", to: "visual-decision" },
    { id: "visual-decision-run", from: "visual-decision", fromOutput: "MATCH", to: "visual-review" },
    { id: "visual-decision-skip", from: "visual-decision", fromOutput: "NO_MATCH", to: "validate-goal" },
    { id: "visual-decision-error", from: "visual-decision", fromOutput: "ERROR", to: "validate-goal" },
    { id: "visual-success-to-validate", from: "visual-review", fromOutput: "SUCCESS", to: "validate-goal" },
    { id: "visual-unavailable-to-validate", from: "visual-review", fromOutput: "UNAVAILABLE", to: "validate-goal" },
    { id: "visual-error-to-validate", from: "visual-review", fromOutput: "ERROR", to: "validate-goal" },
    { id: "validation-done-to-read-completed", from: "validate-goal", fromOutput: "DONE", to: "read-completed-goal" },
    { id: "validation-continue", from: "validate-goal", fromOutput: "CONTINUE", to: "select-next-task" },
    { id: "validation-retry", from: "validate-goal", fromOutput: "RETRY", to: "select-next-task" },
    { id: "validation-error", from: "validate-goal", fromOutput: "ERROR", to: "blocked" },
    { id: "validation-invalid", from: "validate-goal", fromOutput: "INVALID", to: "blocked" },
    { id: "read-completed-to-append", from: "read-completed-goal", fromOutput: "SUCCESS", to: "append-completed-goal" },
    { id: "read-completed-invalid", from: "read-completed-goal", fromOutput: "INVALID", to: "blocked" },
    { id: "read-completed-not-found", from: "read-completed-goal", fromOutput: "NOT_FOUND", to: "blocked" },
    { id: "read-completed-error", from: "read-completed-goal", fromOutput: "ERROR", to: "blocked" },
    { id: "append-completed-to-report", from: "append-completed-goal", fromOutput: "SUCCESS", to: "final-report" },
    { id: "append-completed-invalid", from: "append-completed-goal", fromOutput: "INVALID", to: "blocked" },
    { id: "append-completed-error", from: "append-completed-goal", fromOutput: "ERROR", to: "blocked" },
    { id: "report-success-to-archive", from: "final-report", fromOutput: "SUCCESS", to: "archive-goal" },
    { id: "report-error-to-archive", from: "final-report", fromOutput: "ERROR", to: "archive-goal" },
    { id: "archive-to-counter", from: "archive-goal", fromOutput: "SUCCESS", to: "goals-per-run-counter" },
    { id: "archive-not-found-to-counter", from: "archive-goal", fromOutput: "NOT_FOUND", to: "goals-per-run-counter" },
    { id: "archive-error", from: "archive-goal", fromOutput: "ERROR", to: "blocked" },
    { id: "counter-continue-to-detect-next", from: "goals-per-run-counter", fromOutput: "CONTINUE", to: "detect-project-commands" },
    { id: "counter-limit-to-success", from: "goals-per-run-counter", fromOutput: "LIMIT_REACHED", to: "success" },
    { id: "counter-error", from: "goals-per-run-counter", fromOutput: "ERROR", to: "blocked" },
  ],
};

export const autonomousFeatureGenerationLoopStarterFlow = {
  id: "autonomous-feature-generation-loop",
  version: 8,
  defaultAlias: "autonomous-feature-generation-loop",
  category: "Implementation",
  tags: ["autonomous", "feature", "loop"],
  flow: autonomousFeatureGenerationLoopFlow,
} as const satisfies RalphStarterFlow;
