import type { RalphFlow } from "../ralph.js";
import type { RalphStarterFlow } from "../ralph-starter-flows.js";

const RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS = 30 * 60;

const RALPH_VALIDATOR_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["decision", "confidence", "summary", "evidence", "remainingWork"],
  properties: {
    decision: { type: "string", enum: ["DONE", "CONTINUE", "RETRY", "ERROR"] },
    confidence: { type: "number", minimum: 0, maximum: 1 },
    summary: { type: "string" },
    evidence: { type: "array", items: { type: "string" }, maxItems: 30 },
    remainingWork: { type: "array", items: { type: "string" }, maxItems: 30 },
  },
} as const;

const ENRICHED_UI_DESIGN_POLICY = [
  "Preserve the repository's existing design-system conventions, component APIs, tokens, routing, data fetching, and accessibility patterns before inventing new UI primitives.",
  "Treat sibling views and established product surfaces as primary references: compare their information architecture, density, primitives, states, and interaction patterns before planning changes, and bring a visibly inconsistent view up to the same standard.",
  "Aim for a clean, minimalist, modern interface with strong hierarchy, restrained color, clear spacing, stable dimensions, and no decorative clutter.",
  "When evidence shows that local polish cannot resolve a view's structural inconsistency, prefer a coherent view-level refactor over a collection of tiny patches; change component boundaries and shared primitives when that is the maintainable path.",
  "Use current official design systems from mature product companies as comparative evidence when useful, but adapt the underlying layout, accessibility, content, and interaction principles to this product instead of copying another company's brand.",
  "Audit installed UI packages and their official release notes or registry metadata when library behavior limits the result; upgrade or add a package only when it materially improves the selected outcome and the migration is verified.",
  "Make layouts responsive and mobile friendly across desktop, tablet, mobile, and small-mobile states; avoid horizontal overflow, clipped content, overlapping text, and controls that resize or shift unexpectedly.",
  "Use badges sparingly for status or category information only; do not turn ordinary labels, metadata, or explanatory text into badge-heavy UI.",
  "Keep copy concise and task-focused; remove overexplained helper text while preserving necessary labels, errors, empty states, and accessible names.",
  "Use icons only when they improve recognition or scanability, prefer the existing icon library, pair unfamiliar icons with labels/tooltips, and keep icon-only controls keyboard and screen-reader accessible.",
  "Respect WCAG 2.2-oriented accessibility: semantic HTML, labels, visible focus, keyboard operation, sufficient contrast, target size/spacing, source order, alt text where needed, and no focus traps.",
  "Check responsive and hydration-sensitive UI for console errors, layout bugs, network failures, loading/empty/error/success states, and regressions introduced by client/server boundaries.",
].join(" ");

const autonomousUiImprovementLoopFlow: RalphFlow = {
  schemaVersion: 1,
  id: "starter-autonomous-ui-improvement-loop",
  alias: "autonomous-ui-improvement-loop",
  name: "Autonomous UI Improvement Loop",
  description:
    "Bounded autonomous UI cycle that scores evidence-backed work packages, applies the design policy, verifies code and visual states, defers exhausted packages, and can be scheduled repeatedly.",
  settings: {
    maxTransitions: 500,
    autonomy: {
      recoverFailedEnd: true,
      maxRecoveryAttempts: 3,
      transitionExhaustion: "checkpoint",
      recoveryExhaustion: "defer",
      deferToBlockId: "defer-scope",
    },
  },
  variables: [
    { name: "scopeRoot", type: "path", default: ".", required: false },
    { name: "uiScope", type: "text", default: "auto-detect", required: false },
    { name: "scopeSelectionStrategy", type: "text", default: "ui-first", required: false },
    { name: "scopeRegistryFile", type: "path", default: ".machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.json", required: false },
    { name: "scopeRegistryMarkdown", type: "path", default: ".machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.md", required: false },
    { name: "scopeScanMaxDepth", type: "number", default: "5", required: false },
    { name: "scopeScanMaxResults", type: "number", default: "280", required: false },
    { name: "designPolicy", type: "text", default: ENRICHED_UI_DESIGN_POLICY, required: false },
    { name: "uiImprovementPolicy", type: "text", default: "Prefer visible, user-facing UI improvements that make the product clearer, calmer, more responsive, more accessible, and easier to operate. Preserve coherent product conventions, but allow a complete view-level redesign or component refactor when comparative repository evidence shows the current surface is materially behind sibling views.", required: false },
    { name: "meaningfulThreshold", type: "text", default: "Continue only when there is concrete UI evidence: layout overflow, overlapping text, responsive breakage, accessibility issue, confusing hierarchy, overexplained copy, badge/icon misuse, inconsistent design-system usage, hydration/console errors, or a clearly bounded visual opportunity with user value. Stop instead of inventing speculative redesigns or tiny cosmetic nits, but do not treat a small diff as success when the selected package or sibling-view comparison supports a larger coherent refactor.", required: false },
    { name: "riskTolerance", type: "text", default: "ambitious", required: false },
    { name: "allowAmbitiousUiChanges", type: "boolean", default: "true", required: false },
    { name: "allowDependencyChanges", type: "boolean", default: "true", required: false },
    { name: "allowSchemaChanges", type: "boolean", default: "true", required: false },
    { name: "allowPublicApiChanges", type: "boolean", default: "true", required: false },
    { name: "excludePaths", type: "text", default: "node_modules, dist, build, coverage, target, .next, .nuxt, .turbo, .cache, vendor, generated, .machdoch", required: false },
    { name: "enableOnlineResearch", type: "boolean", default: "true", required: false },
    { name: "verificationCommand", type: "text", default: "", required: false },
    { name: "enableVisualReview", type: "boolean", default: "true", required: false },
    { name: "targetUrl", type: "url", default: "", required: false },
    { name: "targetUrlEnvKey", type: "text", default: "RALPH_UI_TARGET_URL", required: false },
    { name: "healthUrl", type: "url", default: "", required: false },
    { name: "healthUrlEnvKey", type: "text", default: "RALPH_UI_HEALTH_URL", required: false },
    { name: "visualServerCommand", type: "text", default: "", required: false },
    { name: "visualServerCwd", type: "path", default: "", required: false },
    { name: "screenshotPath", type: "path", default: "", required: false },
    { name: "maxUiImprovementPasses", type: "number", default: "8", required: false },
    { name: "maxVerificationRepairPasses", type: "number", default: "3", required: false },
    { name: "activeUiImprovementFile", type: "path", default: ".machdoch/ralph/ui-improvements/active-ui-improvement.json", required: false },
    { name: "completedUiImprovementsFile", type: "path", default: ".machdoch/ralph/ui-improvements/completed-ui-improvements.jsonl", required: false },
    { name: "uiImprovementOutcomesFile", type: "path", default: ".machdoch/ralph/ui-improvements/outcomes.jsonl", required: false },
    { name: "archivedUiImprovementsDirectory", type: "path", default: ".machdoch/ralph/ui-improvements/archive", required: false },
    { name: "projectCommandsFile", type: "path", default: "{{run:artifactRoot}}/ui-improvements/project-commands.json", required: false },
    { name: "candidateFile", type: "path", default: "{{run:artifactRoot}}/ui-improvements/candidate.json", required: false },
    { name: "reviewFile", type: "path", default: "{{run:artifactRoot}}/ui-improvements/review.json", required: false },
    { name: "gitSnapshotFile", type: "path", default: "{{run:artifactRoot}}/ui-improvements/git-snapshot.json", required: false },
    { name: "gitDiffFile", type: "path", default: "{{run:artifactRoot}}/ui-improvements/git-diff.json", required: false },
    { name: "uiReportFile", type: "path", default: "{{run:artifactRoot}}/ui-improvements/final-report.json", required: false },
    { name: "uiReportMarkdown", type: "path", default: "{{run:artifactRoot}}/ui-improvements/final-report.md", required: false },
    { name: "notesFile", type: "path", default: ".machdoch/ralph/ui-improvements/RALPH_UI_IMPROVEMENT_NOTES.md", required: false },
  ],
  blocks: [
    {
      id: "start",
      title: "Start",
      position: { x: 0, y: 0 },
      size: { width: 256, height: 140 },
      type: "START",
    },
    {
      id: "scan-ui-scopes",
      title: "Scan UI Scope Evidence",
      position: { x: 700, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SCAN_SCOPE_EVIDENCE",
        rootPath: "{{scopeRoot:path=.}}",
        excludePaths: "{{excludePaths:text=node_modules, dist, build, coverage, target, .next, .nuxt, .turbo, .cache, vendor, generated, .machdoch}}",
        maxDepth: "{{scopeScanMaxDepth:number=5}}",
        maxResults: "{{scopeScanMaxResults:number=280}}",
      },
    },
    {
      id: "update-scope-registry",
      title: "Update UI Scope Registry",
      position: { x: 1040, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "UPDATE_SCOPE_REGISTRY",
        flowAlias: "autonomous-ui-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.md}}",
        strategy: "{{scopeSelectionStrategy:text=ui-first}}",
        includeMarkdown: true,
      },
    },
    {
      id: "select-scope",
      title: "Select UI Scope",
      position: { x: 1380, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SELECT_SCOPE",
        flowAlias: "autonomous-ui-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.json}}",
        strategy: "{{scopeSelectionStrategy:text=ui-first}}",
      },
    },
    {
      id: "detect-project-commands",
      title: "Detect Project Commands",
      position: { x: 1720, y: -160 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "DETECT_PROJECT_COMMANDS",
        rootPath: "{{data:select-scope:scope.paths.0}}",
        outputPath:
          "{{projectCommandsFile:path=.machdoch/ralph/ui-improvements/project-commands.json}}",
      },
    },
    {
      id: "read-completed-ui-improvements",
      title: "Read Completed UI Improvements",
      position: { x: 1720, y: 40 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "QUERY_JSONL",
        path: "{{completedUiImprovementsFile:path=.machdoch/ralph/ui-improvements/completed-ui-improvements.jsonl}}",
        maxResults: 50,
        order: "newest",
      },
    },
    {
      id: "propose-ui-improvements",
      title: "Propose UI Portfolio",
      position: { x: 2060, y: 40 },
      size: { width: 320, height: 250 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        maxAttempts: 2,
        schema: {
          type: "object",
          additionalProperties: false,
          required: ["projectConstitution", "candidates", "researchDecision"],
          properties: {
            projectConstitution: {
              type: "object",
              additionalProperties: false,
              required: ["productPurpose", "users", "designPrinciples", "uiArchitecture", "constraints"],
              properties: {
                productPurpose: { type: "string" },
                users: { type: "array", items: { type: "string" } },
                designPrinciples: { type: "array", items: { type: "string" } },
                uiArchitecture: { type: "array", items: { type: "string" } },
                constraints: { type: "array", items: { type: "string" } },
              },
            },
            candidates: {
              type: "array",
              minItems: 1,
              maxItems: 5,
              items: {
                type: "object",
                additionalProperties: false,
                required: ["id", "title", "uiEvidence", "userValueScore", "confidenceScore", "effortScore", "riskScore", "visualReviewPlan"],
                properties: {
                  id: { type: "string" },
                  title: { type: "string" },
                  uiEvidence: { type: "array", items: { type: "string" } },
                  userValueScore: { type: "number", minimum: 0, maximum: 100 },
                  confidenceScore: { type: "number", minimum: 0, maximum: 100 },
                  effortScore: { type: "number", minimum: 0, maximum: 100 },
                  riskScore: { type: "number", minimum: 0, maximum: 100 },
                  visualReviewPlan: { type: "array", items: { type: "string" } },
                },
              },
            },
            researchDecision: {
              type: "object",
              additionalProperties: false,
              required: ["needsResearch", "reason", "queries"],
              properties: {
                needsResearch: { type: "boolean" },
                reason: { type: "string" },
                queries: { type: "array", items: { type: "string" } },
              },
            },
          },
        },
        prompt:
          "First inspect selected UI scope {{result:select-scope}}, detected commands {{result:detect-project-commands}}, bounded relevant history {{result:read-completed-ui-improvements}}, repository package/config metadata, the target view, and representative sibling views without editing files. Infer a concise product/UI constitution, record comparative gaps in information architecture, density, primitives, states, accessibility, and responsive behavior, then generate 3-5 materially different cohesive UI packages. Include a view-level refactor candidate when the target is structurally inconsistent with stronger sibling surfaces and local polish would leave the root problem intact. Score each from 0-100 for user value, evidence confidence, effort, and risk. Base them on concrete responsive, accessibility, hierarchy, design-system, copy, visual-state, hydration, runtime, or package-capability evidence. Identify only focused current research needed to discriminate among leading candidates. Make bounded reversible design assumptions autonomously and return only schema-valid JSON.",
      },
    },
    {
      id: "research-decision",
      title: "Use Online Research?",
      position: { x: 2400, y: -150 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'variables.enableOnlineResearch === "true" && lastData?.output?.researchDecision?.needsResearch === true',
        },
      },
    },
    {
      id: "ui-research",
      title: "UI Best-Practice Research",
      position: { x: 2720, y: -180 },
      size: { width: 300, height: 230 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        webAccess: true,
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Use content enrichment only for the research decision in provisional UI portfolio {{data:propose-ui-improvements:output}}. If search_web is available, run focused searches for current primary-source framework/library behavior; official design-system guidance from mature product companies such as GitHub Primer, Microsoft Fluent, Atlassian Design System, or Material Design when relevant; W3C/WAI WCAG guidance; MDN and web.dev accessibility/responsive guidance; browser/runtime notes; and testing approaches that discriminate among leading packages. Inspect the repository's installed UI package versions first, then consult the npm registry plus official maintainer release notes and migration docs only where a current package capability or upgrade could materially improve the candidates. Compare transferable principles and interaction patterns without copying another company's branding. Use fetch_url on the best official or maintainer pages before relying on them. Keep findings concise with source links, freshness/version notes, practical UI implications, upgrade cost/compatibility when relevant, explicit non-findings, and which candidates should be promoted, revised, or rejected. If web search is unavailable, say so and rely on local evidence plus provided URLs.",
    },
    {
      id: "choose-ui-improvement",
      title: "Plan UI Improvement Package",
      position: { x: 3060, y: 0 },
      size: { width: 320, height: 250 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{candidateFile:path=.machdoch/ralph/ui-improvements/candidate.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: [
            "decision",
            "rationale",
            "scopeAnalysis",
            "researchDecision",
            "selectedCandidate",
            "rejectedCandidates",
            "stopReason",
          ],
          properties: {
            decision: { type: "string", enum: ["IMPLEMENT", "STOP", "DEFER"] },
            rationale: { type: "string" },
            scopeAnalysis: {
              type: "object",
              required: ["scope", "scopeCluster", "uiSignals", "designSystem", "constraints", "stopSignals"],
              properties: {
                scope: {
                  type: "object",
                  required: ["id", "title", "kind", "paths", "risk"],
                  properties: {
                    id: { type: "string" },
                    title: { type: "string" },
                    kind: { type: "string" },
                    paths: { type: "array", items: { type: "string" } },
                    globs: { type: "array", items: { type: "string" } },
                    tags: { type: "array", items: { type: "string" } },
                    priority: { type: "number" },
                    risk: { type: "string", enum: ["low", "medium", "high"] },
                  },
                },
                scopeCluster: {
                  type: "object",
                  required: ["rootScopeId", "scopeIds", "paths", "risk", "rationale"],
                  properties: {
                    rootScopeId: { type: "string" },
                    scopeIds: { type: "array", items: { type: "string" } },
                    paths: { type: "array", items: { type: "string" } },
                    globs: { type: "array", items: { type: "string" } },
                    tags: { type: "array", items: { type: "string" } },
                    risk: { type: "string", enum: ["low", "medium", "high"] },
                    rationale: { type: "array", items: { type: "string" } },
                  },
                },
                uiSignals: { type: "array", items: { type: "string" } },
                designSystem: { type: "array", items: { type: "string" } },
                constraints: { type: "array", items: { type: "string" } },
                stopSignals: { type: "array", items: { type: "string" } },
              },
            },
            researchDecision: {
              type: "object",
              required: ["needsResearch", "reason", "queries"],
              properties: {
                needsResearch: { type: "boolean" },
                reason: { type: "string" },
                queries: { type: "array", items: { type: "string" } },
              },
            },
            selectedCandidate: {
              anyOf: [
                {
                  type: "object",
                  additionalProperties: false,
                  required: [
                    "id",
                    "title",
                    "evidence",
                    "userValue",
                    "currentBehavior",
                    "proposedBehavior",
                    "relatedChanges",
                    "affectedFiles",
                    "acceptanceCriteria",
                    "expectedOutcome",
                    "visualReviewPlan",
                    "verificationPlan",
                    "verificationTier",
                    "reviewTier",
                    "accessibilityConsiderations",
                    "responsiveConsiderations",
                    "rollbackNotes",
                    "remainingRelatedWork",
                  ],
                  properties: {
                id: { type: "string" },
                title: { type: "string" },
                evidence: { type: "array", items: { type: "string" } },
                userValue: { type: "string" },
                currentBehavior: { type: "string" },
                proposedBehavior: { type: "string" },
                relatedChanges: {
                  type: "array",
                  items: {
                    type: "object",
                    required: ["title", "description", "affectedFiles"],
                    properties: {
                      title: { type: "string" },
                      description: { type: "string" },
                      affectedFiles: { type: "array", items: { type: "string" } },
                    },
                  },
                },
                affectedFiles: { type: "array", items: { type: "string" } },
                acceptanceCriteria: { type: "array", items: { type: "string" } },
                expectedOutcome: { type: "string" },
                visualReviewPlan: { type: "array", items: { type: "string" } },
                verificationPlan: { type: "array", items: { type: "string" } },
                verificationTier: { type: "string", enum: ["focused", "standard", "broad"] },
                reviewTier: { type: "string", enum: ["validator-only", "strict"] },
                accessibilityConsiderations: { type: "array", items: { type: "string" } },
                responsiveConsiderations: { type: "array", items: { type: "string" } },
                rollbackNotes: { type: "array", items: { type: "string" } },
                remainingRelatedWork: { type: "array", items: { type: "string" } },
                  },
                },
                {
                  type: "object",
                  properties: {},
                  additionalProperties: false,
                },
              ],
            },
            rejectedCandidates: {
              type: "array",
              items: {
                type: "object",
                required: ["id", "reason"],
                properties: {
                  id: { type: "string" },
                  title: { type: "string" },
                  reason: { type: "string" },
                  evidence: { type: "array", items: { type: "string" } },
                },
              },
            },
            stopReason: { type: "string" },
          },
        },
        prompt:
          "Refine, rescore, and select from provisional UI portfolio {{data:propose-ui-improvements:output}} after focused research {{summary:ui-research}}. Inspect selected JSON scope and dependency-aware scope cluster {{result:select-scope}} without editing files. Apply uiScope={{uiScope:text=auto-detect}}, riskTolerance={{riskTolerance:text=ambitious}}, allowAmbitiousUiChanges={{allowAmbitiousUiChanges:boolean=true}}, designPolicy={{designPolicy:text=}}, detected commands {{result:detect-project-commands}}, bounded completed history {{result:read-completed-ui-improvements}}, uiImprovementPolicy={{uiImprovementPolicy:text=}}, and excludePaths={{excludePaths:text=}}. Reject candidates contradicted by research and revise acceptance criteria when current standards or framework behavior change the plan. Return decision IMPLEMENT only for the highest-value cohesive UI work package, not one micro-change: select 2-5 tightly related UI changes when they share files, states, responsive/accessibility acceptance criteria, or visual review needs. Scope by the complete user-facing outcome rather than by line count. If comparative evidence shows the target view is structurally behind sibling views, select the coherent view-level refactor even when it changes many components; do not downscope it to token spacing or two-line cosmetic edits merely because those are safer to describe. The package must use the schema fields id (stable kebab-case), title, evidence, userValue, currentBehavior, proposedBehavior, relatedChanges with affectedFiles, acceptanceCriteria, expectedOutcome, affectedFiles, visualReviewPlan, verificationPlan, verificationTier (focused, standard, or broad), reviewTier (validator-only or strict), accessibilityConsiderations, responsiveConsiderations, rollbackNotes, and remainingRelatedWork. Dependencies, schemas, migrations, shared primitives, routing, and public APIs may change when required for the selected outcome and covered by rollback and verification plans. Make the best bounded reversible product/design assumption from repository evidence. Return DEFER only when unavailable external credentials/state make all candidates impossible now. Return STOP when remaining ideas are speculative, cosmetic churn without evidence, duplicate completed work, or fail threshold {{meaningfulThreshold:text=}}. If decision is STOP or DEFER, selectedCandidate must be {} and stopReason must explain why. Return only schema-valid JSON.",
      },
    },
    {
      id: "has-actionable-ui-improvement",
      title: "Actionable UI Improvement?",
      position: { x: 3400, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'context.resultsByBlock?.["choose-ui-improvement"]?.data?.output?.decision === "IMPLEMENT" && context.resultsByBlock?.["choose-ui-improvement"]?.data?.output?.selectedCandidate && Object.keys(context.resultsByBlock["choose-ui-improvement"].data.output.selectedCandidate).length > 0',
        },
      },
    },
    {
      id: "selection-is-deferred",
      title: "UI Selection Deferred?",
      position: { x: 3560, y: 260 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "String(context.resultsByBlock?.['choose-ui-improvement']?.data?.output?.decision ?? '').toUpperCase() === 'DEFER'",
        },
      },
    },
    {
      id: "find-active-ui-improvement",
      title: "Find Existing Active UI Improvement",
      position: { x: 3720, y: -220 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FILE_EXISTS",
        path: "{{activeUiImprovementFile:path=.machdoch/ralph/ui-improvements/active-ui-improvement.json}}",
      },
    },
    {
      id: "archive-superseded-ui-improvement",
      title: "Archive Superseded UI Improvement",
      position: { x: 3880, y: -260 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "ARCHIVE_FILE",
        path: "{{activeUiImprovementFile:path=.machdoch/ralph/ui-improvements/active-ui-improvement.json}}",
        rootPath:
          "{{archivedUiImprovementsDirectory:path=.machdoch/ralph/ui-improvements/archive}}",
      },
    },
    {
      id: "write-active-ui-improvement",
      title: "Track Active UI Improvement",
      position: { x: 3720, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "WRITE_JSON",
        path: "{{activeUiImprovementFile:path=.machdoch/ralph/ui-improvements/active-ui-improvement.json}}",
        input: "{{data:choose-ui-improvement:output.selectedCandidate}}",
      },
    },
    {
      id: "git-snapshot-before",
      title: "Git Snapshot Before",
      position: { x: 4060, y: -170 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_SNAPSHOT",
        outputPath:
          "{{gitSnapshotFile:path=.machdoch/ralph/ui-improvements/git-snapshot.json}}",
      },
    },
    {
      id: "count-ui-improvement-pass",
      title: "Count UI Improvement Pass",
      position: { x: 4060, y: 230 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        counterName:
          "autonomous-ui-improvement-loop.implementation-pass.{{data:select-scope:scope.id}}.{{data:choose-ui-improvement:output.selectedCandidate.id}}",
        maxAttempts: "{{maxUiImprovementPasses:number=8}}",
      },
    },
    {
      id: "baseline-verification",
      title: "Record Verification Baseline",
      position: { x: 4060, y: -360 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{verificationCommand:text=}}",
        fallbackCommand: "{{data:detect-project-commands:focusedVerificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "implement-ui-improvement",
      title: "Implement UI Improvement",
      position: { x: 4060, y: 40 },
      size: { width: 340, height: 260 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 4,
      },
      type: "PROMPT",
      prompt:
        "Implement the active UI improvement package at {{activeUiImprovementFile:path=.machdoch/ralph/ui-improvements/active-ui-improvement.json}} using package {{data:choose-ui-improvement:output.selectedCandidate}}, selected scope cluster {{result:select-scope}}, research {{summary:ui-research}}, deterministic baseline {{result:git-snapshot-before}}, verification baseline, detected commands, latest validator/reviewer feedback, scope guard {{result:scope-change-guard}}, work-yield evidence {{data:work-yield-analysis:output}}, verification routing, and designPolicy={{designPolicy:text=}}. Complete the whole cohesive UI package within selected paths plus required adjacent tests/docs/imports. A full view/component refactor, replacement of weak local structure, shared-primitive change, or verified dependency upgrade is allowed when the package calls for it; preserve behavior that is outside the package, not accidental implementation shape. Do not declare success after a small diff while any acceptance criterion, related change, state, viewport, or sibling-view consistency gap in the selected package remains. Prefer clean minimalist responsive accessible UI, restrained badges/copy/icons, stable dimensions, and no overflow/hydration regressions. Security-only hardening is low priority in this nonsecurity UI flow. Dependency changes use allowDependencyChanges={{allowDependencyChanges:boolean=true}}, schemas/migrations use allowSchemaChanges={{allowSchemaChanges:boolean=true}}, and public APIs/shared primitives use allowPublicApiChanges={{allowPublicApiChanges:boolean=true}} when necessary and verified. Repair only new/worsened failures, make bounded reversible design decisions, do not start/restart servers, and append an evidence note to {{notesFile:path=.machdoch/ralph/ui-improvements/RALPH_UI_IMPROVEMENT_NOTES.md}}.",
    },
    {
      id: "select-verification-command",
      title: "Select Verification Tier",
      position: { x: 4400, y: -140 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "TRANSFORM_JSON",
        input: "{}",
        expression:
          "(() => { const candidate = context.resultsByBlock?.get?.('choose-ui-improvement')?.data?.output?.selectedCandidate ?? {}; const commands = context.resultsByBlock?.get?.('detect-project-commands')?.data ?? {}; const requestedTier = String(candidate.verificationTier ?? candidate.riskAssessment?.verificationTier ?? '').toLowerCase(); const requestedReviewTier = String(candidate.reviewTier ?? candidate.riskAssessment?.reviewTier ?? '').toLowerCase(); const riskText = JSON.stringify([candidate.risk, candidate.riskAssessment, candidate.affectedFiles, candidate.relatedChanges, candidate.visualReviewPlan, candidate.accessibility, candidate.responsive]).toLowerCase(); const highRisk = /(database|migration|schema|ipc|api|dependency|package|lockfile|persistence|public api|contract|hydration|routing|accessibility|semantic|responsive|shared primitive|design system)/u.test(riskText); const tier = highRisk || requestedTier === 'broad' || requestedTier === 'strict' ? 'broad' : requestedTier === 'standard' ? 'standard' : 'focused'; const detectedCommand = tier === 'broad' ? commands.broadVerificationCommand : tier === 'standard' ? commands.standardVerificationCommand : commands.focusedVerificationCommand; const command = (variables.verificationCommand ?? '').trim() || detectedCommand || commands.verificationCommand || ''; const reviewTier = highRisk || requestedReviewTier === 'strict' || tier === 'broad' ? 'strict' : 'validator-only'; return { tier, command, reviewTier, highRisk, source: (variables.verificationCommand ?? '').trim() ? 'variable' : 'detected', focusedCommand: commands.focusedVerificationCommand || '', standardCommand: commands.standardVerificationCommand || '', broadCommand: commands.broadVerificationCommand || '' }; })()",
      },
    },
    {
      id: "verification-decision",
      title: "Run Verification?",
      position: { x: 4400, y: 40 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "Boolean(context.resultsByBlock?.['select-verification-command']?.data?.output?.command?.trim())",
        },
      },
    },
    {
      id: "run-verification",
      title: "Run Verification",
      position: { x: 4720, y: -110 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{data:select-verification-command:output.command}}",
        fallbackCommand: "{{data:detect-project-commands:focusedVerificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "count-verification-repair",
      title: "Count Verification Repair",
      position: { x: 4720, y: 330 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        counterName:
          "autonomous-ui-improvement-loop.verification-repair.{{data:select-scope:scope.id}}.{{data:choose-ui-improvement:output.selectedCandidate.id}}",
        maxAttempts: "{{maxVerificationRepairPasses:number=3}}",
      },
    },
    {
      id: "fix-validation-failures",
      title: "Fix Validation Failures",
      position: { x: 4720, y: 120 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "PROMPT",
      prompt:
        "Fix verification failures from {{result:run-verification}} that were caused by the current UI package, comparing signatures with pre-change baseline {{result:baseline-verification}}. Repair only new or worsened failures. Keep fixes scoped to active UI package {{data:choose-ui-improvement:output.selectedCandidate}} and selected scope cluster {{result:select-scope}}. Do not broaden the package or start unrelated work or servers.",
    },
    {
      id: "resolve-runtime-urls",
      title: "Resolve Runtime URLs",
      position: { x: 5060, y: -130 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "TRANSFORM_JSON",
        input: "{}",
        expression:
          "(() => { const readEnv = (key) => { if (!key || typeof process === 'undefined') return ''; const value = process.env?.[String(key).trim()]; return typeof value === 'string' ? value.trim() : ''; }; const detected = context.resultsByBlock?.get?.('detect-project-commands')?.data ?? {}; const configuredTargetUrl = (variables.targetUrl ?? '').trim(); const configuredHealthUrl = (variables.healthUrl ?? '').trim(); const configuredCommand = (variables.visualServerCommand ?? '').trim(); const targetUrl = configuredTargetUrl || readEnv(variables.targetUrlEnvKey) || String(detected.targetUrl ?? '').trim(); const healthUrl = configuredHealthUrl || readEnv(variables.healthUrlEnvKey) || targetUrl; const serverCommand = configuredCommand || String(detected.serveCommand ?? '').trim(); const serverCwd = (variables.visualServerCwd ?? '').trim() || String(detected.rootPath ?? '.'); const visualStatus = targetUrl ? (serverCommand ? 'managed-or-reused' : 'existing-only') : (variables.screenshotPath?.trim() ? 'screenshot-only' : 'degraded-unavailable'); return { targetUrl, healthUrl, serverCommand, serverCwd, visualStatus, degradedReason: visualStatus === 'degraded-unavailable' ? 'No configured, environment, or detected target URL; code verification continues and FINAL_REPORT records degraded visual coverage.' : '', targetUrlEnvKey: variables.targetUrlEnvKey, healthUrlEnvKey: variables.healthUrlEnvKey, targetSource: targetUrl ? (configuredTargetUrl ? 'variable' : readEnv(variables.targetUrlEnvKey) ? variables.targetUrlEnvKey : 'detected') : '', healthSource: healthUrl ? (configuredHealthUrl ? 'variable' : readEnv(variables.healthUrlEnvKey) ? variables.healthUrlEnvKey : 'target') : '', commandSource: serverCommand ? (configuredCommand ? 'variable' : detected.serveCommandSource || 'detected') : '' }; })()",
      },
    },
    {
      id: "visual-decision",
      title: "Run Visual Review?",
      position: { x: 5380, y: 40 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'variables.enableVisualReview === "true" && (Boolean(context.resultsByBlock?.["resolve-runtime-urls"]?.data?.output?.targetUrl?.trim()) || Boolean(variables.screenshotPath?.trim()))',
        },
      },
    },
    {
      id: "visual-review",
      title: "Visual Review",
      position: { x: 5700, y: 40 },
      size: { width: 280, height: 190 },
      type: "UTILITY",
      utility: {
        type: "UI_ANALYZE",
        adapter: "auto",
        targetUrl: "{{data:resolve-runtime-urls:output.targetUrl}}",
        screenshotPath: "{{screenshotPath:path=}}",
        server: {
          mode: "managed",
          healthUrl: "{{data:resolve-runtime-urls:output.healthUrl}}",
          command: "{{data:resolve-runtime-urls:output.serverCommand}}",
          cwd: "{{data:resolve-runtime-urls:output.serverCwd}}",
          reuseExisting: true,
        },
        checks: {
          screenshots: true,
          accessibility: true,
          console: true,
          network: true,
          responsive: true,
        },
        viewports: [
          { name: "desktop", width: 1280, height: 900 },
          { name: "tablet", width: 768, height: 1024 },
          { name: "mobile", width: 390, height: 844 },
          { name: "small-mobile", width: 320, height: 568 },
        ],
        timeoutSeconds: 30,
        fullPage: true,
        waitUntil: "domcontentloaded",
      },
    },
    {
      id: "git-diff-summary",
      title: "Git Diff Summary",
      position: { x: 6040, y: 40 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_DIFF_SUMMARY",
        outputPath:
          "{{gitDiffFile:path=.machdoch/ralph/ui-improvements/git-diff.json}}",
      },
    },
    {
      id: "scope-change-guard",
      title: "Guard UI Improvement Scope",
      position: { x: 6100, y: -160 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CHANGE_SCOPE_GUARD",
        input:
          "{\"scope\":{{data:select-scope:scope}},\"gitSummary\":{{data:git-diff-summary}}}",
      },
    },
    {
      id: "work-yield-analysis",
      title: "Assess UI Work Yield",
      position: { x: 6260, y: -120 },
      size: { width: 300, height: 190 },
      type: "UTILITY",
      utility: {
        type: "TRANSFORM_JSON",
        input: "{}",
        expression:
          "(() => { const diff = context.resultsByBlock?.get?.('git-diff-summary'); const baseline = context.resultsByBlock?.get?.('git-snapshot-before'); const current = Array.isArray(diff?.data?.files) ? diff.data.files : []; const before = new Map((Array.isArray(baseline?.data?.files) ? baseline.data.files : []).map((file) => [String(file?.path ?? '').replace(/\\\\/gu, '/'), file?.signature])); const changedFiles = current.filter((file) => before.get(String(file?.path ?? '').replace(/\\\\/gu, '/')) !== file?.signature).map((file) => String(file?.path ?? '').replace(/\\\\/gu, '/')).filter(Boolean); return { changedFiles, changedFileCount: changedFiles.length, producedWork: changedFiles.length > 0, scopeGuard: context.resultsByBlock?.get?.('scope-change-guard')?.output ?? '', visualStatus: context.resultsByBlock?.get?.('resolve-runtime-urls')?.data?.output?.visualStatus ?? '' }; })()",
      },
    },
    {
      id: "useful-work-produced",
      title: "Useful UI Work Produced?",
      position: { x: 6440, y: -80 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "lastData?.producedWork === true && lastData?.scopeGuard === 'IN_SCOPE'",
        },
      },
    },
    {
      id: "review-tier-decision",
      title: "Strict UI Review?",
      position: { x: 6200, y: 230 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'context.resultsByBlock?.["select-verification-command"]?.data?.output?.reviewTier === "strict"',
        },
      },
    },
    {
      id: "independent-ui-review",
      title: "Independent UI Review",
      position: { x: 6380, y: 40 },
      size: { width: 320, height: 250 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{reviewFile:path=.machdoch/ralph/ui-improvements/review.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          additionalProperties: false,
          required: ["decision", "summary", "issues", "verificationNotes", "visualNotes"],
          properties: {
            decision: { type: "string", enum: ["PASS", "FIX", "DEFER"] },
            summary: { type: "string" },
            issues: {
              type: "array",
              items: {
                type: "object",
                required: ["severity", "title", "evidence", "requiredFix"],
                properties: {
                  severity: { type: "string", enum: ["critical", "high", "medium", "low", "info"] },
                  title: { type: "string" },
                  evidence: { type: "string" },
                  requiredFix: { type: "string" },
                  affectedFiles: { type: "array", items: { type: "string" } },
                },
              },
            },
            verificationNotes: { type: "array", items: { type: "string" } },
            visualNotes: { type: "array", items: { type: "string" } },
          },
        },
        prompt:
          "Review the current UI improvement package as a separate reviewer because verification routing requested strict review. Active package: {{data:choose-ui-improvement:output.selectedCandidate}}. Scope cluster: {{result:select-scope}}. Diff: {{result:git-diff-summary}}. Baseline verification: {{result:baseline-verification}}. Post-change verification: {{result:run-verification}}. Runtime URL resolution: {{data:resolve-runtime-urls:output}}. Visual review: {{result:visual-review}}. Evaluate only the active package and required adjacent tests/docs/imports. Ignore unrelated workspace changes. Check every acceptance criterion and related change, designPolicy={{designPolicy:text=}}, target-versus-sibling-view consistency, responsive/mobile behavior, accessibility, hierarchy, badge restraint, concise copy, icon usage, overflow, focus/keyboard states, console/network/hydration issues, and design-system consistency. Do not reward a small clean diff when it leaves the package's structural outcome incomplete. Return PASS only when the complete package is cohesive and no new regression exists relative to baseline, FIX when specific autonomous repairs remain, and DEFER only when unavailable external state prevents completion after bounded reversible assumptions. Return only schema-valid JSON.",
      },
    },
    {
      id: "review-is-deferred",
      title: "UI Review Deferred?",
      position: { x: 6580, y: 310 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "String(context.resultsByBlock?.['independent-ui-review']?.data?.output?.decision ?? '').toUpperCase() === 'DEFER'",
        },
      },
    },
    {
      id: "review-needs-fix",
      title: "UI Review Needs Fix?",
      position: { x: 6740, y: 310 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "String(context.resultsByBlock?.['independent-ui-review']?.data?.output?.decision ?? '').toUpperCase() === 'FIX'",
        },
      },
    },
    {
      id: "validate-ui-improvement",
      title: "Validate UI Improvement",
      position: { x: 6740, y: 40 },
      size: { width: 320, height: 250 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "VALIDATOR_JSON",
        maxAttempts: 2,
        schema: RALPH_VALIDATOR_SCHEMA,
        prompt:
          "Validate the latest autonomous UI improvement package. Package: {{data:choose-ui-improvement:output.selectedCandidate}}. Scope cluster: {{result:select-scope}}. Strict review: {{data:independent-ui-review:output}}. Baseline verification: {{result:baseline-verification}}. Post-change verification: {{result:run-verification}}. Runtime URL resolution: {{data:resolve-runtime-urls:output}}. Visual review: {{result:visual-review}}. Git diff: {{result:git-diff-summary}}. Judge only the active package and required adjacent tests/docs/imports; ignore unrelated workspace changes. Return DONE only when every acceptance criterion and related change in the cohesive package is complete, the result reaches the planned target-versus-sibling-view standard, satisfies designPolicy={{designPolicy:text=}}, has no obvious desktop/mobile overflow, overlapping text, badge/copy/icon misuse, accessibility or hydration regression, and introduces no new or worsened failure relative to baseline. Changed lines or files are evidence of activity, never evidence of completion by themselves. Return CONTINUE for bounded implementation work, RETRY for own regressions, and ERROR only when unavailable credentials/external state or repeated non-progress makes this package deferrable. The flow counter enforces maxUiImprovementPasses={{maxUiImprovementPasses:number=8}}. Never wait for a human decision; make the best bounded reversible design assumption.",
      },
    },
    {
      id: "final-report",
      title: "Final UI Improvement Report",
      position: { x: 7080, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{uiReportFile:path=.machdoch/ralph/ui-improvements/final-report.json}}",
        outputPath:
          "{{uiReportMarkdown:path=.machdoch/ralph/ui-improvements/final-report.md}}",
      },
    },
    {
      id: "retained-active-report",
      title: "Retained Active UI Report",
      position: { x: 7080, y: 120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{uiReportFile:path=.machdoch/ralph/ui-improvements/final-report.json}}",
        outputPath:
          "{{uiReportMarkdown:path=.machdoch/ralph/ui-improvements/final-report.md}}",
      },
    },
    {
      id: "read-active-ui-improvement",
      title: "Read Active UI Improvement",
      position: { x: 7420, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "READ_JSON",
        path: "{{activeUiImprovementFile:path=.machdoch/ralph/ui-improvements/active-ui-improvement.json}}",
      },
    },
    {
      id: "append-completed-ui-improvement",
      title: "Append Completed UI Improvement",
      position: { x: 7760, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{completedUiImprovementsFile:path=.machdoch/ralph/ui-improvements/completed-ui-improvements.jsonl}}",
        input: "{{data:read-active-ui-improvement:json}}",
      },
    },
    {
      id: "archive-active-ui-improvement",
      title: "Archive Active UI Improvement",
      position: { x: 8100, y: -120 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "ARCHIVE_FILE",
        path: "{{activeUiImprovementFile:path=.machdoch/ralph/ui-improvements/active-ui-improvement.json}}",
        rootPath:
          "{{archivedUiImprovementsDirectory:path=.machdoch/ralph/ui-improvements/archive}}",
      },
    },
    {
      id: "mark-scope-result",
      title: "Mark Scope Result",
      position: { x: 3720, y: 300 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "autonomous-ui-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.md}}",
        result: "DONE",
        includeMarkdown: true,
      },
    },
    {
      id: "defer-scope",
      title: "Defer Exhausted UI Package",
      position: { x: 3720, y: 500 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "autonomous-ui-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.md}}",
        result: "DEFERRED_AFTER_BOUNDED_REPAIR",
        includeMarkdown: true,
      },
    },
    {
      id: "mark-stop-scope",
      title: "Mark No-Action UI Scope",
      position: { x: 3720, y: 680 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "autonomous-ui-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.md}}",
        result: "STOP_NO_MEANINGFUL_WORK",
        includeMarkdown: true,
      },
    },
    {
      id: "mark-invalid-scope",
      title: "Mark Invalid UI Scope Outcome",
      position: { x: 3720, y: 860 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "autonomous-ui-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/ui-improvements/autonomous-ui-improvement-loop.scope-registry.md}}",
        result: "INVALID_OUTPUT",
        includeMarkdown: true,
      },
    },
    {
      id: "record-done-outcome",
      title: "Record Completed UI Outcome",
      position: { x: 8260, y: -320 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{uiImprovementOutcomesFile:path=.machdoch/ralph/ui-improvements/outcomes.jsonl}}",
        input: "{\"outcome\":\"DONE\",\"scopeId\":\"{{data:select-scope:scope.id}}\",\"candidateId\":\"{{data:choose-ui-improvement:output.selectedCandidate.id}}\",\"visualStatus\":\"{{data:resolve-runtime-urls:output.visualStatus}}\"}",
      },
    },
    {
      id: "record-deferred-outcome",
      title: "Record Deferred UI Outcome",
      position: { x: 8260, y: 60 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{uiImprovementOutcomesFile:path=.machdoch/ralph/ui-improvements/outcomes.jsonl}}",
        input: "{\"outcome\":\"DEFER\",\"scopeRoot\":\"{{scopeRoot:path=.}}\"}",
      },
    },
    {
      id: "record-stop-outcome",
      title: "Record No-Action UI Outcome",
      position: { x: 8260, y: 260 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{uiImprovementOutcomesFile:path=.machdoch/ralph/ui-improvements/outcomes.jsonl}}",
        input: "{\"outcome\":\"STOP\",\"scopeRoot\":\"{{scopeRoot:path=.}}\",\"reason\":\"No evidence-backed UI package cleared the threshold.\"}",
      },
    },
    {
      id: "record-invalid-outcome",
      title: "Record Invalid UI Outcome",
      position: { x: 8260, y: 460 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{uiImprovementOutcomesFile:path=.machdoch/ralph/ui-improvements/outcomes.jsonl}}",
        input: "{\"outcome\":\"INVALID\",\"scopeRoot\":\"{{scopeRoot:path=.}}\",\"reason\":\"Discovery, state, or validation output was invalid.\"}",
      },
    },
    {
      id: "scope-cycle-complete",
      title: "Scope Cycle Complete?",
      position: { x: 4060, y: 300 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "['EMPTY', 'ERROR'].includes(String(context.resultsByBlock?.['scan-ui-scopes']?.output ?? '')) || context.resultsByBlock?.['select-scope']?.output === 'EMPTY' || ['mark-scope-result', 'defer-scope', 'mark-stop-scope', 'mark-invalid-scope'].some((id) => context.resultsByBlock?.[id]?.data?.cycleCompleted === true)",
        },
      },
    },
    {
      id: "success",
      title: "No Meaningful UI Improvements",
      position: { x: 4400, y: 300 },
      size: { width: 280, height: 114 },
      type: "END",
      status: "success",
    },
    {
      id: "deferred",
      title: "Active UI Improvement Retained for Retry",
      position: { x: 4400, y: 520 },
      size: { width: 280, height: 114 },
      type: "END",
      status: "success",
    },
  ],
  edges: [
    { id: "start-to-scan-ui-scopes", from: "start", fromOutput: "SUCCESS", to: "scan-ui-scopes" },
    { id: "scan-ui-scopes-to-update", from: "scan-ui-scopes", fromOutput: "SUCCESS", to: "update-scope-registry" },
    { id: "scan-ui-scopes-empty", from: "scan-ui-scopes", fromOutput: "EMPTY", to: "record-stop-outcome" },
    { id: "scan-ui-scopes-error", from: "scan-ui-scopes", fromOutput: "ERROR", to: "record-invalid-outcome" },
    { id: "update-registry-to-select", from: "update-scope-registry", fromOutput: "SUCCESS", to: "select-scope" },
    { id: "update-registry-empty", from: "update-scope-registry", fromOutput: "EMPTY", to: "record-stop-outcome" },
    { id: "update-registry-error", from: "update-scope-registry", fromOutput: "ERROR", to: "record-invalid-outcome" },
    { id: "select-scope-to-detect", from: "select-scope", fromOutput: "SELECTED", to: "detect-project-commands" },
    { id: "select-scope-empty", from: "select-scope", fromOutput: "EMPTY", to: "record-stop-outcome" },
    { id: "select-scope-error", from: "select-scope", fromOutput: "ERROR", to: "record-invalid-outcome" },
    { id: "detect-success-to-history", from: "detect-project-commands", fromOutput: "SUCCESS", to: "read-completed-ui-improvements" },
    { id: "detect-empty-to-history", from: "detect-project-commands", fromOutput: "EMPTY", to: "read-completed-ui-improvements" },
    { id: "detect-error-to-history", from: "detect-project-commands", fromOutput: "ERROR", to: "read-completed-ui-improvements" },
    { id: "history-success-to-propose", from: "read-completed-ui-improvements", fromOutput: "SUCCESS", to: "propose-ui-improvements" },
    { id: "history-empty-to-propose", from: "read-completed-ui-improvements", fromOutput: "EMPTY", to: "propose-ui-improvements" },
    { id: "history-not-found-to-propose", from: "read-completed-ui-improvements", fromOutput: "NOT_FOUND", to: "propose-ui-improvements" },
    { id: "history-invalid-to-propose", from: "read-completed-ui-improvements", fromOutput: "INVALID", to: "propose-ui-improvements" },
    { id: "history-error-to-propose", from: "read-completed-ui-improvements", fromOutput: "ERROR", to: "propose-ui-improvements" },
    { id: "propose-to-research-decision", from: "propose-ui-improvements", fromOutput: "SUCCESS", to: "research-decision" },
    { id: "propose-invalid", from: "propose-ui-improvements", fromOutput: "INVALID", to: "mark-invalid-scope" },
    { id: "propose-error", from: "propose-ui-improvements", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "research-decision-run", from: "research-decision", fromOutput: "MATCH", to: "ui-research" },
    { id: "research-decision-skip", from: "research-decision", fromOutput: "NO_MATCH", to: "choose-ui-improvement" },
    { id: "research-decision-error", from: "research-decision", fromOutput: "ERROR", to: "choose-ui-improvement" },
    { id: "research-to-refine", from: "ui-research", fromOutput: "SUCCESS", to: "choose-ui-improvement" },
    { id: "research-error-to-refine", from: "ui-research", fromOutput: "ERROR", to: "choose-ui-improvement" },
    { id: "choose-to-actionable", from: "choose-ui-improvement", fromOutput: "SUCCESS", to: "has-actionable-ui-improvement" },
    { id: "choose-invalid", from: "choose-ui-improvement", fromOutput: "INVALID", to: "mark-invalid-scope" },
    { id: "choose-error", from: "choose-ui-improvement", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "actionable-to-find-active", from: "has-actionable-ui-improvement", fromOutput: "MATCH", to: "find-active-ui-improvement" },
    { id: "not-actionable-to-classify", from: "has-actionable-ui-improvement", fromOutput: "NO_MATCH", to: "selection-is-deferred" },
    { id: "actionable-error", from: "has-actionable-ui-improvement", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "selection-deferred", from: "selection-is-deferred", fromOutput: "MATCH", to: "defer-scope" },
    { id: "selection-stopped", from: "selection-is-deferred", fromOutput: "NO_MATCH", to: "mark-stop-scope" },
    { id: "selection-classification-error", from: "selection-is-deferred", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "active-ui-exists", from: "find-active-ui-improvement", fromOutput: "EXISTS", to: "archive-superseded-ui-improvement" },
    { id: "active-ui-missing", from: "find-active-ui-improvement", fromOutput: "MISSING", to: "write-active-ui-improvement" },
    { id: "active-ui-check-error", from: "find-active-ui-improvement", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "superseded-ui-archive-to-write", from: "archive-superseded-ui-improvement", fromOutput: "SUCCESS", to: "write-active-ui-improvement" },
    { id: "superseded-ui-archive-missing-to-write", from: "archive-superseded-ui-improvement", fromOutput: "NOT_FOUND", to: "write-active-ui-improvement" },
    { id: "superseded-ui-archive-error", from: "archive-superseded-ui-improvement", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "write-to-snapshot", from: "write-active-ui-improvement", fromOutput: "SUCCESS", to: "git-snapshot-before" },
    { id: "write-invalid", from: "write-active-ui-improvement", fromOutput: "INVALID", to: "mark-invalid-scope" },
    { id: "write-error", from: "write-active-ui-improvement", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "snapshot-to-baseline", from: "git-snapshot-before", fromOutput: "SUCCESS", to: "baseline-verification" },
    { id: "snapshot-error-to-baseline", from: "git-snapshot-before", fromOutput: "ERROR", to: "baseline-verification" },
    { id: "baseline-success-to-count", from: "baseline-verification", fromOutput: "SUCCESS", to: "count-ui-improvement-pass" },
    { id: "baseline-failed-to-count", from: "baseline-verification", fromOutput: "FAILED", to: "count-ui-improvement-pass" },
    { id: "baseline-error-to-count", from: "baseline-verification", fromOutput: "ERROR", to: "count-ui-improvement-pass" },
    { id: "count-ui-improvement-pass-continue", from: "count-ui-improvement-pass", fromOutput: "CONTINUE", to: "implement-ui-improvement" },
    { id: "count-ui-improvement-pass-limit", from: "count-ui-improvement-pass", fromOutput: "LIMIT_REACHED", to: "defer-scope" },
    { id: "count-ui-improvement-pass-error", from: "count-ui-improvement-pass", fromOutput: "ERROR", to: "defer-scope" },
    { id: "implement-to-verification-tier", from: "implement-ui-improvement", fromOutput: "SUCCESS", to: "select-verification-command" },
    { id: "implement-error", from: "implement-ui-improvement", fromOutput: "ERROR", to: "defer-scope" },
    { id: "verification-tier-to-decision", from: "select-verification-command", fromOutput: "SUCCESS", to: "verification-decision" },
    { id: "verification-tier-error", from: "select-verification-command", fromOutput: "ERROR", to: "verification-decision" },
    { id: "verification-decision-run", from: "verification-decision", fromOutput: "MATCH", to: "run-verification" },
    { id: "verification-decision-skip", from: "verification-decision", fromOutput: "NO_MATCH", to: "resolve-runtime-urls" },
    { id: "verification-decision-error", from: "verification-decision", fromOutput: "ERROR", to: "resolve-runtime-urls" },
    { id: "verification-success-to-runtime-urls", from: "run-verification", fromOutput: "SUCCESS", to: "resolve-runtime-urls" },
    { id: "verification-failed-to-repair-counter", from: "run-verification", fromOutput: "FAILED", to: "count-verification-repair" },
    { id: "verification-error-to-repair-counter", from: "run-verification", fromOutput: "ERROR", to: "count-verification-repair" },
    { id: "repair-counter-to-fix", from: "count-verification-repair", fromOutput: "CONTINUE", to: "fix-validation-failures" },
    { id: "repair-counter-limit", from: "count-verification-repair", fromOutput: "LIMIT_REACHED", to: "defer-scope" },
    { id: "repair-counter-error", from: "count-verification-repair", fromOutput: "ERROR", to: "defer-scope" },
    { id: "fix-validation-to-decision", from: "fix-validation-failures", fromOutput: "SUCCESS", to: "verification-decision" },
    { id: "fix-validation-error", from: "fix-validation-failures", fromOutput: "ERROR", to: "defer-scope" },
    { id: "runtime-urls-success-to-visual-decision", from: "resolve-runtime-urls", fromOutput: "SUCCESS", to: "visual-decision" },
    { id: "runtime-urls-error-to-visual-decision", from: "resolve-runtime-urls", fromOutput: "ERROR", to: "visual-decision" },
    { id: "visual-decision-run", from: "visual-decision", fromOutput: "MATCH", to: "visual-review" },
    { id: "visual-decision-skip", from: "visual-decision", fromOutput: "NO_MATCH", to: "git-diff-summary" },
    { id: "visual-decision-error", from: "visual-decision", fromOutput: "ERROR", to: "git-diff-summary" },
    { id: "visual-success-to-diff", from: "visual-review", fromOutput: "SUCCESS", to: "git-diff-summary" },
    { id: "visual-unavailable-to-diff", from: "visual-review", fromOutput: "UNAVAILABLE", to: "git-diff-summary" },
    { id: "visual-error-to-diff", from: "visual-review", fromOutput: "ERROR", to: "git-diff-summary" },
    { id: "diff-success-to-scope-guard", from: "git-diff-summary", fromOutput: "SUCCESS", to: "scope-change-guard" },
    { id: "diff-empty-to-scope-guard", from: "git-diff-summary", fromOutput: "EMPTY", to: "scope-change-guard" },
    { id: "diff-error-to-scope-guard", from: "git-diff-summary", fromOutput: "ERROR", to: "scope-change-guard" },
    { id: "scope-guard-in-scope", from: "scope-change-guard", fromOutput: "IN_SCOPE", to: "work-yield-analysis" },
    { id: "scope-guard-out-of-scope", from: "scope-change-guard", fromOutput: "OUT_OF_SCOPE", to: "count-ui-improvement-pass" },
    { id: "scope-guard-empty", from: "scope-change-guard", fromOutput: "EMPTY", to: "count-ui-improvement-pass" },
    { id: "scope-guard-error", from: "scope-change-guard", fromOutput: "ERROR", to: "count-ui-improvement-pass" },
    { id: "work-yield-to-decision", from: "work-yield-analysis", fromOutput: "SUCCESS", to: "useful-work-produced" },
    { id: "work-yield-error-to-count", from: "work-yield-analysis", fromOutput: "ERROR", to: "count-ui-improvement-pass" },
    { id: "useful-work-to-review", from: "useful-work-produced", fromOutput: "MATCH", to: "review-tier-decision" },
    { id: "no-useful-work-to-count", from: "useful-work-produced", fromOutput: "NO_MATCH", to: "count-ui-improvement-pass" },
    { id: "useful-work-error-to-count", from: "useful-work-produced", fromOutput: "ERROR", to: "count-ui-improvement-pass" },
    { id: "review-tier-strict", from: "review-tier-decision", fromOutput: "MATCH", to: "independent-ui-review" },
    { id: "review-tier-validator-only", from: "review-tier-decision", fromOutput: "NO_MATCH", to: "validate-ui-improvement" },
    { id: "review-tier-error-to-validate", from: "review-tier-decision", fromOutput: "ERROR", to: "validate-ui-improvement" },
    { id: "review-to-defer-check", from: "independent-ui-review", fromOutput: "SUCCESS", to: "review-is-deferred" },
    { id: "review-invalid", from: "independent-ui-review", fromOutput: "INVALID", to: "mark-invalid-scope" },
    { id: "review-error", from: "independent-ui-review", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "review-deferred", from: "review-is-deferred", fromOutput: "MATCH", to: "defer-scope" },
    { id: "review-not-deferred", from: "review-is-deferred", fromOutput: "NO_MATCH", to: "review-needs-fix" },
    { id: "review-defer-check-error", from: "review-is-deferred", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "review-fix", from: "review-needs-fix", fromOutput: "MATCH", to: "fix-validation-failures" },
    { id: "review-pass", from: "review-needs-fix", fromOutput: "NO_MATCH", to: "validate-ui-improvement" },
    { id: "review-fix-check-error", from: "review-needs-fix", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "validate-done", from: "validate-ui-improvement", fromOutput: "DONE", to: "read-active-ui-improvement" },
    { id: "validate-continue", from: "validate-ui-improvement", fromOutput: "CONTINUE", to: "count-ui-improvement-pass" },
    { id: "validate-retry", from: "validate-ui-improvement", fromOutput: "RETRY", to: "count-verification-repair" },
    { id: "validate-error", from: "validate-ui-improvement", fromOutput: "ERROR", to: "defer-scope" },
    { id: "validate-invalid", from: "validate-ui-improvement", fromOutput: "INVALID", to: "defer-scope" },
    { id: "read-active-success-to-append", from: "read-active-ui-improvement", fromOutput: "SUCCESS", to: "append-completed-ui-improvement" },
    { id: "read-active-invalid", from: "read-active-ui-improvement", fromOutput: "INVALID", to: "mark-invalid-scope" },
    { id: "read-active-not-found", from: "read-active-ui-improvement", fromOutput: "NOT_FOUND", to: "mark-invalid-scope" },
    { id: "read-active-error", from: "read-active-ui-improvement", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "append-completed-to-mark", from: "append-completed-ui-improvement", fromOutput: "SUCCESS", to: "mark-scope-result" },
    { id: "append-completed-invalid", from: "append-completed-ui-improvement", fromOutput: "INVALID", to: "mark-invalid-scope" },
    { id: "append-completed-error", from: "append-completed-ui-improvement", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "mark-done-to-ledger", from: "mark-scope-result", fromOutput: "SUCCESS", to: "record-done-outcome" },
    { id: "mark-done-missing-to-ledger", from: "mark-scope-result", fromOutput: "NOT_FOUND", to: "record-done-outcome" },
    { id: "mark-done-error-to-ledger", from: "mark-scope-result", fromOutput: "ERROR", to: "record-done-outcome" },
    { id: "mark-defer-to-ledger", from: "defer-scope", fromOutput: "SUCCESS", to: "record-deferred-outcome" },
    { id: "mark-defer-missing-to-ledger", from: "defer-scope", fromOutput: "NOT_FOUND", to: "record-deferred-outcome" },
    { id: "mark-defer-error-to-ledger", from: "defer-scope", fromOutput: "ERROR", to: "record-deferred-outcome" },
    { id: "mark-stop-to-ledger", from: "mark-stop-scope", fromOutput: "SUCCESS", to: "record-stop-outcome" },
    { id: "mark-stop-missing-to-ledger", from: "mark-stop-scope", fromOutput: "NOT_FOUND", to: "record-stop-outcome" },
    { id: "mark-stop-error-to-ledger", from: "mark-stop-scope", fromOutput: "ERROR", to: "record-stop-outcome" },
    { id: "mark-invalid-to-ledger", from: "mark-invalid-scope", fromOutput: "SUCCESS", to: "record-invalid-outcome" },
    { id: "mark-invalid-missing-to-ledger", from: "mark-invalid-scope", fromOutput: "NOT_FOUND", to: "record-invalid-outcome" },
    { id: "mark-invalid-error-to-ledger", from: "mark-invalid-scope", fromOutput: "ERROR", to: "record-invalid-outcome" },
    { id: "done-ledger-to-archive", from: "record-done-outcome", fromOutput: "SUCCESS", to: "archive-active-ui-improvement" },
    { id: "done-ledger-invalid-to-retained-report", from: "record-done-outcome", fromOutput: "INVALID", to: "retained-active-report" },
    { id: "done-ledger-error-to-retained-report", from: "record-done-outcome", fromOutput: "ERROR", to: "retained-active-report" },
    { id: "defer-ledger-to-retained-report", from: "record-deferred-outcome", fromOutput: "SUCCESS", to: "retained-active-report" },
    { id: "defer-ledger-invalid-to-retained-report", from: "record-deferred-outcome", fromOutput: "INVALID", to: "retained-active-report" },
    { id: "defer-ledger-error-to-retained-report", from: "record-deferred-outcome", fromOutput: "ERROR", to: "retained-active-report" },
    { id: "stop-ledger-to-archive", from: "record-stop-outcome", fromOutput: "SUCCESS", to: "archive-active-ui-improvement" },
    { id: "stop-ledger-invalid-to-retained-report", from: "record-stop-outcome", fromOutput: "INVALID", to: "retained-active-report" },
    { id: "stop-ledger-error-to-retained-report", from: "record-stop-outcome", fromOutput: "ERROR", to: "retained-active-report" },
    { id: "invalid-ledger-to-archive", from: "record-invalid-outcome", fromOutput: "SUCCESS", to: "archive-active-ui-improvement" },
    { id: "invalid-ledger-invalid-to-retained-report", from: "record-invalid-outcome", fromOutput: "INVALID", to: "retained-active-report" },
    { id: "invalid-ledger-error-to-retained-report", from: "record-invalid-outcome", fromOutput: "ERROR", to: "retained-active-report" },
    { id: "archive-to-report", from: "archive-active-ui-improvement", fromOutput: "SUCCESS", to: "final-report" },
    { id: "archive-missing-to-report", from: "archive-active-ui-improvement", fromOutput: "NOT_FOUND", to: "final-report" },
    { id: "archive-error-to-retained-report", from: "archive-active-ui-improvement", fromOutput: "ERROR", to: "retained-active-report" },
    { id: "report-success-to-cycle", from: "final-report", fromOutput: "SUCCESS", to: "scope-cycle-complete" },
    { id: "report-error-to-cycle", from: "final-report", fromOutput: "ERROR", to: "scope-cycle-complete" },
    { id: "retained-report-success-to-deferred", from: "retained-active-report", fromOutput: "SUCCESS", to: "deferred" },
    { id: "retained-report-error-to-deferred", from: "retained-active-report", fromOutput: "ERROR", to: "deferred" },
    { id: "scope-cycle-complete-success", from: "scope-cycle-complete", fromOutput: "MATCH", to: "success" },
    { id: "scope-cycle-next", from: "scope-cycle-complete", fromOutput: "NO_MATCH", to: "select-scope" },
    { id: "scope-cycle-error", from: "scope-cycle-complete", fromOutput: "ERROR", to: "select-scope" },
  ],
};

export const autonomousUiImprovementLoopStarterFlow = {
  id: "autonomous-ui-improvement-loop",
  version: 9,
  defaultAlias: "autonomous-ui-improvement-loop",
  category: "Design Quality",
  tags: ["autonomous", "ui", "design", "visual-check"],
  flow: autonomousUiImprovementLoopFlow,
} as const satisfies RalphStarterFlow;
