import type { RalphFlow } from "../ralph.js";
import type { RalphStarterFlow } from "../ralph-starter-flows.js";

const RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS = 30 * 60;

const fullFeatureImplementationFlow: RalphFlow = {
  schemaVersion: 1,
  id: "starter-full-feature-implementation",
  alias: "feature-implementation-checklist-loop",
  name: "Feature Implementation Checklist Loop",
  description:
    "Configurable, resumable feature implementation loop with content-enriched research, interview, verification, and visual review.",
  settings: {
    maxTransitions: 70,
  },
  variables: [
    { name: "featureId", type: "text", default: "current-feature", required: false },
    { name: "featureRequest", type: "text", default: "", required: true },
    { name: "acceptanceCriteria", type: "text", default: "", required: false },
    { name: "checklistDirectory", type: "path", default: ".machdoch/feature-implementation", required: false },
    { name: "checklistFile", type: "path", default: ".machdoch/feature-implementation/current-feature.checklist.json", required: false },
    { name: "projectCommandsFile", type: "path", default: ".machdoch/feature-implementation/project-commands.json", required: false },
    { name: "gitSnapshotFile", type: "path", default: ".machdoch/feature-implementation/git-snapshot.json", required: false },
    { name: "gitDiffFile", type: "path", default: ".machdoch/feature-implementation/git-diff.json", required: false },
    { name: "featureReportFile", type: "path", default: ".machdoch/feature-implementation/final-report.json", required: false },
    { name: "featureReportMarkdown", type: "path", default: ".machdoch/feature-implementation/final-report.md", required: false },
    { name: "enableOnlineResearch", type: "boolean", default: "true", required: false },
    { name: "enableInterview", type: "boolean", default: "false", required: false },
    { name: "enableVisualReview", type: "boolean", default: "false", required: false },
    { name: "targetUrl", type: "url", default: "", required: false },
    { name: "healthUrl", type: "url", default: "", required: false },
    { name: "screenshotPath", type: "path", default: "", required: false },
    { name: "verificationCommand", type: "text", default: "", required: false },
    { name: "authInstructions", type: "text", default: "", required: false },
    { name: "designGuidelines", type: "text", default: "", required: false },
    { name: "implementationScope", type: "text", default: "auto-detect", required: false },
    { name: "maxImplementationPasses", type: "number", default: "8", required: false },
  ],
  blocks: [
    {
      id: "start",
      title: "Start",
      position: { x: 0, y: 0 },
      size: { width: 256, height: 140 },
      type: "START",
    },
    {
      id: "detect-project-commands",
      title: "Detect Project Commands",
      position: { x: 720, y: 0 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "DETECT_PROJECT_COMMANDS",
        rootPath: ".",
        outputPath:
          "{{projectCommandsFile:path=.machdoch/feature-implementation/project-commands.json}}",
      },
    },
    {
      id: "checklist-exists",
      title: "Checklist Exists?",
      position: { x: 1060, y: -110 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "FILE_EXISTS",
        path: "{{checklistFile:path=.machdoch/feature-implementation/current-feature.checklist.json}}",
      },
    },
    {
      id: "read-checklist",
      title: "Read Checklist",
      position: { x: 1400, y: -160 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "READ_JSON",
        path: "{{checklistFile:path=.machdoch/feature-implementation/current-feature.checklist.json}}",
      },
    },
    {
      id: "prepare-feature-brief",
      title: "Prepare Feature Brief",
      position: { x: 1400, y: 40 },
      size: { width: 280, height: 190 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Prepare a concise implementation brief from featureId={{featureId:text=current-feature}}, featureRequest={{featureRequest:text=}}, acceptanceCriteria={{acceptanceCriteria:text=}}, implementationScope={{implementationScope:text=auto-detect}}, authInstructions={{authInstructions:text=}}, designGuidelines={{designGuidelines:text=}}, detected project commands {{result:detect-project-commands}}, checklist existence {{result:checklist-exists}}, and existing checklist JSON {{result:read-checklist}} when present. Treat existing checklist JSON as resume context and ask no questions here.",
    },
    {
      id: "research-decision",
      title: "Use Online Research?",
      position: { x: 1400, y: -120 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression: 'variables.enableOnlineResearch === "true"',
        },
      },
    },
    {
      id: "initial-research",
      title: "Initial Research",
      position: { x: 1720, y: -170 },
      size: { width: 280, height: 190 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        webAccess: true,
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Use content enrichment before implementation. If search_web is available, run focused searches for current primary-source documentation, changelogs, release notes, standards, accessibility/security guidance, and comparable implementation examples relevant to this feature brief: {{summary:prepare-feature-brief}}. Use fetch_url on the best official or maintainer pages before relying on them. Also inspect local package/config metadata when it affects version assumptions. Keep findings concise with source links, risks, version/date assumptions, and implementation implications. If web search is unavailable, say so and base findings on local package docs/config plus any provided URLs.",
    },
    {
      id: "interview-decision",
      title: "Run Interview?",
      position: { x: 1720, y: 60 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression: 'variables.enableInterview === "true"',
        },
      },
    },
    {
      id: "interview-user",
      title: "Interview User",
      position: { x: 2040, y: 60 },
      size: { width: 280, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "INTERVIEW",
      prompt:
        "Interview the user only for information required to implement this feature correctly. Feature brief: {{summary:prepare-feature-brief}}. Research: {{summary:initial-research}}. Acceptance criteria: {{acceptanceCriteria:text=}}. Ask targeted questions about scope, behavior, UI, data, auth, edge cases, tests, rollout, and resume behavior.",
      completionCriteria:
        "Stop when implementation scope, acceptance criteria, important constraints, and verification expectations are clear enough to create a checklist.",
      maxTurns: 3,
      questionsPerTurn: 4,
      outputVariableName: "featureInterviewSummary",
      submitLabel: "Continue",
      cancelLabel: "Skip interview",
    },
    {
      id: "specification-checklist",
      title: "Create Checklist",
      position: { x: 2380, y: 0 },
      size: { width: 280, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{checklistFile:path=.machdoch/feature-implementation/current-feature.checklist.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: ["featureId", "request", "acceptanceCriteria", "tasks", "status"],
          properties: {
            featureId: { type: "string" },
            request: { type: "string" },
            acceptanceCriteria: { type: "array", items: { type: "string" } },
            tasks: {
              type: "array",
              items: {
                type: "object",
                required: ["id", "title", "status"],
                properties: {
                  id: { type: "string" },
                  title: { type: "string" },
                  status: { type: "string" },
                },
              },
            },
            status: { type: "string" },
          },
        },
        prompt:
          "Create or update the canonical JSON implementation checklist at {{checklistFile:path=.machdoch/feature-implementation/current-feature.checklist.json}}. Preserve completed tasks when resuming from {{result:read-checklist}}. Include feature request, acceptance criteria, implementation guide, content-enrichment notes with source links/version assumptions when research is present, test plan, optional visual review plan, auth notes, design guidelines, resume notes, and actionable tasks with stable ids and status values todo/in_progress/done/blocked. Inputs: brief {{summary:prepare-feature-brief}}, research {{summary:initial-research}}, interview {{featureInterviewSummary:text=}}, detected commands {{result:detect-project-commands}}. Return only schema-valid JSON.",
      },
    },
    {
      id: "git-snapshot-before",
      title: "Git Snapshot",
      position: { x: 2550, y: -220 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_SNAPSHOT",
        cwd: ".",
        outputPath:
          "{{gitSnapshotFile:path=.machdoch/feature-implementation/git-snapshot.json}}",
      },
    },
    {
      id: "select-next-task",
      title: "Select Next Checklist Task",
      position: { x: 2550, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SELECT_JSON_TASK",
        path: "{{checklistFile:path=.machdoch/feature-implementation/current-feature.checklist.json}}",
        jsonPath: "tasks",
        strategy: "start-to-end",
      },
    },
    {
      id: "implement-feature",
      title: "Implement Checklist Items",
      position: { x: 2720, y: 0 },
      size: { width: 280, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 3,
      },
      type: "PROMPT",
      prompt:
        "Implement selected checklist task {{data:select-next-task:task}} from JSON checklist {{checklistFile:path=.machdoch/feature-implementation/current-feature.checklist.json}} using checklist content {{data:specification-checklist:output}} or resumed checklist {{data:read-checklist:json}}, research {{summary:initial-research}}, git baseline {{result:git-snapshot-before}}, detected commands {{result:detect-project-commands}}, pass count {{result:count-implementation-pass}}, and latest validation feedback {{result:validate-progress}}. Apply source-backed guidance for version-sensitive APIs or standards, keep changes scoped to {{implementationScope:text=auto-detect}}, follow existing project patterns, apply design guidelines {{designGuidelines:text=}}, follow auth instructions {{authInstructions:text=}}, update tests when relevant, and update the selected task/checklist JSON statuses and resume notes only when work is actually done.",
    },
    {
      id: "count-implementation-pass",
      title: "Count Implementation Pass",
      position: { x: 2720, y: 240 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        counterName:
          "feature-implementation-checklist-loop.implementation-pass.{{data:select-next-task:task.id}}.{{data:select-next-task:index}}",
        maxAttempts: "{{maxImplementationPasses:number=8}}",
      },
    },
    {
      id: "verification-decision",
      title: "Run Verification?",
      position: { x: 3060, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "Boolean(variables.verificationCommand?.trim() || context.resultsByBlock?.['detect-project-commands']?.data?.verificationCommand?.trim())",
        },
      },
    },
    {
      id: "run-configured-checks",
      title: "Run Verification",
      position: { x: 3380, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{verificationCommand:text=}}",
        fallbackCommand: "{{data:detect-project-commands:verificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "visual-decision",
      title: "Run Visual Review?",
      position: { x: 3380, y: 120 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'variables.enableVisualReview === "true" && (Boolean(variables.targetUrl?.trim()) || Boolean(variables.screenshotPath?.trim()))',
        },
      },
    },
    {
      id: "visual-analysis",
      title: "Visual Review",
      position: { x: 3720, y: 20 },
      size: { width: 280, height: 190 },
      type: "UTILITY",
      utility: {
        type: "UI_ANALYZE",
        adapter: "auto",
        targetUrl: "{{targetUrl:url=}}",
        screenshotPath: "{{screenshotPath:path=}}",
        server: {
          mode: "existing",
          healthUrl: "{{healthUrl:url=}}",
        },
        checks: {
          screenshots: true,
          accessibility: true,
          console: true,
          network: true,
          responsive: true,
        },
        viewports: [
          { name: "desktop", width: 1280, height: 900 },
          { name: "tablet", width: 768, height: 1024 },
          { name: "mobile", width: 390, height: 844 },
          { name: "small-mobile", width: 320, height: 568 },
        ],
        timeoutSeconds: 30,
        fullPage: true,
        waitUntil: "domcontentloaded",
      },
    },
    {
      id: "git-diff-summary",
      title: "Git Diff Summary",
      position: { x: 3890, y: -200 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_DIFF_SUMMARY",
        cwd: ".",
        outputPath:
          "{{gitDiffFile:path=.machdoch/feature-implementation/git-diff.json}}",
      },
    },
    {
      id: "validate-progress",
      title: "Validate Progress",
      position: { x: 4060, y: 0 },
      size: { width: 300, height: 238 },
      type: "UTILITY",
      utility: {
        type: "VALIDATOR_JSON",
        maxAttempts: 2,
        prompt:
          "Validate implementation against JSON checklist {{checklistFile:path=.machdoch/feature-implementation/current-feature.checklist.json}}, selected task {{data:select-next-task:task}}, feature request, acceptance criteria, research, interview, verification result {{result:run-configured-checks}}, git diff {{result:git-diff-summary}}, and visual review {{result:visual-analysis}} when present. Judge only the active feature, selected task, checklist file, resume notes, and required adjacent tests/docs/imports. Ignore unrelated workspace changes outside that feature/task unless they directly break verification or acceptance criteria. Confirm done tasks are truly implemented, tests are meaningful or justified, optional checks were skipped only because configuration disabled them or required inputs were blank, and resume notes are current. Return JSON decision DONE when all checklist tasks are done and acceptance criteria pass. Return CONTINUE when more work remains. Return RETRY when the last pass needs correction. Return ERROR when blocked by missing context, unsafe changes in the active feature/task, failing verification that cannot be fixed, or repeated ambiguity. Include confidence, summary, evidence, and remainingWork.",
      },
    },
    {
      id: "final-report",
      title: "Final Feature Report",
      position: { x: 4380, y: -180 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{featureReportFile:path=.machdoch/feature-implementation/final-report.json}}",
        outputPath:
          "{{featureReportMarkdown:path=.machdoch/feature-implementation/final-report.md}}",
      },
    },
    {
      id: "complete",
      title: "Complete",
      position: { x: 4400, y: 0 },
      size: { width: 256, height: 114 },
      type: "END",
      status: "success",
    },
    {
      id: "blocked",
      title: "Blocked",
      position: { x: 1060, y: 240 },
      size: { width: 256, height: 114 },
      type: "END",
      status: "failed",
    },
  ],
  edges: [
    { id: "start-to-detect-commands", from: "start", fromOutput: "SUCCESS", to: "detect-project-commands" },
    { id: "detect-commands-to-checklist-exists", from: "detect-project-commands", fromOutput: "SUCCESS", to: "checklist-exists" },
    { id: "detect-commands-empty-to-checklist-exists", from: "detect-project-commands", fromOutput: "EMPTY", to: "checklist-exists" },
    { id: "detect-commands-error-to-checklist-exists", from: "detect-project-commands", fromOutput: "ERROR", to: "checklist-exists" },
    { id: "checklist-exists-read", from: "checklist-exists", fromOutput: "EXISTS", to: "read-checklist" },
    { id: "checklist-missing-to-brief", from: "checklist-exists", fromOutput: "MISSING", to: "prepare-feature-brief" },
    { id: "checklist-exists-error-to-brief", from: "checklist-exists", fromOutput: "ERROR", to: "prepare-feature-brief" },
    { id: "read-checklist-to-brief", from: "read-checklist", fromOutput: "SUCCESS", to: "prepare-feature-brief" },
    { id: "read-checklist-invalid-to-brief", from: "read-checklist", fromOutput: "INVALID", to: "prepare-feature-brief" },
    { id: "read-checklist-error-to-brief", from: "read-checklist", fromOutput: "ERROR", to: "prepare-feature-brief" },
    { id: "read-checklist-not-found-to-brief", from: "read-checklist", fromOutput: "NOT_FOUND", to: "prepare-feature-brief" },
    { id: "brief-to-research-decision", from: "prepare-feature-brief", fromOutput: "SUCCESS", to: "research-decision" },
    { id: "brief-error", from: "prepare-feature-brief", fromOutput: "ERROR", to: "blocked" },
    { id: "research-decision-run", from: "research-decision", fromOutput: "MATCH", to: "initial-research" },
    { id: "research-decision-skip", from: "research-decision", fromOutput: "NO_MATCH", to: "interview-decision" },
    { id: "research-decision-error", from: "research-decision", fromOutput: "ERROR", to: "interview-decision" },
    { id: "research-to-interview-decision", from: "initial-research", fromOutput: "SUCCESS", to: "interview-decision" },
    { id: "research-error-to-interview-decision", from: "initial-research", fromOutput: "ERROR", to: "interview-decision" },
    { id: "interview-decision-run", from: "interview-decision", fromOutput: "MATCH", to: "interview-user" },
    { id: "interview-decision-skip", from: "interview-decision", fromOutput: "NO_MATCH", to: "specification-checklist" },
    { id: "interview-decision-error", from: "interview-decision", fromOutput: "ERROR", to: "specification-checklist" },
    { id: "interview-done-to-specification", from: "interview-user", fromOutput: "DONE", to: "specification-checklist" },
    { id: "interview-incomplete-to-specification", from: "interview-user", fromOutput: "INCOMPLETE", to: "specification-checklist" },
    { id: "interview-cancelled", from: "interview-user", fromOutput: "CANCELLED", to: "specification-checklist" },
    { id: "interview-error", from: "interview-user", fromOutput: "ERROR", to: "blocked" },
    { id: "specification-to-select-task", from: "specification-checklist", fromOutput: "SUCCESS", to: "select-next-task" },
    { id: "specification-invalid", from: "specification-checklist", fromOutput: "INVALID", to: "blocked" },
    { id: "specification-error", from: "specification-checklist", fromOutput: "ERROR", to: "blocked" },
    { id: "select-task-to-snapshot", from: "select-next-task", fromOutput: "SELECTED", to: "git-snapshot-before" },
    { id: "select-task-empty-to-validate", from: "select-next-task", fromOutput: "EMPTY", to: "validate-progress" },
    { id: "select-task-not-found", from: "select-next-task", fromOutput: "NOT_FOUND", to: "blocked" },
    { id: "select-task-invalid", from: "select-next-task", fromOutput: "INVALID", to: "blocked" },
    { id: "select-task-error", from: "select-next-task", fromOutput: "ERROR", to: "blocked" },
    { id: "snapshot-to-count-implementation-pass", from: "git-snapshot-before", fromOutput: "SUCCESS", to: "count-implementation-pass" },
    { id: "snapshot-error-to-count-implementation-pass", from: "git-snapshot-before", fromOutput: "ERROR", to: "count-implementation-pass" },
    { id: "count-implementation-pass-continue", from: "count-implementation-pass", fromOutput: "CONTINUE", to: "implement-feature" },
    { id: "count-implementation-pass-limit", from: "count-implementation-pass", fromOutput: "LIMIT_REACHED", to: "blocked" },
    { id: "count-implementation-pass-error", from: "count-implementation-pass", fromOutput: "ERROR", to: "blocked" },
    { id: "implementation-to-verification-decision", from: "implement-feature", fromOutput: "SUCCESS", to: "verification-decision" },
    { id: "implementation-error", from: "implement-feature", fromOutput: "ERROR", to: "blocked" },
    { id: "verification-decision-run", from: "verification-decision", fromOutput: "MATCH", to: "run-configured-checks" },
    { id: "verification-decision-skip", from: "verification-decision", fromOutput: "NO_MATCH", to: "visual-decision" },
    { id: "verification-decision-error", from: "verification-decision", fromOutput: "ERROR", to: "visual-decision" },
    { id: "checks-success-to-visual-decision", from: "run-configured-checks", fromOutput: "SUCCESS", to: "visual-decision" },
    { id: "checks-failed-to-visual-decision", from: "run-configured-checks", fromOutput: "FAILED", to: "visual-decision" },
    { id: "checks-error-to-visual-decision", from: "run-configured-checks", fromOutput: "ERROR", to: "visual-decision" },
    { id: "visual-decision-run", from: "visual-decision", fromOutput: "MATCH", to: "visual-analysis" },
    { id: "visual-decision-skip", from: "visual-decision", fromOutput: "NO_MATCH", to: "git-diff-summary" },
    { id: "visual-decision-error", from: "visual-decision", fromOutput: "ERROR", to: "git-diff-summary" },
    { id: "visual-success-to-diff", from: "visual-analysis", fromOutput: "SUCCESS", to: "git-diff-summary" },
    { id: "visual-unavailable-to-diff", from: "visual-analysis", fromOutput: "UNAVAILABLE", to: "git-diff-summary" },
    { id: "visual-error-to-diff", from: "visual-analysis", fromOutput: "ERROR", to: "git-diff-summary" },
    { id: "git-diff-success-to-validate", from: "git-diff-summary", fromOutput: "SUCCESS", to: "validate-progress" },
    { id: "git-diff-empty-to-validate", from: "git-diff-summary", fromOutput: "EMPTY", to: "validate-progress" },
    { id: "git-diff-error-to-validate", from: "git-diff-summary", fromOutput: "ERROR", to: "validate-progress" },
    { id: "validation-done", from: "validate-progress", fromOutput: "DONE", to: "final-report" },
    { id: "validation-continue", from: "validate-progress", fromOutput: "CONTINUE", to: "select-next-task" },
    { id: "validation-retry", from: "validate-progress", fromOutput: "RETRY", to: "select-next-task" },
    { id: "validation-error", from: "validate-progress", fromOutput: "ERROR", to: "blocked" },
    { id: "validation-invalid", from: "validate-progress", fromOutput: "INVALID", to: "blocked" },
    { id: "report-success-to-complete", from: "final-report", fromOutput: "SUCCESS", to: "complete" },
    { id: "report-error-to-complete", from: "final-report", fromOutput: "ERROR", to: "complete" },
  ],
};

export const featureImplementationChecklistLoopStarterFlow = {
  id: "full-feature-implementation",
  version: 7,
  defaultAlias: "feature-implementation-checklist-loop",
  category: "Implementation",
  tags: ["feature", "research", "visual-check"],
  flow: fullFeatureImplementationFlow,
} as const satisfies RalphStarterFlow;
