import type { RalphFlow } from "../ralph.js";
import type { RalphStarterFlow } from "../ralph-starter-flows.js";

const RALPH_REFACTOR_AGENT_TIMEOUT_SECONDS = 60 * 60;
const RALPH_REFACTOR_VALIDATION_COMMAND_TIMEOUT_SECONDS = 30 * 60;

const RALPH_VALIDATOR_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["decision", "confidence", "summary", "evidence", "remainingWork"],
  properties: {
    decision: { type: "string", enum: ["DONE", "CONTINUE", "RETRY", "ERROR"] },
    confidence: { type: "number", minimum: 0, maximum: 1 },
    summary: { type: "string" },
    evidence: { type: "array", items: { type: "string" }, maxItems: 30 },
    remainingWork: { type: "array", items: { type: "string" }, maxItems: 30 },
  },
} as const;

const autonomousRefactoringFlow: RalphFlow = {
  schemaVersion: 1,
  id: "starter-autonomous-refactoring-flow",
  alias: "repository-refactor-validation-loop",
  name: "Repository Refactor & Validation Loop",
  description:
    "Bounded autonomous refactor cycle that scores dependency-aware packages from coupling, churn, complexity, and testability evidence, then validates and defers exhausted scopes without human intervention.",
  settings: {
    maxTransitions: 240,
    autonomy: {
      recoverFailedEnd: true,
      maxRecoveryAttempts: 3,
      transitionExhaustion: "checkpoint",
      recoveryExhaustion: "defer",
      deferToBlockId: "defer-scope",
    },
  },
  variables: [
    { name: "scopeRoot", type: "path", default: ".", required: false },
    { name: "scopeSelectionStrategy", type: "text", default: "priority", required: false },
    { name: "scopeRegistryFile", type: "path", default: ".machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.json", required: false },
    { name: "scopeRegistryMarkdown", type: "path", default: ".machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.md", required: false },
    { name: "scopeScanMaxDepth", type: "number", default: "4", required: false },
    { name: "scopeScanMaxResults", type: "number", default: "200", required: false },
    { name: "refactorObjective", type: "text", default: "Improve maintainability while preserving behavior.", required: false },
    { name: "fileNamingPolicy", type: "text", default: "Follow existing framework and repository conventions.", required: false },
    { name: "maxFileLines", type: "number", default: "500", required: false },
    { name: "helperPlacementPolicy", type: "text", default: "Follow existing module-local and shared helper conventions.", required: false },
    { name: "testFramework", type: "text", default: "auto-detect", required: false },
    { name: "enableOnlineResearch", type: "boolean", default: "true", required: false },
    { name: "validationCommand", type: "text", default: "", required: false },
    { name: "excludePaths", type: "text", default: "node_modules, dist, build, coverage, target, .next, .nuxt, .turbo, .cache, vendor, generated", required: false },
    { name: "allowPublicApiChanges", type: "boolean", default: "true", required: false },
    { name: "allowDependencyChanges", type: "boolean", default: "true", required: false },
    { name: "allowSchemaChanges", type: "boolean", default: "true", required: false },
    { name: "notesFile", type: "path", default: ".machdoch/ralph/refactor/RALPH_REFACTOR_NOTES.md", required: false },
    { name: "maxRefactorPasses", type: "number", default: "5", required: false },
    { name: "maxVerificationRepairPasses", type: "number", default: "3", required: false },
    { name: "projectCommandsFile", type: "path", default: "{{run:artifactRoot}}/refactor/project-commands.json", required: false },
    { name: "refactorPlanFile", type: "path", default: "{{run:artifactRoot}}/refactor/refactor-plan.json", required: false },
    { name: "gitSnapshotFile", type: "path", default: "{{run:artifactRoot}}/refactor/git-snapshot.json", required: false },
    { name: "gitDiffFile", type: "path", default: "{{run:artifactRoot}}/refactor/git-diff.json", required: false },
    { name: "refactorReportFile", type: "path", default: "{{run:artifactRoot}}/refactor/final-report.json", required: false },
    { name: "refactorReportMarkdown", type: "path", default: "{{run:artifactRoot}}/refactor/final-report.md", required: false },
    { name: "refactorOutcomesFile", type: "path", default: ".machdoch/ralph/refactor/outcomes.jsonl", required: false },
  ],
  blocks: [
    {
      id: "start",
      title: "Start",
      position: { x: 0, y: 0 },
      size: { width: 256, height: 140 },
      type: "START",
    },
    {
      id: "scan-scopes",
      title: "Scan Scope Evidence",
      position: { x: 700, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SCAN_SCOPE_EVIDENCE",
        rootPath: "{{scopeRoot:path=.}}",
        excludePaths: "{{excludePaths:text=node_modules, dist, build, coverage, target, .next, .nuxt, .turbo, .cache, vendor, generated}}",
        maxDepth: "{{scopeScanMaxDepth:number=4}}",
        maxResults: "{{scopeScanMaxResults:number=200}}",
      },
    },
    {
      id: "update-scope-registry",
      title: "Update Scope Registry",
      position: { x: 1040, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "UPDATE_SCOPE_REGISTRY",
        flowAlias: "repository-refactor-validation-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.md}}",
        strategy: "{{scopeSelectionStrategy:text=priority}}",
        includeMarkdown: true,
      },
    },
    {
      id: "select-scope",
      title: "Select Refactor Scope",
      position: { x: 1380, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SELECT_SCOPE",
        flowAlias: "repository-refactor-validation-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.json}}",
        strategy: "{{scopeSelectionStrategy:text=priority}}",
      },
    },
    {
      id: "detect-project-commands",
      title: "Detect Project Commands",
      position: { x: 1720, y: -260 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "DETECT_PROJECT_COMMANDS",
        rootPath: "{{data:select-scope:scope.paths.0}}",
        outputPath:
          "{{projectCommandsFile:path=.machdoch/ralph/refactor/project-commands.json}}",
      },
    },
    {
      id: "propose-refactor-packages",
      title: "Propose Refactor Portfolio",
      position: { x: 1880, y: -40 },
      size: { width: 320, height: 250 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 2,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        maxAttempts: 2,
        schema: {
          type: "object",
          additionalProperties: false,
          required: ["projectConstitution", "candidates", "researchDecision"],
          properties: {
            projectConstitution: {
              type: "object",
              additionalProperties: false,
              required: ["architecture", "publicContracts", "conventions", "qualityPriorities", "constraints"],
              properties: {
                architecture: { type: "array", items: { type: "string" } },
                publicContracts: { type: "array", items: { type: "string" } },
                conventions: { type: "array", items: { type: "string" } },
                qualityPriorities: { type: "array", items: { type: "string" } },
                constraints: { type: "array", items: { type: "string" } },
              },
            },
            candidates: {
              type: "array",
              minItems: 1,
              maxItems: 5,
              items: {
                type: "object",
                additionalProperties: false,
                required: ["id", "title", "evidence", "maintainabilityScore", "confidenceScore", "effortScore", "riskScore", "files"],
                properties: {
                  id: { type: "string" },
                  title: { type: "string" },
                  evidence: { type: "array", items: { type: "string" } },
                  maintainabilityScore: { type: "number", minimum: 0, maximum: 100 },
                  confidenceScore: { type: "number", minimum: 0, maximum: 100 },
                  effortScore: { type: "number", minimum: 0, maximum: 100 },
                  riskScore: { type: "number", minimum: 0, maximum: 100 },
                  files: { type: "array", items: { type: "string" } },
                },
              },
            },
            researchDecision: {
              type: "object",
              additionalProperties: false,
              required: ["needsResearch", "reason", "queries"],
              properties: {
                needsResearch: { type: "boolean" },
                reason: { type: "string" },
                queries: { type: "array", items: { type: "string" } },
              },
            },
          },
        },
        prompt:
          "Inspect selected dependency-aware scope {{result:select-scope}} and detected commands {{result:detect-project-commands}} without editing files. Infer a concise project constitution, then generate 3-5 materially different cohesive refactor packages. Score each from 0-100 for maintainability leverage, evidence confidence, effort, and risk. Prioritize coupling, dependency topology, change frequency, duplicated behavior, test ownership, complexity, runtime errors, coverage gaps, and TODO/failure evidence; file length is only a supporting signal. Identify focused research needed to discriminate among leading candidates. Make bounded reversible architectural assumptions autonomously and return only schema-valid JSON.",
      },
    },
    {
      id: "research-decision",
      title: "Use Online Research?",
      position: { x: 2060, y: -420 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'variables.enableOnlineResearch === "true" && lastData?.output?.researchDecision?.needsResearch === true',
        },
      },
    },
    {
      id: "refactor-research",
      title: "Refactor Research",
      position: { x: 2400, y: -420 },
      size: { width: 300, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        webAccess: true,
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Use content enrichment only for research decision in provisional refactor portfolio {{data:propose-refactor-packages:output}}. If search_web is available, run focused searches for current framework/library refactor guidance, official migration/deprecation notes, testing guidance, codemod recommendations, lint/type-check guidance, and architecture conventions that discriminate among leading candidates. Use fetch_url on the best official or maintainer pages before relying on them, and inspect local package/config metadata for version assumptions. Keep findings concise with source links, version/date assumptions, safe refactor constraints, anti-patterns, and which candidates should be promoted, revised, or rejected. If web search is unavailable, say so and base findings on local repository evidence plus any provided URLs.",
    },
    {
      id: "audit-against-policy",
      title: "Audit Against Policy",
      position: { x: 2060, y: 0 },
      size: { width: 280, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{refactorPlanFile:path=.machdoch/ralph/refactor/refactor-plan.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: [
            "outcome",
            "outcomeReason",
            "objective",
            "scope",
            "conventions",
            "researchDecision",
            "passes",
            "risks",
            "verification",
            "verificationTier",
            "reviewTier",
          ],
          properties: {
            outcome: { type: "string", enum: ["IMPLEMENT", "STOP", "DEFER"] },
            outcomeReason: { type: "string" },
            objective: { type: "string" },
            scope: {
              type: "object",
              required: ["id", "title", "kind", "paths", "risk", "rationale"],
              properties: {
                id: { type: "string" },
                title: { type: "string" },
                kind: { type: "string" },
                paths: { type: "array", items: { type: "string" } },
                relatedScopeIds: { type: "array", items: { type: "string" } },
                risk: { type: "string", enum: ["low", "medium", "high"] },
                rationale: { type: "array", items: { type: "string" } },
              },
            },
            conventions: {
              type: "object",
              required: ["sourceRoots", "testFramework", "naming", "helperPlacement", "publicApiBoundaries", "exclusions"],
              properties: {
                sourceRoots: { type: "array", items: { type: "string" } },
                testFramework: { type: "string" },
                naming: {
                  type: "object",
                  required: ["files", "symbols", "tests"],
                  properties: {
                    files: { type: "string" },
                    symbols: { type: "string" },
                    tests: { type: "string" },
                    examples: { type: "array", items: { type: "string" } },
                    exceptions: { type: "array", items: { type: "string" } },
                  },
                },
                helperPlacement: { type: "array", items: { type: "string" } },
                publicApiBoundaries: { type: "array", items: { type: "string" } },
                exclusions: { type: "array", items: { type: "string" } },
              },
            },
            researchDecision: {
              type: "object",
              required: ["needsResearch", "reason", "queries"],
              properties: {
                needsResearch: { type: "boolean" },
                reason: { type: "string" },
                queries: { type: "array", items: { type: "string" } },
              },
            },
            passes: {
              type: "array",
              items: {
                type: "object",
                required: ["title", "files", "actions"],
                properties: {
                  title: { type: "string" },
                  files: { type: "array", items: { type: "string" } },
                  actions: { type: "array", items: { type: "string" } },
                  acceptanceCriteria: { type: "array", items: { type: "string" } },
                },
              },
            },
            risks: { type: "array", items: { type: "string" } },
            verification: { type: "array", items: { type: "string" } },
            verificationTier: { type: "string", enum: ["focused", "standard", "broad"] },
            reviewTier: { type: "string", enum: ["validator-only", "strict"] },
          },
        },
        prompt:
          "Refine, rescore, and select from provisional refactor portfolio {{data:propose-refactor-packages:output}} after focused research {{summary:refactor-research}}. Inspect selected scope {{result:select-scope}} without editing files. Prioritize coupling, complexity, churn, duplication, test ownership, runtime failures, coverage, and dependency boundaries over raw line count; security-only hardening is low priority in this nonsecurity refactor flow. Return outcome IMPLEMENT with tightly related passes for the highest-leverage evidence-backed package, STOP with passes [] when no meaningful package remains, or DEFER with passes [] only for unavailable external state. Include outcomeReason. Public APIs, dependencies, schemas, and migrations may change when required and verified. Make bounded reversible assumptions without human approval and return only schema-valid JSON.",
      },
    },
    {
      id: "has-actionable-refactor",
      title: "Actionable Refactor?",
      position: { x: 2280, y: 180 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "context.resultsByBlock?.['audit-against-policy']?.data?.output?.outcome === 'IMPLEMENT' && Array.isArray(context.resultsByBlock?.['audit-against-policy']?.data?.output?.passes) && context.resultsByBlock['audit-against-policy'].data.output.passes.length > 0",
        },
      },
    },
    {
      id: "selection-is-deferred",
      title: "Refactor Selection Deferred?",
      position: { x: 2440, y: 300 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "context.resultsByBlock?.['audit-against-policy']?.data?.output?.outcome === 'DEFER'",
        },
      },
    },
    {
      id: "git-snapshot-before",
      title: "Git Snapshot",
      position: { x: 2280, y: -180 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_SNAPSHOT",
        cwd: ".",
        outputPath:
          "{{gitSnapshotFile:path=.machdoch/ralph/refactor/git-snapshot.json}}",
      },
    },
    {
      id: "refactor-pass",
      title: "Refactor Pass",
      position: { x: 2400, y: 0 },
      size: { width: 280, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 2,
        timeoutSeconds: RALPH_REFACTOR_AGENT_TIMEOUT_SECONDS,
      },
      type: "PROMPT",
      prompt:
        "Apply one cohesive refactor package in selected scope cluster {{result:select-scope}} using structured conventions {{data:audit-against-policy:output.conventions}}, refactor plan, research, git/validation baselines, pass count, validation routing, scope guard {{result:scope-change-guard}}, and latest feedback. Complete the related pass set before stopping. Follow objective {{refactorObjective:text=Improve maintainability while preserving behavior.}}, naming policy {{fileNamingPolicy:text=Follow existing framework and repository conventions.}}, max-lines advisory {{maxFileLines:number=500}}, helper placement {{helperPlacementPolicy:text=Follow existing module-local and shared helper conventions.}}, and test framework {{testFramework:text=auto-detect}}. Public API changes use allowPublicApiChanges={{allowPublicApiChanges:boolean=true}}, dependencies use allowDependencyChanges={{allowDependencyChanges:boolean=true}}, and schemas/migrations use allowSchemaChanges={{allowSchemaChanges:boolean=true}} when justified and verified. Security-only hardening is low priority here. Repair only new/worsened failures, make bounded reversible decisions, update consumers/tests, and avoid broad formatting sweeps.",
    },
    {
      id: "count-refactor-pass",
      title: "Count Refactor Pass",
      position: { x: 2400, y: -180 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        counterName:
          "repository-refactor-validation-loop.refactor-pass.{{data:select-scope:scope.id}}",
        maxAttempts: "{{maxRefactorPasses:number=5}}",
      },
    },
    {
      id: "validation-decision",
      title: "Run Validation?",
      position: { x: 2740, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "Boolean(context.resultsByBlock?.['select-validation-command']?.data?.output?.command?.trim())",
        },
      },
    },
    {
      id: "baseline-validation",
      title: "Record Validation Baseline",
      position: { x: 2400, y: -360 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{validationCommand:text=}}",
        fallbackCommand: "{{data:detect-project-commands:focusedVerificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: RALPH_REFACTOR_VALIDATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "select-validation-command",
      title: "Select Validation Tier",
      position: { x: 2740, y: -180 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "TRANSFORM_JSON",
        input: "{}",
        expression:
          "(() => { const plan = context.resultsByBlock?.get?.('audit-against-policy')?.data?.output ?? {}; const commands = context.resultsByBlock?.get?.('detect-project-commands')?.data ?? {}; const requestedTier = String(plan.verificationTier ?? '').toLowerCase(); const requestedReviewTier = String(plan.reviewTier ?? '').toLowerCase(); const riskText = JSON.stringify([plan.risks, plan.passes, plan.scope, plan.conventions]).toLowerCase(); const highRisk = /(security|auth|token|secret|permission|database|migration|schema|ipc|api|dependency|package|lockfile|persistence|public api|contract|config|cross-package)/u.test(riskText); const tier = highRisk || requestedTier === 'broad' || requestedTier === 'strict' ? 'broad' : requestedTier === 'standard' ? 'standard' : 'focused'; const detectedCommand = tier === 'broad' ? commands.broadVerificationCommand : tier === 'standard' ? commands.standardVerificationCommand : commands.focusedVerificationCommand; const command = (variables.validationCommand ?? '').trim() || detectedCommand || commands.verificationCommand || ''; const reviewTier = highRisk || requestedReviewTier === 'strict' || tier === 'broad' ? 'strict' : 'validator-only'; return { tier, command, reviewTier, highRisk, source: (variables.validationCommand ?? '').trim() ? 'variable' : 'detected', focusedCommand: commands.focusedVerificationCommand || '', standardCommand: commands.standardVerificationCommand || '', broadCommand: commands.broadVerificationCommand || '' }; })()",
      },
    },
    {
      id: "run-validation-checks",
      title: "Run Validation",
      position: { x: 3060, y: -95 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{data:select-validation-command:output.command}}",
        fallbackCommand: "{{data:detect-project-commands:focusedVerificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: RALPH_REFACTOR_VALIDATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "count-verification-repair",
      title: "Count Verification Repair",
      position: { x: 3400, y: 300 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        counterName:
          "repository-refactor-validation-loop.verification-repair.{{data:select-scope:scope.id}}",
        maxAttempts: "{{maxVerificationRepairPasses:number=3}}",
      },
    },
    {
      id: "fix-validation-failures",
      title: "Fix Validation Failures",
      position: { x: 3400, y: 95 },
      size: { width: 280, height: 190 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 1,
        timeoutSeconds: RALPH_REFACTOR_AGENT_TIMEOUT_SECONDS,
      },
      type: "PROMPT",
      prompt:
        "Fix validation failures from {{result:run-validation-checks}} that were caused by the current refactor package, comparing signatures with pre-change baseline {{result:baseline-validation}}. Repair only new or worsened failures, keep changes scoped to selected scope cluster {{result:select-scope}}, preserve intended behavior, and update consumers/tests/imports/exports as needed. If validation is unavailable, document that in {{notesFile:path=.machdoch/ralph/refactor/RALPH_REFACTOR_NOTES.md}} and continue.",
    },
    {
      id: "git-diff-summary",
      title: "Git Diff Summary",
      position: { x: 3400, y: -330 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_DIFF_SUMMARY",
        cwd: ".",
        outputPath: "{{gitDiffFile:path=.machdoch/ralph/refactor/git-diff.json}}",
      },
    },
    {
      id: "final-refactor-scan",
      title: "Final Refactor Scan",
      position: { x: 3400, y: -150 },
      size: { width: 300, height: 238 },
      type: "UTILITY",
      settings: {
        timeoutSeconds: RALPH_REFACTOR_AGENT_TIMEOUT_SECONDS,
      },
      utility: {
        type: "VALIDATOR_JSON",
        maxAttempts: 2,
        schema: RALPH_VALIDATOR_SCHEMA,
        prompt:
          "Validate the cohesive refactor package for selected scope {{result:select-scope}} against conventions, plan, validation routing/result, scope guard {{result:scope-change-guard}}, git diff, notes, tests, public contracts, and exclusions. Ignore unrelated changes. Return DONE only when the package is complete, in scope, behavior-preserving as intended, and has no new/worsened failure; CONTINUE for bounded work; RETRY for own regressions; ERROR only for unavailable external state or repeated non-progress. Include confidence, summary, evidence, and remainingWork.",
      },
    },
    {
      id: "final-report",
      title: "Final Refactor Report",
      position: { x: 3740, y: -220 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{refactorReportFile:path=.machdoch/ralph/refactor/final-report.json}}",
        outputPath:
          "{{refactorReportMarkdown:path=.machdoch/ralph/refactor/final-report.md}}",
      },
    },
    {
      id: "mark-scope-result",
      title: "Mark Scope Result",
      position: { x: 3740, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "repository-refactor-validation-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.md}}",
        result: "DONE",
        includeMarkdown: true,
      },
    },
    {
      id: "retained-outcome-report",
      title: "Retained Refactor Outcome Report",
      position: { x: 3740, y: -420 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{refactorReportFile:path=.machdoch/ralph/refactor/final-report.json}}",
        outputPath:
          "{{refactorReportMarkdown:path=.machdoch/ralph/refactor/final-report.md}}",
      },
    },
    {
      id: "scope-change-guard",
      title: "Guard Refactor Scope",
      position: { x: 3560, y: -420 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CHANGE_SCOPE_GUARD",
        input:
          "{\"scope\":{{data:select-scope:scope}},\"gitSummary\":{{data:git-diff-summary}}}",
      },
    },
    {
      id: "defer-scope",
      title: "Defer Exhausted Refactor",
      position: { x: 3740, y: 220 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "repository-refactor-validation-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.md}}",
        result: "DEFERRED_AFTER_BOUNDED_REPAIR",
        includeMarkdown: true,
      },
    },
    {
      id: "mark-stop-scope",
      title: "Mark No-Action Refactor Scope",
      position: { x: 3740, y: 400 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "repository-refactor-validation-loop",
        registryPath: "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.json}}",
        outputPath: "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.md}}",
        result: "STOP_NO_MEANINGFUL_WORK",
        includeMarkdown: true,
      },
    },
    {
      id: "mark-invalid-scope",
      title: "Mark Invalid Refactor Scope",
      position: { x: 3740, y: 580 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "repository-refactor-validation-loop",
        registryPath: "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.json}}",
        outputPath: "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.md}}",
        result: "INVALID_OUTPUT",
        includeMarkdown: true,
      },
    },
    {
      id: "record-done-outcome",
      title: "Record Completed Refactor Outcome",
      position: { x: 4080, y: -260 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: { type: "APPEND_JSONL", path: "{{refactorOutcomesFile:path=.machdoch/ralph/refactor/outcomes.jsonl}}", input: "{\"outcome\":\"DONE\",\"scopeRoot\":\"{{scopeRoot:path=.}}\"}" },
    },
    {
      id: "record-deferred-outcome",
      title: "Record Deferred Refactor Outcome",
      position: { x: 4080, y: 180 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: { type: "APPEND_JSONL", path: "{{refactorOutcomesFile:path=.machdoch/ralph/refactor/outcomes.jsonl}}", input: "{\"outcome\":\"DEFER\",\"scopeRoot\":\"{{scopeRoot:path=.}}\"}" },
    },
    {
      id: "record-stop-outcome",
      title: "Record No-Action Refactor Outcome",
      position: { x: 4080, y: 380 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: { type: "APPEND_JSONL", path: "{{refactorOutcomesFile:path=.machdoch/ralph/refactor/outcomes.jsonl}}", input: "{\"outcome\":\"STOP\",\"scopeRoot\":\"{{scopeRoot:path=.}}\"}" },
    },
    {
      id: "record-invalid-outcome",
      title: "Record Invalid Refactor Outcome",
      position: { x: 4080, y: 580 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: { type: "APPEND_JSONL", path: "{{refactorOutcomesFile:path=.machdoch/ralph/refactor/outcomes.jsonl}}", input: "{\"outcome\":\"INVALID\",\"scopeRoot\":\"{{scopeRoot:path=.}}\"}" },
    },
    {
      id: "scope-cycle-complete",
      title: "Scope Cycle Complete?",
      position: { x: 4080, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "['EMPTY', 'ERROR'].includes(String(context.resultsByBlock?.['scan-scopes']?.output ?? '')) || context.resultsByBlock?.['select-scope']?.output === 'EMPTY' || ['mark-scope-result', 'defer-scope', 'mark-stop-scope', 'mark-invalid-scope'].some((id) => context.resultsByBlock?.[id]?.data?.cycleCompleted === true)",
        },
      },
    },
    {
      id: "success",
      title: "Refactor Complete",
      position: { x: 4420, y: 0 },
      size: { width: 256, height: 114 },
      type: "END",
      status: "success",
    },
    {
      id: "deferred",
      title: "Refactor Outcome Retained for Retry",
      position: { x: 4420, y: 300 },
      size: { width: 280, height: 114 },
      type: "END",
      status: "success",
    },
  ],
  edges: [
    { id: "start-to-scan-scopes", from: "start", fromOutput: "SUCCESS", to: "scan-scopes" },
    { id: "scan-scopes-to-update", from: "scan-scopes", fromOutput: "SUCCESS", to: "update-scope-registry" },
    { id: "scan-scopes-empty", from: "scan-scopes", fromOutput: "EMPTY", to: "record-stop-outcome" },
    { id: "scan-scopes-error", from: "scan-scopes", fromOutput: "ERROR", to: "record-invalid-outcome" },
    { id: "update-registry-to-select", from: "update-scope-registry", fromOutput: "SUCCESS", to: "select-scope" },
    { id: "update-registry-empty", from: "update-scope-registry", fromOutput: "EMPTY", to: "record-stop-outcome" },
    { id: "update-registry-error", from: "update-scope-registry", fromOutput: "ERROR", to: "record-invalid-outcome" },
    { id: "select-scope-to-detect-commands", from: "select-scope", fromOutput: "SELECTED", to: "detect-project-commands" },
    { id: "select-scope-empty", from: "select-scope", fromOutput: "EMPTY", to: "record-stop-outcome" },
    { id: "select-scope-error", from: "select-scope", fromOutput: "ERROR", to: "record-invalid-outcome" },
    { id: "detect-commands-to-propose", from: "detect-project-commands", fromOutput: "SUCCESS", to: "propose-refactor-packages" },
    { id: "detect-commands-empty-to-propose", from: "detect-project-commands", fromOutput: "EMPTY", to: "propose-refactor-packages" },
    { id: "detect-commands-error-to-propose", from: "detect-project-commands", fromOutput: "ERROR", to: "propose-refactor-packages" },
    { id: "propose-to-research-decision", from: "propose-refactor-packages", fromOutput: "SUCCESS", to: "research-decision" },
    { id: "propose-invalid", from: "propose-refactor-packages", fromOutput: "INVALID", to: "mark-invalid-scope" },
    { id: "propose-error", from: "propose-refactor-packages", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "research-decision-run", from: "research-decision", fromOutput: "MATCH", to: "refactor-research" },
    { id: "research-decision-skip", from: "research-decision", fromOutput: "NO_MATCH", to: "audit-against-policy" },
    { id: "research-decision-error", from: "research-decision", fromOutput: "ERROR", to: "audit-against-policy" },
    { id: "research-to-refine", from: "refactor-research", fromOutput: "SUCCESS", to: "audit-against-policy" },
    { id: "research-error-to-refine", from: "refactor-research", fromOutput: "ERROR", to: "audit-against-policy" },
    { id: "audit-to-actionable", from: "audit-against-policy", fromOutput: "SUCCESS", to: "has-actionable-refactor" },
    { id: "audit-invalid", from: "audit-against-policy", fromOutput: "INVALID", to: "mark-invalid-scope" },
    { id: "audit-error", from: "audit-against-policy", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "actionable-refactor-to-snapshot", from: "has-actionable-refactor", fromOutput: "MATCH", to: "git-snapshot-before" },
    { id: "no-actionable-refactor-to-classify", from: "has-actionable-refactor", fromOutput: "NO_MATCH", to: "selection-is-deferred" },
    { id: "actionable-refactor-error", from: "has-actionable-refactor", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "selection-deferred", from: "selection-is-deferred", fromOutput: "MATCH", to: "defer-scope" },
    { id: "selection-stopped", from: "selection-is-deferred", fromOutput: "NO_MATCH", to: "mark-stop-scope" },
    { id: "selection-classification-error", from: "selection-is-deferred", fromOutput: "ERROR", to: "mark-invalid-scope" },
    { id: "snapshot-to-baseline", from: "git-snapshot-before", fromOutput: "SUCCESS", to: "baseline-validation" },
    { id: "snapshot-error-to-baseline", from: "git-snapshot-before", fromOutput: "ERROR", to: "baseline-validation" },
    { id: "baseline-success-to-count", from: "baseline-validation", fromOutput: "SUCCESS", to: "count-refactor-pass" },
    { id: "baseline-failed-to-count", from: "baseline-validation", fromOutput: "FAILED", to: "count-refactor-pass" },
    { id: "baseline-error-to-count", from: "baseline-validation", fromOutput: "ERROR", to: "count-refactor-pass" },
    { id: "count-refactor-pass-continue", from: "count-refactor-pass", fromOutput: "CONTINUE", to: "refactor-pass" },
    { id: "count-refactor-pass-limit", from: "count-refactor-pass", fromOutput: "LIMIT_REACHED", to: "defer-scope" },
    { id: "count-refactor-pass-error", from: "count-refactor-pass", fromOutput: "ERROR", to: "defer-scope" },
    { id: "refactor-to-validation-tier", from: "refactor-pass", fromOutput: "SUCCESS", to: "select-validation-command" },
    { id: "refactor-error", from: "refactor-pass", fromOutput: "ERROR", to: "defer-scope" },
    { id: "validation-tier-to-decision", from: "select-validation-command", fromOutput: "SUCCESS", to: "validation-decision" },
    { id: "validation-tier-error", from: "select-validation-command", fromOutput: "ERROR", to: "validation-decision" },
    { id: "validation-decision-run", from: "validation-decision", fromOutput: "MATCH", to: "run-validation-checks" },
    { id: "validation-decision-skip", from: "validation-decision", fromOutput: "NO_MATCH", to: "git-diff-summary" },
    { id: "validation-decision-error", from: "validation-decision", fromOutput: "ERROR", to: "git-diff-summary" },
    { id: "validation-success-to-diff", from: "run-validation-checks", fromOutput: "SUCCESS", to: "git-diff-summary" },
    { id: "validation-failed-to-repair-counter", from: "run-validation-checks", fromOutput: "FAILED", to: "count-verification-repair" },
    { id: "validation-error-to-repair-counter", from: "run-validation-checks", fromOutput: "ERROR", to: "count-verification-repair" },
    { id: "repair-counter-to-fix", from: "count-verification-repair", fromOutput: "CONTINUE", to: "fix-validation-failures" },
    { id: "repair-counter-limit", from: "count-verification-repair", fromOutput: "LIMIT_REACHED", to: "defer-scope" },
    { id: "repair-counter-error", from: "count-verification-repair", fromOutput: "ERROR", to: "defer-scope" },
    { id: "fix-to-validation-decision", from: "fix-validation-failures", fromOutput: "SUCCESS", to: "validation-decision" },
    { id: "fix-error", from: "fix-validation-failures", fromOutput: "ERROR", to: "defer-scope" },
    { id: "git-diff-success-to-guard", from: "git-diff-summary", fromOutput: "SUCCESS", to: "scope-change-guard" },
    { id: "git-diff-empty-to-guard", from: "git-diff-summary", fromOutput: "EMPTY", to: "scope-change-guard" },
    { id: "git-diff-error-to-guard", from: "git-diff-summary", fromOutput: "ERROR", to: "scope-change-guard" },
    { id: "scope-guard-in-scope", from: "scope-change-guard", fromOutput: "IN_SCOPE", to: "final-refactor-scan" },
    { id: "scope-guard-out-of-scope", from: "scope-change-guard", fromOutput: "OUT_OF_SCOPE", to: "count-refactor-pass" },
    { id: "scope-guard-empty", from: "scope-change-guard", fromOutput: "EMPTY", to: "count-refactor-pass" },
    { id: "scope-guard-error", from: "scope-change-guard", fromOutput: "ERROR", to: "count-refactor-pass" },
    { id: "scan-done", from: "final-refactor-scan", fromOutput: "DONE", to: "mark-scope-result" },
    { id: "scan-continue", from: "final-refactor-scan", fromOutput: "CONTINUE", to: "count-refactor-pass" },
    { id: "scan-retry", from: "final-refactor-scan", fromOutput: "RETRY", to: "count-verification-repair" },
    { id: "scan-error", from: "final-refactor-scan", fromOutput: "ERROR", to: "defer-scope" },
    { id: "scan-invalid", from: "final-refactor-scan", fromOutput: "INVALID", to: "mark-invalid-scope" },
    { id: "mark-done-to-ledger", from: "mark-scope-result", fromOutput: "SUCCESS", to: "record-done-outcome" },
    { id: "mark-done-missing-to-ledger", from: "mark-scope-result", fromOutput: "NOT_FOUND", to: "record-done-outcome" },
    { id: "mark-done-error-to-ledger", from: "mark-scope-result", fromOutput: "ERROR", to: "record-done-outcome" },
    { id: "mark-defer-to-ledger", from: "defer-scope", fromOutput: "SUCCESS", to: "record-deferred-outcome" },
    { id: "mark-defer-missing-to-ledger", from: "defer-scope", fromOutput: "NOT_FOUND", to: "record-deferred-outcome" },
    { id: "mark-defer-error-to-ledger", from: "defer-scope", fromOutput: "ERROR", to: "record-deferred-outcome" },
    { id: "mark-stop-to-ledger", from: "mark-stop-scope", fromOutput: "SUCCESS", to: "record-stop-outcome" },
    { id: "mark-stop-missing-to-ledger", from: "mark-stop-scope", fromOutput: "NOT_FOUND", to: "record-stop-outcome" },
    { id: "mark-stop-error-to-ledger", from: "mark-stop-scope", fromOutput: "ERROR", to: "record-stop-outcome" },
    { id: "mark-invalid-to-ledger", from: "mark-invalid-scope", fromOutput: "SUCCESS", to: "record-invalid-outcome" },
    { id: "mark-invalid-missing-to-ledger", from: "mark-invalid-scope", fromOutput: "NOT_FOUND", to: "record-invalid-outcome" },
    { id: "mark-invalid-error-to-ledger", from: "mark-invalid-scope", fromOutput: "ERROR", to: "record-invalid-outcome" },
    { id: "done-ledger-to-report", from: "record-done-outcome", fromOutput: "SUCCESS", to: "final-report" },
    { id: "done-ledger-invalid-to-retained-report", from: "record-done-outcome", fromOutput: "INVALID", to: "retained-outcome-report" },
    { id: "done-ledger-error-to-retained-report", from: "record-done-outcome", fromOutput: "ERROR", to: "retained-outcome-report" },
    { id: "defer-ledger-to-retained-report", from: "record-deferred-outcome", fromOutput: "SUCCESS", to: "retained-outcome-report" },
    { id: "defer-ledger-invalid-to-retained-report", from: "record-deferred-outcome", fromOutput: "INVALID", to: "retained-outcome-report" },
    { id: "defer-ledger-error-to-retained-report", from: "record-deferred-outcome", fromOutput: "ERROR", to: "retained-outcome-report" },
    { id: "stop-ledger-to-report", from: "record-stop-outcome", fromOutput: "SUCCESS", to: "final-report" },
    { id: "stop-ledger-invalid-to-retained-report", from: "record-stop-outcome", fromOutput: "INVALID", to: "retained-outcome-report" },
    { id: "stop-ledger-error-to-retained-report", from: "record-stop-outcome", fromOutput: "ERROR", to: "retained-outcome-report" },
    { id: "invalid-ledger-to-report", from: "record-invalid-outcome", fromOutput: "SUCCESS", to: "final-report" },
    { id: "invalid-ledger-invalid-to-retained-report", from: "record-invalid-outcome", fromOutput: "INVALID", to: "retained-outcome-report" },
    { id: "invalid-ledger-error-to-retained-report", from: "record-invalid-outcome", fromOutput: "ERROR", to: "retained-outcome-report" },
    { id: "report-success-to-cycle", from: "final-report", fromOutput: "SUCCESS", to: "scope-cycle-complete" },
    { id: "report-error-to-cycle", from: "final-report", fromOutput: "ERROR", to: "scope-cycle-complete" },
    { id: "retained-report-success-to-deferred", from: "retained-outcome-report", fromOutput: "SUCCESS", to: "deferred" },
    { id: "retained-report-error-to-deferred", from: "retained-outcome-report", fromOutput: "ERROR", to: "deferred" },
    { id: "scope-cycle-complete-success", from: "scope-cycle-complete", fromOutput: "MATCH", to: "success" },
    { id: "scope-cycle-next", from: "scope-cycle-complete", fromOutput: "NO_MATCH", to: "select-scope" },
    { id: "scope-cycle-error", from: "scope-cycle-complete", fromOutput: "ERROR", to: "select-scope" },
  ],
};

export const repositoryRefactorValidationLoopStarterFlow = {
  id: "autonomous-refactoring-flow",
  version: 11,
  defaultAlias: "repository-refactor-validation-loop",
  category: "Code Quality",
  tags: ["refactor", "tests", "validation"],
  flow: autonomousRefactoringFlow,
} as const satisfies RalphStarterFlow;
