import type { RalphFlow } from "../ralph.js";
import type { RalphStarterFlow } from "../ralph-starter-flows.js";

const RALPH_REFACTOR_AGENT_TIMEOUT_SECONDS = 60 * 60;
const RALPH_REFACTOR_VALIDATION_COMMAND_TIMEOUT_SECONDS = 30 * 60;

const autonomousRefactoringFlow: RalphFlow = {
  schemaVersion: 1,
  id: "starter-autonomous-refactoring-flow",
  alias: "repository-refactor-validation-loop",
  name: "Repository Refactor & Validation Loop",
  description:
    "Configurable repository refactor loop that detects local conventions, audits against policy, applies scoped changes, and validates when a command is supplied.",
  settings: {
    maxTransitions: 240,
  },
  variables: [
    { name: "scopeRoot", type: "path", default: ".", required: false },
    { name: "scopeSelectionStrategy", type: "text", default: "round-robin", required: false },
    { name: "scopeRegistryFile", type: "path", default: ".machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.json", required: false },
    { name: "scopeRegistryMarkdown", type: "path", default: ".machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.md", required: false },
    { name: "refactorObjective", type: "text", default: "Improve maintainability while preserving behavior.", required: false },
    { name: "fileNamingPolicy", type: "text", default: "Follow existing framework and repository conventions.", required: false },
    { name: "maxFileLines", type: "number", default: "500", required: false },
    { name: "helperPlacementPolicy", type: "text", default: "Follow existing module-local and shared helper conventions.", required: false },
    { name: "testFramework", type: "text", default: "auto-detect", required: false },
    { name: "validationCommand", type: "text", default: "", required: false },
    { name: "excludePaths", type: "text", default: "node_modules, dist, build, coverage, target, .next, .nuxt, .turbo, .cache, vendor, generated", required: false },
    { name: "allowPublicApiChanges", type: "boolean", default: "false", required: false },
    { name: "notesFile", type: "path", default: "RALPH_REFACTOR_NOTES.md", required: false },
    { name: "maxRefactorPasses", type: "number", default: "5", required: false },
    { name: "projectCommandsFile", type: "path", default: ".machdoch/ralph/refactor/project-commands.json", required: false },
    { name: "conventionsFile", type: "path", default: ".machdoch/ralph/refactor/conventions.json", required: false },
    { name: "refactorPlanFile", type: "path", default: ".machdoch/ralph/refactor/refactor-plan.json", required: false },
    { name: "gitSnapshotFile", type: "path", default: ".machdoch/ralph/refactor/git-snapshot.json", required: false },
    { name: "gitDiffFile", type: "path", default: ".machdoch/ralph/refactor/git-diff.json", required: false },
    { name: "refactorReportFile", type: "path", default: ".machdoch/ralph/refactor/final-report.json", required: false },
    { name: "refactorReportMarkdown", type: "path", default: ".machdoch/ralph/refactor/final-report.md", required: false },
  ],
  blocks: [
    {
      id: "start",
      title: "Start",
      position: { x: 0, y: 0 },
      size: { width: 256, height: 140 },
      type: "START",
    },
    {
      id: "scan-scopes",
      title: "Scan Scope Evidence",
      position: { x: 700, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SCAN_SCOPE_EVIDENCE",
        rootPath: "{{scopeRoot:path=.}}",
        excludePaths: "{{excludePaths:text=node_modules, dist, build, coverage, target, .next, .nuxt, .turbo, .cache, vendor, generated}}",
        maxDepth: 4,
        maxResults: 200,
      },
    },
    {
      id: "update-scope-registry",
      title: "Update Scope Registry",
      position: { x: 1040, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "UPDATE_SCOPE_REGISTRY",
        flowAlias: "repository-refactor-validation-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.md}}",
        strategy: "{{scopeSelectionStrategy:text=round-robin}}",
        includeMarkdown: true,
      },
    },
    {
      id: "select-scope",
      title: "Select Refactor Scope",
      position: { x: 1380, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SELECT_SCOPE",
        flowAlias: "repository-refactor-validation-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.json}}",
        strategy: "{{scopeSelectionStrategy:text=round-robin}}",
      },
    },
    {
      id: "detect-project-commands",
      title: "Detect Project Commands",
      position: { x: 1720, y: -260 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "DETECT_PROJECT_COMMANDS",
        rootPath: "{{scopeRoot:path=.}}",
        outputPath:
          "{{projectCommandsFile:path=.machdoch/ralph/refactor/project-commands.json}}",
      },
    },
    {
      id: "detect-conventions",
      title: "Detect Project Conventions",
      position: { x: 1720, y: -120 },
      size: { width: 280, height: 190 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{conventionsFile:path=.machdoch/ralph/refactor/conventions.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: ["scope", "sourceRoots", "testFramework", "naming", "publicApiBoundaries", "exclusions"],
          properties: {
            scope: { type: "object" },
            sourceRoots: { type: "array", items: { type: "string" } },
            testFramework: { type: "string" },
            naming: { type: "object" },
            publicApiBoundaries: { type: "array", items: { type: "string" } },
            exclusions: { type: "array", items: { type: "string" } },
          },
        },
        prompt:
          "Inspect selected JSON scope {{result:select-scope}} and detect repository conventions before applying policy. Use deterministic project command detection {{result:detect-project-commands}}. Identify source roots, test framework (configured as {{testFramework:text=auto-detect}}), naming patterns, framework-required filenames, helper placement conventions, package scripts, generated/vendor paths, and public API boundaries. Exclude {{excludePaths:text=}}. Do not change files. Return only schema-valid JSON.",
      },
    },
    {
      id: "audit-against-policy",
      title: "Audit Against Policy",
      position: { x: 2060, y: 0 },
      size: { width: 280, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{refactorPlanFile:path=.machdoch/ralph/refactor/refactor-plan.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: ["objective", "scope", "passes", "risks", "verification"],
          properties: {
            objective: { type: "string" },
            scope: { type: "object" },
            passes: {
              type: "array",
              items: {
                type: "object",
                required: ["title", "files", "actions"],
                properties: {
                  title: { type: "string" },
                  files: { type: "array", items: { type: "string" } },
                  actions: { type: "array", items: { type: "string" } },
                },
              },
            },
            risks: { type: "array", items: { type: "string" } },
            verification: { type: "array", items: { type: "string" } },
          },
        },
        prompt:
          "Audit selected JSON scope {{result:select-scope}} against detected conventions {{data:detect-conventions:output}} and this template policy: objective {{refactorObjective:text=Improve maintainability while preserving behavior.}}, file naming {{fileNamingPolicy:text=Follow existing framework and repository conventions.}}, max file lines {{maxFileLines:number=500}}, helper placement {{helperPlacementPolicy:text=Follow existing module-local and shared helper conventions.}}, test framework {{testFramework:text=auto-detect}}, public API changes allowed {{allowPublicApiChanges:boolean=false}}. Produce a prioritized, bounded refactor pass plan. Note exceptions in {{notesFile:path=RALPH_REFACTOR_NOTES.md}} when useful. Do not change files. Return only schema-valid JSON.",
      },
    },
    {
      id: "git-snapshot-before",
      title: "Git Snapshot",
      position: { x: 2280, y: -180 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_SNAPSHOT",
        cwd: ".",
        outputPath:
          "{{gitSnapshotFile:path=.machdoch/ralph/refactor/git-snapshot.json}}",
      },
    },
    {
      id: "refactor-pass",
      title: "Refactor Pass",
      position: { x: 2400, y: 0 },
      size: { width: 280, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 2,
        timeoutSeconds: RALPH_REFACTOR_AGENT_TIMEOUT_SECONDS,
      },
      type: "PROMPT",
      prompt:
        "Apply one cohesive refactor pass in selected JSON scope {{result:select-scope}} using structured conventions {{data:detect-conventions:output}}, refactor plan {{data:audit-against-policy:output}}, git baseline {{result:git-snapshot-before}}, and latest validation feedback {{lastResult}}. Follow objective {{refactorObjective:text=Improve maintainability while preserving behavior.}}, naming policy {{fileNamingPolicy:text=Follow existing framework and repository conventions.}}, max lines {{maxFileLines:number=500}}, helper placement {{helperPlacementPolicy:text=Follow existing module-local and shared helper conventions.}}, and test framework {{testFramework:text=auto-detect}}. Do not change public APIs unless allowPublicApiChanges={{allowPublicApiChanges:boolean=false}} and the reason is documented. Keep changes scoped to the selected paths/globs, update imports/exports/tests, and avoid broad formatting sweeps.",
    },
    {
      id: "count-refactor-pass",
      title: "Count Refactor Pass",
      position: { x: 2400, y: -180 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        counterName:
          "repository-refactor-validation-loop.refactor-pass.{{data:select-scope:scope.id}}",
        maxAttempts: "{{maxRefactorPasses:number=5}}",
      },
    },
    {
      id: "validation-decision",
      title: "Run Validation?",
      position: { x: 2740, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "Boolean(variables.validationCommand?.trim() || context.resultsByBlock?.['detect-project-commands']?.data?.verificationCommand?.trim())",
        },
      },
    },
    {
      id: "run-validation-checks",
      title: "Run Validation",
      position: { x: 3060, y: -95 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{validationCommand:text=}}",
        fallbackCommand: "{{data:detect-project-commands:verificationCommand}}",
        timeoutSeconds: RALPH_REFACTOR_VALIDATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "fix-validation-failures",
      title: "Fix Validation Failures",
      position: { x: 3400, y: 95 },
      size: { width: 280, height: 190 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 1,
        timeoutSeconds: RALPH_REFACTOR_AGENT_TIMEOUT_SECONDS,
      },
      type: "PROMPT",
      prompt:
        "Fix validation failures from {{result:run-validation-checks}} that were caused by the refactor. Distinguish pre-existing failures from own regressions, keep changes scoped, preserve behavior, and update tests/imports/exports as needed. If validationCommand is unavailable or blank, document that in {{notesFile:path=RALPH_REFACTOR_NOTES.md}} and continue.",
    },
    {
      id: "git-diff-summary",
      title: "Git Diff Summary",
      position: { x: 3400, y: -330 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_DIFF_SUMMARY",
        cwd: ".",
        outputPath: "{{gitDiffFile:path=.machdoch/ralph/refactor/git-diff.json}}",
      },
    },
    {
      id: "final-refactor-scan",
      title: "Final Refactor Scan",
      position: { x: 3400, y: -150 },
      size: { width: 300, height: 238 },
      type: "VALIDATOR",
      settings: {
        timeoutSeconds: RALPH_REFACTOR_AGENT_TIMEOUT_SECONDS,
      },
      prompt:
        "Perform a final scan for selected JSON scope {{result:select-scope}} using conventions {{data:detect-conventions:output}}, refactor plan {{data:audit-against-policy:output}}, validation result {{result:run-validation-checks}}, git diff {{result:git-diff-summary}}, and latest changes. Evaluate only the selected paths/globs and notes file {{notesFile:path=RALPH_REFACTOR_NOTES.md}}; ignore unrelated workspace changes outside the selected scope unless they directly break verification of this scope. Verify the configured objective, naming policy, max file line policy, helper placement policy, tests, public API policy, and exclusions. If this selected scope is complete, end with RALPH_DECISION: DONE. If unresolved issues remain, end with RALPH_DECISION: CONTINUE; the flow counter enforces maxRefactorPasses={{maxRefactorPasses:number=5}}. If validation failed due to own changes, end with RALPH_DECISION: RETRY. If blocked, end with RALPH_DECISION: ERROR.",
      validationScope: {
        mode: "sinceLastValidator",
        blockIds: [],
      },
    },
    {
      id: "final-report",
      title: "Final Refactor Report",
      position: { x: 3740, y: -220 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{refactorReportFile:path=.machdoch/ralph/refactor/final-report.json}}",
        outputPath:
          "{{refactorReportMarkdown:path=.machdoch/ralph/refactor/final-report.md}}",
      },
    },
    {
      id: "mark-scope-result",
      title: "Mark Scope Result",
      position: { x: 3740, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "repository-refactor-validation-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/repository-refactor-validation-loop.scope-registry.md}}",
        result: "DONE",
        includeMarkdown: true,
      },
    },
    {
      id: "scope-cycle-complete",
      title: "Scope Cycle Complete?",
      position: { x: 4080, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression: "lastData?.cycleCompleted === true",
        },
      },
    },
    {
      id: "success",
      title: "Refactor Complete",
      position: { x: 4420, y: 0 },
      size: { width: 256, height: 114 },
      type: "END",
      status: "success",
    },
    {
      id: "blocked",
      title: "Blocked",
      position: { x: 2060, y: 300 },
      size: { width: 256, height: 114 },
      type: "END",
      status: "failed",
    },
  ],
  edges: [
    { id: "start-to-scan-scopes", from: "start", fromOutput: "SUCCESS", to: "scan-scopes" },
    { id: "scan-scopes-to-update", from: "scan-scopes", fromOutput: "SUCCESS", to: "update-scope-registry" },
    { id: "scan-scopes-empty", from: "scan-scopes", fromOutput: "EMPTY", to: "blocked" },
    { id: "scan-scopes-error", from: "scan-scopes", fromOutput: "ERROR", to: "blocked" },
    { id: "update-registry-to-select", from: "update-scope-registry", fromOutput: "SUCCESS", to: "select-scope" },
    { id: "update-registry-empty", from: "update-scope-registry", fromOutput: "EMPTY", to: "blocked" },
    { id: "update-registry-error", from: "update-scope-registry", fromOutput: "ERROR", to: "blocked" },
    { id: "select-scope-to-detect-commands", from: "select-scope", fromOutput: "SELECTED", to: "detect-project-commands" },
    { id: "select-scope-empty", from: "select-scope", fromOutput: "EMPTY", to: "success" },
    { id: "select-scope-error", from: "select-scope", fromOutput: "ERROR", to: "blocked" },
    { id: "detect-commands-to-conventions", from: "detect-project-commands", fromOutput: "SUCCESS", to: "detect-conventions" },
    { id: "detect-commands-empty-to-conventions", from: "detect-project-commands", fromOutput: "EMPTY", to: "detect-conventions" },
    { id: "detect-commands-error-to-conventions", from: "detect-project-commands", fromOutput: "ERROR", to: "detect-conventions" },
    { id: "detect-to-audit", from: "detect-conventions", fromOutput: "SUCCESS", to: "audit-against-policy" },
    { id: "detect-invalid", from: "detect-conventions", fromOutput: "INVALID", to: "blocked" },
    { id: "detect-error", from: "detect-conventions", fromOutput: "ERROR", to: "blocked" },
    { id: "audit-to-snapshot", from: "audit-against-policy", fromOutput: "SUCCESS", to: "git-snapshot-before" },
    { id: "audit-invalid", from: "audit-against-policy", fromOutput: "INVALID", to: "blocked" },
    { id: "audit-error", from: "audit-against-policy", fromOutput: "ERROR", to: "blocked" },
    { id: "snapshot-to-count-refactor-pass", from: "git-snapshot-before", fromOutput: "SUCCESS", to: "count-refactor-pass" },
    { id: "snapshot-error-to-count-refactor-pass", from: "git-snapshot-before", fromOutput: "ERROR", to: "count-refactor-pass" },
    { id: "count-refactor-pass-continue", from: "count-refactor-pass", fromOutput: "CONTINUE", to: "refactor-pass" },
    { id: "count-refactor-pass-limit", from: "count-refactor-pass", fromOutput: "LIMIT_REACHED", to: "blocked" },
    { id: "count-refactor-pass-error", from: "count-refactor-pass", fromOutput: "ERROR", to: "blocked" },
    { id: "refactor-to-validation-decision", from: "refactor-pass", fromOutput: "SUCCESS", to: "validation-decision" },
    { id: "refactor-error", from: "refactor-pass", fromOutput: "ERROR", to: "blocked" },
    { id: "validation-decision-run", from: "validation-decision", fromOutput: "MATCH", to: "run-validation-checks" },
    { id: "validation-decision-skip", from: "validation-decision", fromOutput: "NO_MATCH", to: "git-diff-summary" },
    { id: "validation-decision-error", from: "validation-decision", fromOutput: "ERROR", to: "git-diff-summary" },
    { id: "validation-success-to-diff", from: "run-validation-checks", fromOutput: "SUCCESS", to: "git-diff-summary" },
    { id: "validation-failed-to-fix", from: "run-validation-checks", fromOutput: "FAILED", to: "fix-validation-failures" },
    { id: "validation-error-to-fix", from: "run-validation-checks", fromOutput: "ERROR", to: "fix-validation-failures" },
    { id: "fix-to-validation-decision", from: "fix-validation-failures", fromOutput: "SUCCESS", to: "validation-decision" },
    { id: "fix-error", from: "fix-validation-failures", fromOutput: "ERROR", to: "blocked" },
    { id: "git-diff-success-to-scan", from: "git-diff-summary", fromOutput: "SUCCESS", to: "final-refactor-scan" },
    { id: "git-diff-empty-to-scan", from: "git-diff-summary", fromOutput: "EMPTY", to: "final-refactor-scan" },
    { id: "git-diff-error-to-scan", from: "git-diff-summary", fromOutput: "ERROR", to: "final-refactor-scan" },
    { id: "scan-done", from: "final-refactor-scan", fromOutput: "DONE", to: "final-report" },
    { id: "scan-continue", from: "final-refactor-scan", fromOutput: "CONTINUE", to: "count-refactor-pass" },
    { id: "scan-retry", from: "final-refactor-scan", fromOutput: "RETRY", to: "validation-decision" },
    { id: "scan-error", from: "final-refactor-scan", fromOutput: "ERROR", to: "blocked" },
    { id: "report-success-to-mark", from: "final-report", fromOutput: "SUCCESS", to: "mark-scope-result" },
    { id: "report-error-to-mark", from: "final-report", fromOutput: "ERROR", to: "mark-scope-result" },
    { id: "mark-scope-success", from: "mark-scope-result", fromOutput: "SUCCESS", to: "scope-cycle-complete" },
    { id: "mark-scope-not-found", from: "mark-scope-result", fromOutput: "NOT_FOUND", to: "blocked" },
    { id: "mark-scope-error", from: "mark-scope-result", fromOutput: "ERROR", to: "blocked" },
    { id: "scope-cycle-complete-success", from: "scope-cycle-complete", fromOutput: "MATCH", to: "success" },
    { id: "scope-cycle-next", from: "scope-cycle-complete", fromOutput: "NO_MATCH", to: "select-scope" },
    { id: "scope-cycle-error", from: "scope-cycle-complete", fromOutput: "ERROR", to: "select-scope" },
  ],
};

export const repositoryRefactorValidationLoopStarterFlow = {
  id: "autonomous-refactoring-flow",
  version: 4,
  defaultAlias: "repository-refactor-validation-loop",
  category: "Code Quality",
  tags: ["refactor", "tests", "validation"],
  flow: autonomousRefactoringFlow,
} as const satisfies RalphStarterFlow;
