import type { RalphFlow } from "../ralph.js";
import type { RalphStarterFlow } from "../ralph-starter-flows.js";

const RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS = 30 * 60;

const securityFixLoopFlow: RalphFlow = {
  schemaVersion: 1,
  id: "starter-security-fix-loop",
  alias: "security-review-fix-loop",
  name: "Security Review & Fix Loop",
  description:
    "Configurable security review, verification, and fix loop for repositories with explicit scope, standards, stack, and safety policies.",
  settings: {
    maxTransitions: 240,
  },
  variables: [
    {
      name: "scopeRoot",
      type: "path",
      default: ".",
      required: false,
    },
    {
      name: "scopeSelectionStrategy",
      type: "text",
      default: "round-robin",
      required: false,
    },
    {
      name: "scopeRegistryFile",
      type: "path",
      default: ".machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.json",
      required: false,
    },
    {
      name: "scopeRegistryMarkdown",
      type: "path",
      default: ".machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.md",
      required: false,
    },
    {
      name: "projectStack",
      type: "text",
      default: "auto-detect",
      required: false,
    },
    {
      name: "securityStandards",
      type: "text",
      default: "OWASP Top 10, OWASP ASVS",
      required: false,
    },
    {
      name: "severityThreshold",
      type: "text",
      default: "high",
      required: false,
    },
    {
      name: "enableOnlineResearch",
      type: "boolean",
      default: "true",
      required: false,
    },
    {
      name: "verificationCommand",
      type: "text",
      default: "",
      required: false,
    },
    {
      name: "authTestInstructions",
      type: "text",
      default: "",
      required: false,
    },
    {
      name: "historyFile",
      type: "path",
      default: ".machdoch/ralph/security/RALPH_SECURITY_HISTORY.md",
      required: false,
    },
    {
      name: "schemaChangePolicy",
      type: "text",
      default: "report-only",
      required: false,
    },
    {
      name: "allowDependencyChanges",
      type: "boolean",
      default: "false",
      required: false,
    },
    {
      name: "maxFixLoops",
      type: "number",
      default: "10",
      required: false,
    },
    { name: "projectCommandsFile", type: "path", default: ".machdoch/ralph/security/project-commands.json", required: false },
    { name: "securityReviewFile", type: "path", default: ".machdoch/ralph/security/review.json", required: false },
    { name: "gitSnapshotFile", type: "path", default: ".machdoch/ralph/security/git-snapshot.json", required: false },
    { name: "gitDiffFile", type: "path", default: ".machdoch/ralph/security/git-diff.json", required: false },
    { name: "securityReportFile", type: "path", default: ".machdoch/ralph/security/final-report.json", required: false },
    { name: "securityReportMarkdown", type: "path", default: ".machdoch/ralph/security/final-report.md", required: false },
  ],
  blocks: [
    {
      id: "start",
      title: "Start",
      position: { x: 0, y: 0 },
      size: { width: 256, height: 140 },
      type: "START",
    },
    {
      id: "research-decision",
      title: "Use Online Research?",
      position: { x: 700, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression: 'variables.enableOnlineResearch === "true"',
        },
      },
    },
    {
      id: "security-research",
      title: "Security Research",
      position: { x: 1020, y: -120 },
      size: { width: 280, height: 190 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        webAccess: true,
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Use content enrichment before the security review. If search_web is available, run focused searches for current primary-source security guidance, standards, advisories, framework hardening docs, and relevant changelogs for {{projectStack:text=auto-detect}} and these standards: {{securityStandards:text=OWASP Top 10, OWASP ASVS}}. Use fetch_url on official standards, vendor, maintainer, or advisory pages before relying on them. Keep the research concise and focus on the configured scope root {{scopeRoot:path=.}} and fix threshold {{severityThreshold:text=high}}. Include source links, standard versions/requirement ids when available, relevant checks, exploitability notes, and assumptions. If web search is unavailable, say so and use local package/config evidence plus any provided URLs.",
    },
    {
      id: "scan-scopes",
      title: "Scan Scope Evidence",
      position: { x: 1020, y: 120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SCAN_SCOPE_EVIDENCE",
        rootPath: "{{scopeRoot:path=.}}",
        excludePaths:
          "node_modules, dist, build, coverage, target, .next, .nuxt, .turbo, .cache, vendor, generated, .machdoch",
        maxDepth: 4,
        maxResults: 200,
      },
    },
    {
      id: "update-scope-registry",
      title: "Update Scope Registry",
      position: { x: 1360, y: 120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "UPDATE_SCOPE_REGISTRY",
        flowAlias: "security-review-fix-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.md}}",
        strategy: "{{scopeSelectionStrategy:text=round-robin}}",
        includeMarkdown: true,
      },
    },
    {
      id: "select-scope",
      title: "Select Review Scope",
      position: { x: 1700, y: 120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SELECT_SCOPE",
        flowAlias: "security-review-fix-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.json}}",
        strategy: "{{scopeSelectionStrategy:text=round-robin}}",
      },
    },
    {
      id: "detect-project-commands",
      title: "Detect Project Commands",
      position: { x: 2040, y: -180 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "DETECT_PROJECT_COMMANDS",
        rootPath: "{{data:select-scope:scope.paths.0}}",
        outputPath:
          "{{projectCommandsFile:path=.machdoch/ralph/security/project-commands.json}}",
      },
    },
    {
      id: "git-snapshot-before",
      title: "Git Snapshot",
      position: { x: 2040, y: 20 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_SNAPSHOT",
        cwd: ".",
        outputPath:
          "{{gitSnapshotFile:path=.machdoch/ralph/security/git-snapshot.json}}",
      },
    },
    {
      id: "security-check",
      title: "Security Review",
      position: { x: 2380, y: 0 },
      size: { width: 280, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{securityReviewFile:path=.machdoch/ralph/security/review.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          required: ["scope", "coveredPaths", "threatModel", "findings"],
          properties: {
            scope: { type: "object" },
            coveredPaths: { type: "array", items: { type: "string" } },
            threatModel: { type: "object" },
            findings: {
              type: "array",
              items: {
                type: "object",
                required: ["id", "severity", "title", "evidence", "fixPlan"],
                properties: {
                  id: { type: "string" },
                  severity: { type: "string" },
                  title: { type: "string" },
                  evidence: { type: "string" },
                  fixPlan: { type: "string" },
                },
              },
            },
          },
        },
        prompt:
          "Run a focused security review for selected JSON scope {{result:select-scope}}. Use project stack {{projectStack:text=auto-detect}}, detected commands {{result:detect-project-commands}}, standards {{securityStandards:text=OWASP Top 10, OWASP ASVS}}, fix threshold {{severityThreshold:text=high}}, auth test instructions {{authTestInstructions:text=}}, git baseline {{result:git-snapshot-before}}, and research {{summary:security-research}} when present. Inspect the selected paths/globs explicitly. Treat user input, files, network responses, environment variables, and IPC/API boundaries as untrusted. Return JSON with coveredPaths, a concise threatModel, and findings at or above the configured threshold. Findings must include severity, evidence, exploitability, file references, and fixPlan. If no qualifying findings exist, return findings: []. Follow schemaChangePolicy={{schemaChangePolicy:text=report-only}}.",
      },
    },
    {
      id: "findings-present",
      title: "Findings Present?",
      position: { x: 2720, y: -120 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "Array.isArray(lastData?.output?.findings) && lastData.output.findings.length > 0",
        },
      },
    },
    {
      id: "fix-findings",
      title: "Fix Findings",
      position: { x: 3060, y: 0 },
      size: { width: 280, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 4,
      },
      type: "PROMPT",
      prompt:
        "Fix security findings from {{data:security-check:output.findings}} for selected scope {{result:select-scope}} at or above {{severityThreshold:text=high}}. Use threat model {{data:security-check:output.threatModel}} and git baseline {{result:git-snapshot-before}}. Keep changes narrow, preserve behavior unless the security fix requires a contract change, add or update targeted tests, and do not start or restart servers. Dependency changes are allowed only when allowDependencyChanges={{allowDependencyChanges:boolean=false}} permits them or when the security fix cannot be done safely otherwise; document the reason. Follow schemaChangePolicy={{schemaChangePolicy:text=report-only}} for schema or migration needs. Append a concise note to {{historyFile:path=.machdoch/ralph/security/RALPH_SECURITY_HISTORY.md}} with fixed findings, tests, remaining risks, and blocked items.",
    },
    {
      id: "verification-decision",
      title: "Run Verification?",
      position: { x: 3400, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "Boolean(variables.verificationCommand?.trim() || context.resultsByBlock?.['detect-project-commands']?.data?.verificationCommand?.trim())",
        },
      },
    },
    {
      id: "run-verification",
      title: "Run Verification",
      position: { x: 3720, y: -95 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{verificationCommand:text=}}",
        fallbackCommand: "{{data:detect-project-commands:verificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "git-diff-summary",
      title: "Git Diff Summary",
      position: { x: 4060, y: -95 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_DIFF_SUMMARY",
        cwd: ".",
        outputPath: "{{gitDiffFile:path=.machdoch/ralph/security/git-diff.json}}",
      },
    },
    {
      id: "verify-stop-condition",
      title: "Verify Stop Condition",
      position: { x: 4400, y: 0 },
      size: { width: 300, height: 238 },
      type: "VALIDATOR",
      prompt:
        "Validate the latest iteration since the previous validator for selected scope {{result:select-scope}}. Confirm whether the structured review {{result:security-check}} and git diff {{result:git-diff-summary}} show no remaining findings at or above {{severityThreshold:text=high}} in the selected scope, fixes followed schemaChangePolicy={{schemaChangePolicy:text=report-only}}, dependency changes followed allowDependencyChanges={{allowDependencyChanges:boolean=false}}, {{historyFile:path=.machdoch/ralph/security/RALPH_SECURITY_HISTORY.md}} was updated when changes were made, no servers were started or restarted, and verification result {{result:run-verification}} was considered when a command was configured. Ignore unrelated workspace changes outside the selected scope unless they directly break verification of this security fix. If this selected scope is done, end with RALPH_DECISION: DONE. If qualifying findings remain and fewer than {{maxFixLoops:number=10}} loops have been attempted for this scope, end with RALPH_DECISION: CONTINUE. If the last fix needs correction or verification rerun, end with RALPH_DECISION: RETRY. If blocked by missing credentials, unsafe schema work, unavailable tooling, or repeated failures, end with RALPH_DECISION: ERROR.",
      validationScope: {
        mode: "sinceLastValidator",
        blockIds: [],
      },
    },
    {
      id: "final-report",
      title: "Final Security Report",
      position: { x: 4760, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{securityReportFile:path=.machdoch/ralph/security/final-report.json}}",
        outputPath:
          "{{securityReportMarkdown:path=.machdoch/ralph/security/final-report.md}}",
      },
    },
    {
      id: "mark-scope-result",
      title: "Mark Scope Result",
      position: { x: 5100, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "security-review-fix-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.md}}",
        result: "DONE",
        includeMarkdown: true,
      },
    },
    {
      id: "scope-cycle-complete",
      title: "Scope Cycle Complete?",
      position: { x: 5440, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression: "lastData?.cycleCompleted === true",
        },
      },
    },
    {
      id: "success",
      title: "No Blocking Findings",
      position: { x: 5780, y: 0 },
      size: { width: 256, height: 114 },
      type: "END",
      status: "success",
    },
    {
      id: "blocked",
      title: "Blocked",
      position: { x: 2380, y: 300 },
      size: { width: 256, height: 114 },
      type: "END",
      status: "failed",
    },
  ],
  edges: [
    { id: "start-to-research-decision", from: "start", fromOutput: "SUCCESS", to: "research-decision" },
    { id: "research-decision-run", from: "research-decision", fromOutput: "MATCH", to: "security-research" },
    { id: "research-decision-skip", from: "research-decision", fromOutput: "NO_MATCH", to: "scan-scopes" },
    { id: "research-decision-error", from: "research-decision", fromOutput: "ERROR", to: "scan-scopes" },
    { id: "research-to-scan-scopes", from: "security-research", fromOutput: "SUCCESS", to: "scan-scopes" },
    { id: "research-error-to-scan-scopes", from: "security-research", fromOutput: "ERROR", to: "scan-scopes" },
    { id: "scan-scopes-to-update", from: "scan-scopes", fromOutput: "SUCCESS", to: "update-scope-registry" },
    { id: "scan-scopes-empty", from: "scan-scopes", fromOutput: "EMPTY", to: "blocked" },
    { id: "scan-scopes-error", from: "scan-scopes", fromOutput: "ERROR", to: "blocked" },
    { id: "update-registry-to-select", from: "update-scope-registry", fromOutput: "SUCCESS", to: "select-scope" },
    { id: "update-registry-empty", from: "update-scope-registry", fromOutput: "EMPTY", to: "blocked" },
    { id: "update-registry-error", from: "update-scope-registry", fromOutput: "ERROR", to: "blocked" },
    { id: "select-scope-to-detect-commands", from: "select-scope", fromOutput: "SELECTED", to: "detect-project-commands" },
    { id: "select-scope-empty", from: "select-scope", fromOutput: "EMPTY", to: "success" },
    { id: "select-scope-error", from: "select-scope", fromOutput: "ERROR", to: "blocked" },
    { id: "detect-commands-to-snapshot", from: "detect-project-commands", fromOutput: "SUCCESS", to: "git-snapshot-before" },
    { id: "detect-commands-empty-to-snapshot", from: "detect-project-commands", fromOutput: "EMPTY", to: "git-snapshot-before" },
    { id: "detect-commands-error-to-snapshot", from: "detect-project-commands", fromOutput: "ERROR", to: "git-snapshot-before" },
    { id: "git-snapshot-to-security-check", from: "git-snapshot-before", fromOutput: "SUCCESS", to: "security-check" },
    { id: "git-snapshot-error-to-security-check", from: "git-snapshot-before", fromOutput: "ERROR", to: "security-check" },
    { id: "security-check-to-findings-present", from: "security-check", fromOutput: "SUCCESS", to: "findings-present" },
    { id: "security-check-invalid", from: "security-check", fromOutput: "INVALID", to: "blocked" },
    { id: "security-check-error", from: "security-check", fromOutput: "ERROR", to: "blocked" },
    { id: "findings-present-fix", from: "findings-present", fromOutput: "MATCH", to: "fix-findings" },
    { id: "findings-present-none", from: "findings-present", fromOutput: "NO_MATCH", to: "final-report" },
    { id: "findings-present-error", from: "findings-present", fromOutput: "ERROR", to: "blocked" },
    { id: "fix-findings-to-verification-decision", from: "fix-findings", fromOutput: "SUCCESS", to: "verification-decision" },
    { id: "fix-findings-error", from: "fix-findings", fromOutput: "ERROR", to: "blocked" },
    { id: "verification-decision-run", from: "verification-decision", fromOutput: "MATCH", to: "run-verification" },
    { id: "verification-decision-skip", from: "verification-decision", fromOutput: "NO_MATCH", to: "git-diff-summary" },
    { id: "verification-decision-error", from: "verification-decision", fromOutput: "ERROR", to: "git-diff-summary" },
    { id: "verification-success-to-diff", from: "run-verification", fromOutput: "SUCCESS", to: "git-diff-summary" },
    { id: "verification-failed-to-diff", from: "run-verification", fromOutput: "FAILED", to: "git-diff-summary" },
    { id: "verification-error-to-diff", from: "run-verification", fromOutput: "ERROR", to: "git-diff-summary" },
    { id: "git-diff-success-to-verify", from: "git-diff-summary", fromOutput: "SUCCESS", to: "verify-stop-condition" },
    { id: "git-diff-empty-to-verify", from: "git-diff-summary", fromOutput: "EMPTY", to: "verify-stop-condition" },
    { id: "git-diff-error-to-verify", from: "git-diff-summary", fromOutput: "ERROR", to: "verify-stop-condition" },
    { id: "verify-done", from: "verify-stop-condition", fromOutput: "DONE", to: "final-report" },
    { id: "verify-continue", from: "verify-stop-condition", fromOutput: "CONTINUE", to: "select-scope" },
    { id: "verify-retry", from: "verify-stop-condition", fromOutput: "RETRY", to: "verification-decision" },
    { id: "verify-error", from: "verify-stop-condition", fromOutput: "ERROR", to: "blocked" },
    { id: "report-success-to-mark", from: "final-report", fromOutput: "SUCCESS", to: "mark-scope-result" },
    { id: "report-error-to-mark", from: "final-report", fromOutput: "ERROR", to: "mark-scope-result" },
    { id: "mark-scope-success", from: "mark-scope-result", fromOutput: "SUCCESS", to: "scope-cycle-complete" },
    { id: "mark-scope-not-found", from: "mark-scope-result", fromOutput: "NOT_FOUND", to: "blocked" },
    { id: "mark-scope-error", from: "mark-scope-result", fromOutput: "ERROR", to: "blocked" },
    { id: "scope-cycle-complete-success", from: "scope-cycle-complete", fromOutput: "MATCH", to: "success" },
    { id: "scope-cycle-next", from: "scope-cycle-complete", fromOutput: "NO_MATCH", to: "select-scope" },
    { id: "scope-cycle-error", from: "scope-cycle-complete", fromOutput: "ERROR", to: "select-scope" },
  ],
};

export const securityReviewFixLoopStarterFlow = {
  id: "security-fix-loop",
  version: 6,
  defaultAlias: "security-review-fix-loop",
  category: "Security",
  tags: ["review", "fix", "tests"],
  flow: securityFixLoopFlow,
} as const satisfies RalphStarterFlow;
