import type { MediaNodeDefinition } from "./node-registry.js";

export const AUDIO_NODE_DEFINITIONS: readonly MediaNodeDefinition[] = [
  {
    type: "task.generate-audio",
    version: 1,
    displayName: "Generate audio",
    summary: "",
    layer: "task",
    category: "Generation",
    paletteVisibility: "default",
    maxInstances: 1,
    inputs: [
      {
        id: "prompt",
        label: "Prompt",
        dataType: "prompt",
        required: true,
        cardinality: "single",
        description: "",
      },
    ],
    outputs: [
      {
        id: "audio",
        label: "Audio",
        dataType: "audio",
        required: true,
        cardinality: "single",
        description: "",
      },
    ],
    fields: [
      {
        id: "modelId",
        label: "Model",
        kind: "model",
        group: "Basic",
        defaultValue: null,
        required: false,
        description: "",
        examples: [],
      },
      {
        id: "durationSeconds",
        label: "Duration (s)",
        kind: "number",
        group: "Basic",
        defaultValue: 5,
        min: 1,
        max: 30,
        step: 0.1,
        required: true,
        description: "",
        examples: [],
      },
      {
        id: "negativePrompt",
        label: "Negative prompt",
        kind: "textarea",
        group: "Creative",
        defaultValue: "",
        required: true,
        allowEmpty: true,
        maxLength: 8000,
        description: "",
        examples: [],
      },
      {
        id: "numInferenceSteps",
        label: "Steps",
        kind: "number",
        group: "Expert",
        defaultValue: 100,
        min: 1,
        max: 200,
        integer: true,
        required: true,
        description: "",
        examples: [],
      },
      {
        id: "guidanceScale",
        label: "Guidance",
        kind: "number",
        group: "Expert",
        defaultValue: 3.5,
        min: 0,
        max: 20,
        step: 0.1,
        required: true,
        description: "",
        examples: [],
      },
      {
        id: "seed",
        label: "Seed",
        kind: "number",
        group: "Expert",
        defaultValue: null,
        min: 0,
        max: Number.MAX_SAFE_INTEGER,
        integer: true,
        required: false,
        description: "",
        examples: [],
      },
    ],
    privacyEffects: [],
    costEffects: [],
  },
  {
    type: "output.audio",
    version: 1,
    displayName: "Save audio",
    summary: "",
    layer: "output",
    category: "Output",
    paletteVisibility: "output",
    maxInstances: 1,
    inputs: [
      {
        id: "audio",
        label: "Audio",
        dataType: "audio",
        required: true,
        cardinality: "single",
        description: "",
      },
    ],
    outputs: [],
    fields: [
      {
        id: "format",
        label: "Format",
        kind: "select",
        group: "Basic",
        defaultValue: "wav",
        required: true,
        description: "",
        examples: [],
        options: [{ value: "wav", label: "WAV", description: "" }],
      },
    ],
    privacyEffects: [],
    costEffects: [],
  },
];
