import type {
  MediaNodeDefinition,
  MediaNodeFieldDefinition,
  MediaNodePortDefinition,
} from "./node-registry.js";

const video: MediaNodePortDefinition = {
  id: "video",
  label: "Video",
  dataType: "video",
  required: true,
  cardinality: "single",
  description: "",
};
const audio: MediaNodePortDefinition = {
  ...video,
  id: "audio",
  label: "Audio",
  dataType: "audio",
};
const assetField: MediaNodeFieldDefinition = {
  id: "assetId",
  label: "Asset",
  kind: "asset",
  group: "Basic",
  defaultValue: "",
  required: false,
  allowEmpty: true,
  maxLength: 256,
  description: "",
  examples: [],
};
const audioStart: MediaNodeFieldDefinition = {
  id: "audioStartSeconds",
  label: "Audio start (s)",
  kind: "number",
  group: "Basic",
  defaultValue: 0,
  min: 0,
  max: 86400,
  step: 0.1,
  required: true,
  description: "",
  examples: [],
};

export const VIDEO_COMPOSITION_NODE_DEFINITIONS: readonly MediaNodeDefinition[] = [
  {
    type: "operation.lip-sync",
    version: 1,
    displayName: "Lip sync",
    summary: "",
    layer: "operation",
    category: "Transform",
    paletteVisibility: "default",
    inputs: [video, audio, { ...audio, id: "voice", label: "Vocals", required: false }],
    outputs: [video],
    fields: [
      {
        ...assetField,
        id: "modelPath",
        label: "MuseTalk 1.5",
        kind: "directory",
        maxLength: 2048,
      },
      audioStart,
      {
        ...audioStart,
        id: "cropShift",
        integer: true,
        label: "Face crop shift (px)",
        group: "Expert",
        min: -64,
        max: 64,
        step: 1,
      },
      {
        ...audioStart,
        id: "batchSize",
        integer: true,
        label: "Batch size",
        group: "Expert",
        defaultValue: 4,
        min: 1,
        max: 8,
        step: 1,
      },
      {
        ...audioStart,
        id: "seed",
        integer: true,
        label: "Seed",
        group: "Expert",
        defaultValue: 42,
        max: 4294967295,
        step: 1,
      },
    ],
    privacyEffects: [],
    costEffects: [],
  },
  {
    type: "source.audio",
    version: 1,
    displayName: "Audio asset",
    summary: "",
    layer: "source",
    category: "Input",
    paletteVisibility: "default",
    inputs: [],
    outputs: [audio],
    fields: [assetField],
    privacyEffects: [],
    costEffects: [],
  },
  {
    type: "source.video",
    version: 1,
    displayName: "Video asset",
    summary: "",
    layer: "source",
    category: "Input",
    paletteVisibility: "default",
    inputs: [],
    outputs: [video],
    fields: [assetField],
    privacyEffects: [],
    costEffects: [],
  },
  {
    type: "operation.video-sequence",
    version: 1,
    displayName: "Join scenes",
    summary: "",
    layer: "operation",
    category: "Transform",
    paletteVisibility: "default",
    inputs: [
      ...Array.from({ length: 8 }, (_, index) => ({
        ...video,
        id: `scene-${index + 1}`,
        label: `Scene ${index + 1}`,
        required: index < 2,
      })),
      { ...audio, required: false },
    ],
    outputs: [video],
    fields: [audioStart],
    privacyEffects: [],
    costEffects: [],
  },
  {
    type: "operation.video-audio",
    version: 1,
    displayName: "Set soundtrack",
    summary: "",
    layer: "operation",
    category: "Transform",
    paletteVisibility: "default",
    inputs: [video, audio],
    outputs: [video],
    fields: [audioStart],
    privacyEffects: [],
    costEffects: [],
  },
];
