// This file is generated by scripts/generate-runtime-contract.mjs.
// Source of truth: src/shared/runtime-config.schema.json

export const RUNTIME_CONFIG_SCHEMA_ID = "https://machdoch.local/schemas/runtime-config.schema.json";
export const RUNTIME_CONFIG_SCHEMA_VERSION = 1 as const;

export const RUN_MODES = ["ask", "machdoch"] as const;
export type RunMode = (typeof RUN_MODES)[number];

export const REASONING_MODES = ["default", "none", "minimal", "low", "medium", "high", "xhigh", "max", "ultra"] as const;
export type ReasoningMode = (typeof REASONING_MODES)[number];

export const VALID_TOOLS = ["filesystem", "shell", "network", "browser", "git", "packages", "mcp", "scheduler", "utilities"] as const;
export type ToolName = (typeof VALID_TOOLS)[number];

export const VALID_MODEL_PROVIDERS = ["openai", "anthropic", "google", "langdock", "codex-cli", "claude-cli", "copilot-cli"] as const;
export type ConfiguredModelProvider = (typeof VALID_MODEL_PROVIDERS)[number];

export const MODEL_PROVIDERS = ["openai", "anthropic", "google", "langdock", "codex-cli", "claude-cli", "copilot-cli", "unconfigured"] as const;
export type ModelProvider = (typeof MODEL_PROVIDERS)[number];

export const USER_API_PROVIDERS = ["openai", "anthropic", "google", "langdock"] as const;
export type UserApiProvider = (typeof USER_API_PROVIDERS)[number];

export const AGENT_CLI_PROVIDERS = ["codex-cli", "claude-cli", "copilot-cli"] as const;
export type AgentCliProvider = (typeof AGENT_CLI_PROVIDERS)[number];

export const VALID_WEB_SEARCH_PROVIDERS = ["none", "perplexity", "tavily", "serper"] as const;
export type WebSearchProvider = (typeof VALID_WEB_SEARCH_PROVIDERS)[number];

export const USER_WEB_SEARCH_PROVIDERS = ["perplexity", "tavily", "serper"] as const;
export type UserWebSearchProvider = (typeof USER_WEB_SEARCH_PROVIDERS)[number];

export const USER_AUDIO_AI_PROVIDERS = ["openai", "google"] as const;
export type AudioProvider = (typeof USER_AUDIO_AI_PROVIDERS)[number];

export const VALID_AUDIO_AI_PROVIDERS = ["none", "openai", "google"] as const;
export type VoiceAiProvider = (typeof VALID_AUDIO_AI_PROVIDERS)[number];
export type SpeechToTextProvider = VoiceAiProvider;

export const RUNTIME_MEMORY_SCOPES = ["session", "global"] as const;
export type RuntimeMemoryScope = (typeof RUNTIME_MEMORY_SCOPES)[number];

export const USER_REVIEW_MODEL_MODES = ["base", "dedicated"] as const;
export type UserReviewModelMode = (typeof USER_REVIEW_MODEL_MODES)[number];

export const DEFAULT_MODEL_PROVIDER = "openai" as const satisfies ConfiguredModelProvider;
export const DEFAULT_MODEL_BY_PROVIDER = {
  "openai": "gpt-5.5",
  "anthropic": "claude-sonnet-5",
  "google": "gemini-3.5-flash",
  "langdock": "gpt-5.5",
  "codex-cli": "gpt-5.5",
  "claude-cli": "sonnet",
  "copilot-cli": "auto"
} as const satisfies Record<ConfiguredModelProvider, string>;

export const RUNTIME_ENV_KEYS = ["MACHDOCH_MODE", "MACHDOCH_MODEL", "MACHDOCH_REASONING", "MACHDOCH_OFFLINE", "MACHDOCH_WEB_SEARCH_PROVIDER", "MACHDOCH_EXECUTOR_TURNS", "MACHDOCH_AUTOPILOT_ITERATIONS", "MACHDOCH_INFINITE", "MACHDOCH_CODEX_CLI_PATH", "MACHDOCH_CLAUDE_CLI_PATH", "MACHDOCH_COPILOT_CLI_PATH", "LANGDOCK_REGION", "LANGDOCK_BASE_URL"] as const;
export const PROVIDER_ENV_KEY_BY_PROVIDER = {
  "openai": "OPENAI_API_KEY",
  "anthropic": "ANTHROPIC_API_KEY",
  "google": "GOOGLE_API_KEY",
  "langdock": "LANGDOCK_API_KEY"
} as const satisfies Record<UserApiProvider, string>;
export const AGENT_CLI_PROVIDER_ENV_KEY_BY_PROVIDER = {
  "codex-cli": "MACHDOCH_CODEX_CLI_PATH",
  "claude-cli": "MACHDOCH_CLAUDE_CLI_PATH",
  "copilot-cli": "MACHDOCH_COPILOT_CLI_PATH"
} as const satisfies Record<AgentCliProvider, string>;
export const WEB_SEARCH_ENV_KEY_BY_PROVIDER = {
  "perplexity": "PERPLEXITY_API_KEY",
  "tavily": "TAVILY_API_KEY",
  "serper": "SERPER_API_KEY"
} as const satisfies Record<UserWebSearchProvider, string>;

export const DEFAULT_USER_AGENT_LIMITS_SETTINGS = {
  "infinite": false,
  "executorTurns": 64,
  "autopilotExecutorIterations": 16
} as const satisfies UserAgentLimitsSettings;
export const AGENT_LIMIT_BOUNDS = {
  "executorTurns": {
    "min": 1,
    "max": 1000
  },
  "autopilotExecutorIterations": {
    "min": 1,
    "max": 100
  }
} as const;
export const DEFAULT_USER_REVIEW_MODEL_SETTINGS = {
  "mode": "base"
} as const satisfies UserReviewModelSettings;
export const DEFAULT_USER_DESKTOP_SETTINGS = {
  "autostartEnabled": false,
  "autostartMinimized": false,
  "autostartToTray": false,
  "alwaysRunAsAdministrator": false,
  "assistantBubbleEnabled": true,
  "assistantBubbleHideWhenFullscreen": true,
  "assistantBubbleTemporarilyHideSeconds": 6,
  "aiContextMaxMessages": 60,
  "inactiveSessionArchiveDays": 7,
  "archivedSessionRetentionDays": 7,
  "quickVoiceEnabled": true,
  "quickVoiceShortcut": "CommandOrControl+Alt+V",
  "quickVoiceSilenceSeconds": 1.8,
  "quickVoiceMaxMessages": 50
} as const satisfies UserDesktopSettings;
export const DESKTOP_SETTING_BOUNDS = {
  "assistantBubbleTemporarilyHideSeconds": {
    "min": 2,
    "max": 30
  },
  "aiContextMaxMessages": {
    "min": 1,
    "max": 200
  },
  "inactiveSessionArchiveDays": {
    "min": 1,
    "max": 365
  },
  "archivedSessionRetentionDays": {
    "min": 1,
    "max": 365
  },
  "quickVoiceSilenceSeconds": {
    "min": 0.8,
    "max": 8
  },
  "quickVoiceMaxMessages": {
    "min": 10,
    "max": 200
  }
} as const;

export const isRuntimeContractValue = <T extends readonly string[]>(
  values: T,
  value: string | undefined,
): value is T[number] =>
  value !== undefined && values.some((entry) => entry === value);

export const isRunMode = (value: string | undefined): value is RunMode =>
  isRuntimeContractValue(RUN_MODES, value);

export const isReasoningMode = (
  value: string | undefined,
): value is ReasoningMode =>
  isRuntimeContractValue(REASONING_MODES, value);

export const isConfiguredModelProvider = (
  value: string | undefined,
): value is ConfiguredModelProvider =>
  isRuntimeContractValue(VALID_MODEL_PROVIDERS, value);

export const isModelProvider = (value: string | undefined): value is ModelProvider =>
  isRuntimeContractValue(MODEL_PROVIDERS, value);

export const isUserApiProvider = (value: string | undefined): value is UserApiProvider =>
  isRuntimeContractValue(USER_API_PROVIDERS, value);

export const isAgentCliProvider = (value: string | undefined): value is AgentCliProvider =>
  isRuntimeContractValue(AGENT_CLI_PROVIDERS, value);

export const isWebSearchProvider = (
  value: string | undefined,
): value is WebSearchProvider =>
  isRuntimeContractValue(VALID_WEB_SEARCH_PROVIDERS, value);

export const isUserWebSearchProvider = (
  value: string | undefined,
): value is UserWebSearchProvider =>
  isRuntimeContractValue(USER_WEB_SEARCH_PROVIDERS, value);

export const isAudioProvider = (value: string | undefined): value is AudioProvider =>
  isRuntimeContractValue(USER_AUDIO_AI_PROVIDERS, value);

export const isVoiceAiProvider = (
  value: string | undefined,
): value is VoiceAiProvider =>
  isRuntimeContractValue(VALID_AUDIO_AI_PROVIDERS, value);

export interface WorkspaceCompatibilityConfig {
  discoverGithubCustomizations?: boolean;
}

export interface RuntimeAgentLimitOverrides {
  infinite?: boolean;
  executorTurns?: number;
  autopilotExecutorIterations?: number;
}

export interface RuntimeAgentLimits {
  executorTurns: number | null;
  autopilotExecutorIterations: number | null;
}

export interface WorkspaceConfigFile {
  defaultMode?: RunMode;
  provider?: ConfiguredModelProvider;
  model?: string;
  reasoning?: ReasoningMode;
  offline?: boolean;
  agentLimits?: RuntimeAgentLimitOverrides;
  compatibility?: WorkspaceCompatibilityConfig;
}

export interface ProviderAvailability {
  provider: ConfiguredModelProvider;
  configured: boolean;
}

export interface WebSearchProviderAvailability {
  provider: UserWebSearchProvider;
  configured: boolean;
}

export interface AudioProviderAvailability {
  provider: AudioProvider;
  configured: boolean;
}

export interface RuntimeWebSearchConfig {
  activeProvider: WebSearchProvider;
  providerAvailability: WebSearchProviderAvailability[];
}

export interface RuntimeReviewModelConfig {
  mode: UserReviewModelMode;
  provider?: ConfiguredModelProvider;
  model?: string;
}

export interface UserWebSearchSettings {
  activeProvider: WebSearchProvider;
  apiKeys: UserWebSearchApiKeys;
  providerAvailability: WebSearchProviderAvailability[];
}

export interface UserVoiceSettings {
  activeProvider: VoiceAiProvider;
  providerAvailability: AudioProviderAvailability[];
}

export interface UserSpeechToTextSettings {
  activeProvider: SpeechToTextProvider;
  inputDeviceId: string | null;
  providerAvailability: AudioProviderAvailability[];
}

export interface RuntimeConfig {
  workspaceRoot: string;
  workspaceConfigPath?: string;
  userConfigPath?: string;
  mode: RunMode;
  provider: ModelProvider;
  model: string;
  reasoning: ReasoningMode;
  offline: boolean;
  agentLimits?: RuntimeAgentLimits;
  compatibility: WorkspaceCompatibilityConfig;
  providerAvailability: ProviderAvailability[];
  webSearch: RuntimeWebSearchConfig;
  reviewModel: RuntimeReviewModelConfig;
}

export interface UiControlAvailability {
  available: boolean;
  platform: "windows" | "macos" | "linux" | "unknown";
  supportsScreenshots: boolean;
  supportsWindowEnumeration: boolean;
  supportsInput: boolean;
  supportsWindowHandles: boolean;
  reason?: string;
}

export interface RuntimeSnapshot extends Omit<RuntimeConfig, "agentLimits"> {
  defaultMode: RunMode;
  defaultReasoning: ReasoningMode;
  agentLimits: RuntimeAgentLimits;
  uiControl?: UiControlAvailability;
}

export type UserProviderApiKeys = Partial<Record<UserApiProvider, string>>;
export type UserAgentCliPaths = Partial<Record<AgentCliProvider, string>>;
export type UserWebSearchApiKeys = Partial<Record<UserWebSearchProvider, string>>;

export interface UserWebSearchConfigFile {
  activeProvider?: WebSearchProvider;
  apiKeys?: UserWebSearchApiKeys;
}

export interface UserVoiceConfigFile {
  activeProvider?: VoiceAiProvider;
}

export interface UserSpeechToTextConfigFile {
  activeProvider?: SpeechToTextProvider;
  inputDeviceId?: string;
}

export interface RuntimeMemoryEntry {
  id: string;
  scope: RuntimeMemoryScope;
  content: string;
  createdAt: number;
  updatedAt: number;
}

export interface UserMemoryConfigFile {
  globalEnabled?: boolean;
  entries?: RuntimeMemoryEntry[];
}

export interface UserReviewModelConfigFile {
  mode?: UserReviewModelMode;
  provider?: ConfiguredModelProvider;
  model?: string;
}

export interface UserConfigFile {
  apiKeys?: UserProviderApiKeys;
  agentCliPaths?: UserAgentCliPaths;
  webSearch?: UserWebSearchConfigFile;
  voice?: UserVoiceConfigFile;
  speechToText?: UserSpeechToTextConfigFile;
  desktop?: Partial<UserDesktopSettings>;
  agentLimits?: RuntimeAgentLimitOverrides;
  memory?: UserMemoryConfigFile;
  reviewModel?: UserReviewModelConfigFile;
}

export interface UserAgentLimitsSettings {
  infinite: boolean;
  executorTurns: number;
  autopilotExecutorIterations: number;
}

export interface UserReviewModelSettings {
  mode: UserReviewModelMode;
  provider?: ConfiguredModelProvider;
  model?: string;
}

export interface UserDesktopSettings {
  autostartEnabled: boolean;
  autostartMinimized: boolean;
  autostartToTray: boolean;
  alwaysRunAsAdministrator: boolean;
  assistantBubbleEnabled: boolean;
  assistantBubbleHideWhenFullscreen: boolean;
  assistantBubbleTemporarilyHideSeconds: number;
  aiContextMaxMessages: number;
  inactiveSessionArchiveDays: number;
  archivedSessionRetentionDays: number;
  quickVoiceEnabled: boolean;
  quickVoiceShortcut: string;
  quickVoiceSilenceSeconds: number;
  quickVoiceMaxMessages: number;
}
