import type {
  RalphBlockSettings,
  RalphFlow,
  RalphUtilityBlock,
  RalphUtilityConfig,
} from "../ralph.js";
import type { RalphStarterFlow } from "../ralph-starter-flows.js";
import { RALPH_VALIDATOR_JSON_SCHEMA } from "../_helpers/parse-ralph-validator-json-result.helper.js";

const VERIFICATION_TIMEOUT_SECONDS = 30 * 60;

const taskSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "id",
    "title",
    "status",
    "batchKey",
    "dependencies",
    "likelyFiles",
    "priority",
    "evidence",
    "value",
    "currentBehavior",
    "proposedBehavior",
    "acceptanceCriteria",
    "verificationPlan",
    "verificationTier",
    "reviewTier",
    "rollbackNotes",
  ],
  properties: {
    id: { type: "string", minLength: 1 },
    title: { type: "string", minLength: 1 },
    status: {
      type: "string",
      enum: [
        "planned",
        "implementing",
        "verifying",
        "repairing",
        "completed",
        "deferred",
      ],
    },
    batchKey: { type: "string", minLength: 1 },
    dependencies: { type: "array", items: { type: "string" } },
    likelyFiles: {
      type: "array",
      minItems: 1,
      items: { type: "string", minLength: 1 },
    },
    priority: { type: "number", minimum: 0, maximum: 100 },
    evidence: {
      type: "array",
      minItems: 1,
      items: { type: "string", minLength: 1 },
    },
    value: { type: "string", minLength: 1 },
    currentBehavior: { type: "string", minLength: 1 },
    proposedBehavior: { type: "string", minLength: 1 },
    acceptanceCriteria: {
      type: "array",
      minItems: 1,
      items: { type: "string", minLength: 1 },
    },
    verificationPlan: {
      type: "array",
      minItems: 1,
      items: { type: "string", minLength: 1 },
    },
    verificationTier: {
      type: "string",
      enum: ["focused", "standard", "broad"],
    },
    reviewTier: {
      type: "string",
      enum: ["validator-only", "strict"],
    },
    rollbackNotes: { type: "array", items: { type: "string" } },
  },
} as const;

const planDraftSchema = {
  type: "object",
  additionalProperties: false,
  required: ["decision", "rationale", "tasks", "stopReason"],
  properties: {
    decision: { type: "string", enum: ["IMPLEMENT", "STOP", "DEFER"] },
    rationale: { type: "string", minLength: 1 },
    tasks: { type: "array", maxItems: 5, items: taskSchema },
    stopReason: { type: "string", minLength: 1 },
  },
} as const;

const modelSettings = (
  reasoning: "medium" | "high",
  webAccess = false,
): RalphBlockSettings => ({
  workspace: { mode: "default" },
  reasoning,
  ...(webAccess ? { webAccess: true } : {}),
  attachments: [],
  packs: [],
});

const promptSettings = (
  reasoning: "medium" | "high",
  webAccess = false,
): RalphBlockSettings => ({
  ...modelSettings(reasoning, webAccess),
  maxIterations: 1,
});

const utilityBlock = (
  id: string,
  title: string,
  utility: RalphUtilityConfig,
  column: number,
  row = 0,
  settings?: RalphBlockSettings,
): RalphUtilityBlock => ({
  id,
  title,
  position: { x: column * 330, y: row * 230 },
  size: { width: 300, height: 180 },
  ...(settings ? { settings } : {}),
  type: "UTILITY",
  utility,
});

const edge = (id: string, from: string, fromOutput: string, to: string) => ({
  id,
  from,
  fromOutput,
  to,
});

const autonomousCodeImprovementLoopFlow: RalphFlow = {
  schemaVersion: 1,
  id: "starter-autonomous-code-improvement-loop",
  alias: "autonomous-code-improvement-loop",
  name: "Autonomous Code Improvement Loop",
  description:
    "Autonomous code-improvement cycle that retains and verifies an evidence-backed portfolio until it is complete or genuinely blocked.",
  settings: {
    maxTransitions: 5_000,
    autonomy: {
      recoverFailedEnd: true,
      maxRecoveryAttempts: 3,
      transitionExhaustion: "checkpoint",
      recoveryExhaustion: "defer",
      deferToBlockId: "record-deferred-outcome",
    },
  },
  variables: [
    { name: "scopeRoot", type: "path", default: ".", required: false },
    {
      name: "scopeSelectionStrategy",
      type: "text",
      default: "priority",
      required: false,
    },
    {
      name: "scopeRegistryFile",
      type: "path",
      default:
        ".machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json",
      required: false,
    },
    {
      name: "scopeRegistryMarkdown",
      type: "path",
      default:
        ".machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md",
      required: false,
    },
    {
      name: "scopeScanMaxDepth",
      type: "number",
      default: "6",
      required: false,
    },
    {
      name: "scopeScanMaxResults",
      type: "number",
      default: "240",
      required: false,
    },
    {
      name: "improvementPolicy",
      type: "text",
      default:
        "Prefer high-confidence improvements to correctness, reliability, UX, accessibility, performance, error handling, tests, or maintainability.",
      required: false,
    },
    {
      name: "meaningfulThreshold",
      type: "text",
      default:
        "Continue only for concrete code, test, runtime, UX, accessibility, performance, or security evidence. Exclude cosmetic churn and speculative cleanup.",
      required: false,
    },
    {
      name: "riskTolerance",
      type: "text",
      default: "ambitious",
      required: false,
    },
    {
      name: "excludePaths",
      type: "text",
      default:
        "node_modules, dist, build, coverage, target, .next, .nuxt, .turbo, .cache, vendor, generated, .machdoch",
      required: false,
    },
    {
      name: "enableOnlineResearch",
      type: "boolean",
      default: "true",
      required: false,
    },
    {
      name: "allowDependencyChanges",
      type: "boolean",
      default: "true",
      required: false,
    },
    {
      name: "allowSchemaChanges",
      type: "boolean",
      default: "true",
      required: false,
    },
    {
      name: "allowPublicApiChanges",
      type: "boolean",
      default: "true",
      required: false,
    },
    { name: "verificationCommand", type: "text", default: "", required: false },
    {
      name: "enableVisualReview",
      type: "boolean",
      default: "false",
      required: false,
    },
    { name: "targetUrl", type: "url", default: "", required: false },
    { name: "healthUrl", type: "url", default: "", required: false },
    { name: "screenshotPath", type: "path", default: "", required: false },
    {
      name: "maxImprovementPasses",
      type: "number",
      default: "3",
      required: false,
    },
    {
      name: "maxVerificationRepairPasses",
      type: "number",
      default: "4",
      required: false,
    },
    {
      name: "maxFinalValidationScans",
      type: "number",
      default: "3",
      required: false,
    },
    {
      name: "activeImprovementPlanFile",
      type: "path",
      default: ".machdoch/ralph/code-improvements/active-improvement-plan.json",
      required: false,
    },
    {
      name: "completedImprovementsFile",
      type: "path",
      default: ".machdoch/ralph/code-improvements/completed-improvements.jsonl",
      required: false,
    },
    {
      name: "deferredImprovementsFile",
      type: "path",
      default: ".machdoch/ralph/code-improvements/deferred-improvements.jsonl",
      required: false,
    },
    {
      name: "improvementOutcomesFile",
      type: "path",
      default: ".machdoch/ralph/code-improvements/outcomes.jsonl",
      required: false,
    },
    {
      name: "archivedImprovementsDirectory",
      type: "path",
      default: ".machdoch/ralph/code-improvements/archive",
      required: false,
    },
    {
      name: "projectCommandsFile",
      type: "path",
      default: "{{run:artifactRoot}}/code-improvements/project-commands.json",
      required: false,
    },
    {
      name: "reviewFile",
      type: "path",
      default: "{{run:artifactRoot}}/code-improvements/review.json",
      required: false,
    },
    {
      name: "gitSnapshotFile",
      type: "path",
      default: "{{run:artifactRoot}}/code-improvements/git-snapshot.json",
      required: false,
    },
    {
      name: "gitDiffFile",
      type: "path",
      default: "{{run:artifactRoot}}/code-improvements/git-diff.json",
      required: false,
    },
    {
      name: "improvementReportFile",
      type: "path",
      default: "{{run:artifactRoot}}/code-improvements/final-report.json",
      required: false,
    },
    {
      name: "improvementReportMarkdown",
      type: "path",
      default: "{{run:artifactRoot}}/code-improvements/final-report.md",
      required: false,
    },
  ],
  blocks: [
    {
      id: "start",
      title: "Start",
      position: { x: 0, y: 0 },
      size: { width: 256, height: 140 },
      type: "START",
    },
    utilityBlock(
      "find-active-improvement",
      "Find Active Improvement Plan",
      {
        type: "FILE_EXISTS",
        path: "{{activeImprovementPlanFile:path=.machdoch/ralph/code-improvements/active-improvement-plan.json}}",
      },
      1,
    ),
    utilityBlock(
      "begin-scope-cycle",
      "Begin Scope Cycle",
      {
        type: "BEGIN_SCOPE_CYCLE",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md}}",
        strategy: "{{scopeSelectionStrategy:text=priority}}",
        includeMarkdown: true,
      },
      2,
      1,
    ),
    utilityBlock(
      "scan-scopes",
      "Scan Scope Evidence",
      {
        type: "SCAN_SCOPE_EVIDENCE",
        rootPath: "{{scopeRoot:path=.}}",
        excludePaths:
          "{{excludePaths:text=node_modules, dist, build, coverage, target, .next, .nuxt, .turbo, .cache, vendor, generated, .machdoch}}",
        maxDepth: "{{scopeScanMaxDepth:number=6}}",
        maxResults: "{{scopeScanMaxResults:number=240}}",
      },
      2,
    ),
    utilityBlock(
      "update-scope-registry",
      "Update Scope Registry",
      {
        type: "UPDATE_SCOPE_REGISTRY",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md}}",
        strategy: "{{scopeSelectionStrategy:text=priority}}",
        includeMarkdown: true,
      },
      3,
    ),
    utilityBlock(
      "select-scope",
      "Select Improvement Scope",
      {
        type: "SELECT_SCOPE",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        strategy: "{{scopeSelectionStrategy:text=priority}}",
      },
      4,
    ),
    utilityBlock(
      "detect-selected-commands",
      "Detect Project Commands",
      {
        type: "DETECT_PROJECT_COMMANDS",
        rootPath: "{{data:select-scope:scope.paths.0}}",
        outputPath:
          "{{projectCommandsFile:path=.machdoch/ralph/code-improvements/project-commands.json}}",
      },
      5,
      -1,
    ),
    utilityBlock(
      "read-completed-improvements",
      "Read Completed Improvements",
      {
        type: "QUERY_JSONL",
        path: "{{completedImprovementsFile:path=.machdoch/ralph/code-improvements/completed-improvements.jsonl}}",
        maxResults: 50,
        order: "newest",
      },
      5,
    ),
    utilityBlock(
      "read-deferred-improvements",
      "Read Deferred Improvements",
      {
        type: "QUERY_JSONL",
        path: "{{deferredImprovementsFile:path=.machdoch/ralph/code-improvements/deferred-improvements.jsonl}}",
        maxResults: 50,
        order: "newest",
      },
      6,
      1,
    ),
    utilityBlock(
      "propose-improvements",
      "Discover Improvement Portfolio",
      {
        type: "PROMPT_JSON",
        maxAttempts: 2,
        schema: {
          type: "object",
          additionalProperties: false,
          required: ["constitution", "candidates", "researchDecision"],
          properties: {
            constitution: {
              type: "object",
              additionalProperties: false,
              required: ["purpose", "constraints"],
              properties: {
                purpose: { type: "string" },
                constraints: { type: "array", items: { type: "string" } },
              },
            },
            candidates: {
              type: "array",
              minItems: 1,
              maxItems: 5,
              items: {
                type: "object",
                additionalProperties: false,
                required: [
                  "id",
                  "title",
                  "evidence",
                  "valueScore",
                  "riskScore",
                ],
                properties: {
                  id: { type: "string" },
                  title: { type: "string" },
                  evidence: { type: "array", items: { type: "string" } },
                  valueScore: { type: "number", minimum: 0, maximum: 100 },
                  riskScore: { type: "number", minimum: 0, maximum: 100 },
                },
              },
            },
            researchDecision: {
              type: "object",
              additionalProperties: false,
              required: ["needsResearch", "queries"],
              properties: {
                needsResearch: { type: "boolean" },
                queries: { type: "array", items: { type: "string" } },
              },
            },
          },
        },
        prompt:
          "Inspect scope {{result:select-scope}}, commands {{result:detect-selected-commands}}, completed history {{result:read-completed-improvements}}, and deferred portfolio history {{result:read-deferred-improvements}} without edits. Preserve still-relevant deferred work instead of silently replacing it. Produce a concise constitution and 3-5 materially different evidence-backed candidates. Score value and risk 0-100. Prefer correctness, reliability, performance, accessibility, test, runtime, complexity, and churn evidence. Identify only research that can change the ranking. Return only schema-valid JSON.",
      },
      6,
      0,
      modelSettings("high"),
    ),
    utilityBlock(
      "research-decision",
      "Use Online Research",
      {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'variables.enableOnlineResearch === "true" && lastData?.output?.researchDecision?.needsResearch === true',
        },
      },
      7,
      -1,
    ),
    {
      id: "improvement-research",
      title: "Improvement Research",
      position: { x: 2_350, y: -230 },
      size: { width: 300, height: 200 },
      settings: promptSettings("medium", true),
      type: "PROMPT",
      prompt:
        "Research only {{data:propose-improvements:output.researchDecision.queries}}. Use search_web and fetch_url when available, prefer official maintainer and primary sources, verify version-sensitive claims against local metadata, and report source links, freshness, implications, and ranking changes. If web search is unavailable, continue from local evidence. Do not edit files.",
    },
    utilityBlock(
      "choose-improvement",
      "Plan Improvement Portfolio",
      {
        type: "PROMPT_JSON",
        maxAttempts: 2,
        schema: planDraftSchema,
        prompt:
          "Turn discovery {{data:propose-improvements:output}}, research {{summary:improvement-research}}, selected scope {{result:select-scope}}, commands {{result:detect-selected-commands}}, completed history {{result:read-completed-improvements}}, and deferred history {{result:read-deferred-improvements}} into a persistent portfolio. Resume still-relevant deferred packages with stable task ids and updated evidence. Return decision IMPLEMENT only when meaningful work remains. IMPLEMENT must retain every currently eligible meaningful package rather than selecting one and discarding the rest. Usually return 2-5 dependency-aware tasks; return one only when only one meaningful package exists. Each IMPLEMENT task must have status planned, stable kebab-case id, priority, likelyFiles, concrete evidence, bounded acceptance criteria, verification and review tiers, and rollback notes. DEFER only when unavailable external credentials or state block every task. STOP only with evidence that no meaningful candidate remains under {{meaningfulThreshold:text=}}. STOP and DEFER require empty tasks. Return only schema-valid JSON.",
      },
      8,
      0,
      modelSettings("high"),
    ),
    utilityBlock(
      "build-improvement-plan",
      "Build Improvement Plan",
      {
        type: "TRANSFORM_JSON",
        input: "{}",
        expression:
          "(() => { const draft = context.resultsByBlock?.get?.('choose-improvement')?.data?.output; const selection = context.resultsByBlock?.get?.('select-scope')?.data ?? {}; const scope = selection.scope; if (!draft || !scope || typeof scope.id !== 'string') throw new Error('Improvement plan requires a valid draft and selected scope.'); const tasks = Array.isArray(draft.tasks) ? draft.tasks : []; const cluster = selection.scopeCluster ?? { rootScopeId: scope.id, scopeIds: [scope.id], paths: Array.isArray(scope.paths) ? scope.paths : [], risk: scope.risk, rationale: ['Selected scope'] }; const ids = tasks.map((task) => String(task?.id ?? '')).filter(Boolean).join(','); return { planId: String(scope.id) + ':' + (ids || String(draft.decision).toLowerCase()), decision: draft.decision, rationale: draft.rationale, stopReason: draft.stopReason, scope, scopeCluster: cluster, constitution: context.resultsByBlock?.get?.('propose-improvements')?.data?.output?.constitution ?? {}, research: context.resultsByBlock?.get?.('improvement-research')?.summary ?? '', tasks }; })()",
      },
      9,
    ),
    utilityBlock(
      "has-actionable-improvement",
      "Actionable Improvement",
      {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "(() => { const plan = context.resultsByBlock?.['build-improvement-plan']?.data?.output; if (!['IMPLEMENT', 'STOP', 'DEFER'].includes(plan?.decision)) throw new Error('Code improvement plan decision is missing or invalid.'); if (plan.decision !== 'IMPLEMENT') return false; if (!Array.isArray(plan.tasks) || plan.tasks.length === 0) throw new Error('IMPLEMENT requires persisted tasks.'); return plan.tasks.every((task) => task?.status === 'planned' && typeof task.id === 'string' && task.id.length > 0); })()",
        },
      },
      10,
    ),
    utilityBlock(
      "selection-is-deferred",
      "Plan Deferred",
      {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "(() => { const decision = context.resultsByBlock?.['build-improvement-plan']?.data?.output?.decision; if (!['IMPLEMENT', 'STOP', 'DEFER'].includes(decision)) throw new Error('Code improvement plan decision is missing or invalid.'); return decision === 'DEFER'; })()",
        },
      },
      10,
      1,
    ),
    utilityBlock(
      "write-active-improvement",
      "Write Active Improvement Plan",
      {
        type: "WRITE_JSON",
        path: "{{activeImprovementPlanFile:path=.machdoch/ralph/code-improvements/active-improvement-plan.json}}",
        input: "{{data:build-improvement-plan:output}}",
      },
      11,
    ),
    utilityBlock(
      "read-active-improvement",
      "Read Active Improvement Plan",
      {
        type: "READ_JSON",
        path: "{{activeImprovementPlanFile:path=.machdoch/ralph/code-improvements/active-improvement-plan.json}}",
      },
      12,
    ),
    utilityBlock(
      "detect-project-commands",
      "Detect Active Plan Commands",
      {
        type: "DETECT_PROJECT_COMMANDS",
        rootPath: "{{data:read-active-improvement:json.scope.paths.0}}",
        outputPath:
          "{{projectCommandsFile:path=.machdoch/ralph/code-improvements/project-commands.json}}",
      },
      13,
    ),
    utilityBlock(
      "assess-improvement-tasks",
      "Assess Improvement Tasks",
      {
        type: "ASSESS_JSON_TASKS",
        path: "{{activeImprovementPlanFile:path=.machdoch/ralph/code-improvements/active-improvement-plan.json}}",
        jsonPath: "tasks",
        strategy: "priority",
        maxTasks: 1,
      },
      14,
    ),
    utilityBlock(
      "select-improvement-task",
      "Select Improvement Task",
      {
        type: "SELECT_JSON_TASK",
        path: "{{activeImprovementPlanFile:path=.machdoch/ralph/code-improvements/active-improvement-plan.json}}",
        jsonPath: "tasks",
        strategy: "priority",
        maxTasks: 1,
      },
      15,
    ),
    utilityBlock(
      "git-snapshot-before",
      "Git Snapshot",
      {
        type: "GIT_SNAPSHOT",
        cwd: ".",
        outputPath:
          "{{gitSnapshotFile:path=.machdoch/ralph/code-improvements/git-snapshot.json}}",
      },
      16,
      -1,
    ),
    utilityBlock(
      "select-verification-command",
      "Select Verification Tier",
      {
        type: "TRANSFORM_JSON",
        input: "{}",
        expression:
          "(() => { const task = context.resultsByBlock?.get?.('select-improvement-task')?.data?.tasks?.[0] ?? {}; const commands = context.resultsByBlock?.get?.('detect-project-commands')?.data ?? {}; const tierValid = ['focused', 'standard', 'broad'].includes(task.verificationTier); const tier = tierValid ? task.verificationTier : 'broad'; const reviewValid = ['validator-only', 'strict'].includes(task.reviewTier); const reviewTier = tier === 'broad' || !reviewValid ? 'strict' : task.reviewTier; const detected = tier === 'broad' ? commands.broadVerificationCommand : tier === 'standard' ? commands.standardVerificationCommand : commands.focusedVerificationCommand; return { tier, reviewTier, protocolValid: tierValid && reviewValid, command: (variables.verificationCommand ?? '').trim() || detected || commands.verificationCommand || '' }; })()",
      },
      17,
      -1,
    ),
    utilityBlock(
      "baseline-verification",
      "Record Verification Baseline",
      {
        type: "RUN_CHECK",
        command: "{{data:select-verification-command:output.command}}",
        fallbackCommand:
          "{{data:detect-project-commands:focusedVerificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: VERIFICATION_TIMEOUT_SECONDS,
      },
      18,
      -1,
    ),
    utilityBlock(
      "count-improvement-pass",
      "Count Improvement Pass",
      {
        type: "LOOP_COUNTER",
        counterName:
          "autonomous-code-improvement-loop.implementation-pass.{{data:read-active-improvement:json.planId}}.{{data:select-improvement-task:tasks.0.id}}",
        maxAttempts: "{{maxImprovementPasses:number=3}}",
      },
      18,
    ),
    {
      id: "implement-improvement",
      title: "Implement Improvement",
      position: { x: 6_300, y: 0 },
      size: { width: 320, height: 250 },
      settings: promptSettings("high"),
      type: "PROMPT",
      prompt:
        "Implement only selected task {{data:select-improvement-task:tasks.0}} from active plan {{data:read-active-improvement:json}}. Use git baseline {{result:git-snapshot-before}}, verification baseline {{result:baseline-verification}}, commands {{result:detect-project-commands}}, pass {{result:count-improvement-pass}}, validator feedback {{data:validate-improvement:output}}, review feedback {{data:independent-review:output}}, and scope guard {{result:scope-change-guard}}. Do not repeat discovery or modify task lifecycle fields; SELECT_JSON_TASK and MARK_JSON_TASK own state. Complete the bounded task and required adjacent tests/docs/imports. Dependency changes use allowDependencyChanges={{allowDependencyChanges:boolean=true}}, schemas use allowSchemaChanges={{allowSchemaChanges:boolean=true}}, and public APIs use allowPublicApiChanges={{allowPublicApiChanges:boolean=true}} only when necessary and verified. Do not start or restart servers.",
    },
    utilityBlock(
      "mark-improvement-task-verifying",
      "Mark Task Verifying",
      {
        type: "MARK_JSON_TASK",
        path: "{{activeImprovementPlanFile:path=.machdoch/ralph/code-improvements/active-improvement-plan.json}}",
        jsonPath: "tasks",
        input: "{{data:select-improvement-task}}",
        status: "verifying",
      },
      20,
    ),
    utilityBlock(
      "verification-decision",
      "Run Verification",
      {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "Boolean(context.resultsByBlock?.['select-verification-command']?.data?.output?.command?.trim())",
        },
      },
      21,
      -1,
    ),
    utilityBlock(
      "run-verification",
      "Run Verification",
      {
        type: "RUN_CHECK",
        command: "{{data:select-verification-command:output.command}}",
        fallbackCommand:
          "{{data:detect-project-commands:focusedVerificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: VERIFICATION_TIMEOUT_SECONDS,
      },
      22,
      -1,
    ),
    utilityBlock(
      "mark-improvement-task-repairing",
      "Mark Task Repairing",
      {
        type: "MARK_JSON_TASK",
        path: "{{activeImprovementPlanFile:path=.machdoch/ralph/code-improvements/active-improvement-plan.json}}",
        jsonPath: "tasks",
        input: "{{data:select-improvement-task}}",
        status: "repairing",
      },
      22,
      1,
    ),
    utilityBlock(
      "count-verification-repair",
      "Count Verification Repair",
      {
        type: "LOOP_COUNTER",
        counterName:
          "autonomous-code-improvement-loop.verification-repair.{{data:read-active-improvement:json.planId}}.{{data:select-improvement-task:tasks.0.id}}",
        maxAttempts: "{{maxVerificationRepairPasses:number=4}}",
      },
      23,
      1,
    ),
    {
      id: "fix-validation-failures",
      title: "Fix Validation Failures",
      position: { x: 7_920, y: 230 },
      size: { width: 320, height: 230 },
      settings: promptSettings("medium"),
      type: "PROMPT",
      prompt:
        "Repair only selected task {{data:select-improvement-task:tasks.0}} using verification {{result:run-verification}}, review {{data:independent-review:output}}, validation {{data:validate-improvement:output}}, and baseline {{result:baseline-verification}}. Fix concrete new or worsened failures within {{data:read-active-improvement:json.scopeCluster}}. Do not rediscover work, modify task state, broaden the task, or start servers.",
    },
    utilityBlock(
      "visual-decision",
      "Run Visual Review",
      {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'variables.enableVisualReview === "true" && (Boolean(variables.targetUrl?.trim()) || Boolean(variables.screenshotPath?.trim()))',
        },
      },
      23,
      -1,
    ),
    utilityBlock(
      "visual-review",
      "Visual Review",
      {
        type: "UI_ANALYZE",
        adapter: "auto",
        targetUrl: "{{targetUrl:url=}}",
        screenshotPath: "{{screenshotPath:path=}}",
        server: { mode: "existing", healthUrl: "{{healthUrl:url=}}" },
        checks: {
          screenshots: true,
          accessibility: true,
          console: true,
          network: true,
          responsive: true,
        },
        viewports: [
          { name: "desktop", width: 1280, height: 900 },
          { name: "tablet", width: 768, height: 1024 },
          { name: "mobile", width: 390, height: 844 },
          { name: "small-mobile", width: 320, height: 568 },
        ],
        timeoutSeconds: 30,
        fullPage: true,
        waitUntil: "domcontentloaded",
      },
      24,
      -1,
    ),
    utilityBlock(
      "git-diff-summary",
      "Git Diff Summary",
      {
        type: "GIT_DIFF_SUMMARY",
        cwd: ".",
        outputPath:
          "{{gitDiffFile:path=.machdoch/ralph/code-improvements/git-diff.json}}",
      },
      25,
      -1,
    ),
    utilityBlock(
      "scope-change-guard",
      "Guard Improvement Scope",
      {
        type: "CHANGE_SCOPE_GUARD",
        baselineBlockId: "git-snapshot-before",
        input:
          '{"scope":{{data:read-active-improvement:json.scope}},"gitSummary":{{data:git-diff-summary}}}',
      },
      26,
      -1,
    ),
    utilityBlock(
      "work-yield-analysis",
      "Assess Work Yield",
      {
        type: "TRANSFORM_JSON",
        input: "{}",
        expression:
          "(() => { const diff = context.resultsByBlock?.get?.('git-diff-summary')?.data ?? {}; const prior = context.resultsByBlock?.get?.('work-yield-analysis')?.data?.output ?? {}; const taskId = String(context.resultsByBlock?.get?.('select-improvement-task')?.data?.tasks?.[0]?.id ?? ''); const files = Array.isArray(diff.files) ? diff.files.map((file) => String(file?.path ?? '')).filter(Boolean).sort() : []; const signature = files.join('|'); return { taskId, changedFiles: files, madeProgress: files.length > 0 && (prior.taskId !== taskId || prior.signature !== signature), signature, scopeGuard: context.resultsByBlock?.get?.('scope-change-guard')?.output ?? '' }; })()",
      },
      27,
      -1,
    ),
    utilityBlock(
      "useful-work-produced",
      "Useful Work Produced",
      {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "lastData?.output?.madeProgress === true && lastData?.output?.scopeGuard === 'IN_SCOPE'",
        },
      },
      28,
      -1,
    ),
    utilityBlock(
      "review-tier-decision",
      "Strict Review",
      {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            'context.resultsByBlock?.["select-verification-command"]?.data?.output?.reviewTier === "strict"',
        },
      },
      29,
      -1,
    ),
    utilityBlock(
      "independent-review",
      "Independent Review",
      {
        type: "PROMPT_JSON",
        outputPath:
          "{{reviewFile:path=.machdoch/ralph/code-improvements/review.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          additionalProperties: false,
          required: ["decision", "summary", "findings"],
          properties: {
            decision: { type: "string", enum: ["PASS", "FIX", "DEFER"] },
            summary: { type: "string" },
            findings: {
              type: "array",
              items: {
                type: "object",
                additionalProperties: false,
                required: ["severity", "title", "evidence", "requiredFix"],
                properties: {
                  severity: { type: "string" },
                  title: { type: "string" },
                  evidence: { type: "string" },
                  requiredFix: { type: "string" },
                },
              },
            },
          },
        },
        prompt:
          "Review selected task {{data:select-improvement-task:tasks.0}} from active plan {{data:read-active-improvement:json}}, diff {{result:git-diff-summary}}, verification baseline {{result:baseline-verification}}, post-change verification {{result:run-verification}}, and visual review {{result:visual-review}}. PASS requires a cohesive verified result with no new regression. FIX requires a concrete autonomous repair. DEFER is only for unavailable external credentials or state. Return only schema-valid JSON.",
      },
      30,
      -1,
      modelSettings("high"),
    ),
    utilityBlock(
      "review-is-deferred",
      "Review Deferred",
      {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "(() => { const decision = context.resultsByBlock?.['independent-review']?.data?.output?.decision; if (!['PASS', 'FIX', 'DEFER'].includes(decision)) throw new Error('Code improvement review decision is missing or invalid.'); return decision === 'DEFER'; })()",
        },
      },
      31,
      -1,
    ),
    utilityBlock(
      "review-needs-fix",
      "Review Needs Fix",
      {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "(() => { const decision = context.resultsByBlock?.['independent-review']?.data?.output?.decision; if (!['PASS', 'FIX', 'DEFER'].includes(decision)) throw new Error('Code improvement review decision is missing or invalid.'); return decision === 'FIX'; })()",
        },
      },
      32,
      -1,
    ),
    utilityBlock(
      "count-final-validation-scan",
      "Count Final Validation Scan",
      {
        type: "LOOP_COUNTER",
        counterName:
          "autonomous-code-improvement-loop.final-validation-scan.{{data:read-active-improvement:json.planId}}.{{data:select-improvement-task:tasks.0.id}}",
        maxAttempts: "{{maxFinalValidationScans:number=3}}",
      },
      33,
      -1,
    ),
    utilityBlock(
      "validate-improvement",
      "Validate Improvement",
      {
        type: "VALIDATOR_JSON",
        maxAttempts: 2,
        schema: RALPH_VALIDATOR_JSON_SCHEMA,
        prompt:
          "Validate selected task {{data:select-improvement-task:tasks.0}} against active plan scope {{data:read-active-improvement:json.scopeCluster}}, review {{data:independent-review:output}}, verification, visual review, scope guard {{result:scope-change-guard}}, work yield {{data:work-yield-analysis:output}}, and diff {{result:git-diff-summary}}. Ignore unrelated workspace changes. DONE requires acceptance criteria, in-scope changes, meaningful task-specific work, and no new or worsened failure. CONTINUE is remaining bounded work, RETRY is a repair, and ERROR is unavailable external state or repeated non-progress. Include confidence, summary, evidence, and remainingWork.",
      },
      34,
      -1,
    ),
    utilityBlock(
      "mark-improvement-task-completed",
      "Mark Task Completed",
      {
        type: "MARK_JSON_TASK",
        path: "{{activeImprovementPlanFile:path=.machdoch/ralph/code-improvements/active-improvement-plan.json}}",
        jsonPath: "tasks",
        input: "{{data:select-improvement-task}}",
        status: "completed",
      },
      35,
      -1,
    ),
    utilityBlock(
      "mark-improvement-task-deferred",
      "Mark Task Deferred",
      {
        type: "MARK_JSON_TASK",
        path: "{{activeImprovementPlanFile:path=.machdoch/ralph/code-improvements/active-improvement-plan.json}}",
        jsonPath: "tasks",
        input: "{{data:select-improvement-task}}",
        status: "deferred",
      },
      35,
      1,
    ),
    utilityBlock(
      "read-completed-improvement-plan",
      "Read Completed Improvement Plan",
      {
        type: "READ_JSON",
        path: "{{activeImprovementPlanFile:path=.machdoch/ralph/code-improvements/active-improvement-plan.json}}",
      },
      16,
      2,
    ),
    utilityBlock(
      "append-completed-improvement",
      "Append Completed Improvement",
      {
        type: "APPEND_JSONL",
        path: "{{completedImprovementsFile:path=.machdoch/ralph/code-improvements/completed-improvements.jsonl}}",
        input: "{{data:read-completed-improvement-plan:json}}",
      },
      17,
      2,
    ),
    utilityBlock(
      "mark-completed-scope",
      "Mark Completed Scope",
      {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md}}",
        scopeId: "{{data:read-completed-improvement-plan:json.scope.id}}",
        scopeOutcome: "completed",
        includeMarkdown: true,
      },
      18,
      2,
    ),
    utilityBlock(
      "defer-active-plan-scope",
      "Defer Active Plan Scope",
      {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md}}",
        scopeId: "{{data:read-active-improvement:json.scope.id}}",
        scopeOutcome: "deferred",
        includeMarkdown: true,
      },
      16,
      3,
    ),
    utilityBlock(
      "append-deferred-improvement-plan",
      "Retain Deferred Improvement Plan",
      {
        type: "APPEND_JSONL",
        path: "{{deferredImprovementsFile:path=.machdoch/ralph/code-improvements/deferred-improvements.jsonl}}",
        input: "{{data:read-active-improvement:json}}",
      },
      17,
      3,
      { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
    ),
    utilityBlock(
      "defer-selected-scope",
      "Defer Selected Scope",
      {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md}}",
        scopeId: "{{data:select-scope:scope.id}}",
        scopeOutcome: "deferred",
        includeMarkdown: true,
      },
      11,
      2,
    ),
    utilityBlock(
      "mark-stop-selected-scope",
      "Mark No-Action Scope",
      {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md}}",
        scopeId: "{{data:select-scope:scope.id}}",
        scopeOutcome: "no-meaningful-work",
        includeMarkdown: true,
      },
      12,
      2,
    ),
    utilityBlock(
      "mark-invalid-selected-scope",
      "Mark Invalid Selected Scope",
      {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md}}",
        scopeId: "{{data:select-scope:scope.id}}",
        scopeOutcome: "invalid",
        includeMarkdown: true,
      },
      13,
      2,
    ),
    utilityBlock(
      "mark-invalid-active-scope",
      "Mark Invalid Active Scope",
      {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "autonomous-code-improvement-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/autonomous-code-improvement-loop.scope-registry.md}}",
        scopeId: "{{data:read-active-improvement:json.scope.id}}",
        scopeOutcome: "invalid",
        includeMarkdown: true,
      },
      15,
      3,
    ),
    utilityBlock(
      "record-done-outcome",
      "Record Completed Improvement Outcome",
      {
        type: "APPEND_JSONL",
        workOutcome: "DONE",
        path: "{{improvementOutcomesFile:path=.machdoch/ralph/code-improvements/outcomes.jsonl}}",
        input:
          '{"outcome":"DONE","scopeId":"{{data:read-completed-improvement-plan:json.scope.id}}","planId":"{{data:read-completed-improvement-plan:json.planId}}"}',
      },
      19,
      2,
      { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
    ),
    utilityBlock(
      "record-deferred-outcome",
      "Record Deferred Improvement Outcome",
      {
        type: "APPEND_JSONL",
        workOutcome: "DEFER",
        path: "{{improvementOutcomesFile:path=.machdoch/ralph/code-improvements/outcomes.jsonl}}",
        input: '{"outcome":"DEFER","scopeRoot":"{{scopeRoot:path=.}}"}',
      },
      19,
      3,
      { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
    ),
    utilityBlock(
      "record-scope-deferred-outcome",
      "Record Deferred Scope Outcome",
      {
        type: "APPEND_JSONL",
        workOutcome: "DEFER",
        path: "{{improvementOutcomesFile:path=.machdoch/ralph/code-improvements/outcomes.jsonl}}",
        input:
          '{"outcome":"DEFER","scopeRoot":"{{scopeRoot:path=.}}","reason":"The current scope was deferred and retained before coverage continued."}',
      },
      18,
      3,
      { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
    ),
    utilityBlock(
      "record-stop-outcome",
      "Record No-Action Improvement Outcome",
      {
        type: "APPEND_JSONL",
        workOutcome: "STOP",
        path: "{{improvementOutcomesFile:path=.machdoch/ralph/code-improvements/outcomes.jsonl}}",
        input:
          '{"outcome":"STOP","scopeRoot":"{{scopeRoot:path=.}}","reason":"No evidence-backed improvement portfolio remained."}',
      },
      14,
      2,
      { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
    ),
    utilityBlock(
      "record-exhausted-outcome",
      "Record Exhausted Improvement Coverage",
      {
        type: "APPEND_JSONL",
        workOutcome: "STOP",
        path: "{{improvementOutcomesFile:path=.machdoch/ralph/code-improvements/outcomes.jsonl}}",
        input:
          '{"outcome":"STOP","scopeRoot":"{{scopeRoot:path=.}}","reason":"The current coverage cycle has no remaining eligible scope."}',
      },
      23,
      1,
      { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
    ),
    utilityBlock(
      "record-invalid-outcome",
      "Record Invalid Improvement Outcome",
      {
        type: "APPEND_JSONL",
        workOutcome: "INVALID",
        path: "{{improvementOutcomesFile:path=.machdoch/ralph/code-improvements/outcomes.jsonl}}",
        input:
          '{"outcome":"INVALID","scopeRoot":"{{scopeRoot:path=.}}","reason":"Discovery, plan, task, or validation state was invalid."}',
      },
      14,
      3,
      { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
    ),
    utilityBlock(
      "record-scope-invalid-outcome",
      "Record Invalid Scope Outcome",
      {
        type: "APPEND_JSONL",
        workOutcome: "INVALID",
        path: "{{improvementOutcomesFile:path=.machdoch/ralph/code-improvements/outcomes.jsonl}}",
        input:
          '{"outcome":"INVALID","scopeRoot":"{{scopeRoot:path=.}}","reason":"The current scope plan was invalid and was retained for review."}',
      },
      18,
      4,
      { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
    ),
    utilityBlock(
      "archive-active-improvement",
      "Archive Active Improvement Plan",
      {
        type: "ARCHIVE_FILE",
        path: "{{activeImprovementPlanFile:path=.machdoch/ralph/code-improvements/active-improvement-plan.json}}",
        rootPath:
          "{{archivedImprovementsDirectory:path=.machdoch/ralph/code-improvements/archive}}",
      },
      20,
      2,
      { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
    ),
    utilityBlock(
      "final-report",
      "Final Improvement Report",
      {
        type: "FINAL_REPORT",
        path: "{{improvementReportFile:path=.machdoch/ralph/code-improvements/final-report.json}}",
        outputPath:
          "{{improvementReportMarkdown:path=.machdoch/ralph/code-improvements/final-report.md}}",
      },
      21,
      2,
    ),
    utilityBlock(
      "completion-report",
      "Completion Report",
      {
        type: "FINAL_REPORT",
        path: "{{improvementReportFile:path=.machdoch/ralph/code-improvements/final-report.json}}",
        outputPath:
          "{{improvementReportMarkdown:path=.machdoch/ralph/code-improvements/final-report.md}}",
      },
      23,
      2,
    ),
    utilityBlock(
      "retained-active-report",
      "Retained Improvement Report",
      {
        type: "FINAL_REPORT",
        path: "{{improvementReportFile:path=.machdoch/ralph/code-improvements/final-report.json}}",
        outputPath:
          "{{improvementReportMarkdown:path=.machdoch/ralph/code-improvements/final-report.md}}",
      },
      21,
      3,
    ),
    {
      id: "success",
      title: "No Eligible Improvements",
      position: { x: 7_590, y: 460 },
      size: { width: 280, height: 114 },
      type: "END",
      status: "success",
    },
    {
      id: "deferred",
      title: "Improvement Deferred",
      position: { x: 7_590, y: 690 },
      size: { width: 280, height: 114 },
      type: "END",
      outcome: "deferred",
    },
  ],
  edges: [
    edge("start-to-active", "start", "SUCCESS", "find-active-improvement"),
    edge(
      "active-exists",
      "find-active-improvement",
      "EXISTS",
      "read-active-improvement",
    ),
    edge(
      "active-missing",
      "find-active-improvement",
      "MISSING",
      "begin-scope-cycle",
    ),
    edge("begin-cycle-success", "begin-scope-cycle", "SUCCESS", "scan-scopes"),
    edge(
      "begin-cycle-error",
      "begin-scope-cycle",
      "ERROR",
      "record-invalid-outcome",
    ),
    edge(
      "active-error",
      "find-active-improvement",
      "ERROR",
      "record-invalid-outcome",
    ),
    edge("scan-success", "scan-scopes", "SUCCESS", "update-scope-registry"),
    edge("scan-empty", "scan-scopes", "EMPTY", "record-exhausted-outcome"),
    edge("scan-error", "scan-scopes", "ERROR", "record-invalid-outcome"),
    edge(
      "registry-success",
      "update-scope-registry",
      "SUCCESS",
      "select-scope",
    ),
    edge(
      "registry-empty",
      "update-scope-registry",
      "EMPTY",
      "record-exhausted-outcome",
    ),
    edge(
      "registry-error",
      "update-scope-registry",
      "ERROR",
      "record-invalid-outcome",
    ),
    edge(
      "scope-selected",
      "select-scope",
      "SELECTED",
      "detect-selected-commands",
    ),
    edge(
      "scope-exhausted",
      "select-scope",
      "EXHAUSTED",
      "record-exhausted-outcome",
    ),
    edge(
      "scope-deferred",
      "select-scope",
      "DEFERRED",
      "record-deferred-outcome",
    ),
    edge("scope-error", "select-scope", "ERROR", "record-invalid-outcome"),
    edge(
      "selected-commands-success",
      "detect-selected-commands",
      "SUCCESS",
      "read-completed-improvements",
    ),
    edge(
      "selected-commands-empty",
      "detect-selected-commands",
      "EMPTY",
      "read-completed-improvements",
    ),
    edge(
      "selected-commands-error",
      "detect-selected-commands",
      "ERROR",
      "read-completed-improvements",
    ),
    edge(
      "history-success",
      "read-completed-improvements",
      "SUCCESS",
      "read-deferred-improvements",
    ),
    edge(
      "history-empty",
      "read-completed-improvements",
      "EMPTY",
      "read-deferred-improvements",
    ),
    edge(
      "history-missing",
      "read-completed-improvements",
      "NOT_FOUND",
      "read-deferred-improvements",
    ),
    edge(
      "history-invalid",
      "read-completed-improvements",
      "INVALID",
      "read-deferred-improvements",
    ),
    edge(
      "history-error",
      "read-completed-improvements",
      "ERROR",
      "read-deferred-improvements",
    ),
    edge(
      "deferred-history-success",
      "read-deferred-improvements",
      "SUCCESS",
      "propose-improvements",
    ),
    edge(
      "deferred-history-empty",
      "read-deferred-improvements",
      "EMPTY",
      "propose-improvements",
    ),
    edge(
      "deferred-history-missing",
      "read-deferred-improvements",
      "NOT_FOUND",
      "propose-improvements",
    ),
    edge(
      "deferred-history-invalid",
      "read-deferred-improvements",
      "INVALID",
      "propose-improvements",
    ),
    edge(
      "deferred-history-error",
      "read-deferred-improvements",
      "ERROR",
      "propose-improvements",
    ),
    edge(
      "discover-success",
      "propose-improvements",
      "SUCCESS",
      "research-decision",
    ),
    edge(
      "discover-invalid",
      "propose-improvements",
      "INVALID",
      "mark-invalid-selected-scope",
    ),
    edge(
      "discover-error",
      "propose-improvements",
      "ERROR",
      "mark-invalid-selected-scope",
    ),
    edge("research-run", "research-decision", "MATCH", "improvement-research"),
    edge(
      "research-skip",
      "research-decision",
      "NO_MATCH",
      "choose-improvement",
    ),
    edge("research-error", "research-decision", "ERROR", "choose-improvement"),
    edge(
      "research-success",
      "improvement-research",
      "SUCCESS",
      "choose-improvement",
    ),
    edge(
      "research-failure",
      "improvement-research",
      "ERROR",
      "choose-improvement",
    ),
    edge(
      "plan-success",
      "choose-improvement",
      "SUCCESS",
      "build-improvement-plan",
    ),
    edge(
      "plan-invalid",
      "choose-improvement",
      "INVALID",
      "mark-invalid-selected-scope",
    ),
    edge(
      "plan-error",
      "choose-improvement",
      "ERROR",
      "mark-invalid-selected-scope",
    ),
    edge(
      "build-success",
      "build-improvement-plan",
      "SUCCESS",
      "has-actionable-improvement",
    ),
    edge(
      "build-error",
      "build-improvement-plan",
      "ERROR",
      "mark-invalid-selected-scope",
    ),
    edge(
      "actionable",
      "has-actionable-improvement",
      "MATCH",
      "write-active-improvement",
    ),
    edge(
      "not-actionable",
      "has-actionable-improvement",
      "NO_MATCH",
      "selection-is-deferred",
    ),
    edge(
      "actionable-error",
      "has-actionable-improvement",
      "ERROR",
      "mark-invalid-selected-scope",
    ),
    edge(
      "selection-deferred",
      "selection-is-deferred",
      "MATCH",
      "defer-selected-scope",
    ),
    edge(
      "selection-stop",
      "selection-is-deferred",
      "NO_MATCH",
      "mark-stop-selected-scope",
    ),
    edge(
      "selection-error",
      "selection-is-deferred",
      "ERROR",
      "mark-invalid-selected-scope",
    ),
    edge(
      "write-success",
      "write-active-improvement",
      "SUCCESS",
      "read-active-improvement",
    ),
    edge(
      "write-invalid",
      "write-active-improvement",
      "INVALID",
      "mark-invalid-selected-scope",
    ),
    edge(
      "write-error",
      "write-active-improvement",
      "ERROR",
      "mark-invalid-selected-scope",
    ),
    edge(
      "read-active-success",
      "read-active-improvement",
      "SUCCESS",
      "detect-project-commands",
    ),
    edge(
      "read-active-invalid",
      "read-active-improvement",
      "INVALID",
      "record-invalid-outcome",
    ),
    edge(
      "read-active-missing",
      "read-active-improvement",
      "NOT_FOUND",
      "record-invalid-outcome",
    ),
    edge(
      "read-active-error",
      "read-active-improvement",
      "ERROR",
      "record-invalid-outcome",
    ),
    edge(
      "active-commands-success",
      "detect-project-commands",
      "SUCCESS",
      "assess-improvement-tasks",
    ),
    edge(
      "active-commands-empty",
      "detect-project-commands",
      "EMPTY",
      "assess-improvement-tasks",
    ),
    edge(
      "active-commands-error",
      "detect-project-commands",
      "ERROR",
      "assess-improvement-tasks",
    ),
    edge(
      "tasks-ready",
      "assess-improvement-tasks",
      "READY",
      "select-improvement-task",
    ),
    edge(
      "tasks-complete",
      "assess-improvement-tasks",
      "COMPLETE",
      "read-completed-improvement-plan",
    ),
    edge(
      "tasks-blocked",
      "assess-improvement-tasks",
      "BLOCKED",
      "mark-invalid-active-scope",
    ),
    edge(
      "tasks-deferred",
      "assess-improvement-tasks",
      "DEFERRED",
      "defer-active-plan-scope",
    ),
    edge(
      "tasks-empty",
      "assess-improvement-tasks",
      "EMPTY",
      "mark-invalid-active-scope",
    ),
    edge(
      "tasks-invalid",
      "assess-improvement-tasks",
      "INVALID",
      "mark-invalid-active-scope",
    ),
    edge(
      "tasks-missing",
      "assess-improvement-tasks",
      "NOT_FOUND",
      "record-invalid-outcome",
    ),
    edge(
      "tasks-error",
      "assess-improvement-tasks",
      "ERROR",
      "defer-active-plan-scope",
    ),
    edge(
      "task-selected",
      "select-improvement-task",
      "SELECTED",
      "git-snapshot-before",
    ),
    edge(
      "task-empty",
      "select-improvement-task",
      "EMPTY",
      "assess-improvement-tasks",
    ),
    edge(
      "task-invalid",
      "select-improvement-task",
      "INVALID",
      "mark-invalid-active-scope",
    ),
    edge(
      "task-blocked",
      "select-improvement-task",
      "BLOCKED",
      "mark-invalid-active-scope",
    ),
    edge(
      "task-deferred",
      "select-improvement-task",
      "DEFERRED",
      "defer-active-plan-scope",
    ),
    edge(
      "task-missing",
      "select-improvement-task",
      "NOT_FOUND",
      "mark-invalid-active-scope",
    ),
    edge(
      "task-error",
      "select-improvement-task",
      "ERROR",
      "defer-active-plan-scope",
    ),
    edge(
      "snapshot-success",
      "git-snapshot-before",
      "SUCCESS",
      "select-verification-command",
    ),
    edge(
      "snapshot-error",
      "git-snapshot-before",
      "ERROR",
      "select-verification-command",
    ),
    edge(
      "command-success",
      "select-verification-command",
      "SUCCESS",
      "baseline-verification",
    ),
    edge(
      "command-error",
      "select-verification-command",
      "ERROR",
      "baseline-verification",
    ),
    edge(
      "baseline-success",
      "baseline-verification",
      "SUCCESS",
      "count-improvement-pass",
    ),
    edge(
      "baseline-failed",
      "baseline-verification",
      "FAILED",
      "count-improvement-pass",
    ),
    edge(
      "baseline-error",
      "baseline-verification",
      "ERROR",
      "count-improvement-pass",
    ),
    edge(
      "implementation-continue",
      "count-improvement-pass",
      "CONTINUE",
      "implement-improvement",
    ),
    edge(
      "implementation-limit",
      "count-improvement-pass",
      "LIMIT_REACHED",
      "mark-improvement-task-deferred",
    ),
    edge(
      "implementation-counter-error",
      "count-improvement-pass",
      "ERROR",
      "mark-improvement-task-deferred",
    ),
    edge(
      "implementation-success",
      "implement-improvement",
      "SUCCESS",
      "mark-improvement-task-verifying",
    ),
    edge(
      "implementation-error",
      "implement-improvement",
      "ERROR",
      "mark-improvement-task-deferred",
    ),
    edge(
      "mark-verifying-success",
      "mark-improvement-task-verifying",
      "SUCCESS",
      "verification-decision",
    ),
    edge(
      "mark-verifying-missing",
      "mark-improvement-task-verifying",
      "NOT_FOUND",
      "mark-improvement-task-deferred",
    ),
    edge(
      "mark-verifying-invalid",
      "mark-improvement-task-verifying",
      "INVALID",
      "mark-improvement-task-deferred",
    ),
    edge(
      "mark-verifying-error",
      "mark-improvement-task-verifying",
      "ERROR",
      "mark-improvement-task-deferred",
    ),
    edge(
      "verification-run",
      "verification-decision",
      "MATCH",
      "run-verification",
    ),
    edge(
      "verification-skip",
      "verification-decision",
      "NO_MATCH",
      "visual-decision",
    ),
    edge(
      "verification-decision-error",
      "verification-decision",
      "ERROR",
      "visual-decision",
    ),
    edge(
      "verification-success",
      "run-verification",
      "SUCCESS",
      "visual-decision",
    ),
    edge(
      "verification-failed",
      "run-verification",
      "FAILED",
      "mark-improvement-task-repairing",
    ),
    edge(
      "verification-error",
      "run-verification",
      "ERROR",
      "mark-improvement-task-repairing",
    ),
    edge(
      "mark-repairing-success",
      "mark-improvement-task-repairing",
      "SUCCESS",
      "count-verification-repair",
    ),
    edge(
      "mark-repairing-missing",
      "mark-improvement-task-repairing",
      "NOT_FOUND",
      "mark-improvement-task-deferred",
    ),
    edge(
      "mark-repairing-invalid",
      "mark-improvement-task-repairing",
      "INVALID",
      "mark-improvement-task-deferred",
    ),
    edge(
      "mark-repairing-error",
      "mark-improvement-task-repairing",
      "ERROR",
      "mark-improvement-task-deferred",
    ),
    edge(
      "repair-continue",
      "count-verification-repair",
      "CONTINUE",
      "fix-validation-failures",
    ),
    edge(
      "repair-limit",
      "count-verification-repair",
      "LIMIT_REACHED",
      "mark-improvement-task-deferred",
    ),
    edge(
      "repair-counter-error",
      "count-verification-repair",
      "ERROR",
      "mark-improvement-task-deferred",
    ),
    edge(
      "repair-success",
      "fix-validation-failures",
      "SUCCESS",
      "mark-improvement-task-verifying",
    ),
    edge(
      "repair-error",
      "fix-validation-failures",
      "ERROR",
      "mark-improvement-task-deferred",
    ),
    edge("visual-run", "visual-decision", "MATCH", "visual-review"),
    edge("visual-skip", "visual-decision", "NO_MATCH", "git-diff-summary"),
    edge(
      "visual-decision-error",
      "visual-decision",
      "ERROR",
      "git-diff-summary",
    ),
    edge("visual-success", "visual-review", "SUCCESS", "git-diff-summary"),
    edge(
      "visual-unavailable",
      "visual-review",
      "UNAVAILABLE",
      "git-diff-summary",
    ),
    edge("visual-error", "visual-review", "ERROR", "git-diff-summary"),
    edge("diff-success", "git-diff-summary", "SUCCESS", "scope-change-guard"),
    edge("diff-empty", "git-diff-summary", "EMPTY", "scope-change-guard"),
    edge("diff-error", "git-diff-summary", "ERROR", "scope-change-guard"),
    edge("scope-in", "scope-change-guard", "IN_SCOPE", "work-yield-analysis"),
    edge(
      "scope-out",
      "scope-change-guard",
      "OUT_OF_SCOPE",
      "mark-improvement-task-deferred",
    ),
    edge(
      "scope-empty-result",
      "scope-change-guard",
      "EMPTY",
      "mark-improvement-task-deferred",
    ),
    edge(
      "scope-guard-error",
      "scope-change-guard",
      "ERROR",
      "mark-improvement-task-deferred",
    ),
    edge(
      "yield-success",
      "work-yield-analysis",
      "SUCCESS",
      "useful-work-produced",
    ),
    edge(
      "yield-error",
      "work-yield-analysis",
      "ERROR",
      "mark-improvement-task-deferred",
    ),
    edge(
      "useful-work",
      "useful-work-produced",
      "MATCH",
      "review-tier-decision",
    ),
    edge(
      "no-useful-work",
      "useful-work-produced",
      "NO_MATCH",
      "mark-improvement-task-deferred",
    ),
    edge(
      "useful-work-error",
      "useful-work-produced",
      "ERROR",
      "mark-improvement-task-deferred",
    ),
    edge(
      "strict-review",
      "review-tier-decision",
      "MATCH",
      "independent-review",
    ),
    edge(
      "validator-only-review",
      "review-tier-decision",
      "NO_MATCH",
      "count-final-validation-scan",
    ),
    edge(
      "review-tier-error",
      "review-tier-decision",
      "ERROR",
      "count-final-validation-scan",
    ),
    edge(
      "review-success",
      "independent-review",
      "SUCCESS",
      "review-is-deferred",
    ),
    edge(
      "review-invalid",
      "independent-review",
      "INVALID",
      "mark-improvement-task-deferred",
    ),
    edge(
      "review-error",
      "independent-review",
      "ERROR",
      "mark-improvement-task-deferred",
    ),
    edge(
      "review-deferred",
      "review-is-deferred",
      "MATCH",
      "mark-improvement-task-deferred",
    ),
    edge(
      "review-not-deferred",
      "review-is-deferred",
      "NO_MATCH",
      "review-needs-fix",
    ),
    edge(
      "review-deferred-error",
      "review-is-deferred",
      "ERROR",
      "mark-improvement-task-deferred",
    ),
    edge(
      "review-fix",
      "review-needs-fix",
      "MATCH",
      "mark-improvement-task-repairing",
    ),
    edge(
      "review-pass",
      "review-needs-fix",
      "NO_MATCH",
      "count-final-validation-scan",
    ),
    edge(
      "review-fix-error",
      "review-needs-fix",
      "ERROR",
      "mark-improvement-task-deferred",
    ),
    edge(
      "final-scan-continue",
      "count-final-validation-scan",
      "CONTINUE",
      "validate-improvement",
    ),
    edge(
      "final-scan-limit",
      "count-final-validation-scan",
      "LIMIT_REACHED",
      "mark-improvement-task-deferred",
    ),
    edge(
      "final-scan-error",
      "count-final-validation-scan",
      "ERROR",
      "mark-improvement-task-deferred",
    ),
    edge(
      "validate-done",
      "validate-improvement",
      "DONE",
      "mark-improvement-task-completed",
    ),
    edge(
      "validate-continue",
      "validate-improvement",
      "CONTINUE",
      "mark-improvement-task-repairing",
    ),
    edge(
      "validate-retry",
      "validate-improvement",
      "RETRY",
      "mark-improvement-task-repairing",
    ),
    edge(
      "validate-error",
      "validate-improvement",
      "ERROR",
      "mark-improvement-task-deferred",
    ),
    edge(
      "validate-invalid",
      "validate-improvement",
      "INVALID",
      "mark-improvement-task-deferred",
    ),
    edge(
      "mark-completed-success",
      "mark-improvement-task-completed",
      "SUCCESS",
      "assess-improvement-tasks",
    ),
    edge(
      "mark-completed-missing",
      "mark-improvement-task-completed",
      "NOT_FOUND",
      "mark-improvement-task-deferred",
    ),
    edge(
      "mark-completed-invalid",
      "mark-improvement-task-completed",
      "INVALID",
      "mark-improvement-task-deferred",
    ),
    edge(
      "mark-completed-error",
      "mark-improvement-task-completed",
      "ERROR",
      "mark-improvement-task-deferred",
    ),
    edge(
      "mark-deferred-success",
      "mark-improvement-task-deferred",
      "SUCCESS",
      "assess-improvement-tasks",
    ),
    edge(
      "mark-deferred-missing",
      "mark-improvement-task-deferred",
      "NOT_FOUND",
      "defer-active-plan-scope",
    ),
    edge(
      "mark-deferred-invalid",
      "mark-improvement-task-deferred",
      "INVALID",
      "defer-active-plan-scope",
    ),
    edge(
      "mark-deferred-error",
      "mark-improvement-task-deferred",
      "ERROR",
      "defer-active-plan-scope",
    ),
    edge(
      "completed-plan-success",
      "read-completed-improvement-plan",
      "SUCCESS",
      "append-completed-improvement",
    ),
    edge(
      "completed-plan-invalid",
      "read-completed-improvement-plan",
      "INVALID",
      "defer-active-plan-scope",
    ),
    edge(
      "completed-plan-missing",
      "read-completed-improvement-plan",
      "NOT_FOUND",
      "defer-active-plan-scope",
    ),
    edge(
      "completed-plan-error",
      "read-completed-improvement-plan",
      "ERROR",
      "defer-active-plan-scope",
    ),
    edge(
      "append-success",
      "append-completed-improvement",
      "SUCCESS",
      "mark-completed-scope",
    ),
    edge(
      "append-invalid",
      "append-completed-improvement",
      "INVALID",
      "defer-active-plan-scope",
    ),
    edge(
      "append-error",
      "append-completed-improvement",
      "ERROR",
      "defer-active-plan-scope",
    ),
    edge(
      "completed-scope-success",
      "mark-completed-scope",
      "SUCCESS",
      "record-done-outcome",
    ),
    edge(
      "completed-scope-missing",
      "mark-completed-scope",
      "NOT_FOUND",
      "record-done-outcome",
    ),
    edge(
      "completed-scope-error",
      "mark-completed-scope",
      "ERROR",
      "record-done-outcome",
    ),
    edge(
      "defer-active-success",
      "defer-active-plan-scope",
      "SUCCESS",
      "append-deferred-improvement-plan",
    ),
    edge(
      "defer-active-missing",
      "defer-active-plan-scope",
      "NOT_FOUND",
      "append-deferred-improvement-plan",
    ),
    edge(
      "defer-active-error",
      "defer-active-plan-scope",
      "ERROR",
      "append-deferred-improvement-plan",
    ),
    edge(
      "deferred-plan-retained",
      "append-deferred-improvement-plan",
      "SUCCESS",
      "record-scope-deferred-outcome",
    ),
    edge(
      "deferred-plan-invalid",
      "append-deferred-improvement-plan",
      "INVALID",
      "retained-active-report",
    ),
    edge(
      "deferred-plan-error",
      "append-deferred-improvement-plan",
      "ERROR",
      "retained-active-report",
    ),
    edge(
      "defer-selected-success",
      "defer-selected-scope",
      "SUCCESS",
      "record-scope-deferred-outcome",
    ),
    edge(
      "defer-selected-missing",
      "defer-selected-scope",
      "NOT_FOUND",
      "record-scope-deferred-outcome",
    ),
    edge(
      "defer-selected-error",
      "defer-selected-scope",
      "ERROR",
      "record-scope-deferred-outcome",
    ),
    edge(
      "stop-scope-success",
      "mark-stop-selected-scope",
      "SUCCESS",
      "record-stop-outcome",
    ),
    edge(
      "stop-scope-missing",
      "mark-stop-selected-scope",
      "NOT_FOUND",
      "record-stop-outcome",
    ),
    edge(
      "stop-scope-error",
      "mark-stop-selected-scope",
      "ERROR",
      "record-stop-outcome",
    ),
    edge(
      "invalid-selected-success",
      "mark-invalid-selected-scope",
      "SUCCESS",
      "record-scope-invalid-outcome",
    ),
    edge(
      "invalid-selected-missing",
      "mark-invalid-selected-scope",
      "NOT_FOUND",
      "record-scope-invalid-outcome",
    ),
    edge(
      "invalid-selected-error",
      "mark-invalid-selected-scope",
      "ERROR",
      "record-scope-invalid-outcome",
    ),
    edge(
      "invalid-active-success",
      "mark-invalid-active-scope",
      "SUCCESS",
      "record-scope-invalid-outcome",
    ),
    edge(
      "invalid-active-missing",
      "mark-invalid-active-scope",
      "NOT_FOUND",
      "record-scope-invalid-outcome",
    ),
    edge(
      "invalid-active-error",
      "mark-invalid-active-scope",
      "ERROR",
      "record-scope-invalid-outcome",
    ),
    edge(
      "done-recorded",
      "record-done-outcome",
      "SUCCESS",
      "archive-active-improvement",
    ),
    edge(
      "done-record-invalid",
      "record-done-outcome",
      "INVALID",
      "retained-active-report",
    ),
    edge(
      "done-record-error",
      "record-done-outcome",
      "ERROR",
      "retained-active-report",
    ),
    edge(
      "defer-recorded",
      "record-deferred-outcome",
      "SUCCESS",
      "retained-active-report",
    ),
    edge(
      "defer-record-invalid",
      "record-deferred-outcome",
      "INVALID",
      "retained-active-report",
    ),
    edge(
      "defer-record-error",
      "record-deferred-outcome",
      "ERROR",
      "retained-active-report",
    ),
    edge(
      "scope-defer-recorded",
      "record-scope-deferred-outcome",
      "SUCCESS",
      "archive-active-improvement",
    ),
    edge(
      "scope-defer-record-invalid",
      "record-scope-deferred-outcome",
      "INVALID",
      "retained-active-report",
    ),
    edge(
      "scope-defer-record-error",
      "record-scope-deferred-outcome",
      "ERROR",
      "retained-active-report",
    ),
    edge("stop-recorded", "record-stop-outcome", "SUCCESS", "final-report"),
    edge(
      "stop-record-invalid",
      "record-stop-outcome",
      "INVALID",
      "retained-active-report",
    ),
    edge(
      "stop-record-error",
      "record-stop-outcome",
      "ERROR",
      "retained-active-report",
    ),
    edge(
      "invalid-recorded",
      "record-invalid-outcome",
      "SUCCESS",
      "retained-active-report",
    ),
    edge(
      "invalid-record-invalid",
      "record-invalid-outcome",
      "INVALID",
      "retained-active-report",
    ),
    edge(
      "invalid-record-error",
      "record-invalid-outcome",
      "ERROR",
      "retained-active-report",
    ),
    edge(
      "scope-invalid-recorded",
      "record-scope-invalid-outcome",
      "SUCCESS",
      "archive-active-improvement",
    ),
    edge(
      "scope-invalid-record-invalid",
      "record-scope-invalid-outcome",
      "INVALID",
      "retained-active-report",
    ),
    edge(
      "scope-invalid-record-error",
      "record-scope-invalid-outcome",
      "ERROR",
      "retained-active-report",
    ),
    edge(
      "archive-success",
      "archive-active-improvement",
      "SUCCESS",
      "final-report",
    ),
    edge(
      "archive-missing",
      "archive-active-improvement",
      "NOT_FOUND",
      "final-report",
    ),
    edge(
      "archive-error",
      "archive-active-improvement",
      "ERROR",
      "retained-active-report",
    ),
    edge("report-success", "final-report", "SUCCESS", "scan-scopes"),
    edge("report-error", "final-report", "ERROR", "retained-active-report"),
    edge(
      "exhausted-recorded",
      "record-exhausted-outcome",
      "SUCCESS",
      "completion-report",
    ),
    edge(
      "exhausted-record-invalid",
      "record-exhausted-outcome",
      "INVALID",
      "retained-active-report",
    ),
    edge(
      "exhausted-record-error",
      "record-exhausted-outcome",
      "ERROR",
      "retained-active-report",
    ),
    edge(
      "completion-report-success",
      "completion-report",
      "SUCCESS",
      "success",
    ),
    edge(
      "completion-report-error",
      "completion-report",
      "ERROR",
      "retained-active-report",
    ),
    edge(
      "retained-report-success",
      "retained-active-report",
      "SUCCESS",
      "deferred",
    ),
    edge(
      "retained-report-error",
      "retained-active-report",
      "ERROR",
      "deferred",
    ),
  ],
};

export const autonomousCodeImprovementLoopStarterFlow = {
  id: "autonomous-code-improvement-loop",
  version: 22,
  defaultAlias: "autonomous-code-improvement-loop",
  category: "Code Quality",
  tags: ["autonomous", "improvement", "portfolio", "validation"],
  protocol: {
    schemaVersion: 1,
    verification: {
      planId:
        "starter-autonomous-code-improvement-loop:persistent-plan-verification",
      baselineBlockId: "baseline-verification",
      candidateBlockId: "run-verification",
      baselineInconclusiveTargetId: "count-improvement-pass",
      candidateInconclusiveTargetId: "visual-decision",
      routeOverrides: [],
    },
    terminalOutcomes: [
      { blockId: "success", outcome: "succeeded" },
      { blockId: "deferred", outcome: "deferred" },
    ],
  },
  flow: autonomousCodeImprovementLoopFlow,
} as const satisfies RalphStarterFlow;
