import type { RalphFlow } from "../ralph.js";
import type { RalphStarterFlow } from "../ralph-starter-flows.js";
import { RALPH_VALIDATOR_JSON_SCHEMA } from "../_helpers/parse-ralph-validator-json-result.helper.js";
import { layoutFeatureImplementationFlow } from "./feature-implementation-layout.js";

const RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS = 30 * 60;

const RALPH_TASK_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "id",
    "title",
    "status",
    "batchKey",
    "dependencies",
    "likelyFiles",
    "size",
    "acceptanceCriteria",
    "priority",
  ],
  properties: {
    id: { type: "string", minLength: 1 },
    title: { type: "string", minLength: 1 },
    status: {
      type: "string",
      enum: [
        "planned",
        "implementing",
        "verifying",
        "repairing",
        "completed",
        "deferred",
      ],
    },
    batchKey: { type: "string" },
    dependencies: {
      type: "array",
      items: { type: "string", minLength: 1 },
      maxItems: 20,
    },
    likelyFiles: {
      type: "array",
      items: { type: "string", minLength: 1 },
      maxItems: 50,
    },
    size: { type: "string", enum: ["small", "medium", "large"] },
    acceptanceCriteria: {
      type: "array",
      items: { type: "string", minLength: 1 },
      minItems: 1,
      maxItems: 20,
    },
    priority: { type: "number", minimum: 0, maximum: 100 },
  },
} as const;

const fullFeatureImplementationFlow: RalphFlow = {
  schemaVersion: 1,
  id: "starter-full-feature-implementation",
  alias: "feature-implementation-checklist-loop",
  name: "Feature Implementation Checklist Loop",
  description: "Implements feature tasks and verifies the complete feature.",
  settings: {
    autonomy: {
      recoverFailedEnd: true,
      maxRecoveryAttempts: 3,
      transitionExhaustion: "checkpoint",
      recoveryExhaustion: "defer",
      deferToBlockId: "record-deferred-outcome",
    },
  },
  variables: [
    {
      name: "featureId",
      type: "text",
      default: "current-feature",
      required: false,
    },
    {
      name: "featureRequest",
      type: "text",
      default:
        "Autonomously identify and implement the highest-value bounded feature supported by repository evidence.",
      required: false,
    },
    { name: "acceptanceCriteria", type: "text", default: "", required: false },
    { name: "previousGoal", type: "text", default: "", required: false },
    {
      name: "checklistDirectory",
      type: "path",
      default: ".machdoch/local/state/feature-implementation",
      required: false,
    },
    { name: "checklistFile", type: "path", default: "", required: false },
    {
      name: "checklistArchiveDirectory",
      type: "path",
      default: ".machdoch/local/state/feature-implementation/archive",
      required: false,
    },
    {
      name: "featureOutcomesFile",
      type: "path",
      default: ".machdoch/local/state/feature-implementation/outcomes.jsonl",
      required: false,
    },
    {
      name: "projectCommandsFile",
      type: "path",
      default:
        "{{run:artifactRoot}}/feature-implementation/project-commands.json",
      required: false,
    },
    {
      name: "gitSnapshotFile",
      type: "path",
      default: "{{run:artifactRoot}}/feature-implementation/git-snapshot.json",
      required: false,
    },
    {
      name: "gitDiffFile",
      type: "path",
      default: "{{run:artifactRoot}}/feature-implementation/git-diff.json",
      required: false,
    },
    {
      name: "featureReportFile",
      type: "path",
      default: "{{run:artifactRoot}}/feature-implementation/final-report.json",
      required: false,
    },
    {
      name: "featureReportMarkdown",
      type: "path",
      default: "{{run:artifactRoot}}/feature-implementation/final-report.md",
      required: false,
    },
    {
      name: "enableOnlineResearch",
      type: "boolean",
      default: "true",
      required: false,
    },
    {
      name: "enableVisualReview",
      type: "boolean",
      default: "false",
      required: false,
    },
    { name: "targetUrl", type: "url", default: "", required: false },
    { name: "healthUrl", type: "url", default: "", required: false },
    { name: "screenshotPath", type: "path", default: "", required: false },
    { name: "verificationCommand", type: "text", default: "", required: false },
    {
      name: "riskTolerance",
      type: "text",
      default: "ambitious",
      required: false,
    },
    {
      name: "allowDependencyChanges",
      type: "boolean",
      default: "true",
      required: false,
    },
    {
      name: "allowSchemaChanges",
      type: "boolean",
      default: "true",
      required: false,
    },
    {
      name: "allowPublicApiChanges",
      type: "boolean",
      default: "true",
      required: false,
    },
    { name: "authInstructions", type: "text", default: "", required: false },
    { name: "designGuidelines", type: "text", default: "", required: false },
    {
      name: "implementationScope",
      type: "text",
      default: "auto-detect",
      required: false,
    },
    {
      name: "maxImplementationPasses",
      type: "number",
      default: "8",
      required: false,
    },
    {
      name: "maxTasksPerImplementationPass",
      type: "number",
      default: "3",
      required: false,
    },
  ],
  blocks: [
    {
      id: "start",
      title: "Start",
      position: { x: 0, y: 0 },
      size: { width: 256, height: 140 },
      type: "START",
    },
    {
      id: "detect-project-commands",
      title: "Detect Project Commands",
      position: { x: 720, y: 0 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "DETECT_PROJECT_COMMANDS",
        rootPath: ".",
        outputPath:
          "{{projectCommandsFile:path=.machdoch/local/state/feature-implementation/project-commands.json}}",
      },
    },
    {
      id: "resolve-checklist-path",
      title: "Resolve Feature Checklist",
      position: { x: 900, y: 180 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "TRANSFORM_JSON",
        input: "{}",
        expression:
          "(() => { const featureId = String(variables.featureId || 'current-feature').trim().toLowerCase().replace(/[^a-z0-9._-]+/gu, '-').replace(/^-+|-+$/gu, '') || 'current-feature'; const configured = String(variables.checklistFile || '').trim(); const directory = String(variables.checklistDirectory || '.machdoch/local/state/feature-implementation').trim().replace(/[\\/]+$/gu, '') || '.machdoch/local/state/feature-implementation'; const requestKey = JSON.stringify([variables.featureRequest || '', variables.acceptanceCriteria || '', variables.previousGoal || '']); return { featureId, requestKey, path: configured || `${directory}/${featureId}.checklist.json` }; })()",
      },
    },
    {
      id: "checklist-exists",
      title: "Checklist Exists?",
      position: { x: 1060, y: -110 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "FILE_EXISTS",
        path: "{{data:resolve-checklist-path:output.path}}",
      },
    },
    {
      id: "read-checklist",
      title: "Read Checklist",
      position: { x: 1400, y: -160 },
      size: { width: 280, height: 160 },
      type: "UTILITY",
      utility: {
        type: "READ_JSON",
        path: "{{data:resolve-checklist-path:output.path}}",
      },
    },
    {
      id: "checklist-matches-feature",
      title: "Checklist Matches Feature?",
      position: { x: 1560, y: -280 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "json-path",
          path: "lastData.json.featureId",
          operator: "non-empty-string",
          assertMatch: true,
          invalidMessage: "Checklist feature identity is missing or invalid.",
          conditions: [
            {
              style: "json-path",
              path: "resultsByBlock.resolve-checklist-path.data.output.featureId",
              operator: "non-empty-string",
              assertMatch: true,
              invalidMessage:
                "Checklist feature identity is missing or invalid.",
              conditions: [
                {
                  style: "json-path",
                  path: "lastData.json.featureId",
                  operator: "equals-path",
                  valuePath:
                    "resultsByBlock.resolve-checklist-path.data.output.featureId",
                  conditions: [
                    {
                      style: "json-path",
                      path: "lastData.json.requestKey",
                      operator: "equals-path",
                      valuePath:
                        "resultsByBlock.resolve-checklist-path.data.output.requestKey",
                      conditions: [
                        {
                          style: "json-path",
                          path: "lastData.json.requestKey",
                          operator: "non-empty-string",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      },
    },
    {
      id: "archive-mismatched-checklist",
      title: "Archive Mismatched Checklist",
      position: { x: 1740, y: -300 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "ARCHIVE_FILE",
        path: "{{data:resolve-checklist-path:output.path}}",
        rootPath:
          "{{checklistArchiveDirectory:path=.machdoch/local/state/feature-implementation/archive}}",
      },
    },
    {
      id: "prepare-feature-brief",
      title: "Prepare Feature Brief",
      position: { x: 1400, y: 40 },
      size: { width: 280, height: 190 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Prepare a concise implementation brief from normalized feature identity {{data:resolve-checklist-path:output}}, featureRequest={{featureRequest:text=Autonomously identify and implement the highest-value bounded feature supported by repository evidence.}}, previousGoal={{previousGoal:text=}}, acceptanceCriteria={{acceptanceCriteria:text=}}, implementationScope={{implementationScope:text=auto-detect}}, authInstructions={{authInstructions:text=}}, designGuidelines={{designGuidelines:text=}}, detected project commands {{result:detect-project-commands}}, checklist existence {{result:checklist-exists}}, and existing matching checklist JSON {{result:read-checklist}} when present. Use the previous goal to preserve existing product behavior and scope the requested feature. If the request is blank, autonomously infer the highest-value bounded objective from repository behavior, tests, open work, and product structure. Treat only a checklist matching both featureId and requestKey as resume context and ask no questions.",
    },
    {
      id: "research-decision",
      title: "Use Online Research?",
      position: { x: 1400, y: -120 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "json-path",
          path: "variables.enableOnlineResearch",
          operator: "equals",
          value: "true",
        },
      },
    },
    {
      id: "initial-research",
      title: "Initial Research",
      position: { x: 1720, y: -170 },
      size: { width: 280, height: 190 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        webAccess: true,
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Research before implementation using the available live web tools, including the provider's native web search and page-opening tools. Use search_web and fetch_url when exposed; their absence does not mean the provider's native web tools are unavailable. Search current official primary-source documentation, standards, accessibility/security guidance, and maintainer examples relevant to this feature brief: {{summary:prepare-feature-brief}}. Open or fetch the best primary pages before relying on them. Inspect local package/config metadata when it affects version assumptions. Return concise findings with exact source links, risks, version/date assumptions, and implementation implications for the checklist, implementation, and reviews. If web search is unavailable after checking all exposed web tools, report that limitation; never invent searches, fetched content, or references.",
    },
    {
      id: "specification-checklist",
      title: "Create Checklist",
      position: { x: 2380, y: 0 },
      size: { width: 280, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath: "{{data:resolve-checklist-path:output.path}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          additionalProperties: false,
          required: [
            "featureId",
            "requestKey",
            "request",
            "previousGoal",
            "research",
            "acceptanceCriteria",
            "tasks",
            "status",
          ],
          properties: {
            featureId: { type: "string", minLength: 1 },
            requestKey: { type: "string", minLength: 1 },
            request: { type: "string", minLength: 1 },
            previousGoal: { type: "string" },
            research: { type: "string" },
            acceptanceCriteria: {
              type: "array",
              items: { type: "string", minLength: 1 },
              minItems: 1,
              maxItems: 30,
            },
            tasks: {
              type: "array",
              minItems: 1,
              maxItems: 50,
              items: RALPH_TASK_SCHEMA,
            },
            status: {
              type: "string",
              enum: [
                "planned",
                "implementing",
                "verifying",
                "repairing",
                "completed",
                "deferred",
              ],
            },
          },
        },
        prompt:
          "Create or update the canonical JSON implementation checklist at {{data:resolve-checklist-path:output.path}}. Copy featureId and requestKey exactly from {{data:resolve-checklist-path:output}} and previousGoal exactly from {{previousGoal:text=}}. Preserve completed tasks only when resuming a checklist matching both featureId and requestKey. Include the feature request, acceptance criteria, research with source links and version assumptions, and actionable implementation tasks with stable ids. Runtime nodes execute verification and final review; do not create tasks that only rerun checks or review already implemented work. Put product implementation, test coverage, auth, and design requirements in task acceptanceCriteria. Keep engine scheduling, completion of runtime reviews, future acceptance fault campaigns, and resume orchestration as feature-level process context, never implementation-task criteria. The task validator performs the current independent task review; full-feature acceptance and the next review then gate final DONE. Every task must include canonical status planned/implementing/verifying/repairing/completed/deferred, batchKey, dependencies, likelyFiles, size, acceptanceCriteria, and priority. Shape meaningful autonomous batches of up to {{maxTasksPerImplementationPass:number=3}} compatible tasks. Use deferred only for unavailable external state so deterministic selection can continue elsewhere. Make the best bounded reversible assumption from the request, repository, tests, and research; never wait for human input. Inputs: brief {{result:prepare-feature-brief}}, research {{result:initial-research}}, detected commands {{result:detect-project-commands}}. Return only schema-valid JSON.",
      },
    },
    {
      id: "git-snapshot-before",
      title: "Git Snapshot",
      position: { x: 2550, y: -220 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_SNAPSHOT",
        cwd: ".",
        outputPath:
          "{{gitSnapshotFile:path=.machdoch/local/state/feature-implementation/git-snapshot.json}}",
      },
    },
    {
      id: "assess-checklist-tasks",
      title: "Assess Checklist Tasks",
      position: { x: 2550, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "ASSESS_JSON_TASKS",
        path: "{{data:resolve-checklist-path:output.path}}",
        jsonPath: "tasks",
        strategy: "start-to-end",
        maxTasks: "{{maxTasksPerImplementationPass:number=3}}",
      },
    },
    {
      id: "select-next-task",
      title: "Select Next Checklist Task",
      position: { x: 2710, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SELECT_JSON_TASK",
        path: "{{data:resolve-checklist-path:output.path}}",
        jsonPath: "tasks",
        strategy: "start-to-end",
        maxTasks: "{{maxTasksPerImplementationPass:number=3}}",
      },
    },
    {
      id: "read-selected-checklist",
      title: "Read Selected Checklist",
      position: { x: 2560, y: 240 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "READ_JSON",
        path: "{{data:resolve-checklist-path:output.path}}",
      },
    },
    {
      id: "implement-feature",
      title: "Implement Checklist Items",
      position: { x: 2720, y: 0 },
      size: { width: 280, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Implement the selected checklist task batch {{data:select-next-task:tasks}} from JSON checklist {{data:resolve-checklist-path:output.path}}. Complete every compatible selected task in this pass. Preserve the previous goal {{previousGoal:text=}} and use retained research {{data:read-selected-checklist:json.research}}, full research {{result:initial-research}}, checklist/resume context, git/verification baselines, detected commands, pass count, latest validation feedback, and work-yield analysis. Apply source-backed guidance, scope {{implementationScope:text=auto-detect}}, riskTolerance={{riskTolerance:text=ambitious}}, designGuidelines={{designGuidelines:text=}}, and authInstructions={{authInstructions:text=}}. Dependency changes use allowDependencyChanges={{allowDependencyChanges:boolean=true}}, schemas/migrations use allowSchemaChanges={{allowSchemaChanges:boolean=true}}, and public APIs use allowPublicApiChanges={{allowPublicApiChanges:boolean=true}} when needed and verified. Never edit lifecycle fields: runtime SELECT_JSON_TASK/MARK_JSON_TASK own them. Repair only new/worsened failures and make bounded reversible assumptions autonomously.",
    },
    {
      id: "mark-tasks-verifying",
      title: "Mark Selected Tasks Verifying",
      position: { x: 2920, y: 150 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_JSON_TASK",
        path: "{{data:resolve-checklist-path:output.path}}",
        jsonPath: "tasks",
        input: "{{data:select-next-task}}",
        status: "verifying",
      },
    },
    {
      id: "work-yield-analysis",
      title: "Assess Work Yield",
      position: { x: 3060, y: -190 },
      size: { width: 300, height: 190 },
      type: "UTILITY",
      utility: {
        type: "TRANSFORM_JSON",
        input: "{}",
        deterministicTransform: {
          type: "repository-work-yield",
          baselineBlockId: "git-snapshot-before",
          currentBlockId: "git-diff-summary",
          workItemBlockId: "select-next-task",
          excludedPaths: ["{{data:resolve-checklist-path:output.path}}"],
          verifyOnObservationError: true,
        },
      },
    },
    {
      id: "count-implementation-pass",
      title: "Count Implementation Pass",
      position: { x: 2720, y: 240 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        counterName:
          "feature-implementation-checklist-loop.implementation-pass.{{data:resolve-checklist-path:output.featureId}}.{{data:select-next-task:tasks.0.id}}.{{data:select-next-task:indexes.0}}",
        maxAttempts: "{{maxImplementationPasses:number=8}}",
      },
    },
    {
      id: "baseline-verification",
      title: "Record Verification Baseline",
      position: { x: 2720, y: -360 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{verificationCommand:text=}}",
        fallbackCommand:
          "{{data:detect-project-commands:focusedVerificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "verification-decision",
      title: "Run Verification?",
      position: { x: 3060, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "json-path",
          path: "variables.verificationCommand",
          operator: "non-empty-string",
          combinator: "any",
          conditions: [
            {
              style: "json-path",
              path: "resultsByBlock.detect-project-commands.data.verificationCommand",
              operator: "non-empty-string",
            },
          ],
        },
      },
    },
    {
      id: "run-configured-checks",
      title: "Run Verification",
      position: { x: 3380, y: -120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{verificationCommand:text=}}",
        fallbackCommand: "{{data:detect-project-commands:verificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "visual-decision",
      title: "Run Visual Review?",
      position: { x: 3380, y: 120 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "json-path",
          path: "variables.enableVisualReview",
          operator: "equals",
          value: "true",
          conditions: [
            {
              style: "json-path",
              path: "variables.targetUrl",
              operator: "non-empty-string",
              combinator: "any",
              conditions: [
                {
                  style: "json-path",
                  path: "variables.screenshotPath",
                  operator: "non-empty-string",
                },
              ],
            },
          ],
        },
      },
    },
    {
      id: "visual-analysis",
      title: "Visual Review",
      position: { x: 3720, y: 20 },
      size: { width: 280, height: 190 },
      type: "UTILITY",
      utility: {
        type: "UI_ANALYZE",
        adapter: "auto",
        targetUrl: "{{targetUrl:url=}}",
        screenshotPath: "{{screenshotPath:path=}}",
        server: {
          mode: "existing",
          healthUrl: "{{healthUrl:url=}}",
        },
        checks: {
          screenshots: true,
          accessibility: true,
          console: true,
          network: true,
          responsive: true,
        },
        viewports: [
          { name: "desktop", width: 1280, height: 900 },
          { name: "tablet", width: 768, height: 1024 },
          { name: "mobile", width: 390, height: 844 },
          { name: "small-mobile", width: 320, height: 568 },
        ],
        timeoutSeconds: 30,
        fullPage: true,
        waitUntil: "domcontentloaded",
      },
    },
    {
      id: "git-diff-summary",
      title: "Git Diff Summary",
      position: { x: 3890, y: -200 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_DIFF_SUMMARY",
        cwd: ".",
        outputPath:
          "{{gitDiffFile:path=.machdoch/local/state/feature-implementation/git-diff.json}}",
      },
    },
    {
      id: "validate-progress",
      title: "Validate Progress",
      position: { x: 4060, y: 0 },
      size: { width: 300, height: 238 },
      type: "UTILITY",
      utility: {
        type: "VALIDATOR_JSON",
        maxAttempts: 2,
        schema: RALPH_VALIDATOR_JSON_SCHEMA,
        prompt:
          "Perform the independent task review of implementation against JSON checklist {{data:resolve-checklist-path:output.path}}, current selected task batch {{data:mark-tasks-verifying:tasks}}, work-yield analysis {{data:work-yield-analysis:output}}, feature request {{featureRequest:text=}}, previous goal {{previousGoal:text=}}, acceptance criteria {{acceptanceCriteria:text=}}, retained research {{data:mark-tasks-verifying:json.research}}, baseline verification {{result:baseline-verification}}, post-change verification {{result:run-configured-checks}}, git diff {{result:git-diff-summary}}, and visual review {{result:visual-analysis}}. Judge the selected product work and required adjacent tests/docs/imports; ignore unrelated workspace changes. Inspect code, behavior, accessibility, and available screenshots yourself. The selected tasks must already be in runtime-owned verifying state. Return DONE when the selected task's product criteria pass, the previous goal's existing behavior is preserved, cumulative changes against the original task or run baseline establish the requested implementation unless the task explicitly required state-only work, and no new/worsened verification failure exists. DONE completes this task review only; the engine will then perform full-feature acceptance and review. Do not require those later stages or their fault campaigns to be complete here, and do not require another implementation diff to rereview retained verified work. Return CONTINUE for missing selected product work, RETRY for own regressions, and ERROR only for unavailable external credentials/state or repeated non-progress. Never wait for a human. Include confidence, summary, evidence, and remainingWork.",
      },
    },
    {
      id: "mark-tasks-repairing",
      title: "Mark Selected Tasks Repairing",
      position: { x: 4220, y: 260 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_JSON_TASK",
        path: "{{data:resolve-checklist-path:output.path}}",
        jsonPath: "tasks",
        input: "{{data:select-next-task}}",
        status: "repairing",
      },
    },
    {
      id: "mark-tasks-completed",
      title: "Mark Selected Tasks Completed",
      position: { x: 4380, y: -360 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_JSON_TASK",
        path: "{{data:resolve-checklist-path:output.path}}",
        jsonPath: "tasks",
        input: "{{data:select-next-task}}",
        status: "completed",
      },
    },
    {
      id: "mark-tasks-deferred",
      title: "Mark Selected Tasks Deferred",
      position: { x: 4380, y: 240 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_JSON_TASK",
        path: "{{data:resolve-checklist-path:output.path}}",
        jsonPath: "tasks",
        input: "{{data:select-next-task}}",
        status: "deferred",
      },
    },
    {
      id: "read-completed-checklist",
      title: "Read Completed Checklist",
      type: "UTILITY",
      utility: {
        type: "READ_JSON",
        path: "{{data:resolve-checklist-path:output.path}}",
      },
    },
    {
      id: "count-feature-review",
      title: "Count Feature Review",
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        counterName:
          "feature-implementation-checklist-loop.feature-review.{{data:resolve-checklist-path:output.featureId}}",
        maxAttempts: "{{maxImplementationPasses:number=8}}",
      },
    },
    {
      id: "verify-complete-feature",
      title: "Verify Complete Feature",
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{verificationCommand:text=}}",
        fallbackCommand: "{{data:detect-project-commands:verificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "validate-feature",
      title: "Review Complete Feature",
      type: "UTILITY",
      utility: {
        type: "VALIDATOR_JSON",
        maxAttempts: 2,
        schema: RALPH_VALIDATOR_JSON_SCHEMA,
        prompt:
          "Review the whole delivered feature against request {{featureRequest:text=}}, previous goal {{previousGoal:text=}}, acceptance criteria {{acceptanceCriteria:text=}}, and the complete persisted checklist {{data:read-completed-checklist:json}}. Inspect the actual implementation, tests, and product behavior using retained research and design guidelines {{designGuidelines:text=}}. Fresh full-feature verification: {{result:verify-complete-feature}}. Prior visual review: {{result:visual-analysis}}. Task completion alone is insufficient: check that the checklist covers the entire request, previous behavior is preserved, and the integrated feature meets every acceptance criterion. Return DONE only with concrete evidence for full delivery and passing verification. Return CONTINUE or RETRY with specific missing work or regressions to repair. Return ERROR for unavailable external state. Include confidence, summary, evidence, and remainingWork.",
      },
    },
    {
      id: "repair-feature-gaps",
      title: "Repair Feature Gaps",
      type: "PROMPT",
      settings: { maxIterations: 1 },
      prompt:
        "Repair the specific remaining feature gaps from {{result:validate-feature}} and verification failures {{result:verify-complete-feature}}. Use the complete checklist {{data:read-completed-checklist:json}}, original request {{featureRequest:text=}}, previous goal {{previousGoal:text=}}, acceptance criteria {{acceptanceCriteria:text=}}, retained research, scope {{implementationScope:text=auto-detect}}, auth instructions {{authInstructions:text=}}, and design guidelines {{designGuidelines:text=}}. Make bounded changes to the actual implementation and relevant tests; preserve unrelated workspace changes and completed task lifecycle records. Dependency changes require allowDependencyChanges={{allowDependencyChanges:boolean=true}}, schemas/migrations require allowSchemaChanges={{allowSchemaChanges:boolean=true}}, and public API changes require allowPublicApiChanges={{allowPublicApiChanges:boolean=true}}. Do not change the checklist, task status, or verification command to bypass review. Complete the missing work and report concrete evidence; the runtime will rerun full verification and review before recording completion.",
    },
    {
      id: "resolve-feature-scope",
      title: "Resolve Feature Scope",
      type: "UTILITY",
      utility: {
        type: "TRANSFORM_JSON",
        input: "{{data:read-completed-checklist:json}}",
        expression: [
          "(() => {",
          'const configured = String(variables.implementationScope ?? "auto-detect").trim();',
          'const paths = configured && configured !== "auto-detect"',
          "  ? configured.split(/[,;\\n]/u).map(path => path.trim()).filter(Boolean)",
          "  : (input.tasks ?? []).flatMap(task => task.likelyFiles ?? []);",
          "return { allowedPaths: [...new Set(paths)] };",
          "})()",
        ].join("\n"),
      },
    },
    {
      id: "scope-change-guard",
      title: "Check Feature Scope",
      type: "UTILITY",
      utility: {
        type: "CHANGE_SCOPE_GUARD",
        cwd: "{{data:detect-project-commands:rootPath}}",
        baseline: "{{data:detect-project-commands:repositoryBaseline}}",
        input: "{{data:resolve-feature-scope:output}}",
        enforce: true,
      },
    },
    {
      id: "record-done-outcome",
      title: "Record Completed Feature Outcome",
      position: { x: 4700, y: -360 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        workOutcome: "DONE",
        path: "{{featureOutcomesFile:path=.machdoch/local/state/feature-implementation/outcomes.jsonl}}",
        input:
          '{"outcome":"DONE","featureId":"{{data:resolve-checklist-path:output.featureId}}","checklistPath":"{{data:resolve-checklist-path:output.path}}"}',
      },
    },
    {
      id: "record-deferred-outcome",
      title: "Record Deferred Feature Outcome",
      position: { x: 4700, y: 240 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        workOutcome: "DEFER",
        path: "{{featureOutcomesFile:path=.machdoch/local/state/feature-implementation/outcomes.jsonl}}",
        input:
          '{"outcome":"DEFER","reason":"Bounded autonomous recovery exhausted."}',
      },
    },
    {
      id: "record-blocked-outcome",
      title: "Record Blocked Feature Outcome",
      position: { x: 4700, y: 620 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        workOutcome: "BLOCKED",
        path: "{{featureOutcomesFile:path=.machdoch/local/state/feature-implementation/outcomes.jsonl}}",
        input:
          '{"outcome":"BLOCKED","reason":"Persisted checklist tasks have no currently selectable work.","assessment":{{data:assess-checklist-tasks}}}',
      },
    },
    {
      id: "record-invalid-outcome",
      title: "Record Invalid Feature Outcome",
      position: { x: 4700, y: 430 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        workOutcome: "INVALID",
        path: "{{featureOutcomesFile:path=.machdoch/local/state/feature-implementation/outcomes.jsonl}}",
        input:
          '{"outcome":"INVALID","reason":"Autonomous checklist preparation or state recovery produced invalid data."}',
      },
    },
    {
      id: "final-report",
      title: "Final Feature Report",
      position: { x: 4380, y: -180 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{featureReportFile:path=.machdoch/local/state/feature-implementation/final-report.json}}",
        outputPath:
          "{{featureReportMarkdown:path=.machdoch/local/state/feature-implementation/final-report.md}}",
      },
    },
    {
      id: "retained-checklist-report",
      title: "Retained Feature Checklist Report",
      position: { x: 4380, y: 420 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{featureReportFile:path=.machdoch/local/state/feature-implementation/final-report.json}}",
        outputPath:
          "{{featureReportMarkdown:path=.machdoch/local/state/feature-implementation/final-report.md}}",
      },
    },
    {
      id: "record-autonomy-deferral",
      title: "Record Autonomous Deferral",
      position: { x: 4380, y: 240 },
      size: { width: 300, height: 150 },
      type: "UTILITY",
      utility: {
        type: "NOTIFY",
        message:
          "Feature work was deferred after bounded autonomous recovery attempts; preserve the run report and continue on the next independently actionable item.",
      },
    },
    {
      id: "archive-feature-checklist",
      title: "Archive Feature Checklist",
      position: { x: 5040, y: 0 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "ARCHIVE_FILE",
        path: "{{data:resolve-checklist-path:output.path}}",
        rootPath:
          "{{checklistArchiveDirectory:path=.machdoch/local/state/feature-implementation/archive}}",
      },
    },
    {
      id: "outcome-ledger-persisted",
      title: "Outcome Ledger Persisted?",
      position: { x: 4880, y: 120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "json-path",
          path: "resultsByBlock.resolve-checklist-path.output",
          operator: "equals",
          value: "SUCCESS",
          conditions: [
            {
              style: "json-path",
              path: "resultsByBlock.record-done-outcome.output",
              operator: "equals",
              value: "SUCCESS",
            },
          ],
        },
      },
    },
    {
      id: "feature-outcome-is-done",
      title: "Feature Completed?",
      position: { x: 5360, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "json-path",
          path: "resultsByBlock.record-done-outcome.output",
          operator: "equals",
          value: "SUCCESS",
        },
      },
    },
    {
      id: "complete",
      title: "Complete",
      position: { x: 4400, y: 0 },
      size: { width: 256, height: 114 },
      type: "END",
      status: "success",
    },
    {
      id: "deferred",
      title: "Implementation Deferred",
      position: { x: 1400, y: 240 },
      size: { width: 300, height: 114 },
      type: "END",
      outcome: "deferred",
    },
  ],
  edges: [
    {
      id: "completed-checklist-to-review-budget",
      from: "read-completed-checklist",
      fromOutput: "SUCCESS",
      to: "count-feature-review",
    },
    {
      id: "completed-checklist-read-error",
      from: "read-completed-checklist",
      fromOutput: "ERROR",
      to: "record-deferred-outcome",
    },
    {
      id: "completed-checklist-missing",
      from: "read-completed-checklist",
      fromOutput: "NOT_FOUND",
      to: "record-invalid-outcome",
    },
    {
      id: "completed-checklist-invalid",
      from: "read-completed-checklist",
      fromOutput: "INVALID",
      to: "record-invalid-outcome",
    },
    {
      id: "feature-review-budget-continue",
      from: "count-feature-review",
      fromOutput: "CONTINUE",
      to: "verify-complete-feature",
    },
    {
      id: "feature-review-budget-limit",
      from: "count-feature-review",
      fromOutput: "LIMIT_REACHED",
      to: "record-deferred-outcome",
    },
    {
      id: "feature-review-budget-error",
      from: "count-feature-review",
      fromOutput: "ERROR",
      to: "record-deferred-outcome",
    },
    {
      id: "complete-feature-check-to-review",
      from: "verify-complete-feature",
      fromOutput: "SUCCESS",
      to: "validate-feature",
    },
    {
      id: "complete-feature-check-failed",
      from: "verify-complete-feature",
      fromOutput: "FAILED",
      to: "repair-feature-gaps",
    },
    {
      id: "complete-feature-check-inconclusive",
      from: "verify-complete-feature",
      fromOutput: "INCONCLUSIVE",
      to: "record-deferred-outcome",
    },
    {
      id: "complete-feature-check-error",
      from: "verify-complete-feature",
      fromOutput: "ERROR",
      to: "record-deferred-outcome",
    },
    {
      id: "complete-feature-review-done",
      from: "validate-feature",
      fromOutput: "DONE",
      to: "resolve-feature-scope",
    },
    {
      id: "resolved-feature-scope",
      from: "resolve-feature-scope",
      fromOutput: "SUCCESS",
      to: "scope-change-guard",
    },
    {
      id: "feature-scope-resolution-error",
      from: "resolve-feature-scope",
      fromOutput: "ERROR",
      to: "record-deferred-outcome",
    },
    {
      id: "feature-scope-verified",
      from: "scope-change-guard",
      fromOutput: "IN_SCOPE",
      to: "record-done-outcome",
    },
    ...["OUT_OF_SCOPE", "ADVISORY", "EMPTY", "ERROR"].map((output) => ({
      id: `feature-scope-${output.toLowerCase().replaceAll("_", "-")}`,
      from: "scope-change-guard",
      fromOutput: output,
      to: "record-deferred-outcome",
    })),
    {
      id: "complete-feature-review-continue",
      from: "validate-feature",
      fromOutput: "CONTINUE",
      to: "repair-feature-gaps",
    },
    {
      id: "complete-feature-review-retry",
      from: "validate-feature",
      fromOutput: "RETRY",
      to: "repair-feature-gaps",
    },
    {
      id: "complete-feature-review-error",
      from: "validate-feature",
      fromOutput: "ERROR",
      to: "record-deferred-outcome",
    },
    {
      id: "complete-feature-review-invalid",
      from: "validate-feature",
      fromOutput: "INVALID",
      to: "record-invalid-outcome",
    },
    {
      id: "feature-gaps-repaired",
      from: "repair-feature-gaps",
      fromOutput: "SUCCESS",
      to: "read-completed-checklist",
    },
    {
      id: "feature-gaps-repair-error",
      from: "repair-feature-gaps",
      fromOutput: "ERROR",
      to: "record-deferred-outcome",
    },
    {
      id: "selected-checklist-to-implementation",
      from: "read-selected-checklist",
      fromOutput: "SUCCESS",
      to: "implement-feature",
    },
    {
      id: "selected-checklist-error",
      from: "read-selected-checklist",
      fromOutput: "ERROR",
      to: "mark-tasks-deferred",
    },
    {
      id: "selected-checklist-missing",
      from: "read-selected-checklist",
      fromOutput: "NOT_FOUND",
      to: "record-invalid-outcome",
    },
    {
      id: "selected-checklist-invalid",
      from: "read-selected-checklist",
      fromOutput: "INVALID",
      to: "record-invalid-outcome",
    },
    {
      id: "start-to-detect-commands",
      from: "start",
      fromOutput: "SUCCESS",
      to: "detect-project-commands",
    },
    {
      id: "detect-commands-to-resolve-checklist",
      from: "detect-project-commands",
      fromOutput: "SUCCESS",
      to: "resolve-checklist-path",
    },
    {
      id: "detect-commands-empty-to-resolve-checklist",
      from: "detect-project-commands",
      fromOutput: "EMPTY",
      to: "resolve-checklist-path",
    },
    {
      id: "detect-commands-error-to-resolve-checklist",
      from: "detect-project-commands",
      fromOutput: "ERROR",
      to: "resolve-checklist-path",
    },
    {
      id: "resolve-checklist-to-exists",
      from: "resolve-checklist-path",
      fromOutput: "SUCCESS",
      to: "checklist-exists",
    },
    {
      id: "resolve-checklist-error",
      from: "resolve-checklist-path",
      fromOutput: "ERROR",
      to: "record-invalid-outcome",
    },
    {
      id: "checklist-exists-read",
      from: "checklist-exists",
      fromOutput: "EXISTS",
      to: "read-checklist",
    },
    {
      id: "checklist-missing-to-brief",
      from: "checklist-exists",
      fromOutput: "MISSING",
      to: "prepare-feature-brief",
    },
    {
      id: "checklist-exists-error-to-brief",
      from: "checklist-exists",
      fromOutput: "ERROR",
      to: "prepare-feature-brief",
    },
    {
      id: "read-checklist-to-match",
      from: "read-checklist",
      fromOutput: "SUCCESS",
      to: "checklist-matches-feature",
    },
    {
      id: "read-checklist-invalid-to-archive",
      from: "read-checklist",
      fromOutput: "INVALID",
      to: "archive-mismatched-checklist",
    },
    {
      id: "read-checklist-error-to-brief",
      from: "read-checklist",
      fromOutput: "ERROR",
      to: "prepare-feature-brief",
    },
    {
      id: "read-checklist-not-found-to-brief",
      from: "read-checklist",
      fromOutput: "NOT_FOUND",
      to: "prepare-feature-brief",
    },
    {
      id: "matching-checklist-to-assessment",
      from: "checklist-matches-feature",
      fromOutput: "MATCH",
      to: "assess-checklist-tasks",
    },
    {
      id: "mismatched-checklist-to-archive",
      from: "checklist-matches-feature",
      fromOutput: "NO_MATCH",
      to: "archive-mismatched-checklist",
    },
    {
      id: "checklist-match-error-to-archive",
      from: "checklist-matches-feature",
      fromOutput: "ERROR",
      to: "archive-mismatched-checklist",
    },
    {
      id: "archive-mismatch-to-brief",
      from: "archive-mismatched-checklist",
      fromOutput: "SUCCESS",
      to: "prepare-feature-brief",
    },
    {
      id: "archive-mismatch-missing-to-brief",
      from: "archive-mismatched-checklist",
      fromOutput: "NOT_FOUND",
      to: "prepare-feature-brief",
    },
    {
      id: "archive-mismatch-error-to-invalid",
      from: "archive-mismatched-checklist",
      fromOutput: "ERROR",
      to: "record-invalid-outcome",
    },
    {
      id: "brief-to-research-decision",
      from: "prepare-feature-brief",
      fromOutput: "SUCCESS",
      to: "research-decision",
    },
    {
      id: "brief-error",
      from: "prepare-feature-brief",
      fromOutput: "ERROR",
      to: "record-invalid-outcome",
    },
    {
      id: "research-decision-run",
      from: "research-decision",
      fromOutput: "MATCH",
      to: "initial-research",
    },
    {
      id: "research-decision-skip",
      from: "research-decision",
      fromOutput: "NO_MATCH",
      to: "specification-checklist",
    },
    {
      id: "research-decision-error",
      from: "research-decision",
      fromOutput: "ERROR",
      to: "specification-checklist",
    },
    {
      id: "research-to-specification",
      from: "initial-research",
      fromOutput: "SUCCESS",
      to: "specification-checklist",
    },
    {
      id: "research-error-to-specification",
      from: "initial-research",
      fromOutput: "ERROR",
      to: "specification-checklist",
    },
    {
      id: "specification-to-assessment",
      from: "specification-checklist",
      fromOutput: "SUCCESS",
      to: "assess-checklist-tasks",
    },
    {
      id: "specification-invalid",
      from: "specification-checklist",
      fromOutput: "INVALID",
      to: "record-invalid-outcome",
    },
    {
      id: "specification-error",
      from: "specification-checklist",
      fromOutput: "ERROR",
      to: "record-invalid-outcome",
    },
    {
      id: "assessed-checklist-ready-to-select",
      from: "assess-checklist-tasks",
      fromOutput: "READY",
      to: "select-next-task",
    },
    {
      id: "assessed-checklist-complete-to-review",
      from: "assess-checklist-tasks",
      fromOutput: "COMPLETE",
      to: "read-completed-checklist",
    },
    {
      id: "assessed-checklist-blocked-to-ledger",
      from: "assess-checklist-tasks",
      fromOutput: "BLOCKED",
      to: "record-blocked-outcome",
    },
    {
      id: "assessed-checklist-deferred-to-ledger",
      from: "assess-checklist-tasks",
      fromOutput: "DEFERRED",
      to: "record-deferred-outcome",
    },
    {
      id: "assessed-checklist-empty-to-invalid",
      from: "assess-checklist-tasks",
      fromOutput: "EMPTY",
      to: "record-invalid-outcome",
    },
    {
      id: "assessed-checklist-missing-to-invalid",
      from: "assess-checklist-tasks",
      fromOutput: "NOT_FOUND",
      to: "record-invalid-outcome",
    },
    {
      id: "assessed-checklist-invalid",
      from: "assess-checklist-tasks",
      fromOutput: "INVALID",
      to: "record-invalid-outcome",
    },
    {
      id: "assessed-checklist-error-to-defer",
      from: "assess-checklist-tasks",
      fromOutput: "ERROR",
      to: "record-deferred-outcome",
    },
    {
      id: "select-task-to-snapshot",
      from: "select-next-task",
      fromOutput: "SELECTED",
      to: "git-snapshot-before",
    },
    {
      id: "select-task-empty-to-reassessment",
      from: "select-next-task",
      fromOutput: "EMPTY",
      to: "assess-checklist-tasks",
    },
    {
      id: "select-task-deferred",
      from: "select-next-task",
      fromOutput: "DEFERRED",
      to: "record-deferred-outcome",
    },
    {
      id: "select-task-blocked",
      from: "select-next-task",
      fromOutput: "BLOCKED",
      to: "record-blocked-outcome",
    },
    {
      id: "select-task-not-found",
      from: "select-next-task",
      fromOutput: "NOT_FOUND",
      to: "record-invalid-outcome",
    },
    {
      id: "select-task-invalid",
      from: "select-next-task",
      fromOutput: "INVALID",
      to: "assess-checklist-tasks",
    },
    {
      id: "select-task-error",
      from: "select-next-task",
      fromOutput: "ERROR",
      to: "mark-tasks-deferred",
    },
    {
      id: "snapshot-to-baseline",
      from: "git-snapshot-before",
      fromOutput: "SUCCESS",
      to: "baseline-verification",
    },
    {
      id: "snapshot-error-to-baseline",
      from: "git-snapshot-before",
      fromOutput: "ERROR",
      to: "baseline-verification",
    },
    {
      id: "baseline-success-to-count",
      from: "baseline-verification",
      fromOutput: "SUCCESS",
      to: "count-implementation-pass",
    },
    {
      id: "baseline-failed-to-count",
      from: "baseline-verification",
      fromOutput: "FAILED",
      to: "count-implementation-pass",
    },
    {
      id: "baseline-error-to-count",
      from: "baseline-verification",
      fromOutput: "ERROR",
      to: "count-implementation-pass",
    },
    {
      id: "count-implementation-pass-continue",
      from: "count-implementation-pass",
      fromOutput: "CONTINUE",
      to: "read-selected-checklist",
    },
    {
      id: "count-implementation-pass-limit",
      from: "count-implementation-pass",
      fromOutput: "LIMIT_REACHED",
      to: "mark-tasks-deferred",
    },
    {
      id: "count-implementation-pass-error",
      from: "count-implementation-pass",
      fromOutput: "ERROR",
      to: "mark-tasks-deferred",
    },
    {
      id: "implementation-to-mark-verifying",
      from: "implement-feature",
      fromOutput: "SUCCESS",
      to: "mark-tasks-verifying",
    },
    {
      id: "implementation-error",
      from: "implement-feature",
      fromOutput: "ERROR",
      to: "mark-tasks-deferred",
    },
    {
      id: "mark-verifying-to-diff",
      from: "mark-tasks-verifying",
      fromOutput: "SUCCESS",
      to: "git-diff-summary",
    },
    {
      id: "mark-verifying-missing",
      from: "mark-tasks-verifying",
      fromOutput: "NOT_FOUND",
      to: "record-invalid-outcome",
    },
    {
      id: "mark-verifying-invalid",
      from: "mark-tasks-verifying",
      fromOutput: "INVALID",
      to: "record-invalid-outcome",
    },
    {
      id: "mark-verifying-error",
      from: "mark-tasks-verifying",
      fromOutput: "ERROR",
      to: "record-invalid-outcome",
    },
    {
      id: "git-diff-success-to-work-yield",
      from: "git-diff-summary",
      fromOutput: "SUCCESS",
      to: "work-yield-analysis",
    },
    {
      id: "git-diff-empty-to-work-yield",
      from: "git-diff-summary",
      fromOutput: "EMPTY",
      to: "work-yield-analysis",
    },
    {
      id: "git-diff-error-to-work-yield",
      from: "git-diff-summary",
      fromOutput: "ERROR",
      to: "work-yield-analysis",
    },
    {
      id: "work-yield-analysis-success",
      from: "work-yield-analysis",
      fromOutput: "SUCCESS",
      to: "verification-decision",
    },
    {
      id: "work-yield-analysis-error",
      from: "work-yield-analysis",
      fromOutput: "ERROR",
      to: "verification-decision",
    },
    {
      id: "verification-decision-run",
      from: "verification-decision",
      fromOutput: "MATCH",
      to: "run-configured-checks",
    },
    {
      id: "verification-decision-skip",
      from: "verification-decision",
      fromOutput: "NO_MATCH",
      to: "visual-decision",
    },
    {
      id: "verification-decision-error",
      from: "verification-decision",
      fromOutput: "ERROR",
      to: "visual-decision",
    },
    {
      id: "checks-success-to-visual-decision",
      from: "run-configured-checks",
      fromOutput: "SUCCESS",
      to: "visual-decision",
    },
    {
      id: "checks-failed-to-visual-decision",
      from: "run-configured-checks",
      fromOutput: "FAILED",
      to: "visual-decision",
    },
    {
      id: "checks-error-to-visual-decision",
      from: "run-configured-checks",
      fromOutput: "ERROR",
      to: "visual-decision",
    },
    {
      id: "visual-decision-run",
      from: "visual-decision",
      fromOutput: "MATCH",
      to: "visual-analysis",
    },
    {
      id: "visual-decision-skip",
      from: "visual-decision",
      fromOutput: "NO_MATCH",
      to: "validate-progress",
    },
    {
      id: "visual-decision-error",
      from: "visual-decision",
      fromOutput: "ERROR",
      to: "validate-progress",
    },
    {
      id: "visual-success-to-validate",
      from: "visual-analysis",
      fromOutput: "SUCCESS",
      to: "validate-progress",
    },
    {
      id: "visual-unavailable-to-validate",
      from: "visual-analysis",
      fromOutput: "UNAVAILABLE",
      to: "validate-progress",
    },
    {
      id: "visual-error-to-validate",
      from: "visual-analysis",
      fromOutput: "ERROR",
      to: "validate-progress",
    },
    {
      id: "validation-done",
      from: "validate-progress",
      fromOutput: "DONE",
      to: "mark-tasks-completed",
    },
    {
      id: "validation-continue",
      from: "validate-progress",
      fromOutput: "CONTINUE",
      to: "mark-tasks-repairing",
    },
    {
      id: "validation-retry",
      from: "validate-progress",
      fromOutput: "RETRY",
      to: "mark-tasks-repairing",
    },
    {
      id: "validation-error",
      from: "validate-progress",
      fromOutput: "ERROR",
      to: "mark-tasks-deferred",
    },
    {
      id: "validation-invalid",
      from: "validate-progress",
      fromOutput: "INVALID",
      to: "mark-tasks-deferred",
    },
    {
      id: "mark-repairing-to-select",
      from: "mark-tasks-repairing",
      fromOutput: "SUCCESS",
      to: "assess-checklist-tasks",
    },
    {
      id: "mark-repairing-missing",
      from: "mark-tasks-repairing",
      fromOutput: "NOT_FOUND",
      to: "record-invalid-outcome",
    },
    {
      id: "mark-repairing-invalid",
      from: "mark-tasks-repairing",
      fromOutput: "INVALID",
      to: "record-invalid-outcome",
    },
    {
      id: "mark-repairing-error",
      from: "mark-tasks-repairing",
      fromOutput: "ERROR",
      to: "record-invalid-outcome",
    },
    {
      id: "mark-completed-to-select",
      from: "mark-tasks-completed",
      fromOutput: "SUCCESS",
      to: "assess-checklist-tasks",
    },
    {
      id: "mark-completed-missing-to-select",
      from: "mark-tasks-completed",
      fromOutput: "NOT_FOUND",
      to: "assess-checklist-tasks",
    },
    {
      id: "mark-completed-invalid",
      from: "mark-tasks-completed",
      fromOutput: "INVALID",
      to: "record-invalid-outcome",
    },
    {
      id: "mark-completed-error",
      from: "mark-tasks-completed",
      fromOutput: "ERROR",
      to: "record-invalid-outcome",
    },
    {
      id: "mark-deferred-to-reassessment",
      from: "mark-tasks-deferred",
      fromOutput: "SUCCESS",
      to: "assess-checklist-tasks",
    },
    {
      id: "mark-deferred-missing-to-record",
      from: "mark-tasks-deferred",
      fromOutput: "NOT_FOUND",
      to: "record-deferred-outcome",
    },
    {
      id: "mark-deferred-invalid-to-record",
      from: "mark-tasks-deferred",
      fromOutput: "INVALID",
      to: "record-invalid-outcome",
    },
    {
      id: "mark-deferred-error-to-record",
      from: "mark-tasks-deferred",
      fromOutput: "ERROR",
      to: "record-invalid-outcome",
    },
    {
      id: "record-done-to-report",
      from: "record-done-outcome",
      fromOutput: "SUCCESS",
      to: "final-report",
    },
    {
      id: "record-done-invalid-to-retained-report",
      from: "record-done-outcome",
      fromOutput: "INVALID",
      to: "retained-checklist-report",
    },
    {
      id: "record-done-error-to-retained-report",
      from: "record-done-outcome",
      fromOutput: "ERROR",
      to: "retained-checklist-report",
    },
    {
      id: "record-deferred-to-retained-report",
      from: "record-deferred-outcome",
      fromOutput: "SUCCESS",
      to: "retained-checklist-report",
    },
    {
      id: "record-deferred-invalid-to-retained-report",
      from: "record-deferred-outcome",
      fromOutput: "INVALID",
      to: "retained-checklist-report",
    },
    {
      id: "record-deferred-error-to-retained-report",
      from: "record-deferred-outcome",
      fromOutput: "ERROR",
      to: "retained-checklist-report",
    },
    {
      id: "record-blocked-to-retained-report",
      from: "record-blocked-outcome",
      fromOutput: "SUCCESS",
      to: "retained-checklist-report",
    },
    {
      id: "record-blocked-invalid-to-retained-report",
      from: "record-blocked-outcome",
      fromOutput: "INVALID",
      to: "retained-checklist-report",
    },
    {
      id: "record-blocked-error-to-retained-report",
      from: "record-blocked-outcome",
      fromOutput: "ERROR",
      to: "retained-checklist-report",
    },
    {
      id: "record-invalid-to-report",
      from: "record-invalid-outcome",
      fromOutput: "SUCCESS",
      to: "retained-checklist-report",
    },
    {
      id: "record-invalid-invalid-to-retained-report",
      from: "record-invalid-outcome",
      fromOutput: "INVALID",
      to: "retained-checklist-report",
    },
    {
      id: "record-invalid-error-to-retained-report",
      from: "record-invalid-outcome",
      fromOutput: "ERROR",
      to: "retained-checklist-report",
    },
    {
      id: "report-success-to-ledger-gate",
      from: "final-report",
      fromOutput: "SUCCESS",
      to: "outcome-ledger-persisted",
    },
    {
      id: "report-error-to-retained-report",
      from: "final-report",
      fromOutput: "ERROR",
      to: "retained-checklist-report",
    },
    {
      id: "retained-report-success-to-deferral",
      from: "retained-checklist-report",
      fromOutput: "SUCCESS",
      to: "record-autonomy-deferral",
    },
    {
      id: "retained-report-error-to-deferral",
      from: "retained-checklist-report",
      fromOutput: "ERROR",
      to: "record-autonomy-deferral",
    },
    {
      id: "ledger-persisted-to-archive",
      from: "outcome-ledger-persisted",
      fromOutput: "MATCH",
      to: "archive-feature-checklist",
    },
    {
      id: "ledger-failed-retain-state",
      from: "outcome-ledger-persisted",
      fromOutput: "NO_MATCH",
      to: "record-autonomy-deferral",
    },
    {
      id: "ledger-gate-error-retain-state",
      from: "outcome-ledger-persisted",
      fromOutput: "ERROR",
      to: "record-autonomy-deferral",
    },
    {
      id: "archive-feature-to-outcome",
      from: "archive-feature-checklist",
      fromOutput: "SUCCESS",
      to: "feature-outcome-is-done",
    },
    {
      id: "archive-feature-missing-to-outcome",
      from: "archive-feature-checklist",
      fromOutput: "NOT_FOUND",
      to: "feature-outcome-is-done",
    },
    {
      id: "archive-feature-error-to-deferral",
      from: "archive-feature-checklist",
      fromOutput: "ERROR",
      to: "record-autonomy-deferral",
    },
    {
      id: "feature-done-to-complete",
      from: "feature-outcome-is-done",
      fromOutput: "MATCH",
      to: "complete",
    },
    {
      id: "feature-not-done-to-notify",
      from: "feature-outcome-is-done",
      fromOutput: "NO_MATCH",
      to: "record-autonomy-deferral",
    },
    {
      id: "feature-outcome-error-to-notify",
      from: "feature-outcome-is-done",
      fromOutput: "ERROR",
      to: "record-autonomy-deferral",
    },
    {
      id: "record-autonomy-deferral-to-deferred",
      from: "record-autonomy-deferral",
      fromOutput: "SUCCESS",
      to: "deferred",
    },
  ],
};

export const featureImplementationChecklistLoopStarterFlow = {
  id: "full-feature-implementation",
  version: 28,
  defaultAlias: "feature-implementation-checklist-loop",
  category: "Implementation",
  tags: ["feature", "research", "visual-check"],
  protocol: {
    schemaVersion: 1,
    verification: {
      planId: "starter-full-feature-implementation:frozen-verification",
      baselineBlockId: "baseline-verification",
      candidateBlockId: "run-configured-checks",
      baselineInconclusiveTargetId: "mark-tasks-deferred",
      candidateInconclusiveTargetId: "mark-tasks-deferred",
      routeOverrides: [],
    },
    terminalOutcomes: [
      { blockId: "complete", outcome: "succeeded" },
      { blockId: "deferred", outcome: "deferred" },
    ],
  },
  flow: layoutFeatureImplementationFlow(fullFeatureImplementationFlow),
} as const satisfies RalphStarterFlow;
