import type { RalphFlow } from "../ralph.js";
import type { RalphStarterFlow } from "../ralph-starter-flows.js";
import { RALPH_VALIDATOR_JSON_SCHEMA } from "../_helpers/parse-ralph-validator-json-result.helper.js";

const RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS = 30 * 60;

const securityFixLoopFlow: RalphFlow = {
  schemaVersion: 1,
  id: "starter-security-fix-loop",
  alias: "security-review-fix-loop",
  name: "Security Review & Fix Loop",
  description:
    "Optional bounded autonomous security cycle that reviews risk-first scopes, records a verification baseline, repairs findings, and defers exhausted scopes without human intervention.",
  settings: {
    maxTransitions: 5_000,
    autonomy: {
      recoverFailedEnd: true,
      maxRecoveryAttempts: 3,
      transitionExhaustion: "checkpoint",
      recoveryExhaustion: "defer",
      deferToBlockId: "defer-scope",
    },
  },
  variables: [
    {
      name: "scopeRoot",
      type: "path",
      default: ".",
      required: false,
    },
    {
      name: "scopeSelectionStrategy",
      type: "text",
      default: "risk-first",
      required: false,
    },
    {
      name: "scopeRegistryFile",
      type: "path",
      default:
        ".machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.json",
      required: false,
    },
    {
      name: "scopeRegistryMarkdown",
      type: "path",
      default:
        ".machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.md",
      required: false,
    },
    {
      name: "projectStack",
      type: "text",
      default: "auto-detect",
      required: false,
    },
    {
      name: "securityStandards",
      type: "text",
      default: "OWASP Top 10, OWASP ASVS",
      required: false,
    },
    {
      name: "severityThreshold",
      type: "text",
      default: "high",
      required: false,
    },
    {
      name: "enableOnlineResearch",
      type: "boolean",
      default: "true",
      required: false,
    },
    {
      name: "verificationCommand",
      type: "text",
      default: "",
      required: false,
    },
    {
      name: "authTestInstructions",
      type: "text",
      default: "",
      required: false,
    },
    {
      name: "historyFile",
      type: "path",
      default: ".machdoch/ralph/security/RALPH_SECURITY_HISTORY.md",
      required: false,
    },
    {
      name: "schemaChangePolicy",
      type: "text",
      default: "allow-verified",
      required: false,
    },
    {
      name: "allowDependencyChanges",
      type: "boolean",
      default: "true",
      required: false,
    },
    {
      name: "scopeScanMaxDepth",
      type: "number",
      default: "4",
      required: false,
    },
    {
      name: "scopeScanMaxResults",
      type: "number",
      default: "200",
      required: false,
    },
    {
      name: "allowSchemaChanges",
      type: "boolean",
      default: "true",
      required: false,
    },
    {
      name: "allowPublicApiChanges",
      type: "boolean",
      default: "true",
      required: false,
    },
    {
      name: "maxFixLoops",
      type: "number",
      default: "10",
      required: false,
    },
    {
      name: "projectCommandsFile",
      type: "path",
      default: "{{run:artifactRoot}}/security/project-commands.json",
      required: false,
    },
    {
      name: "securityReviewFile",
      type: "path",
      default: "{{run:artifactRoot}}/security/review.json",
      required: false,
    },
    {
      name: "gitSnapshotFile",
      type: "path",
      default: "{{run:artifactRoot}}/security/git-snapshot.json",
      required: false,
    },
    {
      name: "gitDiffFile",
      type: "path",
      default: "{{run:artifactRoot}}/security/git-diff.json",
      required: false,
    },
    {
      name: "securityReportFile",
      type: "path",
      default: "{{run:artifactRoot}}/security/final-report.json",
      required: false,
    },
    {
      name: "securityReportMarkdown",
      type: "path",
      default: "{{run:artifactRoot}}/security/final-report.md",
      required: false,
    },
    {
      name: "securityOutcomesFile",
      type: "path",
      default: ".machdoch/ralph/security/outcomes.jsonl",
      required: false,
    },
  ],
  blocks: [
    {
      id: "start",
      title: "Start",
      position: { x: 0, y: 0 },
      size: { width: 256, height: 140 },
      type: "START",
    },
    {
      id: "begin-scope-cycle",
      title: "Begin Scope Cycle",
      position: { x: 700, y: 120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "BEGIN_SCOPE_CYCLE",
        flowAlias: "security-review-fix-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.md}}",
        strategy: "{{scopeSelectionStrategy:text=risk-first}}",
        includeMarkdown: true,
      },
    },
    {
      id: "research-decision",
      title: "Use Online Research?",
      position: { x: 700, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression: 'variables.enableOnlineResearch === "true"',
        },
      },
    },
    {
      id: "security-research",
      title: "Security Research",
      position: { x: 1020, y: -120 },
      size: { width: 280, height: 190 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "medium",
        webAccess: true,
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Use content enrichment before the security review for selected JSON scope {{result:select-scope}} and bounded durable outcomes {{result:read-security-outcomes}}. If search_web is available, run focused searches for current primary-source security guidance, standards, advisories, framework hardening docs, and relevant changelogs for project stack {{projectStack:text=auto-detect}}, detected commands {{result:detect-project-commands}}, and these standards: {{securityStandards:text=OWASP Top 10, OWASP ASVS}}. Use fetch_url on official standards, vendor, maintainer, or advisory pages before relying on them. Keep the research concise and focus on the selected paths/globs, configured scope root {{scopeRoot:path=.}}, and fix threshold {{severityThreshold:text=high}}. Include source links, standard versions/requirement ids when available, relevant checks, exploitability notes, and assumptions. If web search is unavailable, say so and use local package/config evidence plus any provided URLs.",
    },
    {
      id: "scan-scopes",
      title: "Scan Scope Evidence",
      position: { x: 1020, y: 120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SCAN_SCOPE_EVIDENCE",
        rootPath: "{{scopeRoot:path=.}}",
        excludePaths:
          "node_modules, dist, build, coverage, target, .next, .nuxt, .turbo, .cache, vendor, generated, .machdoch",
        maxDepth: "{{scopeScanMaxDepth:number=4}}",
        maxResults: "{{scopeScanMaxResults:number=200}}",
      },
    },
    {
      id: "update-scope-registry",
      title: "Update Scope Registry",
      position: { x: 1360, y: 120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "UPDATE_SCOPE_REGISTRY",
        flowAlias: "security-review-fix-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.md}}",
        strategy: "{{scopeSelectionStrategy:text=risk-first}}",
        includeMarkdown: true,
      },
    },
    {
      id: "select-scope",
      title: "Select Review Scope",
      position: { x: 1700, y: 120 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "SELECT_SCOPE",
        flowAlias: "security-review-fix-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.json}}",
        strategy: "{{scopeSelectionStrategy:text=risk-first}}",
      },
    },
    {
      id: "detect-project-commands",
      title: "Detect Project Commands",
      position: { x: 2040, y: -180 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "DETECT_PROJECT_COMMANDS",
        rootPath: "{{data:select-scope:scope.paths.0}}",
        outputPath:
          "{{projectCommandsFile:path=.machdoch/ralph/security/project-commands.json}}",
      },
    },
    {
      id: "read-security-outcomes",
      title: "Read Security Outcomes",
      position: { x: 2040, y: -20 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "QUERY_JSONL",
        path: "{{securityOutcomesFile:path=.machdoch/ralph/security/outcomes.jsonl}}",
        maxResults: 50,
        order: "newest",
      },
    },
    {
      id: "git-snapshot-before",
      title: "Git Snapshot",
      position: { x: 2040, y: 20 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_SNAPSHOT",
        cwd: ".",
        outputPath:
          "{{gitSnapshotFile:path=.machdoch/ralph/security/git-snapshot.json}}",
      },
    },
    {
      id: "security-check",
      title: "Security Review",
      position: { x: 2380, y: 0 },
      size: { width: 280, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "UTILITY",
      utility: {
        type: "PROMPT_JSON",
        outputPath:
          "{{securityReviewFile:path=.machdoch/ralph/security/review.json}}",
        maxAttempts: 2,
        schema: {
          type: "object",
          additionalProperties: false,
          required: ["scope", "coveredPaths", "threatModel", "findings"],
          properties: {
            scope: {
              type: "object",
              required: ["id", "title", "paths", "risk"],
              properties: {
                id: { type: "string" },
                title: { type: "string" },
                paths: { type: "array", items: { type: "string" } },
                tags: { type: "array", items: { type: "string" } },
                risk: { type: "string", enum: ["low", "medium", "high"] },
              },
            },
            coveredPaths: { type: "array", items: { type: "string" } },
            threatModel: {
              type: "object",
              required: [
                "assets",
                "actors",
                "trustBoundaries",
                "attackSurfaces",
                "assumptions",
              ],
              properties: {
                assets: { type: "array", items: { type: "string" } },
                actors: { type: "array", items: { type: "string" } },
                trustBoundaries: { type: "array", items: { type: "string" } },
                attackSurfaces: { type: "array", items: { type: "string" } },
                assumptions: { type: "array", items: { type: "string" } },
              },
            },
            findings: {
              type: "array",
              maxItems: 50,
              items: {
                type: "object",
                required: [
                  "id",
                  "severity",
                  "title",
                  "evidence",
                  "exploitability",
                  "fileReferences",
                  "fixPlan",
                ],
                properties: {
                  id: { type: "string" },
                  severity: {
                    type: "string",
                    enum: ["critical", "high", "medium", "low", "info"],
                  },
                  title: { type: "string" },
                  evidence: { type: "string" },
                  exploitability: { type: "string" },
                  fileReferences: { type: "array", items: { type: "string" } },
                  fixPlan: { type: "string" },
                },
              },
            },
          },
        },
        prompt:
          "Run a focused security review for selected JSON scope {{result:select-scope}}. Use project stack {{projectStack:text=auto-detect}}, detected commands {{result:detect-project-commands}}, bounded durable outcomes {{result:read-security-outcomes}}, standards {{securityStandards:text=OWASP Top 10, OWASP ASVS}}, fix threshold {{severityThreshold:text=high}}, auth test instructions {{authTestInstructions:text=}}, git baseline {{result:git-snapshot-before}}, pre-change verification baseline {{result:baseline-verification}}, and research {{summary:security-research}} when present. Inspect selected paths explicitly. Reassess previously repaired findings and resume deferred findings whose blockers are gone without repeating completed work. Return JSON with coveredPaths, concise threatModel, and findings at or above threshold. Findings must include severity, evidence, exploitability, file references, and fixPlan. If none qualify, return findings: []. Schema, dependency, and public API changes are allowed when needed and verified.",
      },
    },
    {
      id: "findings-present",
      title: "Findings Present?",
      position: { x: 2720, y: -120 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "Array.isArray(lastData?.output?.findings) && lastData.output.findings.length > 0",
        },
      },
    },
    {
      id: "baseline-verification",
      title: "Record Verification Baseline",
      position: { x: 2210, y: -220 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{verificationCommand:text=}}",
        fallbackCommand:
          "{{data:detect-project-commands:focusedVerificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "count-fix-loop",
      title: "Count Fix Loop",
      position: { x: 3060, y: -190 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "LOOP_COUNTER",
        counterName:
          "security-review-fix-loop.fix-loop.{{data:select-scope:scope.id}}",
        maxAttempts: "{{maxFixLoops:number=10}}",
      },
    },
    {
      id: "fix-findings",
      title: "Fix Findings",
      position: { x: 3060, y: 0 },
      size: { width: 280, height: 210 },
      settings: {
        workspace: { mode: "default" },
        reasoning: "high",
        attachments: [],
        packs: [],
        maxIterations: 1,
      },
      type: "PROMPT",
      prompt:
        "Fix security findings from {{data:security-check:output.findings}} for selected scope {{result:select-scope}} at or above {{severityThreshold:text=high}}. Use threat model, git/verification baselines, and scope guard {{result:scope-change-guard}}. Keep changes cohesive, add targeted tests, and do not start/restart servers. Dependency changes use allowDependencyChanges={{allowDependencyChanges:boolean=true}}, schemas/migrations follow schemaChangePolicy={{schemaChangePolicy:text=allow-verified}} and allowSchemaChanges={{allowSchemaChanges:boolean=true}}, and public APIs use allowPublicApiChanges={{allowPublicApiChanges:boolean=true}} when necessary and verified; update consumers and rollback notes. Repair only new/worsened failures, make bounded reversible assumptions autonomously, and append concise evidence to {{historyFile:path=.machdoch/ralph/security/RALPH_SECURITY_HISTORY.md}}.",
    },
    {
      id: "verification-decision",
      title: "Run Verification?",
      position: { x: 3400, y: 0 },
      size: { width: 256, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CONDITION",
        condition: {
          style: "javascript",
          expression:
            "Boolean(variables.verificationCommand?.trim() || context.resultsByBlock?.['detect-project-commands']?.data?.verificationCommand?.trim())",
        },
      },
    },
    {
      id: "run-verification",
      title: "Run Verification",
      position: { x: 3720, y: -95 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "RUN_CHECK",
        command: "{{verificationCommand:text=}}",
        fallbackCommand: "{{data:detect-project-commands:verificationCommand}}",
        cwd: "{{data:detect-project-commands:rootPath}}",
        timeoutSeconds: RALPH_VERIFICATION_COMMAND_TIMEOUT_SECONDS,
      },
    },
    {
      id: "git-diff-summary",
      title: "Git Diff Summary",
      position: { x: 4060, y: -95 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "GIT_DIFF_SUMMARY",
        cwd: ".",
        outputPath:
          "{{gitDiffFile:path=.machdoch/ralph/security/git-diff.json}}",
      },
    },
    {
      id: "verify-stop-condition",
      title: "Verify Stop Condition",
      position: { x: 4400, y: 0 },
      size: { width: 300, height: 238 },
      type: "UTILITY",
      utility: {
        type: "VALIDATOR_JSON",
        maxAttempts: 2,
        schema: RALPH_VALIDATOR_JSON_SCHEMA,
        prompt:
          "Validate the latest security iteration for selected scope {{result:select-scope}} against structured findings, scope guard {{result:scope-change-guard}}, git diff, baseline/post-change verification, and tests. Ignore unrelated changes. Return DONE only when no qualifying finding remains, changes are in scope, and no new/worsened verification failure exists; CONTINUE for bounded repairs; RETRY for own regressions; ERROR only for unavailable external state or repeated non-progress. Include confidence, summary, evidence, and remainingWork.",
      },
    },
    {
      id: "final-report",
      title: "Final Security Report",
      position: { x: 4760, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{securityReportFile:path=.machdoch/ralph/security/final-report.json}}",
        outputPath:
          "{{securityReportMarkdown:path=.machdoch/ralph/security/final-report.md}}",
      },
    },
    {
      id: "completion-report",
      title: "Security Coverage Report",
      position: { x: 5100, y: -240 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{securityReportFile:path=.machdoch/ralph/security/final-report.json}}",
        outputPath:
          "{{securityReportMarkdown:path=.machdoch/ralph/security/final-report.md}}",
      },
    },
    {
      id: "mark-scope-result",
      title: "Mark Scope Result",
      position: { x: 5100, y: 0 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "security-review-fix-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.md}}",
        scopeOutcome: "completed",
        includeMarkdown: true,
      },
    },
    {
      id: "retained-outcome-report",
      title: "Retained Security Outcome Report",
      position: { x: 4760, y: -240 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "FINAL_REPORT",
        path: "{{securityReportFile:path=.machdoch/ralph/security/final-report.json}}",
        outputPath:
          "{{securityReportMarkdown:path=.machdoch/ralph/security/final-report.md}}",
      },
    },
    {
      id: "scope-change-guard",
      title: "Guard Security Fix Scope",
      position: { x: 4220, y: -220 },
      size: { width: 280, height: 170 },
      type: "UTILITY",
      utility: {
        type: "CHANGE_SCOPE_GUARD",
        baselineBlockId: "git-snapshot-before",
        input:
          '{"scope":{{data:select-scope:scope}},"gitSummary":{{data:git-diff-summary}}}',
      },
    },
    {
      id: "defer-scope",
      title: "Defer Exhausted Security Scope",
      position: { x: 5100, y: 220 },
      size: { width: 300, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "security-review-fix-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.md}}",
        scopeOutcome: "deferred",
        includeMarkdown: true,
      },
    },
    {
      id: "mark-invalid-scope",
      title: "Mark Invalid Security Scope",
      position: { x: 5100, y: 580 },
      size: { width: 300, height: 170 },
      type: "UTILITY",
      utility: {
        type: "MARK_SCOPE_RESULT",
        flowAlias: "security-review-fix-loop",
        registryPath:
          "{{scopeRegistryFile:path=.machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.json}}",
        outputPath:
          "{{scopeRegistryMarkdown:path=.machdoch/ralph/scope-registry/security-review-fix-loop.scope-registry.md}}",
        scopeOutcome: "invalid",
        includeMarkdown: true,
      },
    },
    {
      id: "record-security-findings",
      title: "Retain Security Findings",
      position: { x: 2890, y: -120 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        path: "{{securityOutcomesFile:path=.machdoch/ralph/security/outcomes.jsonl}}",
        input:
          '{"state":"selected","scopeId":"{{data:select-scope:scope.id}}","review":{{data:security-check:output}}}',
      },
    },
    {
      id: "record-done-outcome",
      title: "Record Completed Security Outcome",
      position: { x: 5440, y: -240 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        workOutcome: "DONE",
        path: "{{securityOutcomesFile:path=.machdoch/ralph/security/outcomes.jsonl}}",
        input:
          '{"state":"repaired","scopeId":"{{data:select-scope:scope.id}}","review":{{data:security-check:output}},"validation":{{data:verify-stop-condition:output}}}',
      },
    },
    {
      id: "record-deferred-outcome",
      title: "Record Deferred Security Outcome",
      position: { x: 5440, y: 180 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        workOutcome: "DEFER",
        path: "{{securityOutcomesFile:path=.machdoch/ralph/security/outcomes.jsonl}}",
        input:
          '{"state":"deferred","scopeId":"{{data:select-scope:scope.id}}","review":{{data:security-check:output}}}',
      },
    },
    {
      id: "record-stop-outcome",
      title: "Record No-Action Security Outcome",
      position: { x: 5440, y: 380 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        workOutcome: "STOP",
        path: "{{securityOutcomesFile:path=.machdoch/ralph/security/outcomes.jsonl}}",
        input:
          '{"state":"clear","scopeId":"{{data:select-scope:scope.id}}","review":{{data:security-check:output}}}',
      },
    },
    {
      id: "record-invalid-outcome",
      title: "Record Invalid Security Outcome",
      position: { x: 5440, y: 580 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        workOutcome: "INVALID",
        path: "{{securityOutcomesFile:path=.machdoch/ralph/security/outcomes.jsonl}}",
        input: '{"outcome":"INVALID","scopeRoot":"{{scopeRoot:path=.}}"}',
      },
    },
    {
      id: "record-coverage-deferred-outcome",
      title: "Record Deferred Security Coverage",
      position: { x: 5780, y: 180 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        workOutcome: "DEFER",
        path: "{{securityOutcomesFile:path=.machdoch/ralph/security/outcomes.jsonl}}",
        input:
          '{"state":"coverage-deferred","scopeRoot":"{{scopeRoot:path=.}}","reason":"The coverage cycle is waiting on deferred scopes."}',
      },
    },
    {
      id: "record-exhausted-outcome",
      title: "Record Exhausted Security Coverage",
      position: { x: 5780, y: 380 },
      size: { width: 280, height: 170 },
      settings: { retry: { mode: "finite", maxRetries: 3, delaySeconds: 1 } },
      type: "UTILITY",
      utility: {
        type: "APPEND_JSONL",
        workOutcome: "STOP",
        path: "{{securityOutcomesFile:path=.machdoch/ralph/security/outcomes.jsonl}}",
        input:
          '{"state":"coverage-exhausted","scopeRoot":"{{scopeRoot:path=.}}","reason":"The current security coverage cycle has no remaining eligible scope."}',
      },
    },
    {
      id: "success",
      title: "No Blocking Findings",
      position: { x: 5780, y: 0 },
      size: { width: 256, height: 114 },
      type: "END",
      status: "success",
    },
    {
      id: "deferred",
      title: "Security Work Deferred",
      position: { x: 5780, y: 260 },
      size: { width: 280, height: 114 },
      type: "END",
      outcome: "deferred",
    },
  ],
  edges: [
    {
      id: "start-to-begin-scope-cycle",
      from: "start",
      fromOutput: "SUCCESS",
      to: "begin-scope-cycle",
    },
    {
      id: "begin-scope-cycle-to-scan-scopes",
      from: "begin-scope-cycle",
      fromOutput: "SUCCESS",
      to: "scan-scopes",
    },
    {
      id: "begin-scope-cycle-error",
      from: "begin-scope-cycle",
      fromOutput: "ERROR",
      to: "retained-outcome-report",
    },
    {
      id: "scan-scopes-to-update",
      from: "scan-scopes",
      fromOutput: "SUCCESS",
      to: "update-scope-registry",
    },
    {
      id: "scan-scopes-empty",
      from: "scan-scopes",
      fromOutput: "EMPTY",
      to: "record-exhausted-outcome",
    },
    {
      id: "scan-scopes-error",
      from: "scan-scopes",
      fromOutput: "ERROR",
      to: "retained-outcome-report",
    },
    {
      id: "update-registry-to-select",
      from: "update-scope-registry",
      fromOutput: "SUCCESS",
      to: "select-scope",
    },
    {
      id: "update-registry-empty",
      from: "update-scope-registry",
      fromOutput: "EMPTY",
      to: "record-exhausted-outcome",
    },
    {
      id: "update-registry-error",
      from: "update-scope-registry",
      fromOutput: "ERROR",
      to: "retained-outcome-report",
    },
    {
      id: "select-scope-to-detect-commands",
      from: "select-scope",
      fromOutput: "SELECTED",
      to: "detect-project-commands",
    },
    {
      id: "select-scope-exhausted",
      from: "select-scope",
      fromOutput: "EXHAUSTED",
      to: "record-exhausted-outcome",
    },
    {
      id: "select-scope-deferred",
      from: "select-scope",
      fromOutput: "DEFERRED",
      to: "record-coverage-deferred-outcome",
    },
    {
      id: "select-scope-error",
      from: "select-scope",
      fromOutput: "ERROR",
      to: "retained-outcome-report",
    },
    {
      id: "detect-commands-to-research-decision",
      from: "detect-project-commands",
      fromOutput: "SUCCESS",
      to: "read-security-outcomes",
    },
    {
      id: "detect-commands-empty-to-research-decision",
      from: "detect-project-commands",
      fromOutput: "EMPTY",
      to: "read-security-outcomes",
    },
    {
      id: "detect-commands-error-to-research-decision",
      from: "detect-project-commands",
      fromOutput: "ERROR",
      to: "read-security-outcomes",
    },
    {
      id: "outcomes-success-to-research-decision",
      from: "read-security-outcomes",
      fromOutput: "SUCCESS",
      to: "research-decision",
    },
    {
      id: "outcomes-empty-to-research-decision",
      from: "read-security-outcomes",
      fromOutput: "EMPTY",
      to: "research-decision",
    },
    {
      id: "outcomes-not-found-to-research-decision",
      from: "read-security-outcomes",
      fromOutput: "NOT_FOUND",
      to: "research-decision",
    },
    {
      id: "outcomes-invalid-to-research-decision",
      from: "read-security-outcomes",
      fromOutput: "INVALID",
      to: "research-decision",
    },
    {
      id: "outcomes-error-to-research-decision",
      from: "read-security-outcomes",
      fromOutput: "ERROR",
      to: "research-decision",
    },
    {
      id: "research-decision-run",
      from: "research-decision",
      fromOutput: "MATCH",
      to: "security-research",
    },
    {
      id: "research-decision-skip",
      from: "research-decision",
      fromOutput: "NO_MATCH",
      to: "git-snapshot-before",
    },
    {
      id: "research-decision-error",
      from: "research-decision",
      fromOutput: "ERROR",
      to: "git-snapshot-before",
    },
    {
      id: "research-to-snapshot",
      from: "security-research",
      fromOutput: "SUCCESS",
      to: "git-snapshot-before",
    },
    {
      id: "research-error-to-snapshot",
      from: "security-research",
      fromOutput: "ERROR",
      to: "git-snapshot-before",
    },
    {
      id: "git-snapshot-to-baseline",
      from: "git-snapshot-before",
      fromOutput: "SUCCESS",
      to: "baseline-verification",
    },
    {
      id: "git-snapshot-error-to-baseline",
      from: "git-snapshot-before",
      fromOutput: "ERROR",
      to: "baseline-verification",
    },
    {
      id: "baseline-success-to-security-check",
      from: "baseline-verification",
      fromOutput: "SUCCESS",
      to: "security-check",
    },
    {
      id: "baseline-failed-to-security-check",
      from: "baseline-verification",
      fromOutput: "FAILED",
      to: "security-check",
    },
    {
      id: "baseline-error-to-security-check",
      from: "baseline-verification",
      fromOutput: "ERROR",
      to: "security-check",
    },
    {
      id: "security-check-to-findings-present",
      from: "security-check",
      fromOutput: "SUCCESS",
      to: "findings-present",
    },
    {
      id: "security-check-invalid",
      from: "security-check",
      fromOutput: "INVALID",
      to: "mark-invalid-scope",
    },
    {
      id: "security-check-error",
      from: "security-check",
      fromOutput: "ERROR",
      to: "mark-invalid-scope",
    },
    {
      id: "findings-present-fix",
      from: "findings-present",
      fromOutput: "MATCH",
      to: "record-security-findings",
    },
    {
      id: "findings-present-none",
      from: "findings-present",
      fromOutput: "NO_MATCH",
      to: "mark-scope-result",
    },
    {
      id: "findings-present-error",
      from: "findings-present",
      fromOutput: "ERROR",
      to: "mark-invalid-scope",
    },
    {
      id: "security-findings-retained",
      from: "record-security-findings",
      fromOutput: "SUCCESS",
      to: "count-fix-loop",
    },
    {
      id: "security-findings-invalid",
      from: "record-security-findings",
      fromOutput: "INVALID",
      to: "mark-invalid-scope",
    },
    {
      id: "security-findings-error",
      from: "record-security-findings",
      fromOutput: "ERROR",
      to: "retained-outcome-report",
    },
    {
      id: "count-fix-loop-continue",
      from: "count-fix-loop",
      fromOutput: "CONTINUE",
      to: "fix-findings",
    },
    {
      id: "count-fix-loop-limit",
      from: "count-fix-loop",
      fromOutput: "LIMIT_REACHED",
      to: "defer-scope",
    },
    {
      id: "count-fix-loop-error",
      from: "count-fix-loop",
      fromOutput: "ERROR",
      to: "defer-scope",
    },
    {
      id: "fix-findings-to-verification-decision",
      from: "fix-findings",
      fromOutput: "SUCCESS",
      to: "verification-decision",
    },
    {
      id: "fix-findings-error",
      from: "fix-findings",
      fromOutput: "ERROR",
      to: "defer-scope",
    },
    {
      id: "verification-decision-run",
      from: "verification-decision",
      fromOutput: "MATCH",
      to: "run-verification",
    },
    {
      id: "verification-decision-skip",
      from: "verification-decision",
      fromOutput: "NO_MATCH",
      to: "git-diff-summary",
    },
    {
      id: "verification-decision-error",
      from: "verification-decision",
      fromOutput: "ERROR",
      to: "git-diff-summary",
    },
    {
      id: "verification-success-to-diff",
      from: "run-verification",
      fromOutput: "SUCCESS",
      to: "git-diff-summary",
    },
    {
      id: "verification-failed-to-diff",
      from: "run-verification",
      fromOutput: "FAILED",
      to: "git-diff-summary",
    },
    {
      id: "verification-error-to-diff",
      from: "run-verification",
      fromOutput: "ERROR",
      to: "git-diff-summary",
    },
    {
      id: "git-diff-success-to-guard",
      from: "git-diff-summary",
      fromOutput: "SUCCESS",
      to: "scope-change-guard",
    },
    {
      id: "git-diff-empty-to-guard",
      from: "git-diff-summary",
      fromOutput: "EMPTY",
      to: "scope-change-guard",
    },
    {
      id: "git-diff-error-to-guard",
      from: "git-diff-summary",
      fromOutput: "ERROR",
      to: "scope-change-guard",
    },
    {
      id: "scope-guard-in-scope",
      from: "scope-change-guard",
      fromOutput: "IN_SCOPE",
      to: "verify-stop-condition",
    },
    {
      id: "scope-guard-out-of-scope",
      from: "scope-change-guard",
      fromOutput: "OUT_OF_SCOPE",
      to: "count-fix-loop",
    },
    {
      id: "scope-guard-empty",
      from: "scope-change-guard",
      fromOutput: "EMPTY",
      to: "count-fix-loop",
    },
    {
      id: "scope-guard-error",
      from: "scope-change-guard",
      fromOutput: "ERROR",
      to: "count-fix-loop",
    },
    {
      id: "verify-done",
      from: "verify-stop-condition",
      fromOutput: "DONE",
      to: "record-done-outcome",
    },
    {
      id: "verify-continue",
      from: "verify-stop-condition",
      fromOutput: "CONTINUE",
      to: "count-fix-loop",
    },
    {
      id: "verify-retry",
      from: "verify-stop-condition",
      fromOutput: "RETRY",
      to: "count-fix-loop",
    },
    {
      id: "verify-error",
      from: "verify-stop-condition",
      fromOutput: "ERROR",
      to: "defer-scope",
    },
    {
      id: "verify-invalid",
      from: "verify-stop-condition",
      fromOutput: "INVALID",
      to: "mark-invalid-scope",
    },
    {
      id: "mark-done-to-ledger",
      from: "mark-scope-result",
      fromOutput: "SUCCESS",
      to: "record-stop-outcome",
    },
    {
      id: "mark-done-missing-to-ledger",
      from: "mark-scope-result",
      fromOutput: "NOT_FOUND",
      to: "record-stop-outcome",
    },
    {
      id: "mark-done-error-to-ledger",
      from: "mark-scope-result",
      fromOutput: "ERROR",
      to: "record-stop-outcome",
    },
    {
      id: "mark-defer-to-ledger",
      from: "defer-scope",
      fromOutput: "SUCCESS",
      to: "record-deferred-outcome",
    },
    {
      id: "mark-defer-missing-to-ledger",
      from: "defer-scope",
      fromOutput: "NOT_FOUND",
      to: "record-deferred-outcome",
    },
    {
      id: "mark-defer-error-to-ledger",
      from: "defer-scope",
      fromOutput: "ERROR",
      to: "record-deferred-outcome",
    },
    {
      id: "mark-invalid-to-ledger",
      from: "mark-invalid-scope",
      fromOutput: "SUCCESS",
      to: "record-invalid-outcome",
    },
    {
      id: "mark-invalid-missing-to-ledger",
      from: "mark-invalid-scope",
      fromOutput: "NOT_FOUND",
      to: "record-invalid-outcome",
    },
    {
      id: "mark-invalid-error-to-ledger",
      from: "mark-invalid-scope",
      fromOutput: "ERROR",
      to: "record-invalid-outcome",
    },
    {
      id: "done-ledger-to-report",
      from: "record-done-outcome",
      fromOutput: "SUCCESS",
      to: "final-report",
    },
    {
      id: "done-ledger-invalid-to-retained-report",
      from: "record-done-outcome",
      fromOutput: "INVALID",
      to: "retained-outcome-report",
    },
    {
      id: "done-ledger-error-to-retained-report",
      from: "record-done-outcome",
      fromOutput: "ERROR",
      to: "retained-outcome-report",
    },
    {
      id: "defer-ledger-to-report",
      from: "record-deferred-outcome",
      fromOutput: "SUCCESS",
      to: "final-report",
    },
    {
      id: "defer-ledger-invalid-to-retained-report",
      from: "record-deferred-outcome",
      fromOutput: "INVALID",
      to: "retained-outcome-report",
    },
    {
      id: "defer-ledger-error-to-retained-report",
      from: "record-deferred-outcome",
      fromOutput: "ERROR",
      to: "retained-outcome-report",
    },
    {
      id: "stop-ledger-to-report",
      from: "record-stop-outcome",
      fromOutput: "SUCCESS",
      to: "final-report",
    },
    {
      id: "stop-ledger-invalid-to-retained-report",
      from: "record-stop-outcome",
      fromOutput: "INVALID",
      to: "retained-outcome-report",
    },
    {
      id: "stop-ledger-error-to-retained-report",
      from: "record-stop-outcome",
      fromOutput: "ERROR",
      to: "retained-outcome-report",
    },
    {
      id: "invalid-ledger-to-report",
      from: "record-invalid-outcome",
      fromOutput: "SUCCESS",
      to: "final-report",
    },
    {
      id: "invalid-ledger-invalid-to-retained-report",
      from: "record-invalid-outcome",
      fromOutput: "INVALID",
      to: "retained-outcome-report",
    },
    {
      id: "invalid-ledger-error-to-retained-report",
      from: "record-invalid-outcome",
      fromOutput: "ERROR",
      to: "retained-outcome-report",
    },
    {
      id: "report-success-to-cycle",
      from: "final-report",
      fromOutput: "SUCCESS",
      to: "scan-scopes",
    },
    {
      id: "report-error-to-retained-report",
      from: "final-report",
      fromOutput: "ERROR",
      to: "retained-outcome-report",
    },
    {
      id: "retained-report-success-to-deferred",
      from: "retained-outcome-report",
      fromOutput: "SUCCESS",
      to: "deferred",
    },
    {
      id: "retained-report-error-to-deferred",
      from: "retained-outcome-report",
      fromOutput: "ERROR",
      to: "deferred",
    },
    {
      id: "coverage-deferred-recorded",
      from: "record-coverage-deferred-outcome",
      fromOutput: "SUCCESS",
      to: "retained-outcome-report",
    },
    {
      id: "coverage-deferred-record-invalid",
      from: "record-coverage-deferred-outcome",
      fromOutput: "INVALID",
      to: "retained-outcome-report",
    },
    {
      id: "coverage-deferred-record-error",
      from: "record-coverage-deferred-outcome",
      fromOutput: "ERROR",
      to: "retained-outcome-report",
    },
    {
      id: "coverage-exhausted-recorded",
      from: "record-exhausted-outcome",
      fromOutput: "SUCCESS",
      to: "completion-report",
    },
    {
      id: "coverage-exhausted-record-invalid",
      from: "record-exhausted-outcome",
      fromOutput: "INVALID",
      to: "retained-outcome-report",
    },
    {
      id: "coverage-exhausted-record-error",
      from: "record-exhausted-outcome",
      fromOutput: "ERROR",
      to: "retained-outcome-report",
    },
    {
      id: "completion-report-success",
      from: "completion-report",
      fromOutput: "SUCCESS",
      to: "success",
    },
    {
      id: "completion-report-error",
      from: "completion-report",
      fromOutput: "ERROR",
      to: "retained-outcome-report",
    },
  ],
};

export const securityReviewFixLoopStarterFlow = {
  id: "security-fix-loop",
  version: 16,
  defaultAlias: "security-review-fix-loop",
  category: "Security",
  tags: ["optional", "review", "fix", "tests"],
  protocol: {
    schemaVersion: 1,
    verification: {
      planId: "starter-security-fix-loop:frozen-verification",
      baselineBlockId: "baseline-verification",
      candidateBlockId: "run-verification",
      baselineInconclusiveTargetId: "security-check",
      candidateInconclusiveTargetId: "git-diff-summary",
      routeOverrides: [],
    },
    terminalOutcomes: [
      { blockId: "success", outcome: "succeeded" },
      { blockId: "deferred", outcome: "deferred" },
    ],
  },
  flow: securityFixLoopFlow,
} as const satisfies RalphStarterFlow;
