#!/bin/sh
set -eu
# Resolve symlinks so /usr/local/bin/machdoch can point at this launcher.
machdoch_entry=$(readlink -f -- "$0")
machdoch_dir=$(dirname -- "$machdoch_entry")
exec node "$machdoch_dir/machdoch-cli.cjs" "$@"
