// This file is generated by scripts/generate-runtime-contract.mjs.
// Source of truth: src/shared/runtime-config.schema.json
#![allow(dead_code)]

pub const RUNTIME_CONFIG_SCHEMA_ID: &str =
    "https://machdoch.local/schemas/runtime-config.schema.json";
pub const RUNTIME_CONFIG_SCHEMA_VERSION: u32 = 1;

pub const RUN_MODES: [&str; 2] = ["ask", "machdoch"];
pub const REASONING_MODES: [&str; 8] = [
    "default", "none", "minimal", "low", "medium", "high", "xhigh", "max",
];
pub const VALID_TOOLS: [&str; 9] = [
    "filesystem",
    "shell",
    "network",
    "browser",
    "git",
    "packages",
    "mcp",
    "scheduler",
    "utilities",
];
pub const VALID_MODEL_PROVIDERS: [&str; 6] = [
    "openai",
    "anthropic",
    "google",
    "codex-cli",
    "claude-cli",
    "copilot-cli",
];
pub const MODEL_PROVIDERS: [&str; 7] = [
    "openai",
    "anthropic",
    "google",
    "codex-cli",
    "claude-cli",
    "copilot-cli",
    "unconfigured",
];
pub const USER_API_PROVIDERS: [&str; 3] = ["openai", "anthropic", "google"];
pub const AGENT_CLI_PROVIDERS: [&str; 3] = ["codex-cli", "claude-cli", "copilot-cli"];
pub const USER_WEB_SEARCH_PROVIDERS: [&str; 3] = ["perplexity", "tavily", "serper"];
pub const USER_AUDIO_AI_PROVIDERS: [&str; 2] = ["openai", "google"];
pub const VALID_WEB_SEARCH_PROVIDERS: [&str; 4] = ["none", "perplexity", "tavily", "serper"];
pub const VALID_AUDIO_AI_PROVIDERS: [&str; 3] = ["none", "openai", "google"];
pub const USER_REVIEW_MODEL_MODES: [&str; 2] = ["base", "dedicated"];
pub const RUNTIME_ENV_KEYS: [&str; 11] = [
    "MACHDOCH_MODE",
    "MACHDOCH_MODEL",
    "MACHDOCH_REASONING",
    "MACHDOCH_OFFLINE",
    "MACHDOCH_WEB_SEARCH_PROVIDER",
    "MACHDOCH_EXECUTOR_TURNS",
    "MACHDOCH_AUTOPILOT_ITERATIONS",
    "MACHDOCH_INFINITE",
    "MACHDOCH_CODEX_CLI_PATH",
    "MACHDOCH_CLAUDE_CLI_PATH",
    "MACHDOCH_COPILOT_CLI_PATH",
];
pub const PROVIDER_ENV_KEYS: [(&str, &str); 3] = [
    ("openai", "OPENAI_API_KEY"),
    ("anthropic", "ANTHROPIC_API_KEY"),
    ("google", "GOOGLE_API_KEY"),
];
pub const AGENT_CLI_PROVIDER_ENV_KEYS: [(&str, &str); 3] = [
    ("codex-cli", "MACHDOCH_CODEX_CLI_PATH"),
    ("claude-cli", "MACHDOCH_CLAUDE_CLI_PATH"),
    ("copilot-cli", "MACHDOCH_COPILOT_CLI_PATH"),
];
pub const WEB_SEARCH_ENV_KEYS: [(&str, &str); 3] = [
    ("perplexity", "PERPLEXITY_API_KEY"),
    ("tavily", "TAVILY_API_KEY"),
    ("serper", "SERPER_API_KEY"),
];
pub const DEFAULT_MODEL_PROVIDER: &str = "openai";
pub const DEFAULT_MODEL_BY_PROVIDER: [(&str, &str); 6] = [
    ("openai", "gpt-5.5"),
    ("anthropic", "claude-sonnet-4-6"),
    ("google", "gemini-3.5-flash"),
    ("codex-cli", "gpt-5.5"),
    ("claude-cli", "claude-sonnet-4-6"),
    ("copilot-cli", "auto"),
];
pub const DEFAULT_USER_REVIEW_MODEL_MODE: &str = "base";

pub const DEFAULT_USER_AGENT_LIMITS_INFINITE: bool = false;
pub const DEFAULT_MAX_EXECUTOR_TURNS: u32 = 64;
pub const DEFAULT_MAX_AUTOPILOT_EXECUTOR_ITERATIONS: u32 = 16;
pub const MAX_CONFIGURED_EXECUTOR_TURNS: u32 = 1000;
pub const MAX_CONFIGURED_AUTOPILOT_ITERATIONS: u32 = 100;

pub const DEFAULT_DESKTOP_SETTING_AUTOSTART_ENABLED: bool = false;
pub const DEFAULT_DESKTOP_SETTING_AUTOSTART_MINIMIZED: bool = false;
pub const DEFAULT_DESKTOP_SETTING_AUTOSTART_TO_TRAY: bool = false;
pub const DEFAULT_DESKTOP_SETTING_ALWAYS_RUN_AS_ADMINISTRATOR: bool = false;
pub const DEFAULT_DESKTOP_SETTING_ASSISTANT_BUBBLE_ENABLED: bool = true;
pub const DEFAULT_DESKTOP_SETTING_ASSISTANT_BUBBLE_HIDE_WHEN_FULLSCREEN: bool = true;
pub const DEFAULT_DESKTOP_SETTING_ASSISTANT_BUBBLE_TEMPORARILY_HIDE_SECONDS: u32 = 6;
pub const DEFAULT_DESKTOP_SETTING_AI_CONTEXT_MAX_MESSAGES: u32 = 60;
pub const DEFAULT_DESKTOP_SETTING_INACTIVE_SESSION_ARCHIVE_DAYS: u32 = 7;
pub const DEFAULT_DESKTOP_SETTING_ARCHIVED_SESSION_RETENTION_DAYS: u32 = 7;
pub const DEFAULT_DESKTOP_SETTING_QUICK_VOICE_ENABLED: bool = true;
pub const DEFAULT_DESKTOP_SETTING_QUICK_VOICE_SHORTCUT: &str = "CommandOrControl+Alt+V";
pub const DEFAULT_DESKTOP_SETTING_QUICK_VOICE_SILENCE_SECONDS: f64 = 1.8;
pub const DEFAULT_DESKTOP_SETTING_QUICK_VOICE_MAX_MESSAGES: u32 = 50;
pub const MIN_DESKTOP_SETTING_ASSISTANT_BUBBLE_TEMPORARILY_HIDE_SECONDS: u32 = 2;
pub const MAX_DESKTOP_SETTING_ASSISTANT_BUBBLE_TEMPORARILY_HIDE_SECONDS: u32 = 30;
pub const MIN_DESKTOP_SETTING_AI_CONTEXT_MAX_MESSAGES: u32 = 1;
pub const MAX_DESKTOP_SETTING_AI_CONTEXT_MAX_MESSAGES: u32 = 200;
pub const MIN_DESKTOP_SETTING_INACTIVE_SESSION_ARCHIVE_DAYS: u32 = 1;
pub const MAX_DESKTOP_SETTING_INACTIVE_SESSION_ARCHIVE_DAYS: u32 = 365;
pub const MIN_DESKTOP_SETTING_ARCHIVED_SESSION_RETENTION_DAYS: u32 = 1;
pub const MAX_DESKTOP_SETTING_ARCHIVED_SESSION_RETENTION_DAYS: u32 = 365;
pub const MIN_DESKTOP_SETTING_QUICK_VOICE_SILENCE_SECONDS: f64 = 0.8;
pub const MAX_DESKTOP_SETTING_QUICK_VOICE_SILENCE_SECONDS: f64 = 8.0;
pub const MIN_DESKTOP_SETTING_QUICK_VOICE_MAX_MESSAGES: u32 = 10;
pub const MAX_DESKTOP_SETTING_QUICK_VOICE_MAX_MESSAGES: u32 = 200;
